### ISSUE TITLE
Pods enter in error state/crashloopbackoff by setting different (from defaults) mask in cluster-cidr in Kubernetes

### ISSUE THREAD

**Issue by pedroclopessyone** [flannel-io/flannel#1008]
I've deployed a Kubernetes 1.10.4 Cluster ( 3 Masters, 2 Workers ) using Kubespray deployment tool ( with kubeadm experimental feature flag enabled ).

By the way I'm using Canal as 'kube_network_plugin'.

My costumer have some networking constraints. They provided the following network spaces:

192.168.150.0/25
192.168.150.128/25
192.168.151.0/25

Regarding kubespray 'k8s-cluster.yml', i've changed the parameters from the defaults, where the defaults are:

kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_node_prefix: 24

We tried to change these parameters to match the network spaces our costumer gave us but unfortunately this modification didn't worked as expected. We soon realized that it would not work as expected by using /25 mask, so we tried to use from /25 to /20 but nothing worked.

I tried using 192.168.150.0/18 or 172.18.0.0/18 and all gone well (as long we use /18 mask), as demonstrated below.

kube_service_addresses: 192.168.150.0/18
kube_pods_subnet: 192.168.151.0/18
kube_network_node_prefix: 24

The behaviour presented by the cluster when using masks different than /18 is a bit weird, since, for example, kube-dns pod, kube-proxy pod, kube-autoscaler, etc, simply doesn't get up or canal-pods are deployed in one node but in the other cluster nodes it does not.

Is there any limitation/constraint of Kubernetes for not supporting any networks different that /16 and /18 or am i doing anything wrong?

I've searched this on web but in none of the stuff i read was clear regarding this. Some say that is possible to set a different mask from the one that is on defaults (/16) but the fact is if we change it, it does not work.

Despite the fact i'm using Canal as network plugin for kubernetes, it is a fact that the problem could be on flannel side as this problem is related with networking.

Keep in mind that i've already tested this parametrization by bootstrapping a Kubernetes cluster using kubeadm tool (https://kubernetes.io/docs/setup/independent/high-availability/) and changed the --cluster-cidr to 192.168.151.0/25 (in the file /etc/kubernetes/manifests/kube-controller-manager.yaml).

This might be a bug as it have to be possible to change the default '--cluster-cidr' because of our network limitations.

Could you please help me with this?

Best regards,

Pedro Cravo Lopes.
## Steps to Reproduce (for bugs)

1. I changed this file 'https://github.com/kubernetes-incubator/kubespray/blob/master/inventory/sample/group_vars/k8s-cluster.yml' to change the default network parameters.

2. On topic above ( 1 ) i changed 'kube_network_plugin: calico' to 'kube_network_plugin: canal' and changed 'kube_service_addresses:' and 'kube_pods_subnet:' to the network spaces explicit above.

3.
4.

## Context

At this moment the cluster is working, however, is working with the network defaults ('kube_service_addresses: 10.233.0.0/18' ; 'kube_pods_subnet: 10.233.64.0/18' and 'kube_network_node_prefix: 24'). This configuration is not accepted from our customer side, because they have network constraints ( like explicit above they gave us the following network spaces: '192.168.150.0/25 ; 192.168.150.128/25 ; 192.168.151.0/25' . We understand that /25 mask provides small bunch of IP's but the customer is fully aware of the consequencies of this.

## Your Environment

* Flannel version: flanneld v0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: v3.2.18
* Kubernetes version (if used): v.1.10.4
* Operating System and version: Red Hat Enterprise Linux 7.4 (we tested all of this on RHEL 7.5, CentOS 7.4, CentOS 7.5, and CentOS Atomic 'Latest')
* Link to your project (optional):
We've opened a few cases on StackOverflow too and pasted there the errors:
https://stackoverflow.com/questions/50415765/kubernetes-canal-cni-error-on-masters

Example of one of the errors (when using Kubeadm to bootsrap the cluster):

[exXXXXX@devmn1 ~]$ kubectl logs canal-rdmnl -n kube-system -c kube-flannel
I0518 16:01:22.555513 1 main.go:487] Using interface with name ens192 and address 10.136.3.38
I0518 16:01:22.556080 1 main.go:504] Defaulting external address to interface address (10.136.3.38)
I0518 16:01:22.565141 1 kube.go:130] Waiting 10m0s for node controller to sync
I0518 16:01:22.565167 1 kube.go:283] Starting kube subnet manager
I0518 16:01:23.565280 1 kube.go:137] Node controller sync successful
I0518 16:01:23.565311 1 main.go:234] Created subnet manager: Kubernetes Subnet Manager - devmn3.cpdprd.pt
I0518 16:01:23.565331 1 main.go:237] Installing signal handlers
I0518 16:01:23.565388 1 main.go:352] Found network config - Backend type: vxlan
I0518 16:01:23.565440 1 vxlan.go:119] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
E0518 16:01:23.565619 1 main.go:279] Error registering network: failed to acquire lease: node "devmn3.cpdprd.pt" pod cidr not assigned
I0518 16:01:23.565671 1 main.go:332] Stopping shutdownHandler...

**Comment by bloodymind** [comment]
I have the same error here!
