### ISSUE TITLE
TX Packets dropped on flannel.1

### ISSUE THREAD

**Issue by discostur** [flannel-io/flannel#1009]
Hi,

we are running a 14 node k8s cluster with flannel (backend: vxlan) and we are seeing some packet drops on the flannel.1 interface:

```
        TX packets 416348507  bytes 685679045151 (638.5 GiB)
        TX errors 0  dropped 402 overruns 0  carrier 0  collisions 0
``` 
Under normal load (cpu about 20%) we are seeing 0.01pps getting dropped. If we are running some high traffic tests with iperf the dropping rate increases up to 1pps.

We are seeing this behaviour also on smaller clusters with only 3 oder 5 nodes.

## Your Environment
* Flannel version: 0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.2.15
* Kubernetes version (if used): 1.10.2
* Operating System and version: centos7.5

**Comment by andyzasl** [comment]
Have same issue on debian 9 with kernel 4.9.110-3+deb9u5

**Comment by willmao** [comment]
same issue

**Comment by willmao** [comment]
@discostur @andyzasl 
find this post: https://tech.xing.com/a-reason-for-unexplained-connection-timeouts-on-kubernetes-docker-abd041cf7e02

**Comment by woosley** [comment]
it seems I have a bigger issues here 
`ifconfig flannel.1
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.233.90.0  netmask 255.255.255.255  broadcast 0.0.0.0
        inet6 fe80::b8ac:efff:fef7:2bfa  prefixlen 64  scopeid 0x20<link>
        ether ba:ac:ef:f7:2b:fa  txqueuelen 0  (Ethernet)
        RX packets 6067601678  bytes 3591982333594 (3.2 TiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5084072209  bytes 4894906311763 (4.4 TiB)
        TX errors 19  dropped 86146 overruns 0  carrier 19  collisions 0
`
Host centos7.4 and  what is the proper way to debug this issue?

**Comment by discostur** [comment]
we switched to backend type "DirectRouting" and since then, we don't see any packet drops; We didn't have time to check if @willmao solution is working for us ...

https://github.com/coreos/flannel/blob/master/Documentation/backends.md

**Comment by marek-obuchowicz** [comment]
So the issue seems to still exist, even with `--random-fully` :(
As @willmao mentions in his blog post, adding it reduced error ocurrence a lot, but we're still getting it from time to time.
@discostur you mentioned mitigating the issue by switching backend to `DirectRouting`. I didn't find backend called like that - it's a configuration option for `vxlan` backend. Is this what you've meant?
