### ISSUE TITLE
Can't set MTU on Flannel

### ISSUE THREAD

**Issue by rakeshJn** [flannel-io/flannel#1011]
Running Flannel in Kubernetes, found that flannel picks up MTU from host interface, reduces it by 50 and sets that as its mtu. There is no way we can set mtu for flannel.
The reason we need this capability is - the host interface could have some mtu, however, some network device in the path from that host to another host may have lower mtu, and in such a case, the packets sent by flannel are dropped at that device. Sometimes some devices in the network are not in our control and can't change mtu or other setting on them. It would be really nice if flannel allowed setting mtu, may be through config map in k8s. I believe some other k8s network addons have this capability, like Calico.

## Expected Behavior
Be able to set mtu when starting flannel

## Current Behavior
Currently it takes mtu from host interface and deducts 50 from it and sets that as its mtu with no way to change it.

## Possible Solution
One example:
command: [ "/opt/bin/flanneld", "--ip-masq", "--kube-subnet-mgr", "--mtu=1400" ]

## Context
We established inter DC flannel network in two zones where this problem came up.

## Your Environment

* Flannel version: 0.91
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.1.2
* Kubernetes version (if used): v1.96
* Operating System and version: RHEL 7.3

**Comment by darashevcstbg** [comment]
I have an environment that is on AWS and Google virtual machines, and it is connected with a VPN. The MTU on the AWS Flannel interface is 8951, but the VPN MTU is 1500 and the packets are dropped. It will be nice if we have the capability of setting the Flannel MTU.

**Comment by viceice** [comment]
Same here 😕  running trough a wireguard vpn behind dsl modem, so need to reduce the mtu somehow

**Comment by zedtux** [comment]
Joining in. I'm running TincVPN (mtu=1500) and Docker (mtu=1500) but Flannel is 1450 😭

**Comment by viceice** [comment]
please reopen, issue still exists

**Comment by rbrtbnfgl** [comment]
I'll reopen the issue but the MTU should be configurable on flannel. I'll check if it rightly working.

**Comment by rbrtbnfgl** [comment]
There was some fix to rightly configure the MTU with Wireguard. Right now the only way to modify the MTU is to change the MTU of the external interface used by flannel. I thought there was already a flag but I was wrong.

**Comment by rbrtbnfgl** [comment]
I updated the backend configuration to be able to configure the MTU.
The MTU should be configured on the net-conf config defined on the configmap https://github.com/flannel-io/flannel/blob/master/Documentation/kube-flannel.yml#L93

**Comment by lszxyz** [comment]
but the doc always MTU is calculated and set automatically by flannel, whether update the [configuration doc ](https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#:~:text=MTU%20is%20calculated%20and%20set%20automatically%20by%20flannel)

**Comment by rbrtbnfgl** [comment]
I missed that on the config. Now it can be changed. I'll fix the doc
