### ISSUE TITLE
iptable forwarding rules added after default REJECT rule on CentOS 7

### ISSUE THREAD

**Issue by geauxvirtual** [flannel-io/flannel#1033]
When deploying flannel on a CentOS 7 host, the iptables forwarding rules for the pod network are added to the FORWARD chain after the default REJECT rule. This causes issues with internal traffic of a kubernetes cluster (pod to pod and pod to service) being rejected before the forwarding rules added by Flannel are hit.

![forward](https://user-images.githubusercontent.com/1395030/44684718-a3d17280-a9fe-11e8-9479-9fe11da8ecfa.JPG)

## Expected Behavior
Forwarding rules are added before any default DROP or REJECT rules in the CentOS FORWARD chain.

## Current Behavior
Forwarding rules are appended to the end of the FORWARD chain after the default DROP and REJECT rules.

## Steps to Reproduce (for bugs)
1. Install kubernetes 1.11.2 on CentOS 7 via kubeadm
2. Install flannel network -- `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml`

## Context
No internal traffic in Kubernetes cluster (pod to pod and pod to service) works as traffic is rejected by a default REJECT rule in the FORWARD chain. 

## Your Environment

* Flannel version: 0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 
* Kubernetes version (if used): 1.11.2
* Operating System and version: CentOS 7

**Comment by vnlinuser** [comment]
I get same problem too...How fix it？

**Comment by perrymana** [comment]
Looks like we are experiencing exactly the same issue with Flannel and CentOS. Manually re-ordering the rules so those 2 ACCEPT rules are above the REJECT rule (or turning the firewall off!) resolves the problem.

Did you find a workaround? I was about to see if I could manually declare some firewall rules to resolve it.
