### ISSUE TITLE
IP routes different between nodes 

### ISSUE THREAD

**Issue by sivarajp** [flannel-io/flannel#1034]
Some of the nodes are missing ip routes 
[root@kube-aws-dev-node-1a11 centos]# ip route
default via 10.xx.xx.1 dev eth0 proto dhcp metric 100 
10.42.0.0/24 via 10.42.0.0 dev flannel.1 onlink 
10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink 
10.42.2.0/24 via 10.42.2.0 dev flannel.1 onlink 
10.42.3.0/24 via 10.42.3.0 dev flannel.1 onlink 
10.42.4.0/24 via 10.42.4.0 dev flannel.1 onlink 
10.42.5.0/24 via 10.42.5.0 dev flannel.1 onlink 
10.42.6.0/24 via 10.42.6.0 dev flannel.1 onlink 
10.42.9.0/24 via 10.42.9.0 dev flannel.1 onlink 
10.42.10.0/24 via 10.42.10.0 dev flannel.1 onlink 
10.42.11.0/24 via 10.42.11.0 dev flannel.1 onlink 
10.42.12.0/24 via 10.42.12.0 dev flannel.1 onlink 
10.42.13.0/24 via 10.42.13.0 dev flannel.1 onlink 
10.42.14.0/24 via 10.42.14.0 dev flannel.1 onlink 
10.42.38.0/24 via 10.42.38.0 dev flannel.1 onlink 
10.42.39.0/24 dev cni0 proto kernel scope link src 10.42.39.1 
10.42.40.0/24 via 10.42.40.0 dev flannel.1 onlink 
10.42.41.0/24 via 10.42.41.0 dev flannel.1 onlink 
10.42.42.0/24 via 10.42.42.0 dev flannel.1 onlink 
10.42.43.0/24 via 10.42.43.0 dev flannel.1 onlink 
10.42.44.0/24 via 10.42.44.0 dev flannel.1 onlink 
10.42.45.0/24 via 10.42.45.0 dev flannel.1 onlink 
10.xx.xx.0/25 dev eth0 proto kernel scope link src 10.xx.xx.10 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 

[root@kube-aws-dev-node-1a1 centos]# ip rou
default via 10.xx.xx.1 dev eth0 proto dhcp metric 100 
10.42.0.0/24 via 10.42.0.0 dev flannel.1 onlink 
10.42.1.0/24 via 10.42.1.0 dev flannel.1 onlink 
10.42.2.0/24 via 10.42.2.0 dev flannel.1 onlink 
10.42.3.0/24 via 10.42.3.0 dev flannel.1 onlink 
10.42.4.0/24 via 10.42.4.0 dev flannel.1 onlink 
10.42.5.0/24 via 10.42.5.0 dev flannel.1 onlink 
10.42.6.0/24 via 10.42.6.0 dev flannel.1 onlink 
10.42.9.0/24 via 10.42.9.0 dev flannel.1 onlink 
10.42.10.0/24 via 10.42.10.0 dev flannel.1 onlink 
10.42.11.0/24 via 10.42.11.0 dev flannel.1 onlink 
10.42.12.0/24 via 10.42.12.0 dev flannel.1 onlink 
10.42.13.0/24 dev cni0 proto kernel scope link src 10.42.13.1 
10.42.14.0/24 via 10.42.14.0 dev flannel.1 onlink 
10.42.15.0/24 via 10.42.15.0 dev flannel.1 onlink 
10.42.17.0/24 via 10.42.17.0 dev flannel.1 onlink 
10.42.19.0/24 via 10.42.19.0 dev flannel.1 onlink 
10.42.20.0/24 via 10.42.20.0 dev flannel.1 onlink 
10.42.21.0/24 via 10.42.21.0 dev flannel.1 onlink 
10.42.25.0/24 via 10.42.25.0 dev flannel.1 onlink 
10.42.26.0/24 via 10.42.26.0 dev flannel.1 onlink 
10.42.29.0/24 via 10.42.29.0 dev flannel.1 onlink 
10.42.30.0/24 via 10.42.30.0 dev flannel.1 onlink 
10.42.31.0/24 via 10.42.31.0 dev flannel.1 onlink 
10.42.34.0/24 via 10.42.34.0 dev flannel.1 onlink 
10.42.35.0/24 via 10.42.35.0 dev flannel.1 onlink 
10.42.36.0/24 via 10.42.36.0 dev flannel.1 onlink 
10.42.38.0/24 via 10.42.38.0 dev flannel.1 onlink 
10.42.39.0/24 via 10.42.39.0 dev flannel.1 onlink 
10.42.40.0/24 via 10.42.40.0 dev flannel.1 onlink 
10.42.41.0/24 via 10.42.41.0 dev flannel.1 onlink 
10.42.42.0/24 via 10.42.42.0 dev flannel.1 onlink 
10.42.43.0/24 via 10.42.43.0 dev flannel.1 onlink 
10.42.44.0/24 via 10.42.44.0 dev flannel.1 onlink 
10.42.45.0/24 via 10.42.45.0 dev flannel.1 onlink 
10.xx.xx.0/25 dev eth0 proto kernel scope link src 10.xx.xx.111 metric 100 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 

## Expected Behavior
ip routes are expected to be the same except the node ip itsefl
## Current Behavior

Some nodes are not routing the traffic to correct pods

## Your Environment

* Flannel version: 0.9.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3+
* Kubernetes version (if used): 1.10.5
* Operating System and version: centos 7.4
* Link to your project (optional):

**Comment by timchenxiaoyu** [comment]
any error logs?
