### ISSUE TITLE
 Failed to create SubnetManager on Windows Server 1803

### ISSUE THREAD

**Issue by luca-esse** [flannel-io/flannel#1037]
The following command works well on Windows Server 2019 but fails on Windows Server 1803 (Exact same config file):
flanneld.exe --kubeconfig-file=C:\k\config --iface=$ipaddress --ip-masq=1 --kube-subnet-mgr=1

## Current Behavior
```
I0909 08:31:56.295504    3656 main.go:475] Determining IP address of default interface
I0909 08:31:56.481511    3656 main.go:488] Using interface with name vEthernet (Ethernet 2) and address 10.0.0.14
I0909 08:31:56.481511    3656 main.go:505] Defaulting external address to interface address (10.0.0.14)
E0909 08:31:56.482463    3656 main.go:232] Failed to create SubnetManager: unable to create k8s config: Error loading config file "C:\k\config": couldn't get version/kind; json parse error: json: cannot unmarshal string into Go value of type struct { APIVersion string "json:\"apiVersion,omitempty\""; Kind string "json:\"kind,omitempty\"" }
```
## Steps to Reproduce (for bugs)
1. Create a kube cluster config file on C:\k\
2. Run flanneld.exe --kubeconfig-file=C:\k\config --iface= --ip-masq=1 --kube-subnet-mgr=1

## Context
I was trying to set up a Kubernetes Windows Node following this guide:
https://onedrive.live.com/view.aspx?resid=E2B6765015E5FA01!339&ithint=file%2cdocx&app=Word&authkey=!AGvs_s_hWs7xHGs
But on Windows Server 1803  i got stuck on the "Waiting for the Network to be created" loop after the powershell script calls flanneld.exe and fails with the error described above.
Following that guide Windows Server 2019 worked flawlessly

## Your Environment
* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): vxlan 
* Etcd version:
* Kubernetes version (if used): Client Version: v1.10.2, Server Version: v1.11.2
* Operating System and version: Windows Server Datacenter 1803 10.0.17134 N/A Build 17134

Kube cluster config file:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: *cut*
    server: https://10.0.0.11:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: *cut*
    client-key-data:  *cut*
```

**Comment by benjackwhite** [comment]
We are also experiencing the exact same issue with almost identical configuration values. Any luck finding a solution @luca-esse ? Is it an actual issue or was there simply something wrong with the config?

**Comment by luca-esse** [comment]
Hi @benjackwhite, unfortunatly i didn't found any solution or the cause of the problem
