### ISSUE TITLE
restart network service will lost routing tables

### ISSUE THREAD

**Issue by miaoshixuan** [flannel-io/flannel#1070]
I use vxlan backend and set  `DirectRouting` true.when I run `service network restart` , routing table added by flanneld will lose
## Expected Behavior

all routing tables should recover
## Current Behavior

routing talble added by flannel will lose
## Steps to Reproduce (for bugs)

1.    deploy flannel  using vxlan backend and set DirectRouting true
2.    restart network service

## Your Environment

* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): vxlan   DirectRouting=true
* Etcd version: 3.2.15
* Kubernetes version (if used):  1.11.2
* Operating System and version: centos 7.4
* Link to your project (optional):

**Comment by daddylhz** [comment]
Flannel doesn't monitor the state of host network. You should restart flannel if you restart network

**Comment by pravin-singhal** [comment]
@zhangxiangui40542  any update on this issue - 
I too have the same issue - flannel routes get lost when used with vxlan with direct routing.

**Comment by apakhomov** [comment]
It is not only network service restart problem. After interface is suddenly reset/disconnected (any maintenance on host/network, or network "flapped") direct routes are being lost and one is to monitor and maintain this situation manually.
