### ISSUE TITLE
kube-flannel-ds Init:CrashLoopBackOff state ppc64le

### ISSUE THREAD

**Issue by langerkunal** [flannel-io/flannel#1073]
After applying kube-flannel.yml file I see that the state of kube-flannel pod is in CrashLoopBackOff state.

## Expected Behavior
I configured kubernetes cluster using kubeadm init. After that applied kube-flannel.yml file from https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml. When I run kubectl get pods --all-namespaces I see the pod state of Kube-flannel in CrashLoopBackOff state

## Steps to Reproduce (for bugs)

1.  kubeadm init --pod-network-cidr=10.244.0.0/16
2. As a non-root user mkdir -p $HOME/.kube
3. sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
4. sudo chown $(id -u):$(id -g) $HOME/.kube/config
5. Applied https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml file 
The state of kube-flannel pod is CrashLoopBackOff
dockuser@Test-LPAR-Ubuntu:~$ kubectl get pods -n kube-system
NAME                                       READY   STATUS             RESTARTS   AGE
coredns-86c58d9df4-5nzss                   1/1     Running            0          29m
coredns-86c58d9df4-hxlqm                   1/1     Running            0          29m
etcd-test-lpar-ubuntu                      1/1     Running            0          29m
kube-apiserver-test-lpar-ubuntu            1/1     Running            0          29m
kube-controller-manager-test-lpar-ubuntu   1/1     Running            0          29m
kube-flannel-ds-ppc64le-7gqr8              0/1     CrashLoopBackOff   9          24m
kube-proxy-55tcx                           1/1     Running            0          29m
kube-scheduler-test-lpar-ubuntu            1/1     Running            0          29m
dockuser@Test-LPAR-Ubuntu:~$

Running kubectl describe pod kube-flannel-ds-ppc64le-7gqr8
Error from server (NotFound): pods "kube-flannel-ds-ppc64le-7gqr8" not found
dockuser@Test-LPAR-Ubuntu:~$

## Context
 I am not able to add worker nodes

## Your Environment

* Flannel version: 0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: N/A
* Kubernetes version (if used): 1.13.0
* Operating System and version: Ubuntu 16.04 LTS ppc64le
* Link to your project (optional):

**Comment by heidini** [comment]
I also got the same same issue for coredns in CrashLoopBackOff state:
osboxes@kubemaster:~$ kubectl get pods -n kube-system
NAME                                 READY   STATUS             RESTARTS   AGE
coredns-86c58d9df4-jrtdv             0/1     CrashLoopBackOff   2          17h
coredns-86c58d9df4-zfwn2             0/1     CrashLoopBackOff   3          17h
etcd-kubemaster                      1/1     Running            0          17h
kube-apiserver-kubemaster            1/1     Running            0          17h
kube-controller-manager-kubemaster   1/1     Running            0          17h
kube-flannel-ds-amd64-s7g8r          1/1     Running            0          77s
kube-proxy-rgp9p                     1/1     Running            0          17h
kube-scheduler-kubemaster            1/1     Running            0          17h

My environment:
Flannel: 0.10.0
Kubernetes version:   Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:39:04Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T10:31:33Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Operating System and version: Ubuntu 16.04 LTS ppc64le

**Comment by heidini** [comment]
I also tried to apply the v0.10.0 yaml, but got pending state:
osboxes@kubemaster:~$ kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.extensions/kube-flannel-ds created
osboxes@kubemaster:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                 READY   STATUS    RESTARTS   AGE
kube-system   coredns-86c58d9df4-jrtdv             0/1     Pending   0          17h
kube-system   coredns-86c58d9df4-zfwn2             0/1     Pending   0          17h
kube-system   etcd-kubemaster                      1/1     Running   0          17h
kube-system   kube-apiserver-kubemaster            1/1     Running   0          17h
kube-system   kube-controller-manager-kubemaster   1/1     Running   0          17h
kube-system   kube-proxy-rgp9p                     1/1     Running   0          17h
kube-system   kube-scheduler-kubemaster            1/1     Running   0          17h

**Comment by cmoulliard** [comment]
I'm getting the same error as the `coredns` pod can't be started. If I look to the log of one of the pod, I see this error

```
[root@cloud kube]# kubectl get pods,ds -n kube-system
NAME                                READY   STATUS             RESTARTS   AGE
pod/coredns-fb8b8dccf-4znqj         0/1     CrashLoopBackOff   6          8m17s
pod/coredns-fb8b8dccf-jsn5x         0/1     CrashLoopBackOff   6          8m17s
pod/etcd-cloud                      1/1     Running            0          7m16s
pod/kube-apiserver-cloud            1/1     Running            0          7m29s
pod/kube-controller-manager-cloud   1/1     Running            0          7m19s
pod/kube-proxy-fwdrn                1/1     Running            0          8m16s
pod/kube-scheduler-cloud            1/1     Running            0          7m12s

[root@cloud kube]# kubectl logs pod/coredns-fb8b8dccf-4znqj -n kube-system
standard_init_linux.go:178: exec user process caused "operation not permitted"
```

Is there a workaround ?
