### ISSUE TITLE
请教一下 flanel 如何实现跨节点的发送广播消息和组播消息？thank you

### ISSUE THREAD

**Issue by yytlmm** [flannel-io/flannel#1077]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by daddylhz** [comment]
好像没做这个

**Comment by xiaods** [comment]
use host-gw to resolve your problem, more details concepts can refers here:

http://cizixs.com/2017/09/28/linux-vxlan/
