### ISSUE TITLE
cannot access other pod on different node

### ISSUE THREAD

**Issue by pain301** [flannel-io/flannel#1085]
## Expected Behavior
The pod on other node is reachable when exec `ping` command

## Current Behavior
1. enter pod on node c1
```sh
kubectl exec -it nginx-deployment-76bf4969df-6h5kd  bash
```
2. 10.244.2.11 is IP of the pod which scheduled on node c3
```sh
ping 10.244.2.11
```
12 packets transmitted, 0 packets received, 100% packet loss

External ip like www.google.com is not reachable in pod on all node.

## Your Environment
* Flannel version:
I do not know how to get flannel version.
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml
```

* Backend used (e.g. vxlan or udp): vxlan

* Etcd version: 3.2.24

* Kubernetes version (if used): 1.13.1

* Operating System and version: 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

## Nodes
```
NAME   STATUS   ROLES    AGE   VERSION   INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                KERNEL-VERSION              CONTAINER-RUNTIME
c1     Ready    <none>   20h   v1.13.1   192.168.1.5   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.0
c2     Ready    master   42h   v1.13.1   192.168.1.6   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.0
c3     Ready    <none>   19h   v1.13.1   192.168.1.7   <none>        CentOS Linux 7 (Core)   3.10.0-957.1.3.el7.x86_64   docker://18.9.0
```

## Pods
```
nginx-deployment-76bf4969df-6h5kd   1/1     Running   0          21m   10.244.1.11   c1     <none>           <none>
nginx-deployment-76bf4969df-fcnh7   1/1     Running   4          18h   10.244.1.10   c1     <none>           <none>
nginx-deployment-76bf4969df-ffrkz   1/1     Running   0          21m   10.244.2.11   c3     <none>           <none>
```

route info on c1
```
default via 10.0.2.2 dev eth0 proto dhcp metric 100 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100 
10.244.0.0/24 via 10.244.0.0 dev flannel.1 onlink 
10.244.1.0/24 dev cni0 proto kernel scope link src 10.244.1.1 
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.5 metric 101
```

route info on c2
```
default via 10.0.2.2 dev eth0 proto dhcp metric 100 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100 
10.244.0.0/24 dev cni0 proto kernel scope link src 10.244.0.1 
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink 
10.244.2.0/24 via 10.244.2.0 dev flannel.1 onlink 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.6 metric 101
```

route info on c3
```
default via 10.0.2.2 dev eth0 proto dhcp metric 100 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.15 metric 100 
10.244.0.0/24 via 10.244.0.0 dev flannel.1 onlink 
10.244.1.0/24 via 10.244.1.0 dev flannel.1 onlink 
10.244.2.0/24 dev cni0 proto kernel scope link src 10.244.2.1 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 
192.168.1.0/24 dev eth1 proto kernel scope link src 192.168.1.7 metric 101
```

I have solved the problem temporarily by switching to weave

**Comment by bogd** [comment]
I am seeing a very similar issue in my lab environment (k8s bootstrapped using kubeadm, flannel installed with `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml` ).

Strangely enough, in my case I can ping from a node to a pod running on another node, but a curl to it fails. Using tcpdump on the destination pod, I can see the initial packet (TCP SYN) on the pod's network interface, but no response ever goes out.

I did configure `iptables -P FORWARD ACCEPT` - same result.

Switching to weave does solve the issue, but I would still like to get flannel to work...

**Comment by pain400** [comment]
@bogd Are there many differences between flannel and weave? I remember that they all run in layer2 mode.

**Comment by bogd** [comment]
As far as I can tell (but don't take my word for it), they both use VXLAN behind the scenes by default. So it is very strange that one works and another one does not. I tested them on exactly the same cloud infrastructure, provisioned by exactly the same scripts - so I can guarantee that the VMs are absolutely identical!

**Comment by snehadeep007** [comment]
Ensure the UDP ports 8285 and 8472 ( For Flannel) are accessing among your nodes.
Ref: https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
