### ISSUE TITLE
Document of building.md is not clear for manully building flannel.exe

### ISSUE THREAD

**Issue by JohnJAS** [flannel-io/flannel#1087]
Document of building.md is not clear for manully building flannel.exe
And it is quite confusing for the beginner like me.

## Expected Behavior

Make it more clear

## Current Behavior

It is not so friendly to beginners.

## Possible Solution

1.Make sure you have required dependencies installed on your machine.
On Ubuntu, run sudo apt-get install linux-libc-dev golang gcc.
On Fedora/Redhat, run sudo yum install kernel-headers golang gcc.

For Ubuntu(I only tested on it),
User also need to update the golang verion to 1.7 or above to compile but apt-get only supported 1.6.
mingw-w64 needed. 

sudo apt-get install mingw-w64

## Steps to Reproduce (for bugs)

1. Following the building.md to compile flanneld.exe
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
Ubuntu 16.04.2
* Link to your project (optional):

**Comment by rajatchopra** [comment]
@madhanrm @ksubrmnn Can you advise here?
@JohnJAS Would you mind posting a doc-update PR?

**Comment by JohnJAS** [comment]
@rajatchopra Sure, I just create a PR for it. Maybe it can be some help for you.
Refer to: https://github.com/coreos/flannel/pull/1089

**Comment by ksubrmnn** [comment]
Fixed by #1089
/close
