### ISSUE TITLE
Windows container DNS suffix is wrong when using flannel overlay

### ISSUE THREAD

**Issue by claudiubelu** [flannel-io/flannel#1091]
## Expected Behavior

On a newly deployed Kubernetes v1.13.1 cluster with Windows Server 2019 nodes and with flannel overlay setup, it can be noticed that the Windows Pod's DNS suffix is wrong.  Normally, the DNS suffix should contain the pod's namespace, like: ``namespace.svc.cluster.local,`` but all the pod's have the DNS suffix ``default.svc.cluster.local``

## Current Behavior

Checking the DNS suffix on newly created Pods, will reveal that all the pods will have the ``default.svc.cluster.local`` sufix.

For example:

    kubectl create namespace test-ns
    kubectl create -f busybox_windows.yaml -n test-ns # [3]
    kubectl exec -n test-ns win-busybox -- ipconfig /all

    Windows IP Configuration

       Host Name . . . . . . . . . . . . : win-busybox
       Primary Dns Suffix  . . . . . . . :
       Node Type . . . . . . . . . . . . : Hybrid
       IP Routing Enabled. . . . . . . . : No
       WINS Proxy Enabled. . . . . . . . : No
       DNS Suffix Search List. . . . . . : default.svc.cluster.local

    Ethernet adapter vEthernet (06ac016fad417c67216f567f0a1b8880058e87431ec76bff8936432f94ab85cf_vxlan0):

       Connection-specific DNS Suffix  . : default.svc.cluster.local
       Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #4
       Physical Address. . . . . . . . . : 0E-2A-0A-F4-03-0A
       DHCP Enabled. . . . . . . . . . . : Yes
       Autoconfiguration Enabled . . . . : Yes
       Link-local IPv6 Address . . . . . : fe80::89a4:198e:5b2a:d6ef%31(Preferred)
       IPv4 Address. . . . . . . . . . . : 10.244.3.10(Preferred)
       Subnet Mask . . . . . . . . . . . : 255.255.255.0
       Default Gateway . . . . . . . . . : 10.244.3.1
       DNS Servers . . . . . . . . . . . : 11.0.0.10
       NetBIOS over Tcpip. . . . . . . . : Disabled
       Connection-specific DNS Suffix Search List :
                                           default.svc.cluster.local

The expected DNS suffix is ``test-ns.svc.cluster.local``.

Note that the DNS suffix is properly set when using flannel l2bridge:

    kubectl exec -n test-ns win-busybox -- ipconfig /all

    Windows IP Configuration

       Host Name . . . . . . . . . . . . : win-busybox
       Primary Dns Suffix  . . . . . . . :
       Node Type . . . . . . . . . . . . : Hybrid
       IP Routing Enabled. . . . . . . . : No
       WINS Proxy Enabled. . . . . . . . : No
       DNS Suffix Search List. . . . . . : test-ns.svc.cluster.local

    Ethernet adapter vEthernet (9f4739603b296d376e560506bde8461957d0116ba8011ba664401dcd73d6a4ba_cbr0):

       Connection-specific DNS Suffix  . : test-ns.svc.cluster.local
       Description . . . . . . . . . . . : Hyper-V Virtual Ethernet Adapter #5
       Physical Address. . . . . . . . . : 00-15-5D-E6-21-EF
       DHCP Enabled. . . . . . . . . . . : Yes
       Autoconfiguration Enabled . . . . : Yes
       Link-local IPv6 Address . . . . . : fe80::9097:233a:883:40ae%31(Preferred)
       IPv4 Address. . . . . . . . . . . : 10.244.6.23(Preferred)
       Subnet Mask . . . . . . . . . . . : 255.255.255.0
       Default Gateway . . . . . . . . . : 10.244.6.2
       DNS Servers . . . . . . . . . . . : 10.96.0.10
       NetBIOS over Tcpip. . . . . . . . : Disabled
       Connection-specific DNS Suffix Search List :
                                           test-ns.svc.cluster.local

## Steps to Reproduce (for bugs)

1. Deploy a Kubernetes cluster with Windows Server 2019 nodes following these guides [1][2], but configuring flannel overlay instead of l2bridge.
2. Create a pod:

    kubectl create namespace test-ns
    kubectl create -f busybox_windows.yaml -n test-ns # [3]

3. Check the DNS suffix: 

    kubectl exec -n test-ns win-busybox -- ipconfig /all

[1] https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows
[2] https://github.com/Microsoft/SDN/tree/master/Kubernetes/flannel/overlay
[3]  https://paste.ubuntu.com/p/FXSzpQ7z2q/

## Your Environment

* Flannel version: built from master
* Backend used (e.g. vxlan or udp): vxlan / overlay.
* Etcd version:
* Kubernetes version (if used): v1.13.1
* Operating System and version: Windows nodes: Windows Server 2019 (10.0.17763 N/A Build 17763)
* Link to your project (optional):

**Comment by daschott** [comment]
@bclau this should be resolved new on newest win-overlay, can you try it out and confirm?
