### ISSUE TITLE
In-cluster communication is partially broken after 0.11.0 upgrade

### ISSUE THREAD

**Issue by eranreshef** [flannel-io/flannel#1092]
## Expected Behavior
After upgrading flannel from v0.10.0 to v0.11.0, the cluster should continue to function as usual.

## Current Behavior
After upgrading the cluster's flannel image, a lot of the pods can't communicate with each other.

## Possible Solution
I have no clue but a cluster-wide reboot solves the problem.

## Steps to Reproduce (for bugs)
I'm using canal deployment file
1. upgrade flannel image to v0.11.0-amd64 in calico daemon set manifest.
2. apply the manifest to the cluster.

## Context
This issue prevents me from upgrading to latest flannel version.

## Your Environment

* Flannel version: 0.10.0 (upgrading to 0.11.0)
* Backend used (e.g. vxlan or udp): extension (wireguard)
* Etcd version: 3.3.10
* Kubernetes version (if used): 1.10.11
* Operating System and version: CoreOS 1800.7.0

Thanks!

**Comment by eranreshef** [comment]
some more info:
After a deeper analysis, it seems that in v0.11.0 packets are coming out from the host with the caliXXX or flannel-wg interface ip address instead of the actual requesting pod's ip address (as in v0.10.0).
Is this behaviour expected?

**Comment by mxey** [comment]
This happen because of the change to --random-fully in Flannel. Flannel tries to clean up existing iptables rules and create new ones, but the existing rules do not match "---j MASQUERADE --random-fully". Therefore flannel only deletes the RETURN rule that prevents the masquerading, but keeps the masquerading rule.

**Comment by SleepyBrett** [comment]
I have a a branch that fixes this, but I haven't written any tests yet, so no pull request quite yet. I've tested this on a side cluster and am banging on it a bit more before we attempt to roll this out ourselves. But if you want to take a quick gander: https://github.com/Nordstrom/flannel/tree/transition

Basically during rule teardown, I check each rule for --fully-random and create a second rule without --fully-random to teardown.
