### ISSUE TITLE
error converting YAML to JSON: yaml: line 529 for latest kube-flannel.yml

### ISSUE THREAD

**Issue by hussainaphroj** [flannel-io/flannel#1097]
kubectl apply -f https://github.com/coreos/flannel/blob/v0.10.0/Documentation/kube-flannel.yml
error: error parsing https://github.com/coreos/flannel/blob/v0.10.0/Documentation/kube-flannel.yml: error converting YAML to JSON: yaml: line 529: mapping values are not allowed in this context

**Comment by rajatchopra** [comment]
Does v0.11.0 work? And the master? Just to bisect the target.

**Comment by sanyuepao** [comment]
i am too

**Comment by mengfanyin** [comment]
me too

**Comment by hussainaphroj** [comment]
I haven't tried yet but it worked on Ubuntu box.

**Comment by shammishailaj** [comment]
I am facing a similar problem on Ubuntu 18.04

**Comment by chenchix** [comment]
You should use this link to use directly:
kubectl applyl -f https://raw.githubusercontent.com/coreos/flannel/v0.11.0/Documentation/kube-flannel.yml

**Comment by sekhar9676** [comment]
I am getting below error 

error: error parsing https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml: error converting YAML to JSON: yaml: line 128: mapping values are not allowed in this context

Can Someone help plz ..

**Comment by Techshrimp** [comment]
The reason is that the file format is inconsistent, so you need to log in to GitHub to copy the file content into the file, and using it directly will cause kubectl to use HTML files
