### ISSUE TITLE
unable to configure flannel in kubernetes from scratch

### ISSUE THREAD

**Issue by phanisowjanyavutukuri** [flannel-io/flannel#1099]
am trying to setup the flannel in ubuntu 18.04 without kubeadm by following hardway
my flannel pod is CrashLoopBackOff 
it is throwing 

"Error registering network: failed to acquire lease: node "kubernetes-minion" pod cidr not assigned"
can anyone help me in this
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by rajatchopra** [comment]
Did you still use the kube-flannel.yml from documentation? To deploy using daemonset?

**Comment by emilywwj** [comment]
I met the same problem here. Should we use this kube-flannel.yml file or not? How should we config the flannel.

**Comment by phanisowjanyavutukuri** [comment]
> the kube-flannel.yml from documentation? To deploy using daemonset?

yes I have used the same from the documentation

**Comment by phanisowjanyavutukuri** [comment]
> I met the same problem here. Should we use this kube-flannel.yml file or not? How should we config the flannel.

Actually I  have messed up with the weave and the flannel and reinstalled the flannel after completely removing the weavenet 
I got that working

**Comment by emilywwj** [comment]
> > I met the same problem here. Should we use this kube-flannel.yml file or not? How should we config the flannel.
> 
> Actually I have messed up with the weave and the flannel and reinstalled the flannel after completely removing the weavenet
> I got that working

I fix it too. I figured that my pods used weavenet already but I didn't know. That's why I failed to install kube-flannel here.
