### ISSUE TITLE
How to fix container network ping jitter

### ISSUE THREAD

**Issue by junhuihuang** [flannel-io/flannel#1107]
## Expected Behavior

No network jitter
## Current Behavior

ping time delay 1170ms, 146ms suddenly.

![image](https://user-images.githubusercontent.com/1772676/53167460-f210a880-3612-11e9-85b6-701c609d7f7c.png)

## Possible Solution

After try `mtr 172.18.101.15`, I found that the jitter may be caused by the destination node's flannel.1 device.

![image](https://user-images.githubusercontent.com/1772676/53167743-d22db480-3613-11e9-9ba9-c914edc9b844.png)

## Steps to Reproduce (for bugs)

1. Create two kubernetes Pods on two different Nodes, e.g. pod-a: 172.18.65.86, pod-b: 172.18.101.15
2. `kubectl exec -it pod-a bash`, then `ping 172.18.101.15`

## Your Environment

* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.9
* Kubernetes version (if used): v1.10.3
* Operating System and version: CoreOS 1855.5.0
* Link to your project (optional):

**Comment by rajatchopra** [comment]
Can you map corresponding cpu consumption for destination node? Just suspecting.

**Comment by junhuihuang** [comment]
Thanks for your reply. This is the corresponding cpu consumption.

![image](https://user-images.githubusercontent.com/1772676/54019261-b60a4580-41c5-11e9-9b28-3caf0f34f2ae.png)

**Comment by xiaods** [comment]
have a try to tcpdump to analysis the network packet.  @junhuihuang
