### ISSUE TITLE
Unable to get ipsec backend working on an AWS multi zone cluster

### ISSUE THREAD

**Issue by pms1969** [flannel-io/flannel#1110]
I've tried to get ipsec working on my kubernetes cluster, but to no avail.

Fresh out of the box, I can communicate pod -> pod, but not from pods running with `hostNetwork: true` . If I fiddle with the routes a bit, I can get host -> pod working but somehow lose pod-pod, and if I fiddle with the routes in other ways, I break everything horribly.

Could really use from help from someone more knowledgable that myself. :)

## Expected Behavior
I'd expect both host -> pod to pod -> pod to work straight out of the box, in a multi AZ setup.

## Current Behavior
doesn't work

## Possible Solution
I really have none.  I've been struggling with this for what seems like weeks now.

## Steps to Reproduce (for bugs)
1. Create a multi az kubernetes cluster in AWS
2. Add flannel networking with IPSEC
3. Add some host network pods and flannel network pods that are in different AZ's
4. Try and communicate between them.

## Context
Just want full encryption of my kubernetes network traffic.

## Your Environment
* Flannel version: 0.11.0
* Backend used (e.g. vxlan or udp): ipsec (with or without udp encapsulation)
* Etcd version: v3.3.12
* Kubernetes version (if used): 1.13.4
* Operating System and version: CoreOS

**Comment by ghouscht** [comment]
Same issue here. This issue is also a duplicate of https://github.com/coreos/flannel/issues/966.

**Comment by pms1969** [comment]
probably time to close this off.
