### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by sanyuepao** [flannel-io/flannel#1118]
kubectl apply -f  https://github.com/coreos/flannel/blob/v0.11.0/Documentation/kube-flannel.yml

error: error parsing https://github.com/coreos/flannel/blob/v0.11.0/Documentation/kube-flannel.yml: error converting YAML to JSON: yaml: line 526: mapping values are not allowed in this context

**Comment by csafg2** [comment]
You are not pointing to the file it self but the github url for that file.
try doing 
`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.11.0/Documentation/kube-flannel.yml`
