### ISSUE TITLE
Flannel Annotations "flannel.alpha.coreos.com" issue

### ISSUE THREAD

**Issue by janraj** [flannel-io/flannel#1122]
Creating a dummy node with following yaml which used to work earlier in flannel.

{
    "apiVersion": "v1",
    "kind": "Node",
    "metadata": {
        "annotations": {
            "flannel.alpha.coreos.com/backend-data": "{VtepMAC:aa:bb:cc:dd:ee}",
            "flannel.alpha.coreos.com/backend-type": "vxlan",
            "flannel.alpha.coreos.com/kube-subnet-manager": "true",
            "flannel.alpha.coreos.com/public-ip": "x.x.x.x",
            "node.alpha.kubernetes.io/ttl": "0"
        },
        "creationTimestamp": "2019-04-03T16:25:17Z",
        "labels": {
            "com.citrix.nodetype": "citrixadc"
        },
        "name": "citrixadc",
        "resourceVersion": "2110260",
        "selfLink": "/api/v1/nodes/citrixadc",
        "uid": "1160fbed-562d-11e9-a157-0050568fced6"
    },
    "spec": {
        "podCIDR": "10.200.254.1/24"
    },

Here we are having an External load balancer which can do VXLAN, so we were using dummy node in the cluster with PODCIDR and Node IP which is actually owned by the load balancer. This is used to work as the cluster creates routes and arp entries on all other nodes for the Public IP and PoDCidr IP. But in lates version flannel this does not happen.  Can somebody help how can we get it work?

**Comment by LabMenV** [comment]
@janraj  i use the k8s-bigip-ctlr as the load balancer, i don't know why flannel don't add the annotations: flannel.alpha.oreos.com/backend-data: '{"VtepMAC": "xx:xx:xx:xx:xx:xx"}'
if flannel missing the annotations, k8s-bigip-ctlr  nodepoller doesn't work and will never do the arps process
