### ISSUE TITLE
Flannel failing on UCP-3.1.4

### ISSUE THREAD

**Issue by Vikash082** [flannel-io/flannel#1125]
Using Flannel CNI with UCP-3.1.4. 

Pod -  `kube-flannel-ds-amd64-*` 
is failing with reason CrashLoopBackOff 

## Expected Behavior
It should come up without issue.

## Current Behavior
`CrashLoopBackOff`

Logs:

`
I0411 06:25:43.171285       1 main.go:514] Determining IP address of default interface
I0411 06:25:43.171778       1 main.go:527] Using interface with name ens5 and address 172.31.23.54
I0411 06:25:43.171793       1 main.go:544] Defaulting external address to interface address (172.31.23.54)
I0411 06:25:43.372374       1 kube.go:126] Waiting 10m0s for node controller to sync
I0411 06:25:43.372410       1 kube.go:309] Starting kube subnet manager
I0411 06:25:44.372523       1 kube.go:133] Node controller sync successful
I0411 06:25:44.372548       1 main.go:244] Created subnet manager: Kubernetes Subnet Manager - ip-172-31-23-54
I0411 06:25:44.372552       1 main.go:247] Installing signal handlers
I0411 06:25:44.372619       1 main.go:386] Found network config - Backend type: vxlan
I0411 06:25:44.372668       1 vxlan.go:120] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
E0411 06:25:44.372839       1 main.go:289] Error registering network: failed to acquire lease: node "ip-172-31-23-54" pod cidr not assigned
I0411 06:25:44.372856       1 main.go:366] Stopping shutdownHandler...
`

## Steps to Reproduce (for bugs)

CNI_URL="https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"

docker container run --rm -it --name ucp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  docker/ucp:3.1.4 install \
  --host-address <host address> \
  --cni-installer-url  ${CNI_URL} \
  --pod-cidr 10.244.0.0/16 \
  --unmanaged-cni true \
  --interactive

## Environment

* Kubernetes version (if used): v1.11.7-docker-1
* Operating System and version: Ubuntu-18.04

**Comment by trapier** [comment]
https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md#kubernetes-specific
