### ISSUE TITLE
s

### ISSUE THREAD

**Issue by kosalaat** [flannel-io/flannel#1139]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by morhook** [comment]
Is this just an issue created wrongly?

**Comment by kosalaat** [comment]
Definetely. I have no idea how this got here.
