### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by nicktming** [flannel-io/flannel#1143]
i tried to build flannel in centos7.6 following https://github.com/coreos/flannel/blob/master/Documentation/building.md, but it had errors :

go version: go version go1.11.5 linux/amd64

[root@vm1 flannel]# CGO_ENABLED=1 make dist/flanneld
go build -o dist/flanneld \
  -ldflags '-s -w -X github.com/coreos/flannel/version.Version=v0.10.0 -extldflags "-static"'
# github.com/coreos/flannel
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

make: *** [dist/flanneld] Error 2

is there any problems? thanks

**Comment by vorburger** [comment]
https://github.com/coreos/flannel/pull/1160 tells you how to fix this...
