### ISSUE TITLE
can not install flannel

### ISSUE THREAD

**Issue by cm527linux** [flannel-io/flannel#1147]
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
podsecuritypolicy.extensions/psp.flannel.unprivileged configured
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/flannel unchanged
serviceaccount/flannel unchanged
configmap/kube-flannel-cfg unchanged
daemonset.extensions/kube-flannel-ds-amd64 unchanged
daemonset.extensions/kube-flannel-ds-arm64 unchanged
daemonset.extensions/kube-flannel-ds-arm unchanged
daemonset.extensions/kube-flannel-ds-ppc64le unchanged
daemonset.extensions/kube-flannel-ds-s390x unchanged

[root@docker ~]# kubectl get pods -n kube-system
NAME                             READY   STATUS                  RESTARTS   AGE
coredns-fb8b8dccf-nfg6b          0/1     Pending                 0          53d
coredns-fb8b8dccf-zch5v          0/1     Pending                 0          53d
etcd-docker                      1/1     Running                 11         53d
kube-apiserver-docker            1/1     Running                 11         53d
kube-controller-manager-docker   1/1     Running                 16         53d
kube-flannel-ds-amd64-hjksp      0/1     Init:ImagePullBackOff   0          53d
kube-proxy-8bxlc                 1/1     Running                 12         53d
kube-scheduler-docker            1/1     Running                 14         53d

**Comment by cm527linux** [comment]
![image](https://user-images.githubusercontent.com/38172441/59661286-0d647c80-91dd-11e9-97ec-2ad0778553ec.png)

![image](https://user-images.githubusercontent.com/38172441/59661313-1ead8900-91dd-11e9-9a35-8b29e834f262.png)

**Comment by yuziqian** [comment]
I have the same problem ,i dont know how to deal with it.Did you already solve it?if yes,could you please teach me?

**Comment by cm527linux** [comment]
可以试下

curl -o kube-flannel.yml https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
sed -i "s/quay.io\/coreos\/flannel/quay-mirror.qiniu.com\/coreos\/flannel/g" kube-flannel.yml
kubectl apply -f kube-flannel.yml
rm -f kube-flannel.yml



cm864548597@163.com
 
From: yuziqian
Date: 2019-08-13 16:32
To: coreos/flannel
CC: cm527linux; Author
Subject: Re: [coreos/flannel] can not install flannel (#1147)
I have the same problem ,i dont know how to deal with it.Did you already solve it?if yes,could you please teach me?

**Comment by yuziqian** [comment]
现在才看到您的回复，非常感谢您的回答，我试一下



发自我的iPhone


------------------ Original ------------------
