### ISSUE TITLE
Kubernetes: Services not working

### ISSUE THREAD

**Issue by vorburger** [flannel-io/flannel#1164]
If you install Flannel as Kubernetes Networking Plugin using `https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml` on a simple single node cluster on a baremetal Fedora 30 Minimal server with containerd (from Fedora) created by `kubeadm init --pod-network-cidr=10.10.0.0/16`, then the kubedns pods (shown by `kubectl get pods -n kube-system`) remain in Status CrashLoopBackOff forever.

I've debugged this, and figured that it's because `kubectl logs -n kube-system coredns-...` hits `Get https://10.96.0.1:443/api/v1/namespaces?limit=500&resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host` ... here 10.96.0.1 is the IP which `kubectl get services` shows as the CLUSTER-IP for `kubernetes` - the apiserver service.

FYI when I install kube-router instead of Flannel using `kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml` this this works.

**Comment by rajatchopra** [comment]
@vorburger Can you also list the endpoints for the services?
```
kubectl get endpoints --all-namespaces```

Just to rule out the fact that kube-flannel.yml has a different network cidr than the one provided to kubelet.

**Comment by nielsbasjes** [comment]
Last few days I had (roughly) the same problem.
In my case the solution was to disable the firewalld .

**Comment by chinglinwen** [comment]
I've encounter the same, it need manual delete coredns pod ( so coredns restart ok ).
