### ISSUE TITLE
should flannel with vxlan reset docker0 to MTU=1450?

### ISSUE THREAD

**Issue by dvanduzer** [flannel-io/flannel#1171]
## Expected Behavior
docker-in-docker containers inherit MTU=1450 setting from vxlan-based eth0

## Current Behavior
docker-in-docker containers inherit MTU=1500 setting from docker0 bridge

## Steps to Reproduce (for bugs)
1. Spawn a container in the flannel-based cluster
2. Note that inside this container, eth0 has vxlan-appropriate MTU=1450
3. Execute a "docker build" command inside the container a la a CI/CD system
4. Note that the docker-in-docker container's eth0 has MTU=1500
5. Experience unfortunate path MTU discovery problems

## Context
We run "baremetal" Kubernetes clusters with the flannel CNI, and integrate with GitLab AutoDevOps to deploy some of our smaller support applications. A Kubernetes node's eth0 MTU is 1500, and its docker0 MTU is 1500. However any container spawned in the "normal way" sees FLANNEL_MTU, and docker correctly sets the interior eth0 to 1450.

When a GitLab CI build container runs, the docker-in-docker executor takes over, and the "middle layer" uses an MTU of 1450, but the innermost layer uses an MTU of 1500 instead. This is presumably because *that* invocation of docker doesn't use FLANNEL_MTU. This problem appears isolated to docker-in-docker situations. **The ultimate problem is that builds usually hang forever, because a package download gets in a [PMTUD black hole situation](https://en.wikipedia.org/wiki/Path_MTU_Discovery#cite_note-9).**

My options around this seem to be 1) Reconfigure Kubernetes docker daemon to always use FLANNEL_MTU or 2) Override GitLab CI to use FLANNEL_MTU in the docker:dind section.

Since it's only the docker-in-docker invocations that *aren't* seeing FLANNEL_MTU, option 1 doesn't seem quite right. But if option 2 is more semantically correct, it isn't clear how GitLab (or any CI) would know to discover FLANNEL_MTU.

## Your Environment
* Flannel version: 0.11.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.10
* Kubernetes version (if used): 1.14.2
* Operating System and version: Ubuntu Xenial host, Alpine build container / Alpine build target

**Comment by batmac** [comment]
same problem here.

**Comment by zedtux** [comment]
Jumping in too. Is there any workaround?
