### ISSUE TITLE
Couldn't fetch network config: 100: Key not found

### ISSUE THREAD

**Issue by jiangxiaoqiang** [flannel-io/flannel#1175]
I am starting flannel(v0.11.0) using this command,the etcd is v3:

`/root/flanneld -etcd-endpoints=https://172.19.104.231:2379,https://172.19.104.230:2379,https://172.19.150.82:2379 -etcd-prefix=/kube-centos/network -etcd-cafile=/etc/kubernetes/ssl/ca.pem -etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem -etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem`

## Expected Behavior

no error,and flannel run.

## Current Behavior

```
[root@iZuf63refzweg1d9dh94t8Z ~]# /root/flanneld -etcd-endpoints=https://172.19.104.231:2379,https://172.19.104.230:2379,https://172.19.150.82:2379 -etcd-prefix=/kube-centos/network -etcd-cafile=/etc/kubernetes/ssl/ca.pem -etcd-certfile=/etc/kubernetes/ssl/kubernetes.pem -etcd-keyfile=/etc/kubernetes/ssl/kubernetes-key.pem
I0908 20:27:17.652749    2331 main.go:514] Determining IP address of default interface
I0908 20:27:17.653154    2331 main.go:527] Using interface with name eth0 and address 172.19.104.231
I0908 20:27:17.653176    2331 main.go:544] Defaulting external address to interface address (172.19.104.231)
2019-09-08 20:27:17.653903 I | warning: ignoring ServerName for user-provided CA for backwards compatibility is deprecated
I0908 20:27:17.653968    2331 main.go:244] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0908 20:27:17.653975    2331 main.go:247] Installing signal handlers
E0908 20:27:17.671602    2331 main.go:382] Couldn't fetch network config: 100: Key not found (/kube-centos) [22]
timed out
E0908 20:27:18.680096    2331 main.go:382] Couldn't fetch network config: 100: Key not found (/kube-centos) [22]
timed out
E0908 20:27:19.688339    2331 main.go:382] Couldn't fetch network config: 100: Key not found (/kube-centos) [22]
```

## Possible Solution

Is flannel do not support etcd v3? Is there any other replace?The kubernetes recommand etcd v3

## Your Environment
* Flannel version:v0.11.0
* Backend used (e.g. vxlan or udp):vxlan
* Etcd version:  3.3.13
* Kubernetes version (if used):1.15.0
* Operating System and version: CentOS 7.6
* Link to your project (optional):

**Comment by likakuli** [comment]
Use etcd v2 api to set the specified key and its value. **DO NOT** use v3.
