### ISSUE TITLE
which code encoding shoud i use ?

### ISSUE THREAD

**Issue by 15838028035** [flannel-io/flannel#1189]
HI, i deploy k8s , down load flannel , 
save file as uninx utf-8

run kubeclt create command,

i  see kube node not ready .

systemctl  status kubelet,

logs 

● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 三 2019-09-25 19:45:54 CST; 12h ago
     Docs: https://kubernetes.io/docs/
 Main PID: 19841 (kubelet)
   Memory: 42.9M
   CGroup: /system.slice/kubelet.service
           └─19841 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --cgroup-driver=systemd --network-plugin=cni --pod...

9月 26 07:51:17 localhost.localdomain kubelet[19841]: W0926 07:51:17.784651   19841 cni.go:202] Error validating CNI config &{cbr0  false [0xc0005e3e20 0xc0005e3ea0] [123 10 32 32 34 110 97 109 101 34 58 32 34 99...112 101 34 58 3
9月 26 07:51:17 localhost.localdomain kubelet[19841]: W0926 07:51:17.784715   19841 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
9月 26 07:51:19 localhost.localdomain kubelet[19841]: E0926 07:51:19.500360   19841 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network pl...g uninitialized
9月 26 07:51:22 localhost.localdomain kubelet[19841]: W0926 07:51:22.786628   19841 cni.go:177] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: error parsing configuration: invalid character 'â' loo…object key string
9月 26 07:51:22 localhost.localdomain kubelet[19841]: W0926 07:51:22.790785   19841 cni.go:202] Error validating CNI config &{cbr0  false [0xc000b24140 0xc000b241c0] [123 10 32 32 34 110 97 109 101 34 58 32 34 99...112 101 34 58 3
9月 26 07:51:22 localhost.localdomain kubelet[19841]: W0926 07:51:22.790835   19841 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d
9月 26 07:51:24 localhost.localdomain kubelet[19841]: E0926 07:51:24.503933   19841 kubelet.go:2187] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network pl...g uninitialized
9月 26 07:51:27 localhost.localdomain kubelet[19841]: W0926 07:51:27.791415   19841 cni.go:177] Error loading CNI config file /etc/cni/net.d/10-flannel.conf: error parsing configuration: invalid character 'â' loo…object key string
9月 26 07:51:27 localhost.localdomain kubelet[19841]: W0926 07:51:27.795747   19841 cni.go:202] Error validating CNI config &{cbr0  false [0xc00101a320 0xc00101a3a0] [123 10 32 32 34 110 97 109 101 34 58 32 34 99...112 101 34 58 3
9月 26 07:51:27 localhost.localdomain kubelet[19841]: W0926 07:51:27.795804   19841 cni.go:237] Unable to update cni config: no valid networks found in /etc/cni/net.d

which code encoding shoud i use ?

**Comment by arasananbu** [comment]
Could you please paste the contents of /etc/cni/net.d/10-flannel.conf

That should give some idea.
