### ISSUE TITLE
How to disable NAT(Network Address Translation) strategy in flannel?  

### ISSUE THREAD

**Issue by mrbian** [flannel-io/flannel#1206]
## Question
How to disable NAT(Network Address Translation) strategy in flannel?  

## Description
I want to send IP packets to k8s' nodes outside of flannel's network. My packet is not TCP or UDP packets but IP packets, so the port mapping strategy is not suitable for me. I have to disable NAT in flannel, which API can I use?

**Comment by lylezxl** [comment]
I think it can be implemented by docker's custom iptables rules.
