### ISSUE TITLE
On service restart, Flannel (host-gw) on Windows is breaking inter-node pod connectivity.

### ISSUE THREAD

**Issue by daschott** [flannel-io/flannel#1208]
On service restart, Flannel (host-gw) on Windows is breaking inter-node pod connectivity.

## Expected Behavior
No changes after service restart

## Current Behavior
Inter-node pod connectivity breaking after service restart. Possibly Flannel is modifying the static routes.

## Steps to Reproduce (for bugs)

1. Launch Flannel in host-gw mode on 2 nodes
2. Launch pods on both
3. Restart Flannel
4. Try to connect the pods

## Your Environment

* Flannel version: v0.11.0
* Backend used (e.g. vxlan or udp): host-gw
* Etcd version:
* Kubernetes version (if used):
* Operating System and version: Windows Insider Builds (10.0.1876.0)
* Link to your project (optional):

**Comment by daschott** [comment]
cc @zawachte-msft

**Comment by dave-meier** [comment]
Any updates on this? I am running v0.12.0 of flannel on windows and trying to restart flannel to deal with detected failures accessing the internet and service name lookups. Restarting flannel is breaking existing pods, making them unable to lookup external dns entries. See root issue here: #1320 

So currently, everything goes well for about 6.5 hours, and then my test pods start failing to access the internet and resolve service names in the cluster. Restarting flannel fixes this, but breaks all existing windows pods, requiring the containers to be stopped. Once new containers are created they work correctly, but my services are disrupted while the new containers are initializing.
