### ISSUE TITLE
Error fetching backend: UDP backend is not supported on this architecture

### ISSUE THREAD

**Issue by wwj-2017-1117** [flannel-io/flannel#1221]
Error fetching backend: UDP backend is not supported on this architecture
## Expected Behavior

When I use flannel， I have encountered the following error: 
 #uname -a
aarch64 GNU/Linux

1. use "flannel-v0.11.0-linux-arm64.tar.gz"  ，
2. systemctl start flanneld  ，
3. Error fetching backend: UDP backend is not supported on this architecture
    Failed to start Flanneld overlay address etcd agent.

**Comment by fnikolai** [comment]
Any update on this issue?

**Comment by dingchenghong** [comment]
i got the same error, has anyone solved it?

**Comment by dingchenghong** [comment]
> i got the same error, has anyone solved it?

i had solved it,changed the default backend type to vxlan.(default:udp)
eg:
etcdctl put /coreos.com/network/config '{"Network":"10.0.0.0/16", "SubnetMin": "10.0.1.0", "SubnetMax": "10.0.20.0", "Backend": {"Type": "vxlan"}}'
