### ISSUE TITLE
Manually installing Flannel with the yaml file does not supply podCIDR

### ISSUE THREAD

**Issue by HankTheCrank** [flannel-io/flannel#1224]
I replaced my Kubernetes cluster Weave network with Flannel manually. I ran the command:

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

but the daemon set pods for flannel were failing due to no IP being assigned

## Expected Behavior

Pods should have received an IP

## Current Behavior

The error from the pod logs:
Error registering network: failed to acquire lease: node "k8node001" pod cidr not assigned

## Possible Solution

Running this corrects the problem:
kubectl patch node k8node001 -p '{"spec":{"podCIDR":"10.244.0.0/16"}}'

while I suspect this is something that could be included in the yaml, there may be a bigger issue. In the node spec, there already exists a spec named podCIDRs that contained the correct range.

## Steps to Reproduce (for bugs)

1. On an existing cluster with networking removed, run "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
2. Check the daemonset logs for errors
3. Run "kubectl patch node k8node001 -p '{"spec":{"podCIDR":"10.244.0.0/16"}}'" for each affected node
4. Errors stop

## Context

I had a compatibility issue with Weave, so I was changing the cluster network to Flannel

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by wajika** [comment]
I got the same problem, used the method you provided, solved it, thanks.

```
[root@k8s-master1 kubernetes]# kubectl get pods -n kube-system
NAME                    READY   STATUS             RESTARTS   AGE
kube-flannel-ds-h2z99   0/1     Error              1          17s
kube-flannel-ds-l9429   0/1     CrashLoopBackOff   1          17s
[root@k8s-master1 kubernetes]# kubectl logs kube-flannel-ds-h2z99 -nkube-system
I0318 01:00:09.490181       1 main.go:519] Determining IP address of default interface
I0318 01:00:09.490717       1 main.go:532] Using interface with name ens192 and address 192.168.10.213
I0318 01:00:09.490768       1 main.go:549] Defaulting external address to interface address (192.168.10.213)
W0318 01:00:09.490804       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0318 01:00:09.787858       1 kube.go:116] Waiting 10m0s for node controller to sync
I0318 01:00:09.788201       1 kube.go:299] Starting kube subnet manager
I0318 01:00:10.788211       1 kube.go:123] Node controller sync successful
I0318 01:00:10.788254       1 main.go:253] Created subnet manager: Kubernetes Subnet Manager - k8s-node2
I0318 01:00:10.788265       1 main.go:256] Installing signal handlers
I0318 01:00:10.788449       1 main.go:391] Found network config - Backend type: vxlan
I0318 01:00:10.788563       1 vxlan.go:123] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
E0318 01:00:10.789080       1 main.go:292] Error registering network: failed to acquire lease: node "k8s-node2" pod cidr not assigned
W0318 01:00:10.789399       1 reflector.go:424] github.com/coreos/flannel/subnet/kube/kube.go:300: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
I0318 01:00:10.789489       1 main.go:371] Stopping shutdownHandler...
[root@k8s-master1 kubernetes]# kubectl get nodes -o jsonpath='{.items[*].spec.podCIDR}'
```


In addition, I wonder why I need to set up a node podcidr separately. I used the hard way method to create the 1.19.2 cluster.

According to the configuration of network provided by flannel yaml, why didn't it take effect?
https://github.com/flannel-io/flannel/blob/master/Documentation/kube-flannel.yml

```
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

**Comment by maple10121** [comment]
I also encountered the same issue, which puzzled me for a long time. After using the command `kubectl patch node k8s2 -p '{"spec":{"podCIDR":"10.244.0.0/16"}}'` to assign a CIDR to each node, the pods worked normally. However, I don't understand why the CIDR defined in `flannel.yaml` and `kube-controller-manager.yaml` didn't take effect. Why is it necessary to manually assign a CIDR to each node?
