### ISSUE TITLE
no matches for kind "DaemonSet" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by a365541453** [flannel-io/flannel#1225]
K8S version 1.16  the following APIs are no longer served by default:
`daemonsets`

run
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-legacy.yml
```
display
`no matches for kind "DaemonSet" in version "extensions/v1beta1`

## Possible Solution
maybe need to change apiVersion
`apiVersion: extensions/v1beta1 -> apiVersion: apps/v1
`

## Your Environment

* Flannel version: flannel:v0.10.0-amd64
* Kubernetes version (if used): v1.16.2
* Operating System and version: arm bian 5.77

**Comment by dmitrytokarev** [comment]
This has been fixed by https://github.com/coreos/flannel/pull/1162

**Comment by MED-SALAH** [comment]
I am using kubctl 1.18 and i try to execute this command, but i have this error.
HOW I CAN FIX THAT PLEASE !!!!!!!!!!!!!!!!!

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml

ERRORS :
no matches for kind "DaemonSet" in version "extensions/v1beta1"

@dmitrytokarev 
@a365541453

**Comment by dmitrytokarev** [comment]
@MED-SALAH github is not the place for support. there is Slack and stackoverflow.
But I think you should be using latest released version of flannel:
https://github.com/coreos/flannel/blob/v0.12.0/Documentation/kube-flannel.yml

**Comment by MED-SALAH** [comment]
@dmitrytokarev  Thanks, Its work.

**Comment by kkonovodoff** [comment]
If someone still has this issue as I had, the solution for me was to use:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
(as documented in the README)
