### ISSUE TITLE
Error registering network: Link not found

### ISSUE THREAD

**Issue by NiLtheGazettE** [flannel-io/flannel#1226]
I follow the steps described in (https://docs.microsoft.com/en-us/virtualization/windowscontainers/kubernetes/network-topologies) and using this yaml file(https://github.com/Microsoft/SDN/blob/master/Kubernetes/flannel/overlay/manifests/kube-flannel-example.yml) to deploy flannel in k8s, but got the following exception.

=======================================================

I1119 08:21:20.033907       1 main.go:514] Determining IP address of default interface
I1119 08:21:20.035243       1 main.go:527] Using interface with name eth0 and address xx.xx.xx.xx
I1119 08:21:20.035311       1 main.go:544] Defaulting external address to interface address (xx.xx.xx.xx)
I1119 08:21:20.331998       1 kube.go:126] Waiting 10m0s for node controller to sync
I1119 08:21:20.332151       1 kube.go:309] Starting kube subnet manager
I1119 08:21:21.332413       1 kube.go:133] Node controller sync successful
I1119 08:21:21.332502       1 main.go:244] Created subnet manager: Kubernetes Subnet Manager - xx.xx.xx.xx
I1119 08:21:21.332513       1 main.go:247] Installing signal handlers
I1119 08:21:21.332646       1 main.go:386] Found network config - Backend type: vxlan
I1119 08:21:21.332899       1 vxlan.go:120] VXLAN config: VNI=4096 Port=4789 GBP=false DirectRouting=false
E1119 08:21:21.333316       1 main.go:289] Error registering network: Link not found
I1119 08:21:21.333373       1 main.go:366] Stopping shutdownHandler...

=======================================================

I also deployed k8s and flannel as the same operations on another machine, it works fine.
What is the cause of this error? I think I did the same configuration for both machines.

## Your Environment

* Flannel version: 0.11.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.10
* Kubernetes version (if used): 1.15.6
* Operating System and version: RHEL7.5

**Comment by ArtemAlagizov** [comment]
having the same issue, any updates?

**Comment by ggruber4711** [comment]
Also have this problem.
My Config:
- Kubernetes 1.18
- Node OS: Centos 7
