### ISSUE TITLE
Loss of performance 86% on 10Gbit links

### ISSUE THREAD

**Issue by strigazi** [flannel-io/flannel#1234]
When running iperf3 on the VMs performance is 9.40 gbps while when running iperf3 on pods which runs on the same nodes performance is 1.31 gbps. I tried another CNI and I have negligible performance loss.
 
Kubernetes is installed by hand.
Flannel is installed using:
https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml
net.bridge.bridge-nf-call-iptables is set to 1

## Your Environment
* Flannel version: v0.11.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: using kubernetes as backend
* Kubernetes version (if used): v1.15.3
* Operating System and version: Fedora 29
* Link to your project (optional):

**Comment by leezout** [comment]
Same problem here.

**Comment by xvzf** [comment]
Can you share more info on your hardware?

**Comment by leezout** [comment]
> Can you share more info on your hardware?

Server A (data server):
2x Intel Gold 5218 @ 2.30GHz
128GB RAM
NIC 10GbE MTU 9000

Server B (k8 node): 
2x Intel Xeon Gold 6128@ 3.40GHz
256GB RAM
NIC 2x 10GbE MTU 9000 bonded in Balance Round Robin

I have noticed if I remove the bonded NIC on my k8 node, I get results close to 10Gbps but if I use the bonding mode 0, I get around 3Gbps when I run iperf3.

**Comment by xvzf** [comment]
Can you try bonding the interface via `802.1ad` ? (you can do that pretty easily via iproute2)
I tried to replicate your issues on my test cluster (slower CPUs but 2x 10G Intel Nics) but there is no sign of bottlenecking.

**Comment by strigazi** [comment]
Thanks @xvzf , are you using vxlan?

**Comment by xvzf** [comment]
@strigazi yes I do

**Comment by strigazi** [comment]
> Can you share more info on your hardware?

I'm in VMs with linux bridge.

16 cores 120000 RAM (one full numa node Intel(R) Xeon(R) CPU E5-2683 v4 @ 2.10GHz ).
One Intel Corporation I350 Gigabit Network Connection (rev 01) per VM.

**Comment by xvzf** [comment]
@strigazi Do you have any monitoring on your cluster (more specific CPU Resources)?
But my nics (Intel X520) should be doing VXLAN offloading!

I am getting 9.6x Gbps between two containers

**Comment by strigazi** [comment]
> @strigazi Do you have any monitoring on your cluster (more specific CPU Resources)?
> But my nics (Intel X520) should be doing VXLAN offloading!
> 
> I am getting 9.6x Gbps between two containers

Are you in VMs or baremetal?

**Comment by xvzf** [comment]
@strigazi Bare metal

**Comment by Deep-Curiosity** [comment]
Same problem here.
