### ISSUE TITLE
error parsing https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml

### ISSUE THREAD

**Issue by AleksandrShkraba** [flannel-io/flannel#1248]
Facing next problem with flannel:
error: error parsing https://github.com/coreos/flannel/blob/master/Documentation/kube-flannel.yml: error converting YAML to JSON: yaml: line 112: mapping values are not allowed in this context
OS: CentOS 7

**Comment by seyfbarhoumi** [comment]
Having the same issue

**Comment by AleksandrShkraba** [comment]
> 
> 
> Having the same issue, looks like problem is when it's downloading
> I just copy paste the file content from the git repo to a file locally and used:
> kubectl apply -f kube-flannel.yml
> It solved the issue.

Use this link. It works nice.
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

**Comment by Techshrimp** [comment]
The reason is that the file format is inconsistent, so you need to log in to GitHub to copy the file content into the file, and using it directly will cause kubectl to use HTML files
