### ISSUE TITLE
IP masquerade & traffic destined outside of overlay network

### ISSUE THREAD

**Issue by ohmydata** [flannel-io/flannel#1253]
I have been using Flannel with Docker in our cluster. I enabled IP masquerade in my Flannel network in the hopes that all outbound traffic will see the host IP address and not the container IP address, but I still see my container IPs (private subnet) in the Firewall!! The Firewall rejects this traffic - I see this in the logs " access-list FLANNEL-IN denied tcp FLANNEL/172.20.17.5(34520)". This happens intermittently

## Expected Behavior
I was hoping the _ip-masq_ flag will masquerade all container IPs and replace with the host IPs, is my understanding correct? 

## Current Behavior
Intermittent ip-address "leak".

## Context
Firewall rejects traffic..

## Your Environment

* Flannel version: v0.11.0
* Backend used (e.g. vxlan or udp): vlan
* Etcd version: 3.3.11
* Docker version: 18.09.3
* Operating System and version: Ubuntu 16.04.6 LTS

**Comment by elnotcho** [comment]
Having similar on-prem issue where packets don't return to containers from public internet, but local LAN routing works fine.  --ip-masq is enabled in flannel daemonset.
Issue is intermittent and not reproduceable so difficult to troubleshoot.
