### ISSUE TITLE
Interpod communication failing running on different worker nodes

### ISSUE THREAD

**Issue by Sarang-Sangram** [flannel-io/flannel#1262]
Pods running on different worker nodes are not able to communicate with each other

## Expected Behavior
Pods running on different workers  should be able to ping each other

## Current Behavior
When I am trying to ping a pod running on workernode1 to pod running on workernode2, it fails.

Upon checking the logs of flannel pod I am getting below errors :

```
E0307 08:20:38.533747       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:20:44.677872       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:20:50.821769       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:20:53.893702       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:20:56.965772       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:21:00.037525       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:21:03.109595       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host
E0307 08:21:06.181565       1 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:310: Failed to list *v1.Node: Get https://10.96.0.1:443/api/v1/nodes?resourceVersion=0: dial tcp 10.96.0.1:443: connect: no route to host

```

## Steps to Reproduce (for bugs)
1.  sysctl net.bridge.bridge-nf-call-iptables=1
2. kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
3. kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml

## Your Environment

* Flannel version: flannel:v0.11.0-amd64
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: k8s.gcr.io/etcd:3.4.3-0
* Kubernetes version (if used): v1.17
* Operating System and version: CentOS Linux release 7.5.1804 , 5.5.2-1.el7

**Comment by rajatchopra** [comment]
Can you list the services on the cluster? `kubectl get svc --all-namespaces`
Then check if you can reach kube-apiserver from the host.

**Comment by bbc88ks** [comment]
@rajatchopra How is the subnet range chosen for each node with kube subnet manager? I've just had a fresh install from https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml and it seems that every node is using the first subnet from kubelet pod CIDR. 
This means that the same IP could be allocated for multiple pods on different nodes. I don't think the pod to pod across nodes can work with this setup.
In my case both nodes have the same subnet 10.244.0.1/16.
```
kubectl get pods -o wide --all-namespaces
kubernetes-external-secrets   kubernetes-external-secrets-8cf6bc649-4xtjm   1/1     Running     0          3h48m   10.244.0.16      ip-172-21-124-176.ec2.internal   <none>           <none>
orcha-ui                      workflow-controller-55f6dd7f4-xzqzt           1/1     Running     0          3h48m   10.244.0.16      ip-172-21-114-229.ec2.internal   <none>           <none>
```
