### ISSUE TITLE
Hi，Is this a bug when backend vxlan works in k8s service ipvs proxy mode?

### ISSUE THREAD

**Issue by leexiaominghub** [flannel-io/flannel#1266]
when I send a request to a pod on another node(named by node B) through k8s's service which works in ipvs proxy mode, 
the UDP packet sended by ensXXX has a udp check sum whose value is 0xFFFF, node B's ensXXX check the udp checksum and get a wrong sum, so the kernel of node B drop the packet.
Strangely, after several tries failed, the last packet have a 0x0000 check sum which means this packet has no check sum, and then node B at last gets this packet and send is to flanneld.
## Expected Behavior

I am not sure this wrong is made by flanneld or the kernel, could you help me? thanks a lot
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

Flannel version: I get the yaml file from :  wget https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
Backend : vxlan
k8s version :1.7.3
OS:CentOS 7.7

**Comment by rajatchopra** [comment]
Flannel does not modify the checksum generation behaviour in VxLAN mode.
I would suspect flannel is not set up correctly at NodeB. See https://tools.ietf.org/html/rfc7348, in the section on UDP Checksum: at the receiver side the packet must be submitted for decapsulation even with checksum '0'.

**Comment by leexiaominghub** [comment]
> Flannel does not modify the checksum generation behaviour in VxLAN mode.
> I would suspect flannel is not set up correctly at NodeB. See https://tools.ietf.org/html/rfc7348, in the section on UDP Checksum: at the receiver side the packet must be submitted for decapsulation even with checksum '0'.

Do you mean that Flannel just add a VxLAN header on the packet? The UDP header is added by knerl?
In my case, before node B  receive packet, the check sum of UDP header send by node A is 0xffff, which mean this is an avalible  check sum, so the kener of node B must check, after it checks, node B drop it.

**Comment by kilsilent** [comment]
hello , I met the same problem, did you solve it?
