### ISSUE TITLE
60 second delayed delivery of packet to pod

### ISSUE THREAD

**Issue by davesargrad** [flannel-io/flannel#1268]
I have a 2 node development cluster:  tonga and spain.
I have a simple test replicaset with 2 pods: kubia-unhealthy-r5kb1 (tonga), kubia-unhealty-thtds (spain) 

![image](https://user-images.githubusercontent.com/48793689/76680639-a71c5700-65c0-11ea-8ba7-8e66ca59e5d9.png)

When I curl the kubia-unhealthy service from within the cluster using its ClusterIP, the request arrives at the pod on the _other_ node with a 60 second delay.

Furthermore I've verified that the 60 seconds comes from a very regular retry behaviour with retries at: 1, 2, 4, 8, 16, and 32 seconds. The last retry succeeds. This is perfectly repeatable.

## Expected Behavior

curl 10.96.11.2:8080 should return promptly

## Current Behavior

I am able to curl each pod via its NodePort. The pod responds successfully to the request within a few milliseconds.
![image](https://user-images.githubusercontent.com/48793689/76680664-d206ab00-65c0-11ea-91d4-bc75032c4e0b.png)

However when I curl  the pod on spain from tonga, or when I curl the pod on tonga from spain using the Cluster-IP, it takes 60 seconds for the request to get to the pod, and for a proper response to be sent back. 
The delayed curl  
![image](https://user-images.githubusercontent.com/48793689/76680848-dcc23f80-65c2-11ea-9801-ebf004d523ee.png)

We do see a successful response from the pod at the end of the 60 second delay

The tcpdump shows the 1, 2, 4, 8, 16, 32 second retries on the associated SYN packet.
![image](https://user-images.githubusercontent.com/48793689/76680727-725ccf80-65c1-11ea-90e8-ff3d3acbc08d.png)

## Context
![image](https://user-images.githubusercontent.com/48793689/76680773-e7c8a000-65c1-11ea-95ab-7f7a01841e19.png)

## Your Environment

* Flannel version:
0.11
* Backend used (e.g. vxlan or udp):
vxlan
* Etcd version:
* Kubernetes version (if used):
1.17
* Operating System and version:
centos 7
* Link to your project (optional):

**Comment by gamer22026** [comment]
Maybe https://github.com/coreos/flannel/issues/1245 and https://github.com/coreos/flannel/issues/1243?

**Comment by davesargrad** [comment]
> Maybe #1245 and #1243?

@gamer22026 ... You Da Man!!

I tried the worka-around found within #1243 . That work-around worked for me. Specifically, for now,  I am using host-gw, rather than vxlan. I do think this is a problem with flannel version 0.11 in conjunction with K8S 1.17. 

I hope the flannel team can come up with a proper solution to this. I think this issue should be left open until a proper vxlan fix is in place.

**Comment by Gacko** [comment]
I guess this can be closed since the related issues have been fixed in Kubernetes.

**Comment by winkee01** [comment]
I don't think the issue has been resolved.
