### ISSUE TITLE
Access through clusterip very slow on other node but works well using nodePort

### ISSUE THREAD

**Issue by cy503328434** [flannel-io/flannel#1274]
I installed flannel like that

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

my svc:

kubectl get svc
NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
api-gateway NodePort 10.107.109.180 5555:30555/TCP 46m

when I curl 10.107.109.180:5555/test/1 for testing ,but responsing very slow in other node . more than 1 minute.
It works well using curl nodeip:30555/test/1

**Comment by kadisi** [comment]
@cy503328434 I had the same problem

**Comment by cy503328434** [comment]
@kadisi if you used aliyun, you can change the backend type with ali-vpc ```
"Backend": {
        "Type": "ali-vpc"
      }
```
It's words well on my k8s cluster.
