### ISSUE TITLE
Flannel does not work with iptables 1.8

### ISSUE THREAD

**Issue by dmitry-irtegov** [flannel-io/flannel#1306]
On CentOS 8, flannel 0.11 and 0.12 does not work.  The pod starts and shows healthy status, but pod->node and pod->pod connectivity between nodes is missing.

The flannel container log is filled with messages like:
```
E0615 13:46:02.007083       1 iptables.go:115] Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t nat -C POSTROUTING -s 100.96.0.0/11 -d 100.96.0.0/11 -j RETURN --wait]: exit status 3: modprobe: can't change directory to '/lib/modules': No such file or directory
iptables v1.8.3 (legacy): can't initialize iptables table `nat': Table does not exist (do you need to insmod?)
Perhaps iptables or your kernel needs to be upgraded.
```
This is probably similar to https://github.com/weaveworks/weave/issues/3465 , i.e. unability to correctly enable native (non-legacy) iptables mode.

## Expected Behavior
Flannel works with native iptables 1.8 on the node (RHeL/CentOS 8, Debian 10, Ubuntu 20.04) 

## Your Environment

* Flannel version: 0.11 and 0.12
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.3
* Kubernetes version (if used): 1.18.2
* Operating System and version: CentOS Linux release 8.1.1911
* Link to your project (optional): https://www.kublr.com

**Comment by volker-raschek** [comment]
Same issue with CentOS 7.8.2003, kubernetes 1.18.4

# Your Environment

- Flannel version: 011 and 0.12 
- Backend used (e.g. vxlan or udp): vxlan 
- Etcd version: 3.4.3
- Kubernetes version (if used): 1.18.4 
- Operating System and version: CentOS Linux release 7.8.2003

**Comment by Oats87** [comment]
@dmitry-irtegov what is the output of `lsmod` from the host on your system?

**Comment by volker-raschek** [comment]
Hey, 
I have found a solution for my problem. 

Here is the thread on [stackoverflow](https://stackoverflow.com/questions/62540512/k8s-1-18-1-api-not-reachable-since-update-to-1-18-1)

**Comment by Oats87** [comment]
> Hey,
> I have found a solution for my problem.
> 
> Here is the thread on [stackoverflow](https://stackoverflow.com/questions/62540512/k8s-1-18-1-api-not-reachable-since-update-to-1-18-1)

Flannel should work when privileged with CentOS 7.8, as by default CentOS 7.8 is using iptables binaries that program the ip_tables packet filter.

The original issue regarding Flannel complaining about a lack of /lib/modules sounds like an issue related to the (legacy) iptables binary attempting to load the legacy kernel modules, which is not necessarily desired behavior.

**Comment by dmitry-irtegov** [comment]
> @dmitry-irtegov what is the output of `lsmod` from the host on your system?
> 




> @dmitry-irtegov what is the output of `lsmod` from the host on your system?
> 
> I'm wondering if the `ip_tables` module isn't loaded on your system. Regardless, you'll probably hit incompatibility issues w/ CentOS 8 and RHEL 8 due to: #1317

> I'm wondering if the `ip_tables` module isn't loaded on your system. Regardless, you'll probably hit incompatibility issues w/ CentOS 8 and RHEL 8 due to: #1317

The issue is deeper than that.  

Yes, the message I received was on a machine where ip_tables was missing.  But as I understand, current versions of Flannel are hardcoded to use legacy iptables.  If you look at the autodetection code in kube-proxy and calico, (https://github.com/kubernetes/kubernetes/blob/623b6978866b5d3790d17ff13601ef9e7e4f4bf0/build/debian-iptables/iptables-wrapper#L28 and https://github.com/projectcalico/felix/blob/954cc9b5cf62e63583d404adc5e04dd0e5ad6be3/iptables/feature_detect.go#L166) you will see that they count legacy-iptables rules, and switch to legacy mode when there are > 10 legacy rules.  So flannel could force both of them to legacy mode.

I actually confirmed that if I setup canal CNI plugin on CentOS 8 (with ip_tables preloaded), it indeed forces calico to legacy mode.  Which is not a good thing (IMO).

**Comment by Oats87** [comment]
@dmitry-irtegov I'm well aware of that logic for switching between them and opened a PR into this repo a few days ago to implement it: https://github.com/coreos/flannel/pull/1318 

Unfortunately, due to a flaky test (which I also opened a PR for) the CI/make will fail, but you can resolve it by cherry-picking the fix here: https://github.com/coreos/flannel/pull/1319

I was specifically looking at your reported issue, which was related to the error message that was received by trying to use the legacy binaries on a host system that does not have `ip_tables` loaded.
