### ISSUE TITLE
How to deploy more than 254 pods on just one node?

### ISSUE THREAD

**Issue by liocveei** [flannel-io/flannel#1309]
Hi, guys.
When I deploy 300 pods on each node of my cluster with Kubernetes, I got this error:
`network: failed to allocate for range 0: no IP addresses available in range set: 10.0.1.1-10.0.1.254`
Is there any solution to solve this issue? Or it is just designed working like this? And why?
I've tried everything I can...
Thank you!

* Flannel version: v0.12.0-amd64

**Comment by volker-raschek** [comment]
It may be that your network range is set too low. This should have been specified by kubeadm init as a parameter with flag --pod-network-cidr. The recommended value is 10.244.0.0/16.

**Comment by liocveei** [comment]
> It may be that your network range is set too low. This should have been specified by kubeadm init as a parameter with flag --pod-network-cidr. The recommended value is 10.244.0.0/16.

I have tried this. But it didn't work. 
The cni0 configuration is like this:
`cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.244.0.1  netmask 255.255.255.0  broadcast 0.0.0.0
`
even with the parameter `--pod-network-cidr=10.244.0.0/16`

I don't know if this has something to do with my problem.

If I change the netmask to 255.255.0.0 of cni0 manually and deploy more than 254 pods, I will get this ERROR:
`"cni0" already has an IP address different from 10.244.0.1/24`

So, I'm stuck by this. I don't know how to enlarge the network range of the pods deployed by Kubernets.

**Comment by povsister** [comment]
`ETCDCTL_API=2 etcdctl get /coreos.com/network/config`
> {"Network":"172.16.0.0/16","SubnetLen":24,"Backend":{"Type":"host-gw"}}

Change the `SubnetLen`.
Modify `Network` if you want more nodes.

**Comment by jiangytcn** [comment]
SO, for kubernetes integration, CNI is configured to use `host-local` and bridge mode for container networking. which means that, all ip addresses created/used are stored in `/var/lib/cni/networks/$NETWORK_NAME`.  If the pods within the node have **less** than /24,  try delete the obsolete files in that directory, for examples 30days, or even delete them all and restart the kubelet, that should fix the problem. 
But if you want to deploy **more** than /24 pods in a single node, I'm not sure if that supported to update subnet in day-02, perhaps need some manual  interactions in both host and kubernetes side

https://www.cni.dev/plugins/ipam/host-local/
https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/

**Comment by brettmilford** [comment]
@jiangytcn are you saying that it is by design that 'used' ip addresses are never cleaned up and need to be manually removed?
I think that is what you're saying, and I think [0] is indicating that as well.

[0] https://www.cni.dev/plugins/current/ipam/host-local/#files

**Comment by jiangytcn** [comment]
> @jiangytcn are you saying that it is by design that 'used' ip addresses are never cleaned up and need to be manually removed?
> I think that is what you're saying, and I think [0] is indicating that as well.
> 
> [0] https://www.cni.dev/plugins/current/ipam/host-local/#files

I'm not sure if that is by design, I didn't find  reconciling job in place to clean up IP resources, but perhaps didn't find  right place. In summary, manually cleanup always help and unblock application development.
