### ISSUE TITLE
k8s on AWS with Windows worker nodes (host-gw) -- flannel disruption every 6.5 hours

### ISSUE THREAD

**Issue by dave-meier** [flannel-io/flannel#1320]
I have a roll my own deployment of a k8s cluster on AWS, using Ubuntu for the master and 3 Windows 1909 Server Core Work nodes. I am using a build of flanneld for windows that I did at the end of May 2020 (flannel -version: **v0.12.0-6-g48564971**). Kubernetes version 1.18.3. Docker version 19.03.5. I periodically deploy windows test pods to check internet access and service name lookups. I am using host-gw mode with flannel. All nodes are in the same subnet, and src/dest checking is disabled on the nodes.

## Expected Behavior

The cluster should continue to work correctly and test pods should indicate that internet access works and service name lookups work.

## Current Behavior

After about 6.5 hours, my test pods start to report that internet access and service name lookups are failing from inside the test containers. If I restart flanneld at this point, the tests start passing again. After another 6.5 hours, then same cycle repeats, with internet access and service name lookups failing again.

## Steps to Reproduce (for bugs)

1. Deploy a k8s cluster on AWS with Ubuntu as the master and Windows nodes as the workers.
2. Ensure all nodes are in the same subnet and src/dest checking is disabled.
3. Wait 6.5 hours or slightly more.
4. Deploy a test windows pod and check internet access with: kubectl exec $container_name -- powershell.exe curl "http://www.google.com" -UseBasicParsing -DisableKeepAlive
5. Deploy a test windows pod and check service name lookup with: kubectl exec $container_name -- powershell.exe curl "http://${service_name}" -UseBasicParsing -DisableKeepAlive)

Steps 4 and 5 will fail. Restart flanneld. To restart, I am running code taken from Microsoft's SDN helper.psm1 to CleanupOldNetwork before starting flanneld again. So the procedure is: stop flanneld process;CleanupOldNetwork;start flanneld process. Now the test pods will pass the tests in step 4 and 5, until another 6.5 hours passes.

## Context

Trying to keep a production cluster running with no disruptions.

## Your Environment

* Flannel version: v0.12.0-6-g48564971
* Ubuntu Flannel pod version: v0.12.0-amd64
* Backend used (e.g. vxlan or udp): host-gw
* Etcd version:
* Kubernetes version (if used): 1.18.3
* Operating System and version: Ubuntu 18.04, Windows 1909 Server Core
* Link to your project (optional):

**Comment by EagleIJoe** [comment]
This _could_ be related: https://github.com/moby/moby/issues/40998#issuecomment-651795006

KB4551853 screws up my connections reproducibly.
