### ISSUE TITLE
Building flannel- consultation question

### ISSUE THREAD

**Issue by imabelli** [flannel-io/flannel#1324]
**Can I change Flannel Alpine base image to Debian 9 (iptables compatibility is of concern)**

The Dockerfile builds iptables into the image. The dist/iptables-wrapper-installer.sh script says it "installs a wrapper iptables script in a container that will figure out whether iptables-legacy or iptables-nft is in use on the host and then replaces itself with the correct underlying iptables version."

Is this to say that k8s iptables operations are done by the iptables package inside of the container, and not the iptables package on the host? I want to replace flannel's Alpine base image with Debian 9, and there is no iptables-nft package on Debian 9. However, I have iptables-nft on the host. The Dockerfile will build, but I need to pass the `--no-sanity-check-` argument to the script. Is it safe to change the base image when using Flannel for k8s?

**Comment by Oats87** [comment]
The Flannel-required `iptables` manipulation for Kubernetes is done by utilizing the userspace binaries from within the Flannel image. The `iptables-wrapper-installer.sh` script installs a helper script that is capable of manipulating the userspace of the Flannel container, to swap the necessary `iptables` binary into place depending on what the script detects. There should be no major issue with using Debian 9 as a base image for Flannel, although I have not explicitly tested this myself and can not give any guarantees.

You have two options for using Debian 9 as a base image -- 
1. Comment out the `iptables-wrapper-installer.sh` sections of the Dockerfile/discard them, and simply use the `iptables` package that is installed by Debian 9, thus using the backend of `iptables` that Debian 9 installs. Upon a quick test, it looks like Debian Stretch (9) ships with `iptables 1.6.0`, which is using the `legacy` backend. This should be OK for systems that are also using `iptables legacy` on the backend, i.e. this will not work well on CentOS 8/RHEL 8/Debian Buster (10), but will work on Ubuntu, Debian Stretch, CentOS 7/RHEL 7, etc. as long as the host level binaries are programming in legacy (`ip_tables`) rules.
2. Figure out how to install both `iptables` into the Debian 9 image. This is a bit more complicated, but if you do this, you'll have compatibility with both legacy and nftables systems.

It's important to keep your host network namespace operating with the same packet filter implementation, i.e. all `ip_tables`/`legacy` or all `nftables`

Does this help answer your question?
