### ISSUE TITLE
SUBNETLEN  not working

### ISSUE THREAD

**Issue by crazy-canux** [flannel-io/flannel#1328]
subnetlen not working.

## Expected Behavior
I want to fix pod IP address from 10.244.0.1 -> 10.244.0.64.

## Current Behavior
sublen always 24.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
1. deploy kubeadm with flannel.
$ sudo kubeadm init --kubernetes-version=v1.18.6 --pod-network-cidr=10.244.0.0/16  -v=6

2. customize kube-flannel.yaml.
    {
      "Network": "10.244.0.0/16",
      "SubnetLen": 26,
      "SubnetMin": "10.244.0.0",
      "SubnetMax": "10.244.20.0",
      "Backend": {
        "Type": "vxlan"
      }
    }

3.  not effective
cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

## Your Environment

* Flannel version:  1.12
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:  
* Kubernetes version (if used): 1.18.6
* Operating System and version: ubuntu16.04
* Link to your project (optional):

**Comment by yunshangdetianya** [comment]
Changing the subnet mask of the POD is not changed in flannel, you need to change it in kube-control, change the configuration item to --node-cidr-mask-size=26 and then you need to re-add node to the cluster to take effect, I It has been verified.

**Comment by crazy-canux** [comment]
@yunshangdetianya   Do you know how to change "--node-cidr-mask-size" with kubeadm?

I got another issue, may be the same.

{
"Network": "10.0.0.0/8",
"SubnetLen": 16,
"SubnetMin": "10.0.0.0",
"SubnetMax": "10.20.0.0",
"Backend": {
"Type": "vxlan"
}
}

cni0 always 24, not 16.

**Comment by yunshangdetianya** [comment]
You can try as follows：
################################
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
kubernetesVersion: v1.16.0
controllerManager:
  extraArgs:
      node-cidr-mask-size: "26"

#####################

**Comment by crazy-canux** [comment]
@yunshangdetianya 

```
controllerManager:
  extraArgs:
    allocate-node-cidrs: 'true'
    node-cidr-mask-size: '16'
    cluster-cidr: '10.0.0.0/8'
```


I tried this. It's works. 
But, this makes the pod can't access external network.

```
cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.0.0.0/8
FLANNEL_SUBNET=10.0.0.1/16
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```

```
 ifconfig cni0
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
        inet 10.0.0.1  netmask 255.255.0.0  broadcast 10.0.255.255
        ether d6:65:3d:6e:7a:a3  txqueuelen 1000  (Ethernet)
        RX packets 317081  bytes 22572812 (22.5 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 254379  bytes 91988805 (91.9 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```



```
k8s@debug:~$ kubectl -n capture exec -it all-in-one-57c9bff478-6lc2k -- /bin/bash
root@all-in-one-57c9bff478-6lc2k:/# ifconfig
eth0      Link encap:Ethernet  HWaddr 7e:7c:8d:e2:93:7f
          inet addr:10.0.0.8  Bcast:10.0.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:1450  Metric:1
          RX packets:989 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1178 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:144574 (144.5 KB)  TX bytes:156245 (156.2 KB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:112 errors:0 dropped:0 overruns:0 frame:0
          TX packets:112 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:11936 (11.9 KB)  TX bytes:11936 (11.9 KB)

root@all-in-one-57c9bff478-6lc2k:/# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.0.1        0.0.0.0         UG    0      0        0 eth0
10.0.0.0        0.0.0.0         255.255.0.0     U     0      0        0 eth0
10.0.0.0        10.0.0.1        255.0.0.0       UG    0      0        0 eth0
```

**Comment by crazy-canux** [comment]
Chain KUBE-POSTROUTING (1 references)
num  target     prot opt source               destination
1    RETURN     all  --  anywhere             anywhere             mark match ! 0x4000/0x4000
2    MARK       all  --  anywhere             anywhere             MARK xor 0x4000
3    MASQUERADE  all  --  anywhere             anywhere             /* kubernetes service traffic requiring SNAT */


delete " RETURN     all  --  anywhere             anywhere             mark match ! 0x4000/0x4000" can fix this.

don't know why.

**Comment by yunshangdetianya** [comment]
Before reinitializing the cluster nodes
1. All iptables rules should be cleared
2. Clear all ipvs rules
3. You can use the following command to execute before the initial node
# iptables -P FORWARD ACCEPT
# iptables -F
# ipvsadm -C

**Comment by crazy-canux** [comment]
@yunshangdetianya  not that problem.
I think it's a bug.

before use kubeadm I clean iptables.
after kubeadm init with my configuration.
I got 3 rules in "KUBE-POSTROUTING".
But, if use default configuration, it's only 1 rule.

Chain KUBE-POSTROUTING (1 references)
 pkts bytes target     prot opt in     out     source               destination
   85  5313 RETURN     all  --  *      *       0.0.0.0/0            0.0.0.0/0            mark match ! 0x4000/0x4000
    0     0 MARK       all  --  *      *       0.0.0.0/0            0.0.0.0/0            MARK xor 0x4000
    0     0 MASQUERADE  all  --  *      *       0.0.0.0/0            0.0.0.0/0            /* kubernetes service traffic requiring SNAT */

**Comment by yunshangdetianya** [comment]
I think you are right
