### ISSUE TITLE
Propagate client real ip to pods

### ISSUE THREAD

**Issue by a2z-ice** [flannel-io/flannel#1333]
I have kubernetes cluster with once master ndoe and two worker nodes and I need to track client real ip address. But unfortunately in my pods I  am always getting ip address of cni0 gateway, which are 10.244.1.1  for node-1 10.244.2.1 for node-2. Is there any way where I can configure flannel in such way so that it can propagate the client's real-ip to pods. Please help me. I installed kubernetes on baremetal and flannel as CNI plugins.

**Comment by w7team** [comment]
i have a same question
