### ISSUE TITLE
iptables cleanup does not accomodate rule ordering or duplicates

### ISSUE THREAD

**Issue by scoof** [flannel-io/flannel#1337]
## Expected Behavior
For reasons unknown to us (probably due to an upgrade of canal/flannel), we've ended up with duplicate MASQ rules:
```
-A POSTROUTING -s $ClusterSubnet ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s $ClusterSubnet -d $ClusterSubnet -j MASQUERADE
-A POSTROUTING -s $ClusterSubnet -d $ClusterSubnet -j RETURN
-A POSTROUTING -s $ClusterSubnet ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s $ClusterSubnet -d $PodCIDR -j RETURN
-A POSTROUTING ! -s $ClusterSubnet -d $ClusterSubnet -j MASQUERADE
```
We expect flannel to discover this during iptables-resync.

## Current Behavior
Flannel finds all the required rules, and does not execute a resync, because it does not consider ordering or duplicates.

## Possible Solution
Consider ordering and duplicates in ensureIPTables

## Steps to Reproduce (for bugs)
Add an additional MASQUERADE rule before the RETURN rule. Flannel will not clean up this rule.

## Context
Having all traffic natted will break e.g. NetworkPolicies

## Your Environment
* Flannel version: 0.11
* Backend used (e.g. vxlan or udp): vxlan

**Comment by fengzixu** [comment]
same issue in flannel 0.9.0. We are still investigating root cause and finding trouble scenario

**Comment by LabMenV** [comment]
We find the same issue in our environment，i checked the flannel/iptables.go，It looks like when the flannel restart the teardownIPTables function meet the xtables.lock and just delete some of the rules. 
`func teardownIPTables(ipt IPTables, rules []IPTablesRule) error {
	for _, rule := range rules {
		log.Info("Deleting iptables rule: ", strings.Join(rule.rulespec, " "))
		err := ipt.Delete(rule.table, rule.chain, rule.rulespec...)
		if err != nil {
			e := err.(IPTablesError)
			// If this error is because the rule is already deleted, the message from iptables will be
			// "Bad rule (does a matching rule exist in that chain?)". These are safe to ignore.
			// However other errors (like EAGAIN caused by other things not respecting the xtables.lock)
			// should halt the ensure process.  Otherwise rules can get out of order when a rule we think
			// is deleted is actually still in the chain.
			// This will leave the rules incomplete until the next successful reconciliation loop.
			if !e.IsNotExist() {
				return err
			}
		}
	}

	return nil
}`

**Comment by LabMenV** [comment]
We find the same issue in our environment，i checked the flannel/iptables.go，It looks like when the flannel restart the teardownIPTables function meet the xtables.lock and just delete some of the rules.
```
func teardownIPTables(ipt IPTables, rules []IPTablesRule) error {
	for _, rule := range rules {
		log.Info("Deleting iptables rule: ", strings.Join(rule.rulespec, " "))
		err := ipt.Delete(rule.table, rule.chain, rule.rulespec...)
		if err != nil {
			e := err.(IPTablesError)
			// If this error is because the rule is already deleted, the message from iptables will be
			// "Bad rule (does a matching rule exist in that chain?)". These are safe to ignore.
			// However other errors (like EAGAIN caused by other things not respecting the xtables.lock)
			// should halt the ensure process.  Otherwise rules can get out of order when a rule we think
			// is deleted is actually still in the chain.
			// This will leave the rules incomplete until the next successful reconciliation loop.
			if !e.IsNotExist() {
				return err
			}
		}
	}

	return nil
}
```

**Comment by LabMenV** [comment]
I found another error in logs, I saw the following logs like this when I restart the flannel.
main.go:335] Current network or subnet (10.42.0.0/16, 10.42.X.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
```
iptables.og:167] Deleting iptables rule: -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
iptables.og:167] Deleting iptables rule: -s 0.0.0.0/0  ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
iptables.og:167] Deleting iptables rule: ! -s 0.0.0.0/0 -d 0.0.0.0/0 -j RETURN
iptables.og:167] Deleting iptables rule: ! -s 0.0.0.0/0  -d 0.0.0.0/0 -j MASQUERADE --random-fully
main.go:305] Setting up masking rules
main.go:313] Changing default FORWARD chain policy to ACCEPT
main.go:321] Worte subnet file to /run/flannel/subnet.env
main.go:325] Running backend.
main.go:343] Waiting for all goroutines to exit
vxlan_network.go:60] watching for new subnet leases
iptables.go:145] Some iptables rules are missing ; deleting and recreating rules
iptables.og:167] Deleting iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
iptables.og:167] Deleting iptables rule: -s 10.42.0.0/16  ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
iptables.og:167] Deleting iptables rule: ! -s 10.42.0.0/16 -d 10.42.X.0/24 -j RETURN
iptables.og:167] Deleting iptables rule: ! -s 10.42.0.0/16  -d 10.42.0.0/16 -j MASQUERADE --random-fully
iptables.og:155] Adding iptables rule: -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
iptables.og:155] Adding iptables rule: -s 10.42.0.0/16  ! -d 224.0.0.0/4 -j MASQUERADE --random-fully
iptables.og:155] Adding iptables rule: ! -s 10.42.0.0/16 -d 10.42.X.0/24 -j RETURN
iptables.og:155] Adding iptables rule: ! -s 10.42.0.0/16  -d 10.42.0.0/16 -j MASQUERADE --random-fully
```
our enviroment iptables doesn't support --random-fully.  Iptables rules generation for all nodes without --random-fully , like this :
```
-A POSTROUTING -s 10.42.0.0/16  ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.42.0.0/16  -d 10.42.0.0/16 -j MASQUERADE
-A POSTROUTING -s 10.42.0.0/16 -d 10.42.0.0/16 -j RETURN
-A POSTROUTING -s 10.42.0.0/16  ! -d 224.0.0.0/4 -j MASQUERADE
-A POSTROUTING ! -s 10.42.0.0/16 -d 10.42.X.0/24 -j RETURN
-A POSTROUTING ! -s 10.42.0.0/16  -d 10.42.0.0/16 -j MASQUERADE
```
