### ISSUE TITLE
ClusterRole & ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+!

### ISSUE THREAD

**Issue by PontusTideman** [flannel-io/flannel#1349]
## Expected Behavior

To be updated?

## Current Behavior

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding`

## Possible Solution

Update the code?

## Steps to Reproduce (for bugs)

1. kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 
2. Ends up with the above warnings!
3.
4.

## Context

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding`

## Your Environment

* Flannel version: 0.12.0
* Backend used (e.g. vxlan or udp): udp
* Etcd version: -
* Kubernetes version (if used): v1.19.2
* Operating System and version: Debian 10
* Link to your project (optional): -

**Comment by PontusTideman** [comment]
So, now I find out that there's a PR for it here: [https://github.com/coreos/flannel/pull/1342](url). But still the [https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml](url) points to the beta version.

**Comment by mveroone** [comment]
Same today with a brand new kubernetes 1.23 and latest Flannel manifests
