### ISSUE TITLE
Failed to find any valid interface to use: failed to get default interface: Unable to find default route

### ISSUE THREAD

**Issue by sukhibrar** [flannel-io/flannel#1353]
kube-system   kube-flannel-ds-qp5j2                  0/1     CrashLoopBackOff

I0929 05:14:00.544880       1 main.go:518] Determining IP address of default interface
E0929 05:14:00.545157       1 main.go:204] Failed to find any valid interface to use: failed to get default interface: Unable to find default route
---------------------------------------------------
kubectl-1.19.2-0.x86_64
kubernetes-cni-0.8.7-0.x86_64
kubeadm-1.19.2-0.x86_64
kubelet-1.19.2-0.x86_64

2 nodes master and 1 node is worker. Issue is when joining worker node. 

kubeadm init --control-plane-endpoint "vip-k8s-master:8443" --upload-certs --pod-network-cidr=10.244.0.0/16
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

Any help is much appreciated.

**Comment by HugoRh** [comment]
Hi,

It's probably too late for you , but since I faced the same issue, let me share what I did to fix.
So the message is very literally the error, no interface has been defined as the default one on your host.

So here's the host routing table , no gateway defined to 0.0.0.0
```
# /sbin/route -n  
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

As root, add the IP adress of my NIC ( eth0 : 10.5.45.152 )
```
# /sbin/route add  default gw 10.5.45.152
```

After adding the default gateway, flannel did start correctly :
```
# /sbin/route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.5.45.152   0.0.0.0         UG    0      0        0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U     0      0        0 eth0
10.233.66.0     10.233.66.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.68.0     10.233.68.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.70.0     10.233.70.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.72.0     10.233.72.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.75.0     10.233.75.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.76.0     10.233.76.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.77.0     10.233.77.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.81.0     10.233.81.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.83.0     10.233.83.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.91.0     10.233.91.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.92.0     10.233.92.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.95.0     10.233.95.0     255.255.255.0   UG    0      0        0 flannel.1
10.233.102.0    10.233.102.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.105.0    10.233.105.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.106.0    10.233.106.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.115.0    10.233.115.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.116.0    10.233.116.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.117.0    10.233.117.0    255.255.255.0   UG    0      0        0 flannel.1
10.233.122.0    10.233.122.0    255.255.255.0   UG    0      0        0 flannel.1
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

**Comment by ghwns9652** [comment]
@HugoRh  Thank you! This was very helpful for me.

**Comment by txfs19260817** [comment]
@HugoRh Thank you for your awesome solution! But I wonder if you know how to make it take effective permanently, since I have to reconfigure it again after every reboot?

**Comment by HugoRh** [comment]
> @HugoRh Thank you for your awesome solution! But I wonder if you know how to make it take effective permanently, since I have to reconfigure it again after every reboot?

Hi!

You just defined a route on your system.
It will remain after a reboot, so you don't have to do anything!

Cheers!

**Comment by phauge** [comment]
@HugoRh  👍
