### ISSUE TITLE
Flannel vxlan windows network creation and Failed to list from api-server

### ISSUE THREAD

**Issue by jsturtevant** [flannel-io/flannel#1359]
Since https://github.com/coreos/flannel/pull/1137 the creation of the external Network by HNS isn't strictly needed but there seems there is a timing issue with Flannel creating the network though:

```
 VXLAN config: Name=flannel.4096 MacPrefix=0E-2A VNI=4096 Port=4789 GBP=false DirectRouting=false
I1015 19:49:28.607933    3888 device_windows.go:116] Attempting to create HostComputeNetwork &{ flannel.4096 Overlay [] {[]} { [] [] []} [{Static [{10.244.3.0/24 [[123 34 84 121 112 101 34 58 34 86 83 73 68 34 44 34 83 101 116 116 105 110 103 115 34 58 123 34 73 115 111 108 97 116 105 111 110 73 100 34 58 52 48 57 54 125 125]] [{10.244.3.1 0.0.0.0/0 0}]}]}] 8 {2 0}}
E1015 19:49:29.505093    3888 streamwatcher.go:109] Unable to decode an event from the watch stream: read tcp 10.1.0.7:51596->20.51.70.218:6443: wsarecv: An established connection was aborted by the software in your host machine.
E1015 19:49:29.505093    3888 reflector.go:304] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to watch *v1.Node: Get https://test-1-4f45b6ec.westus2.cloudapp.azure.com:6443/api/v1/nodes?resourceVersion=36886&timeoutSeconds=582&watch=true: http2: no cached connection was available
E1015 19:49:30.508286    3888 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://test-1-4f45b6ec.westus2.cloudapp.azure.com:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E1015 19:49:31.511558    3888 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://test-1-4f45b6ec.westus2.cloudapp.azure.com:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E1015 19:49:32.525475    3888 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://test-1-4f45b6ec.westus2.cloudapp.azure.com:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
E1015 19:49:33.538736    3888 reflector.go:201] github.com/coreos/flannel/subnet/kube/kube.go:307: Failed to list *v1.Node: Get https://test-1-4f45b6ec.westus2.cloudapp.azure.com:6443/api/v1/nodes?resourceVersion=0: http2: no cached connection was available
I1015 19:49:33.886774    3888 device_windows.go:124] Waiting to get ManagementIP from HostComputeNetwork flannel.4096
I1015 19:49:34.387900    3888 device_windows.go:136] Waiting to get net interface for HostComputeNetwork flannel.4096 (10.1.0.7)
```
Here we see it creating the network and starting to list the Kubernetes nodes via the golang client. The flannel network takes some time and causes a network hicup when first creating the VM switch (see this comment). The network blip causes the connection to the apiserver to get into a bad cached state as defined in coreos/flannel#1272.  This is similar to https://github.com/coreos/flannel/issues/1272 in that it the rote cause is kubernetes/client-go#374.

## Expected Behavior

If a new network is created it should be able to connect to the api-server.

## Possible Solution

1. Upgrading to go 1.15 and configuring resets properly: https://github.com/kubernetes/client-go/issues/374#issuecomment-632457187

2. Waiting to list the nodes until after network is fully up:
I1015 19:49:33.886774    3888 device_windows.go:124] Waiting to get ManagementIP from HostComputeNetwork flannel.4096
I1015 19:49:34.387900    3888 device_windows.go:136] Waiting to get net interface for HostComputeNetwork flannel.4096 (10.1.0.7)

3. Reset connections like kubelet and other cni's kubernetes/kubernetes#78016 and AliyunContainerService/terway#87

## Steps to Reproduce (for bugs)

Start flannel with out the an existing switch set up.

## Context

https://github.com/kubernetes-sigs/sig-windows-tools/issues/103
https://github.com/kubernetes-sigs/sig-windows-tools/issues/83

## Your Environment

* Flannel version: 0.12
* Backend used (e.g. vxlan or udp): vxlan (but i happens with host-gw as well)
* Etcd version:
* Kubernetes version (if used): 1.19.1 or 1.19.2
* Operating System and version: windows
* Link to your project (optional):
https://github.com/kubernetes-sigs/sig-windows-tools/issues/103#issuecomment-709426828

**Comment by jfrenhub** [comment]
`vim /etc/kubernetes/manifests/kube-controller-manager.yaml`
```
    - --kube-api-qps=100
    - --kube-api-burst=100
```
I did that and the error didn't go away

**Comment by jsturtevant** [comment]
I test with the `0.13.1-rc1` release that bumped the client go in #1372 that the connection to the api-server gets reset properly. I am no longer seeing the `Failed to watch *v1.Node` after the network creation
