### ISSUE TITLE
Windows: Cannot reach service running on host IP from inside a container

### ISSUE THREAD

**Issue by DerrickMartinez** [flannel-io/flannel#1369]
## Expected Behavior
From within a pod running on Windows, cannot reach a service running on the Host. For example: 10.130.43.4:8080. Pod service network is in a different subnet and the Pod can reach different hosts on the same subnet as the host. Example: 10.130.43.3:8080. 

## Current Behavior
From a pod, try to curl a service running on the host. 

C:\>curl 10.130.43.225:9182
curl: (7) Failed to connect to 10.130.43.225 port 9182: Timed out

Rolling back to 0.11.0 fixes it.

## Context
We use `windows_exporter` running within wins.exe, and is scraped by Prometheus. When we're unable to hit services running on localhost like `windows_exporter`, we cannot easily get metrics.

## Your Environment
* Flannel version: 0.13.0
* Backend used: vxlan
* Etcd version: 3.4.3
* Kubernetes version (if used): 1.19.4
* Operating System and version: Windows 1909

**Comment by Keith-Mange** [comment]
Just to verify the only difference between the working and non working case is Flannel 0.11.0 vs 0.13.0?  Are all the other components the same?

**Comment by DerrickMartinez** [comment]
Sorry for the late reply. Yes all components are the same, version is the only difference.

**Comment by Keith-Mange** [comment]
Does restarting Flannel fix it?  We're aware of issues with Flannel starting up before HNS is ready.

**Comment by DerrickMartinez** [comment]
No, it doesn't help
