### ISSUE TITLE
Flannel Cause IO High

### ISSUE THREAD

**Issue by xvdy** [flannel-io/flannel#1374]
![image](https://user-images.githubusercontent.com/12590255/99514653-f6741c00-29c6-11eb-9409-e4ea75e9a14c.png)

why flannel read so many data from disk?

I use opensnoop to find which file is reading, it show blow:
![image](https://user-images.githubusercontent.com/12590255/99515499-fe808b80-29c7-11eb-9acf-f0ee7d219433.png)

## Your Environment

* Flannel version:v0.10.0-amd64
* Backend used (e.g. vxlan or udp): hostgw
* Etcd version: v3.2.23
* Kubernetes version (if used): 1.16
* Operating System and version: centos 7.3
* Link to your project (optional):

**Comment by openstack-test** [comment]
We had the same problem. How did you deal with it? Why

**Comment by xvdy** [comment]
给 Flannel 的内存调大一点

**Comment by wwj-2017-1117** [comment]
We had the same problem.
