### ISSUE TITLE
Issues with deploying pod network on Ubuntu 20.04

### ISSUE THREAD

**Issue by purimetla** [flannel-io/flannel#1377]
While deploying the pod network, the command used on the master node: 
`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/k8s-manifests/kube-flannel-rbac.yml
`
resulted in the following warnings:
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRole is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRole
clusterrole.rbac.authorization.k8s.io/flannel unchanged
Warning: rbac.authorization.k8s.io/v1beta1 ClusterRoleBinding is deprecated in v1.17+, unavailable in v1.22+; use rbac.authorization.k8s.io/v1 ClusterRoleBinding
clusterrolebinding.rbac.authorization.k8s.io/flannel unchanged

## Expected Behavior

Unable to deploy Flannel network because of the warnings. Checking kubectl get pods -all-namespaces results in 
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
kube-system   kube-flannel-ds-2ffvh                       0/1     CrashLoopBackOff    9          24m

Expected Behavior is
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
kube-system   kube-flannel-ds-2ffvh                       0/1     Running    9          24m

This should be up and running.

## Possible Solution
Not sure if this has been addressed as part of this PR: https://github.com/coreos/flannel/issues/1349

## Steps to Reproduce (for bugs)

1.kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version: Ubunto 20.04
* Link to your project (optional):

**Comment by purimetla** [comment]
Please let me know if you need any further details.

**Comment by AleksandrNull** [comment]
@purimetla Can you please add logs from the pod ?
like kubectl logs -n kube-system kube-flannel-ds-2ffvh

Thanks!

**Comment by luthermonson** [comment]
@purimetla hi any updates on this with logs? might close this as stale as we can't really reproduce.

**Comment by SHELA** [comment]
`ERROR: logging before flag.Parse: I0131 15:01:03.064526       1 main.go:519] Determining IP address of default interface
ERROR: logging before flag.Parse: I0131 15:01:03.159814       1 main.go:532] Using interface with name eno1 and address xx.xx.xx.xx
ERROR: logging before flag.Parse: I0131 15:01:03.159862       1 main.go:549] Defaulting external address to interface address (xx.xx.xx.xx)
W0131 15:01:03.159907       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
ERROR: logging before flag.Parse: I0131 15:01:03.467367       1 kube.go:116] Waiting 10m0s for node controller to sync
ERROR: logging before flag.Parse: I0131 15:01:03.467461       1 kube.go:299] Starting kube subnet manager
ERROR: logging before flag.Parse: I0131 15:01:04.467614       1 kube.go:123] Node controller sync successful
ERROR: logging before flag.Parse: I0131 15:01:04.467677       1 main.go:253] Created subnet manager: Kubernetes Subnet Manager - kub
ERROR: logging before flag.Parse: I0131 15:01:04.467699       1 main.go:256] Installing signal handlers
ERROR: logging before flag.Parse: I0131 15:01:04.467916       1 main.go:391] Found network config - Backend type: vxlan
ERROR: logging before flag.Parse: I0131 15:01:04.468087       1 vxlan.go:123] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
ERROR: logging before flag.Parse: E0131 15:01:04.468756       1 main.go:292] Error registering network: failed to acquire lease: node "kub" pod cidr not assigned
ERROR: logging before flag.Parse: I0131 15:01:04.468822       1 main.go:371] Stopping shutdownHandler...`

**Comment by AleksandrNull** [comment]
Looks like you have a typo in config somewhere. Please share your both flannel and k8s PODCIDR configs.
