### ISSUE TITLE
Pod-to-Pod connectivity issues with Windows worker nodes on Hyper-V

### ISSUE THREAD

**Issue by dustyjump** [flannel-io/flannel#1394]
Environment information:

- Node A:
	- Pod A

- Node B:
	- Pod B

A TCP SYN arrives Node A with a port mapping for Pod B.

Node A correctly VXLAN encapsulates the TCP SYN and sends the traffic to Node B via UDP port 4789.

The TCP SYN correctly gets decapsulated and sent to Pod B.

Pod B responds with a TCP SYN ACK.

Due to a missing VFP rule for traffic encapsulation, the packet gets sent out onto the wire without VXLAN encapsulation.

The client sends TCP retransmissions but because the TCP SYN ACK is never re-encapsulated and sent back to Node A, the connection fails.

## Expected Behavior
The TCP SYN ACK from Pod B should be re-encapsulated and sent back to Node A.

## Current Behavior
The TCP SYN ACK from Pod B is dropped on the network since the container IP addresses are not publicly routable.

## Possible Solution
This should have a encapsulation rule to handle this traffic as there is no encapsulation rule for traffic on the way back out from Pod B.

Something similar to this:

```
    RULE : EXAMPLE_RULE_10.244.4.0_24
        Friendly name : EXAMPLE_RULE_10.244.4.0_24
        Priority : 10
        Flags : 1 terminating 
        Type : routeencap
        Conditions:
            Destination IP : 10.244.4.0-10.244.4.255
        Flow TTL: 0
        Rule Data:
        Encap Type: VXLAN
        Fixing inner MAC
        Using source PA MAC
        Decrementing TTL
        Encap Source IP : 192.168.1.24
        Encap Destination(s) : 
            { IP address=192.168.1.25, MAC address=00-15-5D-CC-DA-D8, GRE key=4096 }
```

## Steps to Reproduce (for bugs)

I followed the instructions found here [https://kubernetes.io/ja/docs/setup/production-environment/windows/user-guide-windows-nodes/](url) 

For the sake of being thorough, here are the steps in a bit more detail:
1. Install Docker
```
#Install Docker
Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force | Out-Null
Install-Module -Name DockerMsftProvider -Repository PSGallery -Force | Out-Null
Install-Package -Name docker -ProviderName DockerMSFTProvider -Force -RequiredVersion 19.03 | Out-Null

#reboot server
Restart-Computer -Force
```
2. Prepare node to join Kubernetes cluster:
```
#pull image
docker pull "mcr.microsoft.com/windows/nanoserver:1809"
#tag it as "latest"
docker tag "mcr.microsoft.com/windows/nanoserver:1809" "microsoft/nanoserver:latest"
#run the container
docker run "microsoft/nanoserver:latest"

mkdir c:\k | Out-Null

#prompt for Linux master node IP and Linux master node admin user credential
$masterNodeIp = Read-Host -prompt "   Please provide the IP address of the Linux master node: "
$LinuxAdmin = Get-Credential -Message "Please provide the username and password of the admin on the Linux master node"

#use Posh-SSH to transfer Kube config file over to Windows node
Install-Module -Name Posh-SSH -Force -Confirm:$false | Out-Null
Get-SCPFile -ComputerName $masterNodeIp -Credential $LinuxAdmin -RemoteFile "/home/k8s_admin/.kube/config" -LocalFile 'C:\k\config' -AcceptKey

#download 7zip to manage file decompression
Invoke-WebRequest https://www.7-zip.org/a/7z1900-x64.exe -o c:\7zip.exe

c:\7zip.exe /S
#Set environment variables for 7-zip so it can be referenced from console
$env:Path += ";C:\Program Files\7-Zip"
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\7-Zip", [EnvironmentVariableTarget]::Machine)

#download Kubernetes binaries
Invoke-WebRequest https://dl.k8s.io/v1.19.3/kubernetes-node-windows-amd64.tar.gz -o c:\kubernetes-node-windows-amd64.tar.gz

Set-Location c:\
tar.exe xzvf .\kubernetes-node-windows-amd64.tar.gz

Copy-Item -Path c:\kubernetes\node\bin\*.* -Destination c:\k

$env:Path += ";C:\k"
[Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\k", [EnvironmentVariableTarget]::Machine)
$env:KUBECONFIG = "C:\k\config"
[Environment]::SetEnvironmentVariable("KUBECONFIG", "C:\k\config", [EnvironmentVariableTarget]::User)

#Flannel prep
#Download start.ps1 to c:\k
Invoke-WebRequest https://raw.githubusercontent.com/Microsoft/SDN/master/Kubernetes/flannel/start.ps1 -o c:\k\start.ps1
#modify start.ps1
Set-Location c:\k

$flannelPattern = "/master/Kubernetes/windows/install.ps1"
(Get-Content .\start.ps1) |
Foreach-Object {
	$_ # send the current line to output
	if ($_ -match $flannelPattern)
	{
		#Add Lines after the selected pattern 
		""
		'# Added to update flannel to 0.13.0'
		'$fline = Get-Content .\install.ps1 | Select-String download/v0.11.0/flanneld.exe | Select-Object -ExpandProperty Line'
		'$newfLine = "    DownloadFile -Url  `"https://github.com/coreos/flannel/releases/download/v0.13.0/flanneld.exe`" -Destination `$BaseDir\flanneld.exe"'
		'$fcontent = Get-Content .\install.ps1'
		'$fcontent.Replace($fline,$newfline) | Set-Content .\install.ps1'
	}
} | Set-Content .\start.ps1
```
3. Join Windows server to Kubernetes cluster
```
$windowsNodeIp = Get-NetIPAddress | Where-Object { $_.addressfamily -eq "ipv4" -and $_.interfacealias -notlike "*loopback*" -and $_.interfacealias -notlike "*nat*" } | Select-Object -ExpandProperty ipaddress

Set-Location c:\k
.\start.ps1 -ManagementIP $windowsNodeIp -NetworkMode overlay -ClusterCIDR 10.244.0.0/16 -ServiceCIDR 10.96.0.0/12 -KubeDnsServiceIP 10.96.0.10 -InterfaceName Ethernet -LogDir C:\k\logs

```
4. Once the Kubelet, Kube-Proxy, and Flanneld processes are running (in the new Powershell windows), I run the following in a new admin Powershell window to make them Windows services:
```
Get-Process -Name kubelet | Stop-Process
Get-Process -Name kube-proxy | Stop-Process
Get-Process -Name flanneld | Stop-Process

Invoke-WebRequest https://nssm.cc/release/nssm-2.24.zip -o c:\nssm-2.24.zip

Set-Location c:\
7z.exe x .\nssm-2.24.zip

Copy-Item -Path c:\nssm-2.24\win64\nssm.exe -Destination c:\k

#download script to register Kubernetes' windows services
Invoke-WebRequest https://raw.githubusercontent.com/microsoft/SDN/master/Kubernetes/flannel/register-svc.ps1 -o c:\k\register-svc.ps1

Set-Location c:\k
.\register-svc.ps1 -NetworkMode overlay -ManagementIP $windowsNodeIp -ClusterCIDR 10.244.0.0/16 -KubeDnsServiceIP 10.96.0.10 -LogDir C:\k\logs

#check to make that all services are running
get-service -name @("kube*", "flannel*")

Restart-Computer -Force
```

## Context

This is causing traffic via the overlay network to be unusable.

Any SLB or Service VIP that sends traffic that is destined for a pod that is not located on the Node it arrives on will run into this issue.

It is worth noting that we have created a replica of this environment, using the same exact commands, in a VMWare hypervisor and do not experience this issue. 

## Your Environment

* Flannel version: v0.13.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: k8s.gcr.io/etcd:3.4.13-0
* Kubernetes version (if used): v1.19.3
* Operating System and version: Linux -- Ubuntu 20.04 ; Microsoft -- Windows Server 1809 (10.0.17763.1637)
* NLB: BIG-IP F5 using port translation (as an example 443 to Nodeport TCP port 31234)
* MAC Spoofing is Enabled on the VMs
* Link to your project (optional):

**Comment by daschott** [comment]
The instructions being used are outdated. The current instructions are here:
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/adding-windows-nodes/

FlannelD daemon is responsible for creating such REMOTESUBNETROUTE rules that are missing. What are the FlannelD logs showing on the erroneous node?
