### ISSUE TITLE
Windows pods cannot access hosts on local network

### ISSUE THREAD

**Issue by TonyNoble** [flannel-io/flannel#1405]
On a freshly-built cluster with Centos master node and Windows 2019 Core worker nodes, pods started on the worker nodes are unable to connect to hosts on our local network.

## Expected Behavior

`curl http://host.on.my.network` should connect and retrieve data

## Current Behavior

Using the 'win-webserver' example deployment:
Controller node -> internal network communications succeed
Worker node -> internal network communications succeed
Pod -> pod and pod -> service communications (using curl) succeed
Pod -> outside world communications (using curl) succeed
Pod -> internal network communications (on the same /8 subnet as the cluster) time out 

## Steps to Reproduce (for bugs)

1. Run windows webserver demo: https://kubernetes.io/docs/setup/production-environment/windows/user-guide-windows-containers/
2. Connect to one of the pods created: `kubectl exec -it <pod-name> -- powershell`
3. Verify outside world connectivity: 
```
PS C:\> curl www.google.com -UseBasicParsing -Method:Head


StatusCode        : 200
StatusDescription : OK
```
4. Attempt to connect to host on local network:
```
PS C:\> nslookup my.local.application.host
Server:  kube-dns.kube-system.svc.cluster.local
Address:  10.96.0.10

Non-authoritative answer:
Name:    my.local.application.host
Address:  10.105.166.21

PS C:\> curl https://10.105.166.21 -UseBasicParsing -Method:Head
curl : Unable to connect to the remote server
At line:1 char:1
+ curl https://10.105.166.21 -UseBasicParsing -Method:Head
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

## Your Environment

* Flannel version: v0.13.1-rc1 (controller),  v0.13.0-nanoserver (windows nodes)
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.13-0
* Kubernetes version (if used): 1.20.1
* Operating System and version: CentOS Linux release 7.9.2009 (controller), Windows 2019 Build 1809 (nodes)
* Link to your project (optional):

**Comment by alexnastas** [comment]
Hi Tony, 
I have a similar situation where I can't ping hosts in the outside world. I can successfully ping between containers in the overlay, but whenever I try to ping other hosts on the local network, or on the internet - it doesn't work. However, curl works. Tcpdump gives "ICMP protocol unreachable" message, quite confusing. 

I was wondering if you ever found the cause of your issue?
