### ISSUE TITLE
 Failed to create SubnetManager: error retrieving pod spec for xxxxx;  the version of kubernetes cluster is unified to v1.19.0

### ISSUE THREAD

**Issue by YuZongYangHi** [flannel-io/flannel#1409]
I have encountered this problem at present, the version of kubernetes cluster is unified to v1.19.0

_Originally posted by @YuZongYangHi in https://github.com/coreos/flannel/issues/671#issuecomment-774587922_

**Comment by YuZongYangHi** [comment]
Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-d47s4': Get "https://10.96.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-d47s4": dial tcp 10.96.0.1:443: i/o timeout

**Comment by YuZongYangHi** [comment]
[root@kubernetes-1 cni]# kubectl  get node
NAME           STATUS   ROLES                  AGE   VERSION
kubernetes-1   Ready    control-plane,master   44h   v1.19.0
kubernetes-2   Ready    <none>                 42h   v1.19.0
[root@kubernetes-1 cni]# kubectl  get pod -n kube-system -l app=flannel
NAME                    READY   STATUS    RESTARTS   AGE
kube-flannel-ds-7cdd8   1/1     Running   0          5m28s
kube-flannel-ds-d47s4   1/1     Running   5          5m28s

**Comment by YuZongYangHi** [comment]
current kube-flannel-ds-d47s4 pool restart

**Comment by YuZongYangHi** [comment]
![image](https://user-images.githubusercontent.com/35584408/107136288-cb9dc200-693c-11eb-8e31-85b0394a0e36.png)

**Comment by vincentmli** [comment]
it looks your flannel pod fail to connect to  10.96.0.1:443, is 10.96.0.1:443 the cluster services to kube api server ? try kubectl get svc -o wide, examine your iptable rules...etc

**Comment by YuZongYangHi** [comment]
I tried any method, but I didn’t get the result I wanted. Some people said that the rbac of flannel was not released, but it did not work. It is worth noting that the flannel on the master of the two nodes can run normally, but the second The station seems to be broken!

**Comment by YuZongYangHi** [comment]
I upgraded the overall version of k8s to 1.19.6 and solved it. No one found a solution to this problem of 1.19.0. At least in my opinion, rbac and iptables are fine.

**Comment by vincentmli** [comment]
> I tried any method, but I didn’t get the result I wanted. Some people said that the rbac of flannel was not released, but it did not work. It is worth noting that the flannel on the master of the two nodes can run normally, but the second The station seems to be broken!

I recall I had such problem before and I changed some setting in kube-flannel yaml (hostnetwork: true maybe, I can't recall) to make it work

**Comment by vincentmli** [comment]
> I upgraded the overall version of k8s to 1.19.6 and solved it. No one found a solution to this problem of 1.19.0. At least in my opinion, rbac and iptables are fine.

I still suspect iptables rules that are deployed by the k8s could cause the problem, you could compare the iptable rules between 1.19.6 and 1.19.0, and it may show some differences. anyway if  you really want to find out the root cause, just my 2 cents.

**Comment by useadmin-jany** [comment]
My K8S network has been unable to get up, and I can't find a solution
