### ISSUE TITLE
Is there possibility that flannel can connect to ConnectX-5 to use its vxlan implementation to offload?

### ISSUE THREAD

**Issue by zzylol** [flannel-io/flannel#1410]
Hi,
I am wondering whether flannel's performance can be improved by using vxlan ability of ConnectX-5 to offload?
Thanks.

**Comment by Oats87** [comment]
The short answer is yes.

On a Linux system, Flannel is simply creating the underlying `vxlan` devices on the host system. If you have the correct drivers installed/hw vxlan offloading is already enabled, vxlan traffic between nodes should already be offloaded.

**Comment by zzylol** [comment]
Thanks so much.

**Comment by zzylol** [comment]
Hi, thanks so much. I am testing the performance of two containers in different nodes. How can I confirm that flannel-vxlan backend has been offloaded by ConnectX-5? I have ConnectX-5 on two nodes. 

Thanks.

**Comment by zzylol** [comment]
Thx, I verified this by using ethtool -K $DEV tx-udp_tnl-segmentation [on, off] for ConnectX-4 family NIC.
