### ISSUE TITLE
network plugin is not ready: cni config uninitialized

### ISSUE THREAD

**Issue by skycastlelily** [flannel-io/flannel#1413]
the cluster's status is still Notready after I install a Pod network by running:
  kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

## Current Behavior
[root@dell-r330-9 ~]# kubeadm init --pod-network-cidr=10.244.0.0/16
...
kubeadm join 10.37.192.20:6443 --token 7ci5de.gab7mka2nvcsf3v1 \
    --discovery-token-ca-cert-hash sha256:8f344862d2a3f5f352330851962f67a0f0ce93fe57cf97f83506483cdf108cc8 
[root@dell-r330-9 ~]# export KUBECONFIG=/etc/kubernetes/admin.conf
[root@dell-r330-9 ~]# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
podsecuritypolicy.policy/psp.flannel.unprivileged created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.apps/kube-flannel-ds created
[root@dell-r330-9 ~]# kubectl get nodes
NAME                                STATUS     ROLES                  AGE   VERSION
dell-r330-9.gsslab.brq.redhat.com   NotReady   control-plane,master   16m   v1.20.4
[root@dell-r330-9 ~]# kubectl describe node dell-r330-9.gsslab.brq.redhat.com
Name:               dell-r330-9.gsslab.brq.redhat.com
Roles:              control-plane,master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=dell-r330-9.gsslab.brq.redhat.com
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/control-plane=
                    node-role.kubernetes.io/master=
Annotations:        flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"6e:b4:49:87:71:b4"}
                    flannel.alpha.coreos.com/backend-type: vxlan
                    flannel.alpha.coreos.com/kube-subnet-manager: true
                    flannel.alpha.coreos.com/public-ip: 10.37.192.20
                    kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Thu, 25 Feb 2021 09:55:36 +0100
Taints:             node-role.kubernetes.io/master:NoSchedule
                    node.kubernetes.io/not-ready:NoSchedule
Unschedulable:      false
Lease:
  HolderIdentity:  dell-r330-9.gsslab.brq.redhat.com
  AcquireTime:     <unset>
  RenewTime:       Thu, 25 Feb 2021 10:12:41 +0100
Conditions:
  Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
  ----                 ------  -----------------                 ------------------                ------                       -------
  NetworkUnavailable   False   Thu, 25 Feb 2021 10:12:26 +0100   Thu, 25 Feb 2021 10:12:26 +0100   FlannelIsUp                  Flannel is running on this node
  MemoryPressure       False   Thu, 25 Feb 2021 10:10:50 +0100   Thu, 25 Feb 2021 09:55:36 +0100   KubeletHasSufficientMemory   kubelet has sufficient memory available
  DiskPressure         False   Thu, 25 Feb 2021 10:10:50 +0100   Thu, 25 Feb 2021 09:55:36 +0100   KubeletHasNoDiskPressure     kubelet has no disk pressure
  PIDPressure          False   Thu, 25 Feb 2021 10:10:50 +0100   Thu, 25 Feb 2021 09:55:36 +0100   KubeletHasSufficientPID      kubelet has sufficient PID available
  Ready                False   Thu, 25 Feb 2021 10:10:50 +0100   Thu, 25 Feb 2021 09:55:36 +0100   KubeletNotReady              runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized
Addresses:
  InternalIP:  10.37.192.20
  Hostname:    dell-r330-9.gsslab.brq.redhat.com
Capacity:
  cpu:                4
  ephemeral-storage:  15350Mi
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32702412Ki
  pods:               110
Allocatable:
  cpu:                4
  ephemeral-storage:  14486077417
  hugepages-1Gi:      0
  hugepages-2Mi:      0
  memory:             32600012Ki
  pods:               110
System Info:
  Machine ID:                 115bb5a7ee054f378b59d1d81d19e5b3
  System UUID:                4c4c4544-0032-4410-8044-c8c04f5a4732
  Boot ID:                    7a21ded7-86c3-48b3-999e-9bb485c298bb
  Kernel Version:             5.11.0-156.fc34.x86_64
  OS Image:                   Fedora 34 (Thirty Four Prerelease)
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://19.3.13
  Kubelet Version:            v1.20.4
  Kube-Proxy Version:         v1.20.4
PodCIDR:                      10.244.0.0/24
PodCIDRs:                     10.244.0.0/24
Non-terminated Pods:          (6 in total)
  Namespace                   Name                                                         CPU Requests  CPU Limits  Memory Requests  Memory Limits  AGE
  ---------                   ----                                                         ------------  ----------  ---------------  -------------  ---
  kube-system                 etcd-dell-r330-9.gsslab.brq.redhat.com                       100m (2%)     0 (0%)      100Mi (0%)       0 (0%)         17m
  kube-system                 kube-apiserver-dell-r330-9.gsslab.brq.redhat.com             250m (6%)     0 (0%)      0 (0%)           0 (0%)         17m
  kube-system                 kube-controller-manager-dell-r330-9.gsslab.brq.redhat.com    200m (5%)     0 (0%)      0 (0%)           0 (0%)         17m
  kube-system                 kube-flannel-ds-r8nzm                                        100m (2%)     100m (2%)   50Mi (0%)        50Mi (0%)      25s
  kube-system                 kube-proxy-fdsnx                                             0 (0%)        0 (0%)      0 (0%)           0 (0%)         16m
  kube-system                 kube-scheduler-dell-r330-9.gsslab.brq.redhat.com             100m (2%)     0 (0%)      0 (0%)           0 (0%)         17m
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource           Requests    Limits
  --------           --------    ------
  cpu                750m (18%)  100m (2%)
  memory             150Mi (0%)  50Mi (0%)
  ephemeral-storage  100Mi (0%)  0 (0%)
  hugepages-1Gi      0 (0%)      0 (0%)
  hugepages-2Mi      0 (0%)      0 (0%)
Events:
  Type    Reason                   Age   From        Message
  ----    ------                   ----  ----        -------
  Normal  Starting                 18m   kubelet     Starting kubelet.
  Normal  NodeHasSufficientMemory  18m   kubelet     Node dell-r330-9.gsslab.brq.redhat.com status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    18m   kubelet     Node dell-r330-9.gsslab.brq.redhat.com status is now: NodeHasNoDiskPressure
  Normal  Starting                 17m   kubelet     Starting kubelet.
  Normal  NodeAllocatableEnforced  17m   kubelet     Updated Node Allocatable limit across pods
  Normal  NodeHasSufficientMemory  17m   kubelet     Node dell-r330-9.gsslab.brq.redhat.com status is now: NodeHasSufficientMemory
  Normal  NodeHasNoDiskPressure    17m   kubelet     Node dell-r330-9.gsslab.brq.redhat.com status is now: NodeHasNoDiskPressure
  Normal  NodeHasSufficientPID     17m   kubelet     Node dell-r330-9.gsslab.brq.redhat.com status is now: NodeHasSufficientPID
  Normal  Starting                 16m   kube-proxy  Starting kube-proxy.

## Your Environment
* Flannel version: 
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):v1.20.4
* Operating System and version:fedora-34
* Link to your project (optional):

**Comment by Oats87** [comment]
Are there any relevant logs from the `kube-flannel` pod running on your node?

**Comment by skycastlelily** [comment]
hi,
Really sorry for the late reply,actually  I pasted the following log and click "Comment" days before,
but found it's not updated just now.
Anyway,thanks for your quick reply,and here is the log:
[root@dell-r330-9 ~]# kubectl logs kube-flannel-ds-vxkzm -n kube-system
I0304 01:43:21.632539       1 main.go:519] Determining IP address of default interface
I0304 01:43:21.633073       1 main.go:532] Using interface with name eno1 and address 10.37.192.20
I0304 01:43:21.633095       1 main.go:549] Defaulting external address to interface address (10.37.192.20)
W0304 01:43:21.633117       1 client_config.go:608] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0304 01:43:21.832789       1 kube.go:116] Waiting 10m0s for node controller to sync
I0304 01:43:21.832877       1 kube.go:299] Starting kube subnet manager
I0304 01:43:22.832964       1 kube.go:123] Node controller sync successful
I0304 01:43:22.833013       1 main.go:253] Created subnet manager: Kubernetes Subnet Manager - dell-r330-9.gsslab.brq.redhat.com
I0304 01:43:22.833022       1 main.go:256] Installing signal handlers
I0304 01:43:22.833134       1 main.go:391] Found network config - Backend type: vxlan
I0304 01:43:22.833269       1 vxlan.go:123] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
I0304 01:43:22.929463       1 main.go:306] Setting up masking rules
I0304 01:43:23.136696       1 main.go:314] Changing default FORWARD chain policy to ACCEPT
I0304 01:43:23.136940       1 main.go:322] Wrote subnet file to /run/flannel/subnet.env
I0304 01:43:23.136957       1 main.go:326] Running backend.
I0304 01:43:23.136971       1 main.go:344] Waiting for all goroutines to exit
I0304 01:43:23.137043       1 vxlan_network.go:59] watching for new subnet leases

**Comment by WYmindsky** [comment]
same err.
AnyOne knows ?
