### ISSUE TITLE
Wireguard backend has duplicate peers

### ISSUE THREAD

**Issue by txomon** [flannel-io/flannel#1421]
## Expected Behavior
Running `wg` should show one link per node

## Current Behavior
Running `wg` may show more than one link per node

## Possible Solution
Probably check for existing peers before adding a new one

## Steps to Reproduce (for bugs)
Set up several nodes with wireguard backend, check all of them

## Context
Thankfully it doesn't break functionality so it's not such a big problem, but maybe something could be done

## Your Environment
* Flannel version: master
* Backend used (e.g. vxlan or udp): wireguard
* Etcd version: N/A
* Kubernetes version (if used): 1.20
* Operating System and version: arch + k3s
* Link to your project (optional): None

**Comment by nabam** [comment]
I think I experience exactly the same issue here https://github.com/k3s-io/k3s/issues/5216

**Comment by andreek** [comment]
This issue is solved by #1230.

Can be closed.
