### ISSUE TITLE
Pod IP network non-default value and Flannel network

### ISSUE THREAD

**Issue by bhkamath** [flannel-io/flannel#1428]
I created a Baremetal Kubernetes cluster using kubeadm.  The pod-network-cidr specified as part of kubeadm init was 100.244.0.0/16 (instead of default 10.244.0.0/16)

The flannel network and flannel subnet carries a mismatch in the configuration.

```
cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=100.244.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true 

```
The master and worker nodes are in 'Ready' state.  I created a pod (e.g., CentOS Pod) and was functional.

## Expected Behavior

I edited the flannel ConfigMap [kube-flannel-cfg] to modify the default values of net-conf.json and annotations metadata.  This change followed by a rebooted provided the expected output.

```
cat /run/flannel/subnet.env
FLANNEL_NETWORK=100.244.0.0/16
FLANNEL_SUBNET=100.244.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true

```
## Possible Solution

I suspect kube-flannel yaml file requires to handle config data of pod-network-cidr value of the cluster configuration

## Steps to Reproduce (for bugs)

1. Install docker, kubelet, ...
2. kubeadm init --apiserver-advertise-address=192.168.122.199 --pod-network-cidr=100.244.0.0/16
3. ...
4. kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

## Context

I observed an issue when running kubevirt in my environment.  The virt-operator was in CrashLoopBackOff state.

## Your Environment

* Flannel version: 0.3.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:
* Kubernetes version (if used): v1.18.17
* Operating System and version: CentOS 7
* Link to your project (optional):

**Comment by luthermonson** [comment]
flannel v0.3.1? you sure?

**Comment by bhkamath** [comment]
Command I used to deploy kube-flannel is given below.  Also, the output of configuration is provided.

```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

kubectl get cm kube-flannel-cfg -n kube-system -o yaml
apiVersion: v1
data:
  cni-conf.json: |
    {
      "name": "cbr0",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "flannel",
          "delegate": {
            "hairpinMode": true,
            "isDefaultGateway": true
          }
        },
        {
          "type": "portmap",
          "capabilities": {
            "portMappings": true
          }
        }
      ]
    }
  net-conf.json: |
    {
      "Network": "100.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"cni-conf.json":"{\n  \"name\": \"cbr0\",\n  \"cniVersion\": \"0.3.1\",\n  \"plugins\": [\n    {\n      \"type\": \"flannel\",\n      \"delegate\": {\n        \"hairpinMode\": true,\n        \"isDefaultGateway\": true\n      }\n    },\n    {\n      \"type\": \"portmap\",\n      \"capabilities\": {\n        \"portMappings\": true\n      }\n    }\n  ]\n}\n","net-conf.json":"{\n  \"Network\": \"100.244.0.0/16\",\n  \"Backend\": {\n    \"Type\": \"vxlan\"\n  }\n}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app":"flannel","tier":"node"},"name":"kube-flannel-cfg","namespace":"kube-system"}}
  creationTimestamp: "2021-03-29T06:36:56Z"
  labels:
    app: flannel
    tier: node
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:cni-conf.json: {}
        f:net-conf.json: {}
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:tier: {}
    manager: kubectl
    operation: Update
    time: "2021-03-29T06:36:56Z"
  name: kube-flannel-cfg
  namespace: kube-system
  resourceVersion: "4485584"
  selfLink: /api/v1/namespaces/kube-system/configmaps/kube-flannel-cfg
  uid: 0f369f5f-9e1c-4829-b190-5a068f26d814

```

**Comment by bhkamath** [comment]
How do I get the newer version? Have I used a wrong link?

**Comment by mdditt2000** [comment]
I am seeing the same issue

```
kubeadm init --apiserver-advertise-address=192.168.200.80 --pod-network-cidr=10.245.0.0/16
```
```
[kube@ks8-prod-master prod-cluster]$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.245.0.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```
I cannot use 10.244 as its already in use on another cluster. Same process work if using 10.144 but when i change the network to 10.245 i cannot reach the pods

Any suggestions?

**Comment by bhkamath** [comment]
A workaround is to edit the ConfigMap file of flannel, kube-flannel-cfg and to replace with the new Network value. ] to modify the default values of net-conf.json and annotations metadata.

**Comment by mdditt2000** [comment]
Thanks @bhkamath i will try that tomorrow.

**Comment by mdditt2000** [comment]
@bhkamath making a modification of the kube-flannel-cfg and rebooting the cluster did change the value. 

[kube@ks8-prod-master root]$ cat /run/flannel/subnet.env
**FLANNEL_NETWORK=10.245.0.0/16
FLANNEL_SUBNET=10.245.0.1/24**
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
[kube@ks8-prod-master root]$

Great now i can ping the pods

@ks8-prod-master root]$ ping 10.245.1.3
PING 10.245.1.3 (10.245.1.3) 56(84) bytes of data.
64 bytes from 10.245.1.3: icmp_seq=1 ttl=63 time=0.252 ms
64 bytes from 10.245.1.3: icmp_seq=2 ttl=63 time=0.182 ms
