### ISSUE TITLE
Routing rules missing

### ISSUE THREAD

**Issue by tydra-wang** [flannel-io/flannel#1434]
Flannel routing rules will disappear when unplug the node cable and plug it back in.

## Possible Solution

Maybe flannel should reset the routing rules periodically?

## Steps to Reproduce (for bugs)
My k8s is deployed on my physical machines.
A normal routing table on a node:
```
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    100    0        0 ens3
10.2.3.128      192.168.252.51  255.255.255.128 UG    0      0        0 ens3
10.2.33.0       0.0.0.0         255.255.255.128 U     0      0        0 cni0
10.2.48.0       192.168.252.52  255.255.255.128 UG    0      0        0 ens3
192.168.0.0     0.0.0.0         255.255.0.0     U     100    0        0 ens3
```
After I unplug the network cable of this node, it routing table will become:
```
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.2.33.0       0.0.0.0         255.255.255.128 U     0      0        0 cni0
```
As I understand it, when the netlink 'ens3' disappeared, all routing rules associated with it will also be deleted.
When I reset the cable, the default routing rule will come back, while flannel will not reset its rules.
Final routing table:
```
/ # route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         192.168.2.1     0.0.0.0         UG    100    0        0 ens3
10.2.33.0       0.0.0.0         255.255.255.128 U     0      0        0 cni0
192.168.0.0     0.0.0.0         255.255.0.0     U     100    0        0 ens3
```

## Your Environment
* Flannel version: 0.10.0
* Backend used (e.g. vxlan or udp): vxlan directRouting=true
* Etcd version: 3.3.11
* Kubernetes version (if used): 1.15.9
* Operating System and version: centos 7.8
* Cpu Arch: arm64

**Comment by luthermonson** [comment]
@tydra-wang going to be hard to catch this... if you have ideas other than periodically resetting things which could cause connectivity problems... if there is a system event that is catchable and we could reset things upon plugging in the cable?

**Comment by tydra-wang** [comment]
As I know, we can use netlink to catch the events.

See examples in  https://man7.org/linux/man-pages/man7/netlink.7.html.

I believe we can also do this in golang.

**Comment by avoidik** [comment]
static routes?

```
$ cat /etc/syconfig/network-scripts/route-ens3
10.2.3.128/25 via 192.168.252.51 dev ens3
10.2.48.0/25 via 192.168.252.52 dev ens3
```

**Comment by tydra-wang** [comment]
@luthermonson could you please take a look?

**Comment by luthermonson** [comment]
@tydra-wang that sounds like a good idea. We would need someone to implement, feel free to submit a PR or open source your code for your sidecar so we can see your implementation and find a place to put it.
