### ISSUE TITLE
after add new network card how to config 

### ISSUE THREAD

**Issue by zerols** [flannel-io/flannel#1440]
i have 6 node ubuntu18.04  with 3 words and 3 master, i install k8s v1.20.5 and flannel v0.13.1-rc2. the node ip is 192.168.20.2-7 with ens160
now i add node a network card i have Configure static ip 192.168.10.2-7 with ens192, how should i change my config to achieve the  192.168.20 ens160 down or don't work , k8s would use ens192 192.168.10 。
this is my network config:
![image](https://user-images.githubusercontent.com/35661759/118750704-7e61b280-b892-11eb-94d7-72e021da01f9.png)

**Comment by luthermonson** [comment]
flannel picks up the interface with the default route, i dont even think k8s supports two interfaces. if you want to use the new interface you need to change the default route and tear down and rebuild.
