### ISSUE TITLE
s390x travis Build 

### ISSUE THREAD

**Issue by Nayana-ibm** [flannel-io/flannel#1441]
## Expected Behavior
Travis CI build for s390x 

## Current Behavior
No build found for s390x in travis job/logs
https://travis-ci.com/github/flannel-io/flannel

I could see multi-arch image support though this PR: https://github.com/flannel-io/flannel/pull/1327. s390x is also supported. 
However on [travis ](https://travis-ci.com/github/flannel-io/flannel) job , I don't see s390x build.

Also, docker push is failing for  amd64. Is this the reason the command which builds for amd64, ppc64le or s390x doesn't execute? 

```
docker push quay.io/coreos/flannel-git:v0.14.0-rc1-2-ge634dab-dirty-amd64
The push refers to repository [quay.io/coreos/flannel-git]
Makefile:206: recipe for target 'docker-push' failed
make[1]: *** [docker-push] Error 1
make[1]: Leaving directory '/home/travis/gopath/src/github.com/flannel-io/flannel'
Makefile:223: recipe for target 'flannel-git' failed

```

Also, could you please let me know how the images published to https://quay.io/repository/coreos/flannel?tab=tags 
Any script etc. used?

**Comment by luthermonson** [comment]
docker push will fail without creds to quay which are locked down. the s390x build is done and pushed by hand at release time by @rajatchopra.

**Comment by Nayana-ibm** [comment]
@luthermonson Thank you for information
