### ISSUE TITLE
Cannot reach the pod of work node by using the IP that fannel assigned

### ISSUE THREAD

**Issue by MephistoLynn** [flannel-io/flannel#1452]
Except of the work node itself , I cannot reach the pod in work node by using the IP that fannel assigned from any host .

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used): Kubernetes v1.21.1
* Operating System and version: UbuntuOS 
* Link to your project (optional):

And this picture is showing the problem.
![20210624215739](https://user-images.githubusercontent.com/22832393/123275853-43a90500-d537-11eb-96d9-50450761f1e1.png)

**Comment by arashnh11** [comment]
Are you trying pod-to-pod communication? From your screenshot, seems like you are trying to ping a pod from a worker node not from another pod. Not sure if that functionality would work. Most of the threads I am seeing are focused on issues with pod-to-pod communication, i.e., you get on one pod and try to ping a pod in another node (not the node itself)
