### ISSUE TITLE
ipv6 only support

### ISSUE THREAD

**Issue by manuelbuil** [flannel-io/flannel#1453]
Flannel does not work in ipv6 only env

## Expected Behavior

When deploying kubernetes with ipv6 only, flannel should provide the connectivity to the cluster

**Comment by olljanat** [comment]
FYI. I started working on with this one.

However it looks to be that SubnetKey logic need to be refactored as it expect IPv4: https://github.com/flannel-io/flannel/blob/f0f9b5262b993c4800726cb5d59f6da3b8a3dc4e/subnet/subnet.go#L110-L124

Also as #1501 does changes to same area it make sense to merge it first.
