### ISSUE TITLE
windows server 2016 start flanneld error

### ISSUE THREAD

**Issue by utopro** [flannel-io/flannel#1461]
I0711 20:17:29.343176    4352 alivpc_windows.go:22] AliVpc is not supported on this platform
I0711 20:17:29.359774    4352 awsvpc_windows.go:22] AWS VPC is not supported on this platform
I0711 20:17:29.360751    4352 gce_windows.go:45] GCE is not supported on this platform
I0711 20:17:29.362705    4352 ipip_windows.go:23] ipip is not supported on this platform
I0711 20:17:29.363680    4352 ipsec_windows.go:20] ipsec is not supported on this platform
I0711 20:17:29.364656    4352 tencentvpc_windows.go:22] TencentVpc is not supported on this platform
I0711 20:17:29.364656    4352 udp_windows.go:22] udp is not supported on this platform
I0711 20:17:29.366611    4352 main.go:456] Searching for interface using 192.168.10.75
I0711 20:17:29.376287    4352 main.go:533] Using interface with name 以太网 and address 192.168.10.75
I0711 20:17:29.377511    4352 main.go:550] Defaulting external address to interface address (192.168.10.75)
I0711 20:17:29.386060    4352 main.go:254] Created subnet manager: Etcd Local Manager with Previous Subnet: None
I0711 20:17:29.388620    4352 main.go:257] Installing signal handlers
I0711 20:17:29.395056    4352 main.go:392] Found network config - Backend type: vxlan
I0711 20:17:29.396032    4352 vxlan_windows.go:126] VXLAN config: Name=flannel.4096 MacPrefix=0E-2A VNI=4096 Port=4789 GBP=false DirectRouting=false
E0711 20:17:29.429926    4352 main.go:293] Error registering network: Platform does not support feature Remote Subnet
I0711 20:17:29.431569    4352 main.go:372] Stopping shutdownHandler...

**Comment by utopro** [comment]
Is there a solution to this problem?

**Comment by piwenzi** [comment]
i also have the same error in ws-1809 , flannel tag 0.13.0. i am debug it in windows container
PS C:\k\flannel>
PS C:\k\flannel>
PS C:\k\flannel> wins cli process run --path /k/flannel/flanneld.exe --args "--kube-subnet-mgr --kubeconfig-file /k/flannel/kubeconfig.yml" -
-envs "POD_NAME=$env:POD_NAME POD_NAMESPACE=$env:POD_NAMESPACE"
I1210 14:41:41.209572    7592 main.go:519] Determining IP address of default interface
I1210 14:41:43.044342    7592 main.go:532] Using interface with name vEthernet (Ethernet) 2 and address 10.221.161.177
I1210 14:41:43.045338    7592 main.go:549] Defaulting external address to interface address (10.221.161.177)
I1210 14:41:43.071203    7592 kube.go:119] Waiting 10m0s for node controller to sync
I1210 14:41:43.071203    7592 kube.go:306] Starting kube subnet manager
I1210 14:41:44.071329    7592 kube.go:126] Node controller sync successful
I1210 14:41:44.071329    7592 main.go:246] Created subnet manager: Kubernetes Subnet Manager - win177
I1210 14:41:44.071329    7592 main.go:249] pujun Installing signal handlers
I1210 14:41:44.071329    7592 main.go:390] Found network config - Backend type: vxlan
I1210 14:41:44.071329    7592 vxlan_windows.go:127] VXLAN config: Name=flannel.4096 MacPrefix=0E-2A VNI=4096 Port=4789 GBP=false DirectRoutin
g=false
E1210 14:41:44.083717    7592 main.go:291] Error registering network: Platform does not support feature Remote Subnet
I1210 14:41:44.083717    7592 main.go:370] Stopping shutdownHandler...

**Comment by silenceper** [comment]
I also encountered the same problem. according to the log prompt(`Error registering network: Platform does not support feature Remote Subnet`), I found that the system version is too low. The problem of upgrading the system version is solved.
