### ISSUE TITLE
Pod in one node cannot ping another node

### ISSUE THREAD

**Issue by qianzhangxa** [flannel-io/flannel#1477]
I have installed the latest Flannel in my Kubernetes 1.21.1 and the cross-node pod communication works well, but I found I cannot ping a node from a pod on another node, but I can do that in the other way (i.e. ping a pod on a node from another node). I am not sure if it is the design behavior or a bug, can anyone please help? Thanks!

**Comment by bengtfredh** [comment]
I do not know your setup, but have you checked your firewall settings on host? I have experienced the same before when firewall blocking flannel traffick. You should have 8285/udp and 8472/udp open on both hosts.

**Comment by qianzhangxa** [comment]
@bengtfredh My firewall is not running.

**Comment by Slyke** [comment]
This sounds related to: https://github.com/flannel-io/flannel/issues/1474

Try restarting Flannel with `$ kubectl delete pod -n kube-system -l app=flannel` and if it works, then it's that issue.

**Comment by qianzhangxa** [comment]
> This sounds related to: #1474
> 
> Try restarting Flannel with `$ kubectl delete pod -n kube-system -l app=flannel` and if it works, then it's that issue.

Just tried it, but no luck.

**Comment by manuelbuil** [comment]
can you give us more details about your deployment? What kubernetes distro? What OS?
