### ISSUE TITLE
flannel 0.15.0 using rancher/flannel-cni-plugin:v1.2 does not have support for s390x

### ISSUE THREAD

**Issue by PoojaSoni96** [flannel-io/flannel#1494]
I am trying to deploy flannel on kubernetes cluster (1.22.2) on s390x architecture.  Getting following error for the same.
```
# kubectl get pods -A
NAMESPACE     NAME                                          READY   STATUS                  RESTARTS   AGE
kube-system   coredns-78fcd69978-jdf5d                      0/1     Pending                 0          3m4s
kube-system   coredns-78fcd69978-wfpnx                      0/1     Pending                 0          3m4s
kube-system   etcd-psoni1.fyre.ibm.com                      1/1     Running                 10         3m16s
kube-system   kube-apiserver-psoni1.fyre.ibm.com            1/1     Running                 17         3m18s
kube-system   kube-controller-manager-psoni1.fyre.ibm.com   1/1     Running                 10         3m18s
kube-system   kube-flannel-ds-bpfxz                         0/1     Init:ImagePullBackOff   0          24s
kube-system   kube-proxy-gzglv                              1/1     Running                 0          3m4s
kube-system   kube-scheduler-psoni1.fyre.ibm.com            1/1     Running                 11         3m16s
```

After a bit of debugging found that the commit https://github.com/flannel-io/flannel/commit/51fbf37f2e86fabdc21aef16039ccc3e8c40f2d4 has added cni pulgin dependency for version 0.15.0. Also the Image being used here is rancher/flannel-cni-plugin:v1.2 which does not seem to have support for s390x.
```
# sudo docker pull  rancher/mirrored-flannelcni-flannel-cni-plugin:v1.2
v1.2: Pulling from rancher/mirrored-flannelcni-flannel-cni-plugin
no matching manifest for linux/s390x in the manifest list entries
```
I would like to know if  s390x support could be added here or if we switch back to the official cni plugin - `flannelcni/flannel-cni-plugin:v1.2` Which work perfectly fine on s390x architecture.

**Comment by PoojaSoni96** [comment]
The Above image does not work for s390x. Will it be possible to add s390x support to this image -` rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0`? Link for the same - https://hub.docker.com/r/rancher/mirrored-flannelcni-flannel-cni-plugin/tags.

**Comment by luthermonson** [comment]
we dont currently build s390z images for flannel, none of those will work for your situation. you'll have to pull down the flannel repo and use make to generate your own image for that arch.

**Comment by manuelbuil** [comment]
> The Above image does not work for s390x. Will it be possible to add s390x support to this image -` rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0`? Link for the same - https://hub.docker.com/r/rancher/mirrored-flannelcni-flannel-cni-plugin/tags.

You can try to change it to `rancher/mirrored-flannelcni-flannel-cni-plugin:v1.0.0`. But that account has limited pulls

**Comment by luthermonson** [comment]
> we dont currently build s390z images for flannel, none of those will work for your situation. you'll have to pull down the flannel repo and use make to generate your own image for that arch.

Well I should have looked, we do...

**Comment by luthermonson** [comment]
@manuelbuil pointed out to us privately just pointed out to us the image mirror scripts weren't supporting the s390z mirroring and our z team was trying to fix it already 

https://github.com/rancher/image-mirror/pull/175

**Comment by luthermonson** [comment]
we updated the mirror scripts and s390x are now in the image mirror. i believe this issue can be closed now @PoojaSoni96 pls confirm
