### ISSUE TITLE
Update Documentation for Ubuntu 21.10 on Raspberry Pi

### ISSUE THREAD

**Issue by trevor-viljoen** [flannel-io/flannel#1502]
According to [this](https://www.mail-archive.com/ubuntu-bugs@lists.ubuntu.com/msg5968871.html) bug report, kernel modules for vxlan are missing. The `linux-modules-extra-raspi` needs to be installed and the Pi rebooted for k3s to successfully start up and run.

## Expected Behavior

k3s should start after running the install script.

## Current Behavior

```
root@k3s-master:~# modprobe vxlan
modprobe: FATAL: Module vxlan not found in directory /lib/modules/5.13.0-1008-raspi
root@k3s-master:~# lsmod | grep vxlan
root@k3s-master:~#
```
```
...
Nov 03 03:58:07 k3s-master k3s[260961]: I1103 03:58:07.998748  260961 kube.go:127] Node controller sync successful
Nov 03 03:58:08 k3s-master k3s[260961]: I1103 03:58:08.025657  260961 vxlan.go:137] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
Nov 03 03:58:08 k3s-master k3s[260961]: time="2021-11-03T03:58:08Z" level=fatal msg="flannel exited: operation not supported"
Nov 03 03:58:08 k3s-master systemd[1]: k3s.service: Main process exited, code=exited, status=1/FAILURE
Nov 03 03:58:08 k3s-master systemd[1]: k3s.service: Failed with result 'exit-code'.
Nov 03 03:58:08 k3s-master systemd[1]: k3s.service: Consumed 36.292s CPU time.
Nov 03 03:58:13 k3s-master systemd[1]: k3s.service: Scheduled restart job, restart counter is at 805
```

## Possible Solution

```
ubuntu@k3s-master:~$ sudo apt-get install linux-modules-extra-raspi && sudo reboot
```

## Steps to Reproduce (for bugs)

1. Install Ubuntu Server 21.10 on a Raspberry Pi
2. Install k3s as normal

## Context

I spent several hours over the course of a couple days trying to get k3s up and going on a brand new Raspberry Pi to no avail.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:
* Kubernetes version (if used): 1.22
* Operating System and version: Ubuntu Server 21.10
* Link to your project (optional):

**Comment by trevor-viljoen** [comment]
I meant to file this on k3s. It may be relevant here too for people. but I'm going to close this.

**Comment by MattTheCuber** [comment]
Thank you so much! I've been stuck on this issue for 3 days and this solved my problem!
