### ISSUE TITLE
pods can't communicate with each other when in different subnet

### ISSUE THREAD

**Issue by winkee01** [flannel-io/flannel#1510]
#### Environment
I have two nodes in cluster, A master and C is worker, B is a client machine(macOS) for hosting a VM (C).
![canping](https://user-images.githubusercontent.com/49930785/144717706-cf87b82d-7611-4d45-b60b-56a61c6c3bd4.jpg)
As the diagram shows, 
- A has ip 10.10.0.1
- B has ip at 
  - eth0 - 10.10.0.3
  - bridge100 - 172.16.3.1
- C has ip 172.16.3.7

C can ping 10.10.0.1 with success, and C as a worker node, joins A's cluster succefully.

I deploy an app which has two repicas, pod on A has ip 10.244.0.7, pod on C has ip 10.244.1.3, from what I know about the network requirement of kubernetes, pod A should be able to talke to pod C directly, but unfortunately, when I enter pod A, and try ping C's IP, it failed. 

So, this violates Kubernetes's network mode requirement?

**Comment by rbrtbnfgl** [comment]
Hi. Do you still have this issue?
Could you share your flannel config? Are you using VXLAN tunnel to connect the pods?
