### ISSUE TITLE
Documentation should mention that masquerade should be enabled on firewalld

### ISSUE THREAD

**Issue by atos-ghassen-bchir** [flannel-io/flannel#1515]
## Expected Behavior
I struggled when setting up a Kubernetes cluster using Flannel as the CNI.
After a lengthy debugging session, I finally figured out that the masquerade needed to be enabled on firewalld (in addition to the port opening)

## Current Behavior
The file flannel/Documentation/troubleshooting.md mentions the ports that need to be opened. However it does not mention the masquerading.

## Possible Solution
Adding a section about this fix.

## Steps to Reproduce (for bugs)
1. Initialize a cluster (using CRI-O in my case, but not the only scenario I think).
2. Create flannel related items as per the doc
3. Open ports 8472/udp (as per the troubleshooting.md file)
4. Run a pod (e.g. nginx) on one node and try to access it from another: it is not working
5. Enable masquerading: the curl now works across hosts

## Your Environment
* Flannel version: image: quay.io/coreos/flannel:v0.15.1
* Backend used (e.g. vxlan or udp): vxlan

**Comment by manuelbuil** [comment]
Could you create a PR in the docs adding this info please?
