### ISSUE TITLE
source IP not preserved when using hostPort

### ISSUE THREAD

**Issue by yelhouti** [flannel-io/flannel#1528]
## Expected Behavior
When configuring flannel with:
```yam
  {
    "type": "portmap",
    "capabilities": {
      "portMappings": true
    },
    "snat": false
  }

```
I expect the source IP to be preserved. it is not.

## Current Behavior
sourceIp is not preserved, which cause an open relay.

## Steps to Reproduce (for bugs)

1. install a new k8s cluster with flannel
2. create a daemonset with hostPort
3. check the sourceIp of the request

## Context
I am trying to install mailu (SMTP server...) and I tried using hostPort as they do in their helm chart (no load balancer here).

## Your Environment

* Flannel version: v0.15.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5.0
* Kubernetes version (if used): 1.22.5
* Operating System and version: AlmaLinux 8.5

I tried debugging the issue as you can read [here](https://github.com/kubernetes/kubernetes/issues/107591#issuecomment-1018908608)

And I am thinking that rule that is SNATing (or maybe masquerading) is created by kube-proxy, but since flannel adds all these rules for hostPort, I would have expected it to fix the sourceIP too.

**Comment by yelhouti** [comment]
After some debugging here is what I found:

I created a fresh cluster with: `--ip-masq=false` instead of `--ip-masq` and the problem disappeared.
Although the [doc](https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#key-command-line-options)
> --ip-masq=false: setup IP masquerade for traffic destined for outside the flannel network. Flannel assumes that the default policy is ACCEPT in the NAT POSTROUTING chain.

seems to indicate that `--ip-mask` only affects outgoing traffic, it doesn't.

the culprit seems to be the [flannel-cni-plugin](https://github.com/flannel-io/cni-plugin/blob/076c4462d6c6887614fc881b806b690b9e56ceb2/flannel.go#L210)
It check the field set by `--ip-masq` in `/run/flannel/subnet.env`
```
FLANNEL_IPMASQ=true
```
which calls [CNI](https://github.com/containernetworking/cni) which in turn seems to call the [cni-portmap-plugin](https://github.com/containernetworking/plugins/tree/master/plugins/meta/portmap) that adds rule [here](https://github.com/containernetworking/plugins/blob/e27c48b391539f5536918b9c379c59ef2793cb0d/plugins/main/bridge/bridge.go#L556) because ipMasq is set.

Another interesting issue I found is that if you first install with `--ip-mask=false` then switch to `--ip-mask` the problem doesn't appear (which seems to be another bug).

AFAICT, this is a regression as I didn't have this issue before updating my cluster.

**Comment by manuelbuil** [comment]
Could you create the issue in the flannel-cni-plugin repo please?

**Comment by yelhouti** [comment]
done
