### ISSUE TITLE
When I install Flannel0.16.3 in K8S, Node appears ready, but pod doesn't start

### ISSUE THREAD

**Issue by a4363220** [flannel-io/flannel#1547]
Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-sl6gt': Unauthorized

**Comment by manuelbuil** [comment]
Is it possible that you are restricting pods? Perhaps you should add flannel to a less restrictive profile

**Comment by funtionalcode** [comment]
> Is it possible that you are restricting pods? Perhaps you should add flannel to a less restrictive profile

How to solve ? For example, simple solutions

**Comment by AGou-ops** [comment]
same issue here.

```bash
0824 07:17:56.520705       1 main.go:229] Failed to create SubnetManager: error retrieving pod spec for 'kube-flannel/kube-flannel-ds-6s6vr': Unauthorized
```
