### ISSUE TITLE
无法ping通flannel.1网卡

### ISSUE THREAD

**Issue by zhutong196** [flannel-io/flannel#1548]
## Expected Behavior

I use six servers to create k8s clusters, and there is no network segment between each two servers. Now I find that there are only four flannels 1 is connected, and the other two are only connected by themselves, which is not connected with the other four

10.57.2.129   flannel.1    10.244.0.0
10.57.2.130   flannel.1    10.244.1.0

10.57.154.18  flannel.1    10.244.2.0
10.57.154.19  flannel.1    10.244.3.0

10.57.157.48  flannel.1    10.244.7.0
10.57.157.49  flannel.1    10.244.8.0

## Current Behavior

My node information:
![image](https://user-images.githubusercontent.com/48009847/158132217-6fa3c8d1-93ad-4e55-96ad-708b445a942f.png)
10.244.0.0-10.244.3.0 not ping 10.244.7.0/10.244.8.0
![image](https://user-images.githubusercontent.com/48009847/158132129-2e398c1a-9dba-40ed-b5c3-8aa5fcfcf523.png)

10.244.7.0 can ping 10.244.8.0 each
![image](https://user-images.githubusercontent.com/48009847/158132164-96986661-035a-4f03-86f4-c409d767b9d3.png)

## Your Environment

* Flannel version: v0.11.0
* Backend used (e.g. vxlan or udp):   vxlan
* Etcd version:  3.4.3-0
* Kubernetes version (if used): v1.17.0
* Operating System and version:  
* Link to your project (optional):

**Comment by zhutongcloud** [comment]
the udp 8472 port of every host have open

**Comment by manuelbuil** [comment]
Could you use a newer k8s and flannel version please? Perhaps your problem is fixed in newer versions

**Comment by zhangguanzhang** [comment]
```
docker info
iptables -S
```

**Comment by yuzhaopeng** [comment]
检查一下7.0 和 8.0两台机器上，flannel 启动时候绑定的网卡，有可能是flannel 错误的识别了网卡，可以手动指定一下
