### ISSUE TITLE
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

### ISSUE THREAD

**Issue by justsomebody42** [flannel-io/flannel#1560]
PodSecurityPolicy is deprecated and will be removed in v1.25+

## Expected Behavior
Compatibility with v1.25+

## Current Behavior
Deprecation warning...

## Possible Solution
See: _https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125_

## Steps to Reproduce (for bugs)
```bash
:~/.kube$ kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
podsecuritypolicy.policy/psp.flannel.unprivileged configured
clusterrole.rbac.authorization.k8s.io/flannel unchanged
clusterrolebinding.rbac.authorization.k8s.io/flannel unchanged
serviceaccount/flannel unchanged
configmap/kube-flannel-cfg unchanged
daemonset.apps/kube-flannel-ds configured
```

## Your Environment
* Flannel version: v0.17.0
* Etcd version: 3.5.1-0
* Kubernetes version (if used): v1.23.5
* Operating System and version: Ubuntu 21.10 / 20.04.4 LTS

**Comment by manuelbuil** [comment]
Will https://github.com/flannel-io/flannel/pull/1559 fix it?
