### ISSUE TITLE
Please include the manifest in the release itself

### ISSUE THREAD

**Issue by afbjorklund** [flannel-io/flannel#1561]
## Expected Behavior

Install flannel:

kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/v0.17.0/Documentation/kube-flannel.yml

Get `v0.17.0`

## Current Behavior

If you install 0.17.0, you get 0.16.3. If you install 0.16.3, you get 0.16.1. And so on.

## Possible Solution

Please bump the manifest, _before_ tagging the release ? Or include a YAML with the github files, perhaps.

Workaround:
https://raw.githubusercontent.com/flannel-io/flannel/v0.17.0-1-gbf9dbdb0/Documentation/kube-flannel.yml

## Steps to Reproduce (for bugs)

1. Replace "master" with a specific release, for reproducibility.
2.
3.
4.

## Context

https://github.com/flannel-io/flannel#deploying-flannel-manually

```
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

https://github.com/lima-vm/lima/blob/master/examples/k8s.yaml

**Comment by ExNG** [comment]
Can confirm, currently its kinda weird

**Comment by manuelbuil** [comment]
For v0.18.0 this is fixed, could you check?

**Comment by afbjorklund** [comment]
> For v0.18.0 this is fixed, could you check?

Looks good. `flannelcni/flannel:v0.18.0`

https://raw.githubusercontent.com/flannel-io/flannel/v0.18.0/Documentation/kube-flannel.yml

I guess "hosting" the images at rancher is just to get around the pull limits ?

And installing with init containers is just to get around the old CNI packages ?

**Comment by afbjorklund** [comment]
Was broken again in 0.19.0 and 0.19.1

**Comment by afbjorklund** [comment]
Maybe it can be automated ? Anyway, edited the manifest since I want to install a host flannel.

**Comment by afbjorklund** [comment]
Using `v0.19.1-1-gab7a3945` to get the right images (instead of v0.19.0)

Hoping that the new CNI plugin won't mix too poorly with the old CNI plugins...

* CNI portmap plugin v0.8.6

* CNI Plugin flannel version v1.1.0

**Comment by manuelbuil** [comment]
> Using `v0.19.1-1-gab7a3945` to get the right images (instead of v0.19.0)
> 
> Hoping that the new CNI plugin won't mix too poorly with the old CNI plugins...
> 
> * CNI portmap plugin v0.8.6 (0.8.7)
> * CNI Plugin flannel version v1.1.0

Why are you suing old CNI plugins?

**Comment by afbjorklund** [comment]
> Why are you suing old CNI plugins?

These are the ones included with the kubernetes release (for 1.25.0), might consider bumping them for a future version ?

**Comment by afbjorklund** [comment]
When I compiled it myself, I used the 1.1.1 plugins with 1.1.0 flannel. And it seemed to work...

But the kubernetes packages seems to be left in the old version (still including flannel, though)

**Comment by afbjorklund** [comment]
Still broken, in 0.21.2 (uses 0.20.2)

https://raw.githubusercontent.com/flannel-io/flannel/v0.21.2/Documentation/kube-flannel.yml

```
        image: docker.io/flannel/flannel:v0.20.2
       #image: docker.io/rancher/mirrored-flannelcni-flannel:v0.20.2
```

**Comment by rbrtbnfgl** [comment]
Hi we changed the manifest to use. Now it is generated from the release you can use the following link
https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

**Comment by afbjorklund** [comment]
Right, that seems to be in sync. Now, just have to change all references in code...
https://github.com/flannel-io/flannel/releases/download/v0.21.2/kube-flannel.yml
