### ISSUE TITLE
create flannel failed, Failed to find any valid interface to use: failed to get default interface: protocol not available

### ISSUE THREAD

**Issue by xiaofengzs** [flannel-io/flannel#1573]
When creating flannel,  I fount the pods of flannel was on CrashLoopBackOff.  Then i checked the logs, it displayed "protocol not available".  
I am using three centos7 virual machine on my mac. 

> [root@kmaster ops]# kubectl -n kube-system logs kube-flannel-ds-g454r
I0529 01:01:38.853263       1 main.go:207] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W0529 01:01:38.853358       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0529 01:01:40.052708       1 kube.go:121] Waiting 10m0s for node controller to sync
I0529 01:01:40.052767       1 kube.go:398] Starting kube subnet manager
I0529 01:01:41.053866       1 kube.go:128] Node controller sync successful
I0529 01:01:41.053917       1 main.go:227] Created subnet manager: Kubernetes Subnet Manager - knode1
I0529 01:01:41.053928       1 main.go:230] Installing signal handlers
I0529 01:01:41.054189       1 main.go:463] Found network config - Backend type: vxlan
I0529 01:01:41.054246       1 match.go:195] Determining IP address of default interface
E0529 01:01:41.054378       1 main.go:270] Failed to find any valid interface to use: failed to get default interface: protocol not available

## Your Environment

* Flannel version: v0.18.0
* Backend used: vxlan
* Etcd version: 3.4.3-0
* Kubernetes version (if used): v1.18.0
* Operating System and version: centos 7

**Comment by summmer121** [comment]
I have the same problem as you, did you solve it?

**Comment by xiaofengzs** [comment]
Hi @summmer121,  not yet

**Comment by utkarsh1103** [comment]
Even, I have the same problem, so keep me posted!

**Comment by summmer121** [comment]
> Hi @summmer121, not yet

resolved，
修改flannel镜像版本0.17
Modify flannel  image version 0.17

**Comment by summmer121** [comment]
> Even, I have the same problem, so keep me posted!

try   change flannel image version from 0.18.0 to 0.17.0

**Comment by tuwid** [comment]
had the same issue with 0.18.0, had to use 0.17.0 to fix it

**Comment by xiaofengzs** [comment]
@summmer121 cool,  thanks
