### ISSUE TITLE
The v0.18.0 kube-flannel.yml always cannot find local interface 

### ISSUE THREAD

**Issue by Pilipana** [flannel-io/flannel#1576]
when i use kubectl apply -f kube-flannel.yml to deploy v0.18.0 flannel always output errors like can not find local interface. I am sure the - --iface= parameter correct .
## Expected Behavior

![图片](https://user-images.githubusercontent.com/106822935/171909436-290ab4eb-0937-4956-af57-1a75940cbc15.png)
![图片](https://user-images.githubusercontent.com/106822935/171909461-7116cc0c-252b-42c5-86b4-300409427125.png)
![图片](https://user-images.githubusercontent.com/106822935/171909488-ecb0c29a-013e-4c8e-8c27-87b7c8d8290f.png)

## Current Behavior

I try to remove all interface only reserve one and no specify --iface in order to let kubernetes scan the default one. But also some errors 
![图片](https://user-images.githubusercontent.com/106822935/171909924-16236fa7-8362-4954-8564-3d525147636a.png)

## Possible Solution

I have to modify my environment to previous flannel version v0.16.3 , then it's working.
![图片](https://user-images.githubusercontent.com/106822935/171910090-5529053d-4518-43a1-96b6-32a8fee0fb1e.png)
![图片](https://user-images.githubusercontent.com/106822935/171910096-146411a0-942f-45de-8042-c9461493c58d.png)
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version: v0.18.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 1.24.1
* Kubernetes version (if used): 1.24.1
* Operating System and version: CentOS7.9
* Link to your project (optional):

**Comment by legoguy1000** [comment]
We're having the same issue on CentOS 7 and version v0.18.0.  Version 0.17.0 works without issue.
```
I0605 03:32:49.565250       1 main.go:207] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W0605 03:32:49.565348       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0605 03:32:49.671976       1 kube.go:121] Waiting 10m0s for node controller to sync
I0605 03:32:49.672022       1 kube.go:398] Starting kube subnet manager
I0605 03:32:50.672126       1 kube.go:128] Node controller sync successful
I0605 03:32:50.672152       1 main.go:227] Created subnet manager: Kubernetes Subnet Manager - server1.kit.lan
I0605 03:32:50.672157       1 main.go:230] Installing signal handlers
I0605 03:32:50.672241       1 main.go:463] Found network config - Backend type: vxlan
I0605 03:32:50.672266       1 match.go:195] Determining IP address of default interface
E0605 03:32:50.672343       1 main.go:270] Failed to find any valid interface to use: failed to get default interface: protocol not available
```

**Comment by xiaofengzs** [comment]
@legoguy1000 please see my issue.

**Comment by rbrtbnfgl** [comment]
The new release 0.18.1 should fix the issue with centos 7

**Comment by manuelbuil** [comment]
As this is fixed, I think we can close it. If not, please reopen
