### ISSUE TITLE
Hairpin not working with k8s v1.24 on minikube using HyperKit driver

### ISSUE THREAD

**Issue by spowelljr** [flannel-io/flannel#1577]
Hi, I'm a minikube maintainer trying to get get the flannel CNI working with k8s v1.24 for our next release.

## Expected Behavior
Hairpinning works with flannel CNI with k8s v1.24 on minikube using the HyperKit driver

## Current Behavior
Hairpinning does not work with flannel CNI with k8s v1.24 on minikube using the HyperKit driver

## Steps to Reproduce (for bugs)

```
# in minikube repo
$ gh pr checkout 14197

$ make

$ minikube start --driver hyperkit --memory 2048 --wait=true --wait-timeout=5m --cni=flannel
...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

$ minikube kubectl -- replace --force -f test/integration/testdata/netcat-deployment.yaml
deployment.apps/netcat replaced
service/netcat replaced

$ minikube kubectl -- exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z localhost 8080"
Connection to localhost 8080 port [tcp/http-alt] succeeded!

$ minikube kubectl -- exec deployment/netcat -- /bin/sh -c "nc -w 5 -i 5 -v -z netcat 8080"
nc: connect to netcat port 8080 (tcp) timed out: Operation in progress
command terminated with exit code 1
```

## Context

All other drivers work with flannel, so this seems to be specific to HyperKit

This also works fine with k8s version prior to v1.24

flannel YAML: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cni/flannel.go#L30

## Your Environment

* Flannel version: `v0.12.0`
* Backend used (e.g. vxlan or udp):
* Etcd version: `3.5.3-0`
* Kubernetes version (if used): `v1.24.0`
* Operating System and version: minikube's custom Linux distro running on HyperKit
* Link to your project (optional): https://github.com/kubernetes/minikube

**Comment by WoodyWoodsta** [comment]
I'm having the same issue, but with k8s on my own bare-metal server using `cri-docker`. Have been beating around for days without any resolution. It seems `hairpinMode: true` doesn't reflect any change in the way that the `bridge` plugin sets up the network.

All other issues seem to be from many years ago 🙈

**Comment by manuelbuil** [comment]
Interesting, the docs in this repo state that the hairpinMode feature exists in flannel binary. However, if you look at the flannel binary README, that feature is not there: https://github.com/flannel-io/cni-plugin#network-configuration-reference. I wonder if this feature ever existed and was dropped or if it really never existed and it is an error in the docs. Do you know?

**Comment by WoodyWoodsta** [comment]
@manuelbuil Where do you see that documentation? As far as I understand, `hairpinMode` is delegated to the `bridge` plugin, so I'm not sure we'd be expecting it as part of flannel itself. That being said, I'm not 100% sure how this CNI plugin is architectured.

**Comment by manuelbuil** [comment]
You are right but I think we still need to "copy" the fields from one NetConf struct to another. And we are not doing anything like for that for hairpinMode. I should be a pretty easy fix though

**Comment by spowelljr** [comment]
@WoodyWoodsta 
| OS | Arch | Driver | Container Runtime | Hairpinning Status |
| - | - | - | - | - |
| Linux | x86_64 | Docker | cri-docker | Passed |
| Linux | arm64 | Docker | cri-docker | Passed |
| Linux | x86_64 | Docker | containerd | Passed |
| Linux | arm64 | Docker | containerd | Passed |
| Linux | x86_64 | Docker | cri-o | Passed |
| Linux | arm64 | Docker | cri-o | Passed |
| Linux | x86_64 | KVM | cri-docker | Passed |
| Linux | x86_64 | KVM | containerd | Passed |
| Linux | x86_64 | KVM | cri-o | Passed |
| Window | x86_64 | Docker | cri-docker | Passed |
| Window | x86_64 | Hyper-V | cri-docker | Passed |
| macOS | x86_64 | Docker | cri-docker | Passed |
| macOS | x86_64 | HyperKit | cri-docker | Failed |
| macOS | x86_64 | HyperKit | containerd | Paseed |
| macOS | x86_64 | HyperKit | cri-o | Paseed |

**Comment by WoodyWoodsta** [comment]
@spowelljr That's very helpful, thank you. I'm wondering what is similar between the first row (which would be representative of what I currently have), and your failure row, or whether we do in fact have two different issues.

**Comment by WoodyWoodsta** [comment]
Looping in https://github.com/kubernetes-sigs/kind/issues/2791 and https://github.com/projectcalico/calico/issues/6186, same issue as above but on a different CNI plugins. As https://github.com/kubernetes-sigs/kind/issues/2791#issuecomment-1148235704 probably correctly highlights, this sounds like a `cri-docker` bug as opposed to something in the CNI plugins, as it seems to affect all CNI plugins (at least those tested), and is only present after 1.24.

**Comment by spowelljr** [comment]
I found the root of the issue, `cri-docker` hardcodes `HairpinMode` to `none`.
https://github.com/Mirantis/cri-dockerd/blob/60a25a1586890870cfdb9c160cb9d1dfc45a27d9/cmd/server.go#L154

I've changed it to `promiscuous-bridge` and it succeeded, I'm working on marking a PR for it that makes it configurable. Hopefully that resolves your issue @WoodyWoodsta.

**Comment by spowelljr** [comment]
https://github.com/Mirantis/cri-dockerd/pull/71

**Comment by WoodyWoodsta** [comment]
@spowelljr Thanks! I've decided I probably don't need to be using the `cri-docker` middle man so have switched to the `containerd` cri, but appreciate your find!

**Comment by spowelljr** [comment]
Since the solution has been found and my PR has been merged I'm going to close this issue.
