### ISSUE TITLE
Flannel IPv6: allocateSubnet does not move sn6 with Next() in case of Overlap

### ISSUE THREAD

**Issue by pranavadn** [flannel-io/flannel#1580]
When using Flannel with IPv6, allocateSubnet does not move sn6 with Next() in case of overlap. This results in "out of subnets" error leading to nodes not being able to obtain a subnet.

## Expected Behavior
When a v6 subnet is found to overlap with an existing lease, we should move to next leave with sn6.Next().

## Current Behavior
When using Flannel with IPv6, allocateSubnet does not move sn6 with Next() in case of overlap. This results in "out of subnets" error leading to nodes not being able to obtain a subnet.

```
OuterLoop:
	for ; sn.IP <= config.SubnetMax && len(availableIPs) < 100; sn = sn.Next() {
		if !sn6.Empty() {
			if sn6.IP.Cmp(config.IPv6SubnetMax) >= 0 {
				break OuterLoop
			}
		}
		for _, l := range leases {
			if sn.Overlaps(l.Subnet) {
				continue OuterLoop
			}
			if !sn6.Empty() && sn6.Overlaps(l.IPv6Subnet) {
				continue OuterLoop
			}
		}
```

## Possible Solution
Remove the sn.Next() in the loop header and call sn.Next() and sn6.next() inside the loop appropriately for overlap and available IP accumulation cases.

## Steps to Reproduce (for bugs)

3 nodes cluster with the following flannel network config led to one node erroring out and not getting a lease -

Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: getNetworkConfig  {
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "EnableIPv6": true,
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "EnableIPv4": true,
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "Network": "192.168.0.0/16",
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "SubnetLen": 24,
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "IPv6Network": "2000:192:1600::0/64",
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "IPv6SubnetLen": 108,
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "Backend": {
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: "Type": "host-gw"
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: }
Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: }

Jun  7 00:11:49 a1-bqkp73611004-node-1 flanneld: E0607 00:11:49.930511   26803 main.go:317] Error registering network: failed to acquire lease: out of subnets

## Context

We need to have dual stack supported for our pods. Hence, enabling v6 with Flannel.

## Your Environment

* Flannel version:
 v0.17.0

* Backend used (e.g. vxlan or udp):
host-gw
* Etcd version:
3.3.15

* Kubernetes version (if used):
1.20
* Operating System and version:
3.10.0-1160.62.1.el7.x86_64
* Link to your project (optional):

**Comment by pranavadn** [comment]
@manuelbuil These issues are coding errors in Flannel. They are present in latest Flannel binary too. We are not using Kubernetes subnet manager either. Hence, it is the subnet leasing logic of Flannel that is being used on our setup. Could we please have these Flannel coding errors fixed?

**Comment by rbrtbnfgl** [comment]
Are you using etcd as subnet manager?
I did a rework on the loop that chooses the subnet. I'll do a PR with the mod. And you can give us other feedbacks.

**Comment by pranavadn** [comment]
@rbrtbnfgl Yes, we are using etcd subnet manager. Thanks for taking a look and fixing the issue. Let me take a look at the patch and provide feedback if any.

**Comment by pranavadn** [comment]
Does sn6.IP.Cmp(config.IPv6SubnetMax) < 0  comparison not exclude the last subnet? This was also an issue in the original code that raised with 1581. It should be like the v4 comparison sn.IP <= config.SubnetMax.

**Comment by rbrtbnfgl** [comment]
Is this solved?
If it is I'll close it.
