### ISSUE TITLE
Flannel IPv6: Incorrect sn6.IP.Cmp(config.IPv6SubnetMax) >= 0 comparison in allocateSubnet 

### ISSUE THREAD

**Issue by pranavadn** [flannel-io/flannel#1581]
Incorrect sn6.IP.Cmp(config.IPv6SubnetMax) >= 0 comparison in allocateSubnet  causes failure in leasing out last subnet of a network.

## Expected Behavior
The comparison should be sn6.IP.Cmp(config.IPv6SubnetMax) > 0.

## Current Behavior
Fails to lease out the last subnet of a network. According to the definition it should be able to lease out the last subnet -

_IPv6SubnetMax (string): The end of the IPv6 range at which the subnet allocation should end with. **Defaults to the last subnet of Ipv6Network**._

## Possible Solution
Change comparison to sn6.IP.Cmp(config.IPv6SubnetMax) > 0 or to <=0  like you have in ipv4 -
sn.IP <= config.SubnetMax

## Steps to Reproduce (for bugs)

1. Have a 3 node setup.
2. have /65 ipv6 network and subnet length of /67
3. Third node fails to get a lease even though 3 subnets are available. 
4. It errors out with "Error registering network: failed to acquire lease: out of subnets"

## Context
We need flannel to work with v6 for dual stack.

## Your Environment
Flannel version:
v0.17.0

Backend used (e.g. vxlan or udp):
host-gw

Etcd version:
3.3.15

Kubernetes version (if used):
1.20

Operating System and version:
3.10.0-1160.62.1.el7.x86_64
* Link to your project (optional):

**Comment by manuelbuil** [comment]
Thanks for reporting this. Note that Kubernetes 1.20 does not support ipv6. You should move to v1.23 where the feature became stable. Can you try there?

**Comment by pranavadn** [comment]
@manuelbuil These issues are coding errors in Flannel. They are present in latest Flannel binary too. We are not using Kubernetes subnet manager either. Hence, it is the subnet leasing logic of Flannel that is being used on our setup. Could we please have these Flannel coding errors fixed?

**Comment by pranavadn** [comment]
Yes. Please close the issue.
