### ISSUE TITLE
When the packet is transferred from the internal network to the flannel network, the flannel disguises the source IP address?

### ISSUE THREAD

**Issue by 5279314** [flannel-io/flannel#1592]
## Expected Behavior

When I use docker in k8s, I can reserve the pod source IP to access the internal container through SNAT conversion
```
# Before optimization
kubectl logs nginx-ds-85fc6f4dff-6g6tb
10.1.1.100 - - [06/Aug/2020:10:43:23 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.52.1" "-"

# After optimization
kubectl logs nginx-ds-85fc6f4dff-6g6tb
172.7.22.2 - - [06/Aug/2020:10:46:23 +0000] "GET / HTTP/1.1" 200 612 "-" "curl/7.52.1" "-"
```
**However, when using containerd, I found that the iptables rule will not take effect. Please help me check it.**
I tried #864 and # 1528

## Current Behavior

pod sourceIp is not preserved, IP is node ip
```
[root@k8s-master1 ~]# kubectl logs -f nginx-deployment-6c8b449b8f-k9pdt  
10.1.1.130 - - [22/Jun/2022:13:30:24 +0000] "GET / HTTP/1.1" 200 615 "-" "curl/7.74.0" "-"
```
## Steps to Reproduce (for bugs)

1. install a new k8s cluster with flannel
agrs
```
-etcd-cafile=/opt/flannel/ssl/ca.pem \
  -etcd-certfile=/opt/flannel/ssl/etcd.pem \
  -etcd-keyfile=/opt/flannel/ssl/etcd-key.pem \
  -etcd-endpoints=https://10.1.1.100:2379,https://10.1.1.130:2379,https://10.1.1.120:2379 \
  -etcd-prefix=/coreos.com/network \
  -subnet-file=/run/flannel/subnet.env \
  -iface=eth0 \
  -ip-masq=false \
  -healthz-port=2401
```
2.cni config
```
[root@k8s-master1 ~]# cat /etc/cni/net.d/10-flannel.conflist 
{
  "name": "cni0",
  "cniVersion": "0.3.1",
  "plugins": [
    {
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true
      }
    },
    {
      "type": "portmap",
      "capabilities": {
        "portMappings": true
      },
    "snat": false
    }
  ]
}
```
3. create network
```
 /opt/etcd/etcdctl get /coreos.com/network/config
{"Network": "172.7.0.0/16", "Backend": {"Type": "host-gw"}}
```
4. iptables 
```
iptables -t nat -I POSTROUTING -s 172.7.100.0/24 ! -d 172.7.0.0/16 -j MASQUERADE
```
## Your Environment

* Flannel version: v0.17.0
* Backend used (e.g. vxlan or udp): host-gw
* Etcd version:  3.3.22
* Kubernetes version (if used): 1.24.0
* Operating System and version: centos7.9
* Link to your project (optional):

**Comment by manuelbuil** [comment]
What do you mean by internal network and by flannel network?

**Comment by 5279314** [comment]
> What do you mean by internal network and by flannel network?

Internal network refers to mutual visits between pod containers
Flannel network is used to establish network communication between k8s
Is this understandable: IP planning
k8s node network: 10.1.1.0/24
k8s pods network: 172.7.0.0/16

I hope that the pods direct mutual visits do not perform SNAT conversion, and the pods log wants to display the IP address of 172.7.0.0/16

**Comment by rbrtbnfgl** [comment]
Are you testing that another pod contacts the ngnix pod and the IP is masqueraded with the one of the node and it shouldn't?

**Comment by 5279314** [comment]
> Are you testing that another pod contacts the ngnix pod and the IP is masqueraded with the one of the node and it shouldn't?

Yes, I don't want pod IP to be masqueraded by node IP

**Comment by rbrtbnfgl** [comment]
Ok it shouldn't masqueraded pods traffic could you share your iptables rules? (`iptables-save`)
The iptables rule that you mentioned is added by you or you got it from flannel?

**Comment by rbrtbnfgl** [comment]
Ok the issue is related to how the CNI plugin delegates to the CNI bridge. To avoid that the traffic is masqueraded you need to add an additional config to the CNI.
```
   {
      "type": "flannel",
      "delegate": {
        "isDefaultGateway": true,
        "ipMasq": false
      }
    },
```

**Comment by 5279314** [comment]
Thanks for your help, it's solved
