### ISSUE TITLE
Flannel Dual Stack Does not work when both public-ip and public-ipv6 are specified  

### ISSUE THREAD

**Issue by pranavadn** [flannel-io/flannel#1596]
## Current Behavior
Flannel Dual Stack Does not work when both public-ip and public-ipv6 are specified.

When both ipv4 and ipv6 addresses are specified via command line arguments public-ip and public-ipv6, it takes the following code path and errors out -

```
main 
----- calls ----
if len(opts.iface) == 0 && len(opts.ifaceRegex) == 0 && len(opts.ifaceCanReach) == 0 {
		extIface, err = ipmatch.LookupExtIface(opts.publicIP, "", "", ipStack, optsPublicIP)
---- calls -----
		case dualStack:
				iface, err = ip.GetInterfaceByIP(ifaceAddr)
				if err != nil {
					return nil, fmt.Errorf("error looking up interface %s: %s", ifname, err)
				}
				v6Iface, err := ip.GetInterfaceByIP6(ifaceAddr)
				if err != nil {
					return nil, fmt.Errorf("error looking up v6 interface %s: %s", ifname, err)
				}

```
Since only opts.publicIP is passed into LookupExtIface, ip.GetInterfaceByIP6(ifaceAddr) gets called with v4 address and errors out with 

`return nil, errors.New("No interface with given IPv6 found")
`
## Possible Solution
Need to pass provided ipv6 address to LookupExtIface call and use it to find the interface.

## Steps to Reproduce (for bugs)
invoke flannel with both public-ip and public-ipv6 options

## Your Environment
Flannel version:
v0.17.0

Backend used (e.g. vxlan or udp):
host-gw

Etcd version:
3.3.15

Kubernetes version (if used):
1.20

Operating System and version:
3.10.0-1160.62.1.el7.x86_64

**Comment by rbrtbnfgl** [comment]
Are the two public IPs from the same net interface?
Looking at the code it search the net interface of the given IPv4 and then checks that the that iface has an IPv6.

**Comment by pranavadn** [comment]
@rbrtbnfgl Thanks for looking into this issue.

Yes, the addresses are from the same interface. However, in the code under dualStack case that I have mentioned in the description, after the "ip.GetInterfaceByIP(ifaceAddr)" call, the code is making "ip.GetInterfaceByIP6(ifaceAddr)" call passing the same IP address (which is v4 address). Hence, it errors out. This seems to be a bug. 
Also, in our case, the interface has multiple IPv6 addresses and hence, we want to be able to specify the v6 address with public-ipv6 option. We are not able to do it because of this bug.
