### ISSUE TITLE
Flannel does not cleanup old routes when subnet config is changed

### ISSUE THREAD

**Issue by pranavadn** [flannel-io/flannel#1604]
When we change the subnet config, Flannel does not cleanup old routes. For example, if the current cluster CIDR is 192.168.0.0/16 and we change it to 172.16.0.0/16, Flannel does not cleanup the 192.168... routes it had added. They linger around. This can cause a problem if the new cluster CIDR configured overlaps with the old one where the old routes conflict with the new ones.
In fact, what is observed is when we update subnet config on etcd, Flannel does not seem to get any trigger to start using new subnet config. Only on Flannel restart, it start using new config, but does not cleanup the old routes. 

## Expected Behavior
Expected behaviour is for Flannel to cleanup old routes on cluster CIDR change.

## Current Behavior
When we change the subnet config, Flannel does not cleanup old routes. For example, if the current cluster CIDR is 192.168.0.0/16 and we change it to 172.16.0.0/16, Flannel does not cleanup the 192.168... routes it had added. They linger around. This can cause a problem if the new cluster CIDR configured overlaps with the old one where the old routes conflict with the new ones.
In fact, what is observed is when we update subnet config on etcd, Flannel does not seem to get any trigger to start using new subnet config. Only on Flannel restart, it start using new config, but does not cleanup the old routes. 

## Possible Solution
Is Flannel expected to get a trigger and start using new subnet config when we update it on etcd? It does not seem to be happening. Please check why the old routes are not cleaned up even after Flannel starts using update subnet config.

## Steps to Reproduce (for bugs)

1. Have the following subnet config 
$ etcdctl get --prefix /flannel/network/config
/flannel/network/config
{
      "EnableIPv4": true,
      "Network": "172.16.128.0/18",
      "SubnetLen": 26,
      "EnableIPv6": true,
      "IPv6Network": "fc00:172:31:0:8000::/66",
      "IPv6SubnetLen": 104,
      "Backend": {
          "Type": "host-gw",
          "DirectRouting": false
      }
}

2. Change it to 
$ etcdctl get --prefix /flannel/network/config

/flannel/network/config
{
      "EnableIPv4": true,
      "Network": "192.168.128.0/18",
      "SubnetLen": 26,
      "EnableIPv6": true,
      "IPv6Network": "fc00:172:31:0:8000::/66",
      "IPv6SubnetLen": 104,
      "Backend": {
          "Type": "host-gw",
          "DirectRouting": false
      }
}

You will see that old routes Flannel had installed like below linger -

172.16.2.128/26 via 10.95.160.14 dev br0 
172.16.2.192/26 via 10.95.160.12 dev br0 

## Context
We are using Flannel in dual stack mode for our pod network. In our product, customers are given an option to change the pod network CIDR. When that option is exercised, we see that, even though we update the new subnet config value in etcd, Flannel behaviour is not as expected.

## Your Environment
Flannel version:
v0.18.1

Backend used (e.g. vxlan or udp):
host-gw

Etcd version:
3.3.15

Kubernetes version (if used):
1.20

Operating System and version:
3.10.0-1160.62.1.el7.x86_64

**Comment by rbrtbnfgl** [comment]
It's the right behaviour that if you change the network CIDR config you have at least restart the CNI. I don't know if it's better to also restart K8s. After you restarted flannel have the running pods the IPs updated?

**Comment by pranavadn** [comment]
@rbrtbnfgl After Flanneld restart, flanneld is able to use the new network configuration and pods do get new IPs. However, even in this case, the routes installed by Flanneld for previous subnet is not cleaned up.

**Comment by rbrtbnfgl** [comment]
In addition to the routes do you have also the old iptables rules or were they removed?

**Comment by pranavadn** [comment]
@rbrtbnfgl Looks like iptables rules are linger -

sudo iptables -S | grep flannel
-A FORWARD -s 192.168.128.0/18 -m comment --comment "flanneld forward" -j ACCEPT
-A FORWARD -d 192.168.128.0/18 -m comment --comment "flanneld forward" -j ACCEPT
-A FORWARD -s 172.31.192.0/18 -m comment --comment "flanneld forward" -j ACCEPT
-A FORWARD -d 172.31.192.0/18 -m comment --comment "flanneld forward" -j ACCEPT

This is after changing the cluster subnet from 192. to 172.
