### ISSUE TITLE
CrashBackLoopOff kube-flannel-ds timeout curling 10.96.0.1:443

### ISSUE THREAD

**Issue by Pseudow** [flannel-io/flannel#1609]
Hi I found why my kube-flannel-ds pod was always in CrashBackLoopOff state, actually my node can ping my kubeapi server using the ip 10.96.0.1 but sometimes it takes really long time and sometimes it just doesnt. It can take up to 40s or just 2seconds which makes it timeout. But what is actually weird is that when I try getting the kubeapi server using my master address (10.66.66.1:6443) it works without waiting.

**Comment by Pseudow** [comment]
I modified iface in kube flannel yaml file but it seems it didnt do anything.

**Comment by bsneric** [comment]
problem solved. it is because. there is another cluster which cidr is same with this one. I change it to 10.222.0.0/16  
it worked well.thank you

**Comment by rbrtbnfgl** [comment]
I don't know if it could be related to the kube-proxy config it should be in charge of the forwarding of the traffic from the endpoint IP to the right POD.

**Comment by Pseudow** [comment]
I think it was because of a wrong cgroup in containerd but Kubernetes didn't warn me
