### ISSUE TITLE
Recent builds not found on quay.io repo

### ISSUE THREAD

**Issue by waipeng** [flannel-io/flannel#1613]
## Expected Behavior

When there is a new release, we should be able to find the builds at https://quay.io/repository/coreos/flannel?tab=tags

## Current Behavior

There have been a few new releases, but the new images are not found on https://quay.io/repository/coreos/flannel?tab=tags

## Possible Solution

Has this anything to do with https://github.com/flannel-io/flannel/issues/1456
> Also, after the build is complete, images won't be pushed as implementation is just to make sure that new changes don't break the build.

## Your Environment
I got linked to the quay repo via https://github.com/flannel-io/flannel/blob/master/Documentation/building.md#obtaining-master-builds

**Comment by rbrtbnfgl** [comment]
The issue was related to flannel-io on dockerhub.
I am not aware if the image on the quay repo is still supported probably the documentation needs to be updated.
The new released images are deployed on dockerhub https://hub.docker.com/r/flannelcni/flannel/tags

**Comment by rbrtbnfgl** [comment]
I updated the Documentation with the docker registry with the updated version.

**Comment by waipeng** [comment]
Thanks!
