### ISSUE TITLE
namespace changed to kube-flannel

### ISSUE THREAD

**Issue by nardusg** [flannel-io/flannel#1615]
Hi

Not a bug but more a question. I saw the namespace is now kube-flannel instead of kube-system, will this break upgrades ? Any extra steps need to be taken during upgrades ?

Regards,
Nardus

**Comment by instantlinux** [comment]
In the file [kube-flannel-rbac.yml](https://github.com/flannel-io/flannel/blob/master/Documentation/k8s-manifests/kube-flannel-rbac.yml), the old namespace still appears at line 42. Shall I file a new issue, or can you re-open this one?

**Comment by instantlinux** [comment]
PR [#1657](https://github.com/flannel-io/flannel/pull/1657) fixes that issue, if you'd like to review it.
