### ISSUE TITLE
Is using VXLan over the internet insecure?

### ISSUE THREAD

**Issue by clouedoc** [flannel-io/flannel#1634]
Hello,

I am running k3s with flannel as a CNI, and VXLan as a backend to flannel.

My nodes are communicating with their public IP addresses (I did not create a VPC).

I'm worried that an attacker could read the unencrypted data that transits between services spanned across multiple nodes.

I don't want to create a VPC since I would like to add nodes spanned across multiple datacenters. And even so, I'm not sure if packets sent through a VPC should be considered as unreadable by other parties.

Is VXLan traffic encrypted by default, or do I need to use IPSec/Wireguard?

Thanks for your answers

**Comment by rbrtbnfgl** [comment]
VXLAN is unencrypted if you want a more secure connection you have to use Wireguard as a backend.

**Comment by clouedoc** [comment]
Thanks @rbrtbnfgl, this answers my question
