### ISSUE TITLE
After updating to v0.19.2 k8s cannot download image

### ISSUE THREAD

**Issue by mmalyska** [flannel-io/flannel#1639]
## Expected Behavior
k8s should be able to pull image from docker.

## Current Behavior
Cannot pull current image
```
Failed to pull image "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": failed to resolve reference "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2: not found
```
![obraz](https://user-images.githubusercontent.com/999598/188125362-fcd95e99-9e1b-46be-ac2a-0e30df3c3bae.png)

## Possible Solution
push image? or revert changes.

## Steps to Reproduce (for bugs)
Deploy using https://raw.githubusercontent.com/flannel-io/flannel/v0.19.2/Documentation/kube-flannel.yml

## Context
Updated deployment to newest version.

## Your Environment

* Flannel version: v0.19.0 (before update)
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5.1-0
* Kubernetes version (if used): 1.23.4
* Operating System and version: Ubuntu 20.04

**Comment by n1ckjansens** [comment]
Same problem `Failed to pull image "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": failed to resolve reference "docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2": docker.io/rancher/mirrored-flannelcni-flannel:v0.19.2: not found`

**Comment by n1ckjansens** [comment]
@rbrtbnfgl

**Comment by rbrtbnfgl** [comment]
Yes the version was updated today.
It needs time to update the mirrored image

**Comment by n1ckjansens** [comment]
> Yes the version was updated today. It needs time to update the mirrored image

How much time usually it takes?

**Comment by rbrtbnfgl** [comment]
It needs to be approved by an admin of the repo. I think it will fixed for the afternoon you can use the older version until that time.
I'll mark the latest release as pre-release until the new image isn't up.

**Comment by n1ckjansens** [comment]
> It needs to be approved by an admin of the registry. I think it will fixed for the afternoon you can use the older version until that time. I'll mark the latest release as pre-release until the new image isn't up.

THX!

**Comment by rbrtbnfgl** [comment]
The image is up now
