### ISSUE TITLE
Require to do some enhancement in flannel README.md

### ISSUE THREAD

**Issue by amolmote** [flannel-io/flannel#1641]
Changes require in this file [README.md](https://github.com/flannel-io/flannel)

For setting up the flannel for any requirement we can should require to provide the link like below I showed 
```
kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml
```
because it is easier to copy to clipboard directly.

We should require to provide the `kube-flannel-rbac.yml` command as well for deploying flannel.
`kube-flannel-rbac.yml` also missing in  [kubernetes.md](https://github.com/flannel-io/flannel/blob/master/Documentation/kubernetes.md) this file also. either we should provide the yml for `kube-flannel-rbac.yml` or we can provide the link for same directly.

If this issue is valid then assign it to me I will enhance this readme files.

**Comment by rbrtbnfgl** [comment]
I don't fully understand where is the issue.
`kube-flannel.yml` already contains all the RBAC configuration it doesn't need the additional manifest that it's needed only if you are deploying flannel on older kubernetes version.

**Comment by amolmote** [comment]
yeah that great, I really don't know about RBAC is not needed in newer version so I thought that we should require to provide yml for RBAC as well. my bad. but atleast we can provide the link of kube-flannel just like I showed above.
