### ISSUE TITLE
Looking for cert files even when etcd connection is over HTTP

### ISSUE THREAD

**Issue by chazapis** [flannel-io/flannel#1666]
When starting flanneld 0.20.0 with a plain HTTP connection (using `-etcd-endpoints http://...`), flanneld fails with `Failed to create SubnetManager: can't connect to etcd: no cert file found.`. This works as expected at version 0.19.0.

## Expected Behavior

When providing etcd endpoints over HTTP, no cert files should be required. This looks like a regression in 0.20.0.

## Current Behavior

Now flanneld 0.20.0 fails to start with the following message:
```
E1028 05:16:03.859447   38174 main.go:221] Failed to create SubnetManager: can't connect to etcd: no cert file found
```

## Possible Solution

Revert 0.19.0 behavior.

## Steps to Reproduce (for bugs)

1. Install Ubuntu 22.04.1, etcd from apt.
2. Set `ETCD_LISTEN_CLIENT_URLS` and `ETCD_ADVERTISE_CLIENT_URLS` in `/etc/default/etcd` to `http://<local IP address>:2379`.
3. Start etcd.
4. Start flanneld with `flanneld -etcd-endpoints http://<local IP address>:2379 -ip-masq`.

## Your Environment

* Flannel version: 0.20.0, 0.19.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.3.25
* Kubernetes version (if used):
* Operating System and version: Ubuntu 22.04.1 LTS
* Link to your project (optional):

**Comment by chazapis** [comment]
> This commit may be related to the behavior you are seeing:
> 
> [1bcfa6c](https://github.com/flannel-io/flannel/commit/1bcfa6ce99f9a9660a539152a28db7f602b41021)

Yes. It seems that this is what causes it.

**Comment by rbrtbnfgl** [comment]
On the latest release the manager prints only a Warning when HTTP is used.
