### ISSUE TITLE
FLANNEL-FWD and FLANNEL-POSTRTG chains not recreated after firewalld restart

### ISSUE THREAD

**Issue by wheatevo** [flannel-io/flannel#1668]
## Expected Behavior

The FLANNEL-FWD and FLANNEL-POSTRTG chains should be recreated if missing within the `SetupAndEnsureIP4Tables` and `SetupAndEnsureIP6Tables` loops.

https://github.com/flannel-io/flannel/blob/4586e914972da184a34c6022f26778b48c7c6fe3/network/iptables.go#L251-L258
https://github.com/flannel-io/flannel/blob/4586e914972da184a34c6022f26778b48c7c6fe3/network/iptables.go#L288-L295

## Current Behavior

On Oracle Linux 7 with firewalld installed, the FLANNEL-FWD and FLANNEL-POSTRTG chains are dropped if the firewalld service is restarted.

Error messages
```
E1027 16:19:08.773196       1 iptables.go:254] Failed to ensure iptables rules: error checking rule existence: failed to check rule existence: running [/sbin/iptables -t filter -C FORWARD -m comment --comment flanneld forward -j FLANNEL-FWD --wait]: exit status 2: iptables v1.8.6 (legacy): Couldn't load target `FLANNEL-FWD':No such file or directory

E1027 16:19:08.936329       1 iptables.go:254] Failed to ensure iptables rules: error checking rule existence: failed to check rule existence: running [/sbin/iptables -t nat -C POSTROUTING -m comment --comment flanneld masq -j FLANNEL-POSTRTG --wait]: exit status 2: iptables v1.8.6 (legacy): Couldn't load target `FLANNEL-POSTRTG':No such file or directory
```

https://github.com/flannel-io/flannel/blob/4586e914972da184a34c6022f26778b48c7c6fe3/network/iptables.go#L169

## Possible Solution

May be able to add a check within `ipTablesRulesExist` for the chain or add handling for `Couldn't load target .... No such file or directory` errors.

## Steps to Reproduce (for bugs)

1. Create a new Oracle Linux 7/CentOS 7 instance with firewalld running.
2. Start Flannel v0.20.0
3. Verify the FLANNEL-FWD and FLANNEL-POSTRTG chains exist
4. Restart firewalld
5. Verify the FLANNEL-FWD and FLANNEL-POSTRTG chains do not exist
6. Errors should occur within the logs at this point

## Context

We are currently attempting to upgrade to Flannel 0.20.0 in our Kubernetes environment.

The change that renamed the chains was introduced in https://github.com/flannel-io/flannel/pull/1650.

## Your Environment

* Flannel version: 0.20.0
* Backend used (e.g. vxlan or udp): Wireguard
* Etcd version: 3.4.13
* Kubernetes version (if used): 1.21.5
* Operating System and version: Oracle Linux 7.9
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Hi @wheatevo thanks for the report.
I am working on a patch to fix this.
