### ISSUE TITLE
Support for IPV6 on "Deploying flannel manually"

### ISSUE THREAD

**Issue by Shimrockx** [flannel-io/flannel#1674]
docker.io doesn't support ipv6. You should modify kube-flannel.yml to use google mirror instead of docker.io to pull images.

## Expected Behavior
It should pull rancher flannel images.

## Current Behavior
Current kube-flannel.yml is pulling from docker.io who doesn't support ipv6. You should consider adding a solution or a warning.

## Possible Solution
Modify docker.io prefix with mirror.gcr.io
Example : 
`docker.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0`  -> `mirror.gcr.io/rancher/mirrored-flannelcni-flannel-cni-plugin:v1.1.0`

Alternatively you can login to registry.ipv6.docker.com with docker login command.
[Docker blog beta ipv6 support](https://www.docker.com/blog/beta-ipv6-support-on-docker-hub-registry/)
[Kubernetes pull image private registry](https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/)

## Steps to Reproduce (for bugs)
1. Create a virtual machine with only ipv6 stack
2. Init kubeadm normally with support for ipv6
3. Deploy flannel manually via default documentation configuration file
4.

## Context
Trying to deploy flannel manually

## Your Environment
* Flannel version: 0.20.1
* Backend used (e.g. vxlan or udp): tcp
* Etcd version: v4.5.7
* Kubernetes version (if used): client : v1.25.3 server : v1.25.4"
* Operating System and version: Debian 11.5

**Comment by rbrtbnfgl** [comment]
Thanks for reporting this.
I think it'll be better to update the IPv6 only documentation reporting the possible fixes because changing the prefix could affects other IPv4 setup.
