### ISSUE TITLE
How does flannel DaemonSet determine the worker node architecture?

### ISSUE THREAD

**Issue by inianv** [flannel-io/flannel#1678]
**Not a bug report, but a technical clarification!**

I have seen from the the YAML daemonset spec of flannel, `kube-flannel-ds` deploys resources with awareness of the underlying worker node architecture and OS. How does it accomplish that? e.g. `kube-flannel-ds-windows-amd64-bft4l`? I don't see the daemonset resource name hardcoded with `-windows-amd64`. 

Interested in knowing how it is accomplished.

**Comment by rbrtbnfgl** [comment]
It should be done by the image pull process if I recall. The container chosen image should be selected based on the OS/Arch of the node. Which version of flannel are you using?
We are not mirroring the flannel windows image from some release.

**Comment by inianv** [comment]
@rbrtbnfgl Can you point me to the particular section of YAML that does that? Been looking to do something similar for my use case, but can't figure out a way to do it, especially the architecture.  Would close the post after that. Thanks.

**Comment by inianv** [comment]
@rbrtbnfgl - Please take a look above. Thanks

**Comment by rbrtbnfgl** [comment]
If you check the old manifest https://github.com/flannel-io/flannel/blob/master/Documentation/kube-flannel-old.yaml
it checks the architecture with a `nodeSelector` field. I think you can do the same with the OS installed.
