### ISSUE TITLE
Image rancher/mirrored-flannelcni-flannel:v0.20.2 is not (yet?) available on Docker Hub

### ISSUE THREAD

**Issue by starypatyk** [flannel-io/flannel#1685]
## Expected Behavior
When deploying flannel on a new k8s cluster with:
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```
the kube-flannel pod(s) should start.

## Current Behavior
The kube-flannel pod(s) do not start with the following error message:

```
Failed to pull image "docker.io/rancher/mirrored-flannelcni-flannel:v0.20.2": rpc error: code = Unknown desc = Error response from daemon: manifest for rancher/mirrored-flannelcni-flannel:v0.20.2 not found: manifest unknown: manifest unknown
```

## Possible Solution
Apparently the 0.20.2 version of the image is not (yet?) available on Docker Hub.
https://hub.docker.com/r/rancher/mirrored-flannelcni-flannel/tags

## Your Environment
I am trying to deploy a local k8s development cluster using kubeadm (1.23) and suggested method of flannel installation.

**Comment by rbrtbnfgl** [comment]
v0.20.2 it's still on pre-release.
I suggest to use the latest released version and not the one on the master
https://raw.githubusercontent.com/coreos/flannel/v0.20.1/Documentation/kube-flannel.yml

**Comment by carlosnatalino** [comment]
> v0.20.2 it's still on pre-release. I suggest to use the latest released version and not the one on the master https://raw.githubusercontent.com/coreos/flannel/v0.20.1/Documentation/kube-flannel.yml

Yes, this worked for me.

**Comment by starypatyk** [comment]
@rbrtbnfgl - this worked for me as well. :+1: 

Probably would be good to change the readme, to instruct people to use the latest **released** version rather than master. :wink:

**Comment by svetlana41** [comment]
> v0.20.2 it's still on pre-release. I suggest to use the latest released version and not the one on the master https://raw.githubusercontent.com/coreos/flannel/v0.20.1/Documentation/kube-flannel.yml

Thank you

**Comment by brianthelion** [comment]
Is there a canonical URL for the current released (ie, not pre-release) manifest that is stable across releases? Thanks!

**Comment by rbrtbnfgl** [comment]
The new image is available now. There was some delays from the release to the image publishing this time.

**Comment by starypatyk** [comment]
@rbrtbnfgl - Thanks for updating the documentation. :bow:  Agree that such approach provides better stability. :+1:
