### ISSUE TITLE
registering network: failed to acquire lease - dual stack worker node

### ISSUE THREAD

**Issue by satishh1988** [flannel-io/flannel#1688]
trying to deploy a dual stack k8s  setup on version 1.23 using flannel cni, master node deployment was smooth and tested with pod creation on master got both Ipv4 & ipv6 

kubeadm init  --pod-network-cidr=10.244.0.0/16,2001:db8:42:0::/64 --service-cidr=10.96.0.0/16,2001:db8:42:1::/118

https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 

updated the below PARAMETERS to get dual stack support from https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml 

from the yaml
```
  net-conf.json: |
    {
      "EnableIPv6": true,      
      "Network": "10.244.0.0/16",
      "IPv6Network": "2001:db8:42:0::/64",
      "Backend": {
        "Type": "vxlan"
      }
    }
```
was trying to add a worker node and the ds got failed with the below error. was passing the same --pod-network-cidr for the worker nodes aswell.    please suggest on how to proceed with setting up dual stack worker node config using flannel

**kubectl logs -n kube-flannel kube-flannel-ds-bxzn5**
```
I1212 15:04:00.543861       1 main.go:204] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W1212 15:04:00.544002       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1212 15:04:00.746615       1 kube.go:126] Waiting 10m0s for node controller to sync
I1212 15:04:00.746759       1 kube.go:420] Starting kube subnet manager
I1212 15:04:00.851768       1 kube.go:449] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.244.0.0/24 2001:db8:42::/64]
I1212 15:04:01.840637       1 kube.go:133] Node controller sync successful
I1212 15:04:01.840684       1 main.go:224] Created subnet manager: Kubernetes Subnet Manager - flannelmultus1
I1212 15:04:01.840698       1 main.go:227] Installing signal handlers
I1212 15:04:01.840976       1 main.go:467] Found network config - Backend type: vxlan
I1212 15:04:01.841115       1 match.go:206] Determining IP address of default interface
I1212 15:04:01.842130       1 match.go:259] Using interface with name ens160 and address 10.115.86.20
I1212 15:04:01.842315       1 match.go:262] Using interface with name ens160 and v6 address 2402:1f00:8100:400::eb
I1212 15:04:01.842370       1 match.go:281] Defaulting external address to interface address (10.115.86.20)
I1212 15:04:01.842485       1 match.go:294] Defaulting external v6 address to interface address (2402:1f00:8100:400::eb)
I1212 15:04:01.842682       1 vxlan.go:138] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
E1212 15:04:01.843368       1 main.go:327] **Error registering network: failed to acquire lease: node "flannelmultus1" pod cidr not assigned**
I1212 15:04:01.843589       1 main.go:447] Stopping shutdownHandler...
W1212 15:04:01.843733       1 reflector.go:347] github.com/flannel-io/flannel/subnet/kube/kube.go:421: watch of *v1.Node ended with: an error on the server ("unable to decode an event from the watch stream: context canceled") has prevented the request from succeeding
```

**subnet.env from master node  below where the installation is OK**.  /run/flannel/subnet.env file havent got created on the worker node due to the error above.
```
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.0.1/24
FLANNEL_IPV6_NETWORK=2001:db8:42::/64
FLANNEL_IPV6_SUBNET=2001:db8:42::1/64
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```

**ds pod logs from the master node where the node lease is working:**
```
kubectl logs kube-flannel-ds-2gr2w -n kube-flannel
I1213 09:35:44.418353       1 main.go:204] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true ifaceCanReach: subnetFile:/run/flannel/subnet.env publicIP: publicIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json setNodeNetworkUnavailable:true}
W1213 09:35:44.418434       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I1213 09:35:44.618069       1 kube.go:126] Waiting 10m0s for node controller to sync
I1213 09:35:44.618218       1 kube.go:420] Starting kube subnet manager
I1213 09:35:45.618720       1 kube.go:133] Node controller sync successful
I1213 09:35:45.618771       1 main.go:224] Created subnet manager: Kubernetes Subnet Manager - flannel-controller
I1213 09:35:45.618787       1 main.go:227] Installing signal handlers
I1213 09:35:45.619137       1 main.go:467] Found network config - Backend type: vxlan
I1213 09:35:45.619167       1 match.go:206] Determining IP address of default interface
I1213 09:35:45.619861       1 match.go:259] Using interface with name ens160 and address 10.115.82.131
I1213 09:35:45.619914       1 match.go:262] Using interface with name ens160 and v6 address 2402:1f00:8100:400::e9
I1213 09:35:45.619933       1 match.go:281] Defaulting external address to interface address (10.115.82.131)
I1213 09:35:45.619948       1 match.go:294] Defaulting external v6 address to interface address (2402:1f00:8100:400::e9)
I1213 09:35:45.620054       1 vxlan.go:138] VXLAN config: VNI=1 Port=0 GBP=false Learning=false DirectRouting=false
I1213 09:35:45.656675       1 main.go:416] Current network or subnet (10.244.0.0/16, 10.244.0.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
I1213 09:35:45.715115       1 kube.go:449] Creating the node lease for IPv6. This is the n.Spec.PodCIDRs: [10.244.0.0/24 2001:db8:42::/64]
I1213 09:35:46.120133       1 main.go:342] Setting up masking rules
I1213 09:35:46.124007       1 main.go:432] Current ipv6 network or subnet (2001:db8:42::/64, 2001:db8:42::/64) is not equal to previous one (::/0, ::/0), trying to recycle old ip6tables rules
I1213 09:35:46.417220       1 main.go:353] Setting up masking ip6 rules
I1213 09:35:46.516256       1 main.go:364] Changing default FORWARD chain policy to ACCEPT
I1213 09:35:46.615083       1 main.go:369] IPv6: Changing default FORWARD chain policy to ACCEPT
I1213 09:35:46.715911       1 iptables.go:260] bootstrap done
I1213 09:35:46.816769       1 main.go:379] Wrote subnet file to /run/flannel/subnet.env
I1213 09:35:46.816808       1 main.go:383] Running backend.
I1213 09:35:46.817043       1 vxlan_network.go:61] watching for new subnet leases
I1213 09:35:46.916201       1 main.go:404] Waiting for all goroutines to exit
I1213 09:35:47.317256       1 iptables.go:260] bootstrap done
I1213 09:35:47.418075       1 iptables.go:260] bootstrap done
I1213 09:35:47.517254       1 iptables.go:260] bootstrap done
```

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version: "cniVersion": "v0.20.1"
* Backend used (e.g. vxlan or udp):vxlan
* Etcd version:
* Kubernetes version (if used): 1.23
* Operating System and version: Ubuntu 20.04.5 LTS
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Hi @satishh1988 
If you check `kubectl describe node flannelmultus1` what do you get?

**Comment by satishh1988** [comment]
yes correct we use **kubeadm join**, with only Ipv4 it is working fine.

**Comment by rbrtbnfgl** [comment]
Could yo check the content of `/etc/kubernetes/manifestkube-controller-manager.yaml` on both nodes?
Could you also check the kubelet logs on the failing node?

**Comment by satishh1988** [comment]
in the controller kube-controller-manager.yaml we can see **--cluster-cidr=10.244.0.0/16,2001:db8:42:0::/64**. but in the worker node this directory /etc/kubernetes/manifests is empty it is same in the ipv4 setup where the ds pod is running.

**kubelet logs from the worker node**

Dec 15 05:26:40 flannel-worker kubelet[14761]: I1215 05:26:40.617262   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:26:40 flannel-worker kubelet[14761]: E1215 05:26:40.617421   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:26:40 flannel-worker kubelet[14761]: E1215 05:26:40.618181   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:26:54 flannel-worker kubelet[14761]: I1215 05:26:54.616635   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:26:54 flannel-worker kubelet[14761]: E1215 05:26:54.617629   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:26:54 flannel-worker kubelet[14761]: E1215 05:26:54.618325   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:27:03 flannel-worker kubelet[14761]: E1215 05:27:03.621346   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:27:09 flannel-worker kubelet[14761]: I1215 05:27:09.616979   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:27:09 flannel-worker kubelet[14761]: E1215 05:27:09.617137   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:27:09 flannel-worker kubelet[14761]: E1215 05:27:09.617665   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:27:24 flannel-worker kubelet[14761]: I1215 05:27:24.617330   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:27:24 flannel-worker kubelet[14761]: E1215 05:27:24.618299   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:27:24 flannel-worker kubelet[14761]: E1215 05:27:24.618823   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:27:36 flannel-worker kubelet[14761]: I1215 05:27:36.617131   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:27:36 flannel-worker kubelet[14761]: E1215 05:27:36.617302   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:27:36 flannel-worker kubelet[14761]: E1215 05:27:36.617731   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:27:51 flannel-worker kubelet[14761]: I1215 05:27:51.617119   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:27:51 flannel-worker kubelet[14761]: E1215 05:27:51.618118   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:27:51 flannel-worker kubelet[14761]: E1215 05:27:51.618796   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:28:03 flannel-worker kubelet[14761]: I1215 05:28:03.617151   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:28:03 flannel-worker kubelet[14761]: E1215 05:28:03.617339   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:28:03 flannel-worker kubelet[14761]: E1215 05:28:03.617801   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
Dec 15 05:28:14 flannel-worker kubelet[14761]: I1215 05:28:14.616766   14761 scope.go:110] "RemoveContainer" containerID="a36f914eaf95f92800fbc55518a374e797b1e8a1235485cd34728e1320e528cf"
Dec 15 05:28:14 flannel-worker kubelet[14761]: E1215 05:28:14.616952   14761 dns.go:157] "Nameserver limits exceeded" err="Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 10.10.1.20 10.10.1.11 2001:>
Dec 15 05:28:14 flannel-worker kubelet[14761]: E1215 05:28:14.617411   14761 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-flannel\" with CrashLoopBackOff: \"back-off 5m0s restarting failed container=ku>
lines 39451-39488/39488 (END)

**Comment by rbrtbnfgl** [comment]
I saw some errors dns related. Could you check `/etc/hosts` ? 
The issue could be related to the kube-controller. Could you also check the logs for it? It's running on the controller node.

**Comment by arana198** [comment]
Hi mate, I've been following this post for a few weeks now and finally (unknowingly) got my 3 worker nodes working.

I unknowingly fixed the issue on 2 nodes and figured the solution that worked for me.

I run containerd so I had to change SystemdCgroup = true in `/etc/containerd/config.toml`.

`sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml`

If you run containerd maybe you have the same issue as me

Best of luck

**Comment by satishh1988** [comment]
Hi @rbrtbnfgl 

below is the kube-controller logs.

E0103 07:23:53.888487       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:23:53.889384       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:28:59.333668       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:28:59.333986       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:34:04.765466       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:34:04.765665       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:39:11.049166       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:39:11.049254       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:44:17.867383       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:44:17.867722       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:49:24.251578       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:49:24.251801       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:54:30.041935       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:54:30.041971       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 07:59:36.413602       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 07:59:36.413761       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:04:43.543228       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:04:43.543327       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:09:50.473412       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:09:50.473533       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:14:56.862267       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:14:56.862343       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:20:03.156275       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:20:03.156622       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:25:09.684674       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:25:09.685013       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:30:16.323753       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:30:16.324117       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:35:22.691391       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:35:22.691454       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:40:29.991700       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:40:29.992132       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:45:36.931974       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:45:36.932398       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:50:43.529301       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:50:43.530858       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 08:55:49.499148       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 08:55:49.499187       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:00:54.985186       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:00:54.985279       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:06:02.452805       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:06:02.453545       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:11:08.825232       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:11:08.825611       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:16:15.866293       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:16:15.866862       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:21:22.628904       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:21:22.629081       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:26:28.197410       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:26:28.197770       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:31:34.431025       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:31:34.431601       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:36:40.124890       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:36:40.125328       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:41:46.606191       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:41:46.606229       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:46:53.147957       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:46:53.148086       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:51:59.373690       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:51:59.374369       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 09:57:05.888590       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 09:57:05.889217       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
E0103 10:02:12.710830       1 controller_utils.go:260] Error while processing Node Add/Delete: failed to allocate cidr from cluster cidr at idx:0: CIDR allocation failed; there are no remaining CIDRs left to allocate in the accepted range
I0103 10:02:12.711236       1 event.go:294] "Event occurred" object="flannel-worker" kind="Node" apiVersion="v1" type="Normal" reason="CIDRNotAvailable" message="Node flannel-worker status is now: CIDRNotAvailable"
root@flannel-controller:~#

**/etc/hosts**


root@flannel-worker:~# cat /etc/hosts
127.0.0.1 localhost
127.0.1.1 flannel-worker

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

**Comment by satishh1988** [comment]
> Hi mate, I've been following this post for a few weeks now and finally (unknowingly) got my 3 worker nodes working.
> 
> I unknowingly fixed the issue on 2 nodes and figured the solution that worked for me.
> 
> I run containerd so I had to change SystemdCgroup = true in `/etc/containerd/config.toml`.
> 
> ```
> sudo sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml
> sudo systemctl daemon-reload
> sudo systemctl restart containerd
> sudo systemctl enable containerd
> ```
> 
> If you run containerd maybe you have the same issue as me
> 
> Best of luck

Hi @arana198 

Thanks for your comments, the changes mentioned by you didnt helped.

**Comment by rbrtbnfgl** [comment]
Ok the Issue is related to the IPv6 CIDR subnet you configured /64 for the cluster but /64 is the subnet allocated for each node so after the first node get the CIDR the second one has no CIDR available.
Can you try to allocate more addresses /56 should be enough.
