### ISSUE TITLE
Compatibility with CNI?

### ISSUE THREAD

**Issue by anton-johansson** [flannel-io/flannel#1693]
Hey! This is more of a question, and let me know if there are better places to ask this.

I'm planning an upgrade from Kubernetes `1.20`, flannel `0.13` and CNI `0.8` to their respective latest versions. I see that flannels CNI plugin has been extracted to its own repository. I'm thinking that I'll stay on CNI <1.0 for now, so I still have flannel directly from the CNI plugins, and I'll also stay on the [CNI specification version `0.3.1`](https://github.com/containernetworking/cni/blob/spec-v0.3.1/SPEC.md). If this works, it will make my upgrade a lot easier (but of course I'll push the headache to a future upgrade).

My question is: Is the latest version of flannel (`v0.20.2` as of this post) compatible with the [CNI plugins `v0.9.1`](https://github.com/containernetworking/plugins/releases/tag/v0.9.1) (instead of using the [flannel CNI plugin `v1.1.2`](https://github.com/flannel-io/cni-plugin/releases/tag/v1.1.2)) and the [CNI specification version `0.3.1`](https://github.com/containernetworking/cni/blob/spec-v0.3.1/SPEC.md)?

Would it be possible to include some kind of compatibility matrix in the README? Or maybe one already exists, and I haven't been able to find it yet?

Thanks in advance!

**Comment by thomasferrandiz** [comment]
Hi @anton-johansson ,
we don't have a compatibility matrix at the moment.

We test only the versions of flanneld and flannel CNI plugin that are kept in sync in the [kube-flannel.yml](https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml) manifest.

That being said, the `cniVersion` declared in this manifest and which ends up written in the file `/etc/cni/net.d/10-flannel.conflist` is `0.3.1` so I think it should be fine to use an older version with the latest flanneld.

Also I tested (very quickly) the latest flanneld with flannel cni plugin v0.9.1 and it seems to work fine.

**Comment by anton-johansson** [comment]
@thomasferrandiz 

Allright, thanks for the quick response!
