### ISSUE TITLE
flannel on windows replaced Backend type from VXLAN to HOST-GW but container doesn't start

### ISSUE THREAD

**Issue by fairmonk** [flannel-io/flannel#1709]
I run a mixed k8s cluster: 1 control plane, 4 linux nodes and 2 windows 2019 server nodes

**Problem:**
I got flannel CNI installed using the attached 2 resources ( changed their extension from .yml to .log so I could upload them here )
I can start pods without problem on windows nodes, BUT I CAN NOT PING FROM WINDOWS PODS TO EXTERNAL HOSTS ON THE SAME NETWORK WITH THE WINDOWS NODE

**TROUBLESHOOTING I DID**
I verified that starting a windows docker container from same image via powershell docker run ... command will end up in succesfully reaching out to other hosts from within container. So this is a k8s issue with flannel CNI

Tried to change backend from VXLAN to host-gw by updating the snippet below inside kube-flannel.yml
net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan",
        "VNI": 4096,
        "Port": 4789
      }
    }
TO
net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "host-gw"
      }
    }
THEN restarted the windows node, started a windows pod on that node but it fails to start now with this error:
`Warning  FailedCreatePodSandBox  8m16s                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "fb7c656f56fbdc219d154bc1ad649b716542f7aa64e01247d49f39024227c724" network for pod "test-pod": networkPlugin cni failed to set up pod "test-pod_extractor" network: error while GETHNSNewtorkByName(flannel.4096): Network flannel.4096 not found`

How can I fix my problem ( of accessing node's network from windows containers. Note: it works from linux containers of the same cluster ) ?

Environment
* Flannel version: 
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:
* Kubernetes version (if used): v1.23.2
* Operating System and version: Win2019
* Link to your project (optional):

[flannel-overlay.log](https://github.com/flannel-io/flannel/files/10436412/flannel-overlay.log)
[kube-flannel.log](https://github.com/flannel-io/flannel/files/10436413/kube-flannel.log)

**Comment by rbrtbnfgl** [comment]
When you have changed the netconf.json did you restart every the flannel pods on the cluster or only the windows one?
The pods should be able to ping external hosts using the NAT configured on the host.
