### ISSUE TITLE
image flannel/flannel:v0.21.0 is missing

### ISSUE THREAD

**Issue by smira** [flannel-io/flannel#1712]
## Expected Behavior

Image is available for the latest release https://github.com/flannel-io/flannel/releases/tag/v0.21.0

## Current Behavior

There's no multi-arch tag v0.21.0 at https://hub.docker.com/r/flannel/flannel/tags

## Possible Solution

Push the merged manifest.

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Hi `v0.21.0` is still on pre-release. I am doing some test with the updated actions. I updated them to load the new manifest within the files of the release. If you look at the documentation I updated the link to download to the latest released manifest. `v0.21.0` is not released yet.
`kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml`
