### ISSUE TITLE
flanneld[12110]: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by hydev1126** [flannel-io/flannel#1714]
We depoloyed flannel use binary file, flannel version is v0.20.1, the flanneld process random restart,

Here is the logs:

Jan 30 00:00:31 worker-node1 flanneld[12110]: panic: runtime error: index out of range [0] with length 0
Jan 30 00:00:31 worker-node1 flanneld[12110]: goroutine 60 [running]:
Jan 30 00:00:31 worker-node1 flanneld[12110]: github.com/flannel-io/flannel/subnet/etcd.(*etcdSubnetRegistry).watchSubnets(0xc00009ecc0, {0x1d18f68, 0xc00009eb80}, 0x0)
Jan 30 00:00:31 worker-node1 flanneld[12110]:         /go/src/github.com/flannel-io/flannel/subnet/etcd/registry.go:295 +0x4da
Jan 30 00:00:31 worker-node1 flanneld[12110]: github.com/flannel-io/flannel/subnet/etcd.(*LocalManager).WatchLeases(0xc00009f200, {0x1d18f68, 0xc00009eb80}, {0x18d6080?, 0x294cb20?})
Jan 30 00:00:31 worker-node1 flanneld[12110]:         /go/src/github.com/flannel-io/flannel/subnet/etcd/local_manager.go:344 +0xfe
Jan 30 00:00:31 worker-node1 flanneld[12110]: github.com/flannel-io/flannel/subnet.WatchLeases({0x1d18f68, 0xc00009eb80}, {0x1d1cc30, 0xc00009f200}, 0x15f30b3?, 0xc00037c570?)
Jan 30 00:00:31 worker-node1 flanneld[12110]:         /go/src/github.com/flannel-io/flannel/subnet/watch.go:36 +0xcc
Jan 30 00:00:31 worker-node1 flanneld[12110]: github.com/flannel-io/flannel/backend/vxlan.(*network).Run.func1()
Jan 30 00:00:31 worker-node1 flanneld[12110]:         /go/src/github.com/flannel-io/flannel/backend/vxlan/vxlan_network.go:65 +0x45
Jan 30 00:00:31 worker-node1 flanneld[12110]: created by github.com/flannel-io/flannel/backend/vxlan.(*network).Run
Jan 30 00:00:31 worker-node1 flanneld[12110]:         /go/src/github.com/flannel-io/flannel/backend/vxlan/vxlan_network.go:64 +0x171
Jan 30 00:00:31 worker-node1 systemd[1]: flanneld.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 30 00:00:31 worker-node1 systemd[1]: flanneld.service: Unit entered failed state.
Jan 30 00:00:31 worker-node1 systemd[1]: flanneld.service: Failed with result 'exit-code'.
Jan 30 00:00:36 worker-node1 systemd[1]: flanneld.service: Service RestartSec=5s expired, scheduling restart.
Jan 30 00:00:42 worker-node1 systemd[1]: Stopped Flanneld address.
Jan 30 00:00:42 worker-node1 systemd[1]: Starting Flanneld address...

Heris is the systemd configuraton file
cat > /usr/lib/systemd/system/flanneld.service << "EOF"
[Unit]
Description=Flanneld address
After=network.target
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
ExecStart=/usr/local/bin/flanneld \
  --etcd-cafile=/etc/etcd/ssl/ca.pem \
  --etcd-certfile=/etc/etcd/ssl/etcd.pem \
  --etcd-keyfile=/etc/etcd/ssl/etcd-key.pem \
  --etcd-endpoints=https://172.20.80.135:2379,https://172.20.80.136:2379,https://172.20.80.137:2379 \
  --etcd-prefix=/coreos.com/network \
  --iface=ens192
  --ip-masq=\$FLANNEL_OPTIONS
ExecStartPost=/usr/local/bin/mk-docker-opts.sh -k DOCKER_NETWORK_OPTIONS -d /run/flannel/docker
Restart=always
RestartSec=5
StartLimitInterval=0
[Install]
WantedBy=multi-user.target
RequiredBy=docker.service
EOF

**Comment by rbrtbnfgl** [comment]
Hi @hydev1126 which version of etcd are you using?

**Comment by hydev1126** [comment]
etcd version is v3.5.6

**Comment by hydev1126** [comment]
> Hi @hydev1126 which version of etcd are you using?


etcd version is v3.5.6
