### ISSUE TITLE
Missing CNI binaries (loopback, etc) - not compliant?

### ISSUE THREAD

**Issue by KyleSanderson** [flannel-io/flannel#1715]
## Expected Behavior
I'm running on rke2 1.24 with --cni=none as they've removed the ability to just deploy with flannel and nothing else.

## Current Behavior
Flannel tries to invoke loopback and similar binaries, which are not provided by the CNI... I don't understand the CNI spec well but I believe flannel (and not rke2) is out of compliance by not providing these.

## Possible Solution
Ship the binaries required. Installing Multus and then Flannel papers over the bug, but Flannel should be providing these per the spec and every other CNI operating that way.

## Steps to Reproduce (for bugs)

1. Install rke2 with --cni=none
2. Fix the flannel manifest to use the proper cidr
3. Deploy Flannel
4. Deploy a workload and see it get stuck on loopback.

## Context
I'm running rke2 in docker unfortunately due to libvirt defects and virtiofs bugs.

## Your Environment

* Flannel version:  v0.21.0
* Backend used (e.g. vxlan or udp): retail
* Etcd version: sqlite
* Kubernetes version (if used): v1.24.10+rke2r1
* Operating System and version: rhel9.1
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
I don't know if I am wrong but RKE2 is installing the CNI bin if you are using the preconfigured CNI if you use `--cni=none` nothing is installed. I suggest you to manually install the other CNI with
```
mkdir -p /opt/cni/bin
curl -O -L https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v1.1.1.tgz
```
I don't think we should deploy them with flannel. It depends on the setup where it's deployed.

**Comment by KyleSanderson** [comment]
Those instructions worked a treat - thank you. It does feel weird that you can be left in a state where it's relying on binaries that aren't part of the distribution. Perhaps this could be added to the Flannel docs?

**Comment by jeffgtxjava** [comment]
@thomasferrandiz  Any idea flannel supports `nft` instead of `iptables-ntf` via alternatives on RHEL9

**Comment by jeffgtxjava** [comment]
<img width="788" alt="image" src="https://github.com/flannel-io/flannel/assets/74207796/428d7791-c995-4c79-b51b-6e0f5623e7c2">


https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html/9.0_release_notes/deprecated_functionality#deprecated-functionality_networking

**Comment by rbrtbnfgl** [comment]
Hi @jeffgtxjava could you open a new issue related to this. Also other k8s components are using iptables this could be a problem.

**Comment by jeffgtxjava** [comment]
@rbrtbnfgl Done raise one with kube-proxy [here ](https://github.com/kubernetes/kube-proxy/issues/23)

But is there a general recommendation since we have moved past the wrapper stage!

**Comment by KyleSanderson** [comment]
.
