### ISSUE TITLE
 err="[failed to find plugin \"portmap\" in path [/opt/cni/bin]

### ISSUE THREAD

**Issue by liuqi-sun** [flannel-io/flannel#1730]
kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
An error occurred in kubelete after I installed the flannel using the command above，The error is as follows：
![image](https://user-images.githubusercontent.com/48784730/220371057-964c1886-2f7f-4603-a055-79578be6fdff.png)

## Current Behavior
I found the initContainers DaemonSet just copy flannel binary to/opt/the cni/bin/flannel, portmap binary no copy.So I modified the list of nci-conf. json plugins in configMap and removed portmap.I think there is something wrong with kube-flannel.yml.

After modifying configMap, a new error occurs.  Now I don't know what to do,the error is as follows.
![image](https://user-images.githubusercontent.com/48784730/220373354-62836e1f-48ce-4371-a698-5b2b1d97f66f.png)

## Your Environment

* Flannel version: 
* Backend used (e.g. vxlan or udp):vxlan 
* Etcd version:
* Kubernetes version (if used): 1.23.8
* Operating System and version: centos 7, Linux node1 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
You need to install the others kubernetes CNIs
```
mkdir -p /opt/cni/bin
curl -O -L https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
tar -C /opt/cni/bin -xzf cni-plugins-linux-amd64-v1.1.1.tgz
```
