### ISSUE TITLE
error:github.com/flannel-io/flannel/subnet/kube/kube.go:300: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:flannel" cannot list resource "nodes" in API group "" at the cluster scope

### ISSUE THREAD

**Issue by tianzengyin** [flannel-io/flannel#1735]
use :  kubectl logs kube-flannel-ds-xfhg5 -n kube-system
E0228 12:46:56.116449       1 reflector.go:127] github.com/flannel-io/flannel/subnet/kube/kube.go:300: Failed to watch *v1.Node: failed to list *v1.Node: nodes is forbidden: User "system:serviceaccount:kube-system:flannel" cannot list resource "nodes" in API group "" at the cluster scope
It seems that there is no cluster read permission

How to solve it!!!

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):v1.23.6
* Operating System and version:
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
How did you deploy flannel? You missed the RBAC.
