### ISSUE TITLE
windows pod error while adding to cni network: error while ProvisionEndpoint: Cannot create a file when that file already exists.

### ISSUE THREAD

**Issue by yuwei1chen** [flannel-io/flannel#1742]
## Expected Behavior
We want to run docker windows hyperv isolation mode in kubernetes.
Both Windows hyperv isolation mode and process isolation mode container pod in kubernetes is started correctly with a pod ip and right network configuration.

## Current Behavior
Everything works fine for windows isolation mode pods in kubernetes.But for windows hyperv isolation mode pods, they have no pod ip and keeps restarting. 
below is what I got from "kubelet get pod -o wide", we can see that in IP column is "<none>". And it keeps restarting and have restarted 51 times:
`hyperv-0   0/1     CrashLoopBackOff   51         110m   <none>          jf53120cp-hv `

In kubelet log, we see:
`E0315 00:04:48.592295   11324 cni.go:366] Error adding hyperv-0/ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23 to network flannel/flannel.4096: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists.
E0315 00:04:48.592295   11324 cni_windows.go:59] error while adding to cni network: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists.`

The only different in 2 isolation mode pods is the annotation "experimental.windows.kubernetes.io/isolation-type: hyperv", which is to tell kubelet which windows container isolation mode to use.

## Context
We are trying the Windows hyperv isolation mode feature gate in kubernetes. Process isolation mode works fine, but pods cannot get pod ip when started with isolation mode.

## Your Environment
* Flannel version: flannel:v0.13.0-nanoserver
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.4.13
* Kubernetes version (if used): 1.20.2
* Operating System and version: Windows Server 2019
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
That is a very old flannel version where did you get it? I don't find any release with `-nanoserver` is this downloaded from a forked project? I checked the `v0.31.0` tag source code and it seems that there aren't any files named `cni.go` or `cni_windows.go` on it. Reading from the errors it seems like it's trying to create a new interface but it's already created are you sure you are not executing two flannel instances on the same node?

**Comment by yuwei1chen** [comment]
> That is a very old flannel version where did you get it? I don't find any release with `-nanoserver` is this downloaded from a forked project? I checked the `v0.13.0` tag source code and it seems that there aren't any files named `cni.go` or `cni_windows.go` on it. Reading from the errors it seems like it's trying to create a new interface but it's already created are you sure you are not executing two flannel instances on the same node?

"nanoserver" is the tag of flannel container image, from https://hub.docker.com/r/sigwindowstools/flannel. If 0.13.0 is too old, what's the proper version we should use for v1.20 windows k8s cluster?
Those two go file are in kubelet, I believe, it implies that error message is comming from flannel.
And I'm sure that we are not excuting 2 flannel instances, after all, process mode pods don't have the same issue and work well.

**Comment by yuwei1chen** [comment]
After keep creating and deleting hyperv isolation mode pods for a weekend, we cannot create new pod anymore. We see below events though there are only  a few pods running on this node.
failed to make a new HNSEndpoint: error while ipam.ExecAdd: failed to allocate for range 0: no IP addresses available in range set: 10.244.24.1-10.244.24.254
Perhaps flannel have issue cleaning up network entries for hyperv isolation mode containers in windows?

**Comment by rbrtbnfgl** [comment]
That's not flannel doing. The IP should be assigned by the controller.

**Comment by yuwei1chen** [comment]
> That's not flannel doing. The IP should be assigned by the controller.

`E0315 00:04:48.592295   11324 cni.go:366] Error adding hyperv-0/ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23 to network flannel/flannel.4096: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists. E0315 00:04:48.592295   11324 cni_windows.go:59] error while adding to cni network: error while ProvisionEndpoint(ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23_flannel.4096,D3CBB652-3DCC-486F-BBB5-690D54C96F18,ded8068e29d711f9e996fdc753a99a1eb421509decb0035709f6e58291be8a23): Cannot create a file when that file already exists.`

According to kubernetes community, this error message comes from flannel. @rbrtbnfgl 
We have also filed a issue to kubernetes community, https://github.com/kubernetes/kubernetes/issues/116697

**Comment by rbrtbnfgl** [comment]
My reply was related to the error for the IP assignment not the flannel log.
You could check the interface on windows to check if the flannel interfaces were previously created.
