### ISSUE TITLE
Question/advice needed about upgrade Flannel in Vanilla Kubernetes 1.23.4 Cluster

### ISSUE THREAD

**Issue by lightmans2** [flannel-io/flannel#1753]
Question/advice needed about upgrade Flannel in Vanilla Kubernetes 1.23.4 Cluster

## Current Behavior
we have since 2y a vanilla kubernets (kubernetes.io) installation on rhel8 in a productive and dev enviroment with flannel 0.14.1
we do rhel and kubernetes updates, but the cni was not needed to update until now because all was working fine until now.
we found in the rhel and flannel logs that the flannel container crashes with that error `iptables.go:118] Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t filter -C FORWARD -s 10.244.0.0/16 -j ACCEPT --wait]: exit status -1:` and dmesg ` iptables[51388]: segfault at 88 ip 00007fe6cd937e47 sp 00007ffe58e4ed68 error 4 in libnftnl.so.11.3.0[7fe6cd933000+16000]`
 reason is a bug in iptables (nf_tables) 1.8.4 and the old cni plugin. 

## Expected Behavior
that the cni flannel update runs trough without problems and the above error `iptables.go:118] Failed to ensure iptables rules: Error checking rule existence: failed to check rule existence: running [/sbin/iptables -t filter -C FORWARD -s 10.244.0.0/16 -j ACCEPT --wait]: exit status -1:` disapears and the cni container works without crash

## Possible Solution
we read this solution https://github.com/flannel-io/flannel/blob/master/Documentation/upgrade.md
1. do a backup of the os and the kubernetes namespaces/applications
2. scale down all pods and namespaces to 0, only kube-system container would run
3. remove the cni flannel .14.1 with kubectl delete -f kube-flannel.yml
4. reinstall the new cni version with kubectl create -f kube-flannel.yml
5. reboot master and worker nodes
6. cross fingers and hope that all works and scale up the applications and namespaces :-)
7. if all works fine i would like to update kubernetes to 1.23.17 or maybe 1.24.12

## Steps to Reproduce (for bugs)
n/a (error is known as bug in iptables and flannel version)

## Context
can you give me some advice or hints about the procedure to upgrade the cni plugin in kubernetes 1.23.4? 
is the procedure correct that i described above in "possible solution"?
can you tell me which version of flanel is recomended for kubernetes 1.23 and later to 1.24?
where do i found older yaml installation files from older flannel versions?

## Your Environment
* Flannel version:  - 0.14.1
* Backend used (e.g. vxlan or udp): - vxlan 
* Etcd version: - 3.5.1
* Kubernetes version (if used): - 1.23.4
* Operating System and version: - rhel 8.7

thx in advance for all hints and advices

**Comment by rbrtbnfgl** [comment]
Did you get the error with Flannel `0.14.1` or the newer version?

**Comment by lightmans2** [comment]
> Did you get the error with Flannel `0.14.1` or the newer version?

yes on version flannel v0.14.1 with rhel8.7 (uptodate) and iptables 1.8.4
i saw and read in the issue board that this was fixed in >v0.15.1 i guess

**Comment by rbrtbnfgl** [comment]
Your steps should be fine. I suggest you to use the `kube-flannel.yml` of the version that you are using when doing the delete process https://github.com/flannel-io/flannel/blob/v0.14.1/Documentation/kube-flannel.yml
And after that you can use the latest `kube-flannel.yml` to update to the latest version.
Depending on which version of kubernetes you are using you should consider the one with PSP or without it.

**Comment by lightmans2** [comment]
> Your steps should be fine. I suggest you to use the `kube-flannel.yml` of the version that you are using when doing the delete process https://github.com/flannel-io/flannel/blob/v0.14.1/Documentation/kube-flannel.yml And after that you can use the latest `kube-flannel.yml` to update to the latest version. Depending on which version of kubernetes you are using you should consider the one with PSP or without it.

thank you for your answer, but thats the point -> i installed the original vanilla kubernetes from kubernetes.io two years ago and have the version at the moment 1.23.4 ... i want to upgrade later to 1.24... so which version should i use? with or without psp?

**Comment by rbrtbnfgl** [comment]
On `1.24` psp should be already deprecated then it'll be better to use the one without it.

**Comment by rbrtbnfgl** [comment]
I'll close this issue. If there are any other questions feel free to reopen.
