### ISSUE TITLE
Flannel VXLAN interface always listens on 0.0.0.0:8472

### ISSUE THREAD

**Issue by mriesen** [flannel-io/flannel#1757]
Flannel is not respecting configuration when it comes to listening on the port `8472`.

## Expected Behavior
Configuring Flannel to use a specific network interface should cause Flannel to listen to the defined address.
For example, the interface `abc` with the IP address `10.0.0.1` is configured.
The port should be opened on `10.0.0.1:8472`.

## Current Behavior
Flannel is listening on `0.0.0.0:8472`, even if another interface and IP address is configured.

`ip -d link show flannel.1` results in:
```
5: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1370 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff promiscuity 0 minmtu 68 maxmtu 65535 
    vxlan id 1 local 10.0.0.1 dev abc srcport 0 0 dstport 8472 nolearning ttl auto ageing 300 udpcsum noudp6zerocsumtx noudp6zerocsumrx addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```
But flannel listens to `0.0.0.0`:
`netstat -tulpn`
```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name 
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -                 
```
No PID and no state is shown, but this is also true for other network services like Wireguard.

## Steps to Reproduce (for bugs)
By using Canal as CNI for an RKE2 cluster, Flannel is used for inter-node traffic.
Canal is configured via a HelmChartConfiguration, which comes down to the following args for Flannel: 
```
--ip-masq
--kube-subnet-mgr
--iface=abc
--public-ip=10.0.0.1
```

## Context
Open ports on `0.0.0.0` are a security concern.
My approach is to use a specific address of a VPN network interface for inter-node communication.

## Your Environment
* Flannel version: rancher/hardened-flannel:v0.21.3
* Backend used (e.g. vxlan or udp): VXLAN
* Etcd version: v3.5.4-k3s1
* Kubernetes version (if used): v1.25.8+rke2r1
* Operating System and version: Rocky Linux 9

**Comment by rbrtbnfgl** [comment]
Hi thanks for reporting this I'll take a look at it. As temporary solution, if you don't want that the port is exposed on other IPs, you can add an iptables rule on the INPUT chain to drop the traffic on that port if the destination IP is not the desired one.

**Comment by mriesen** [comment]
I can now confirm that this is not directly caused by flannel:
Using Calico as CNI yields the same result.
Therefore, I close this issue here.

**Comment by mriesen** [comment]
After some more research I can confirm that this is not a Flannel specific problem but a problem with VXLAN.

I could reproduce the behavior by creating the IP link manually.
No matter where I bind the port to, it still listens on 0.0.0.0 for some reason.

Therefore, it's confirmed that this ticket was going in the wrong direction.
