### ISSUE TITLE
Flannel Route Dissapears After Interface Restart

### ISSUE THREAD

**Issue by jvincze84** [flannel-io/flannel#1759]
Hi,

I'm using Flannel DS on Kubernetes over Wireguard VPN.
So, I have 5 nodes connected to each other with Wireguard VPN, and I'm using VPN address for node ip address.

Example:

Interface:
```
wg0: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1420
        inet 10.8.0.3  netmask 255.255.255.0  destination 10.8.0.3
        unspec 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00  txqueuelen 1000  (UNSPEC)
        RX packets 584357398  bytes 546130135846 (508.6 GiB)
        RX errors 522  dropped 0  overruns 0  frame 522
        TX packets 335354375  bytes 184853701804 (172.1 GiB)
        TX errors 70715  dropped 121 overruns 0  carrier 0  collisions 0
```

Kubelet:

```
cat /etc/default/kubelet
KUBELET_EXTRA_ARGS=--node-ip=10.8.0.3
```
Container args:

```
     containers:
      - args:
        - --ip-masq=true
        - --kube-subnet-mgr
        - --iface=wg0
        - -v=1
        - --healthz-port=18088
```

Route table:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gw.contabo.net  0.0.0.0         UG    0      0        0 eth0
10.8.0.0        0.0.0.0         255.255.255.0   U     0      0        0 wg0
10.26.0.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
10.26.1.0       10.26.1.0       255.255.255.0   UG    0      0        0 flannel.1
10.26.2.0       10.26.2.0       255.255.255.0   UG    0      0        0 flannel.1
10.26.3.0       10.26.3.0       255.255.255.0   UG    0      0        0 flannel.1
10.26.4.0       10.26.4.0       255.255.255.0   UG    0      0        0 flannel.1
localnet        gw.contabo.net  255.255.240.0   UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```

If wireguard is restarted (systemctl restart wg-quick@wg0) the flannel routes are gone:

```
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         gw.contabo.net  0.0.0.0         UG    0      0        0 eth0
10.8.0.0        0.0.0.0         255.255.255.0   U     0      0        0 wg0
10.26.0.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
localnet        gw.contabo.net  255.255.240.0   UG    0      0        0 eth0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
```
I have to restart the flannel POD on the node to recreate the routes.

## Expected Behavior
Route should be check periodically and recreate them if some is missing.

## Current Behavior
Routes are never recreated.

## Your Environment

* Flannel version: docker.io/flannel/flannel:v0.21.3
* Backend used: vxlan
* Etcd version: registry.k8s.io/etcd:3.5.6-0
* Kubernetes version (if used): v1.25.6
* Operating System and version:  Debian GNU/Linux 11 (bullseye)

Thanks for your help in advance.

**Comment by jvincze84** [comment]
> why do you need to restart wireguard?

When I modify or add new peer sometimes the "wg syncconf wg0 <(wg-quick strip wg0)" command not enough.  I don't know why but last time when I added new peer, the communication not worked until Wireguard restart.

**Comment by rbrtbnfgl** [comment]
Updating the route update on flannel could require a lot of modification on flannel side I think that the route deletion is related to the interface that it's deleted maybe you can try to use a dummy iface instead of wg0 directly on flannel.
