### ISSUE TITLE
Why is an IP address like 10.244.1.0/32 assigned to flannel.1?(VXLAN)

### ISSUE THREAD

**Issue by royroyee** [flannel-io/flannel#1769]
Why is an IP address like 10.244.1.0/32 assigned to flannel.1? (VXLAN) 

I am trying to configure flannel with only Linux bridge commands(VXLAN), but when a broadcast packet comes in through the VXLAN interface, it is not forwarded to the cni0 bridge, and the ARP Request cannot be received. I understand that flannel updates the routing table and updates the ARP table and FDB when nodes are created or deleted

I have also confirmed that flannel.1 interface is not directly connected to cni0 bridge. For example, the following command is not executed:
```
ip link set flannel.1 master cni0
```

Can you tell me what I missed?

Here are the commands I executed:

```
1. Create a virtual bridge (=cni0)
brctl addbr br0

2. Create network namespaces
ip netns add ns1
ip netns add ns2

3. Create network interface pairs
ip link add veth0 type veth peer name eth0
ip link add veth1 type veth peer name eth1

4. Assign network interface pairs
ip link set veth0 master br0
ip link set veth1 master br0

ip link set eth0 netns ns1
ip link set eth1 netns ns2

5. Activate interfaces
ip link set dev veth0 up
ip link set dev veth1 up
ip link set br0 up

ip netns exec ns1 ip link set dev lo up
ip netns exec ns2 ip link set dev lo up

ip netns exec ns1 ip link set eth0 up
ip netns exec ns2 ip link set eth1 up

6. Assign IP addresses
ip netns exec ns1 ip addr add 10.244.1.10/24 dev eth0
ip netns exec ns2 ip addr add 10.244.1.11/24 dev eth1

ip addr add 10.244.1.1/24 dev br0 # gateway

7. If FORWARD is not set to ACCEPT
iptables --policy FORWARD ACCEPT

8. Set routing table
ip route add 10.244.1.0/24 dev br0

9. Set default routing table
ip netns exec ns1 ip route add default via 10.244.1.1
ip netns exec ns2 ip route add default via 10.244.1.1

10. Apply masquerade (access to external network)
sysctl -w net.ipv4.ip_forward=1 # Enable Linux IP forward feature
iptables -t nat -A POSTROUTING -s 10.244.1.0/24 -j MASQUERADE
```

This was executed on two nodes (worker1 and worker2) and the only difference was the IP range:

worker1: 10.244.1.0/24
worker2: 10.244.2.0/24

Then I configured the VXLAN interface as follows:

### worker1
```
ip link add vxlan1 type vxlan id 1 dev ens192 dstport 8472 local 10.0.20.230 remote 10.0.20.231 nolearning
ip addr add 10.244.1.0/32 dev vxlan1

ip link set vxlan1 up

ip route add 10.244.2.0/24 dev vxlan1
ip route add 10.244.0.0/24 dev vxlan1

ip neighbor add 10.0.20.231 lladdr 9a:b1:40:0a:74:36 dev vxlan1 nud permanent
bridge fdb add 9a:b1:40:0a:74:36 dev vxlan1 self dst 10.0.20.231 vni 1 port 8472
```
- 9a:b1:40:0a:74:36 : VXLAN interface MAC address of worker 2 (vxlan1)
- 10.0.20.231 : IP address of worker2 host

### worker 2
```
ip link add vxlan1 type vxlan id 1 dev ens160 dstport 8472 local 10.0.20.231 remote 10.0.20.230 nolearning
ip addr add 10.244.2.0/32 dev vxlan1
ip link set vxlan1 up
ip route add 10.244.1.0/24 dev vxlan1
ip route add 10.244.0.0/24 dev vxlan1

ip neighbor add 10.0.20.230 lladdr d6:02:7e:9e:fb:f0 dev vxlan1 nud permanent
bridge fdb add d6:02:7e:9e:fb:f0 dev vxlan1 self dst 10.0.20.230 vni 1 port 8472
```
- d6:02:7e:9e:fb:f0 : VXLAN interface MAC address of worker1(vxlan1)
- 10.0.20.231 : IP address of worker1 host

After pinging from worker1 to worker2 (from ns 10.244.1.10 on worker1 to ns 10.244.2.10 on worker2), 
I captured the following broadcast packets on the VXLAN interface with tcpdump, but no packets were captured on cni0 (in this case, br0):

```
root@worker2:~# sudo tcpdump -i vxlan1 -vv -nne
tcpdump: listening on vxlan1, link-type EN10MB (Ethernet), capture size 262144 bytes
02:55:36.026530 d6:02:7e:9e:fb:f0 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
02:55:37.055448 d6:02:7e:9e:fb:f0 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
```
- Packets were confirmed to be delivered from worker 1 to worker 2's VXLAN interface

```
root@worker2:~# tcpdump -i br0 -vv -e
```
- But no packets were captured on br0, so the namespace is unable to send an ARP reply.

### If the vxlan interface is connected to a bridge
````
ip link set vxlan1 master br0
````
- Although the ARP reply is sent by the namespace (10.244.2.10) on worker2, the namespace ns1 on worker1 is still unable to ping

```
root@worker2:~# tcpdump -i veth0 -vv -ne
tcpdump: listening on veth0, link-type EN10MB (Ethernet), capture size 262144 bytes
05:37:08.564745 d6:02:7e:9e:fb:f0 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
05:37:08.564807 96:da:34:6f:21:95 > d6:02:7e:9e:fb:f0, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Reply 10.244.2.10 is-at 96:da:34:6f:21:95, length 28
```
- 96:da:34:6f:21:95 : MAC address of  worker2 ns(10.244.2.10) 
- d6:02:7e:9e:fb:f0 : VXLAN interface MAC address of worker1(vxlan1)

```
root@worker1:~# tcpdump -i veth0 -vv -ne
tcpdump: listening on veth0, link-type EN10MB (Ethernet), capture size 262144 bytes
05:37:08.564745 d6:02:7e:9e:fb:f0 > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
05:37:08.564807 96:da:34:6f:21:95 > d6:02:7e:9e:fb:f0, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Reply 10.244.2.10 is-at 96:da:34:6f:21:95, length 28
```

Can you help me figure out what I missed?

**Comment by rbrtbnfgl** [comment]
The commands that you listed is for?
You don't need to add the vxlan interface to the bridge that only connects the pods. Only the traffic for pods on another node are forwarded to the vxlan.

**Comment by royroyee** [comment]
I tried setting up a VXLAN interface without adding it to the bridge as mentioned in this issue(I performed the commands without adding the VXLAN interface to the bridge, as mentioned earlier in the table of **If the vxlan interface connected to bridge**), but it didn't work well. I'm doing this for the purpose of studying CNI. I would appreciate your help in understanding and configuring flannel VXLAN using Linux commands.

**Comment by royroyee** [comment]
Certainly. I understand. In that case, does flanneld provide only ARP and FDB information for configuring VXLAN in flannel? I'm wondering why packets aren't being transmitted with just those commands.
```
ip link add vxlan1 type vxlan id 1 dev ens192 dstport 8472 local 10.0.20.230 remote 10.0.20.231 nolearning
ip addr add 10.244.1.0/32 dev vxlan1

ip link set vxlan1 up

ip route add 10.244.2.0/24 dev vxlan1
ip route add 10.244.0.0/24 dev vxlan1

ip neighbor add 10.0.20.231 lladdr 9a:b1:40:0a:74:36 dev vxlan1 nud permanent
bridge fdb add 9a:b1:40:0a:74:36 dev vxlan1 self dst 10.0.20.231 vni 1 port 8472
```
It seems like flannel has configured VXLAN in a similar manner, but is there something I might have overlooked?

**Comment by royroyee** [comment]
Thank you for your kind response. I'll have to look into it further to see what part I might have overlooked...

**Comment by royroyee** [comment]
Can you provide some additional context?

flannel.1: 10.244.2.0/32
cni0: 10.244.1.0/24

Typically, IP addresses are assigned in this manner. By adding a routing table entry, flannel can route specific node ranges to flannel.1.  However, when a **broadcast packet** like an ARP request reaches flannel.1, how is the packet forwarded to cni0? The IP addresses of the two interfaces belong to different subnets, so I'm curious how L2 networking is possible in this scenario.

```
tcpdump: listening on vxlan1, link-type EN10MB (Ethernet), capture size 262144 bytes
16:17:51.641667 b2:c3:23:33:02:eb > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
16:17:52.664188 b2:c3:23:33:02:eb > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
16:17:53.688147 b2:c3:23:33:02:eb > ff:ff:ff:ff:ff:ff, ethertype ARP (0x0806), length 42: Ethernet (len 6), IPv4 (len 4), Request who-has 10.244.2.10 tell 10.244.1.0, length 28
```
- The VXLAN interface (such as flannel.1) receives ARP broadcast packets from other nodes.
- However, it cannot forward these packets to cni0. As a result, ARP reply is not possible.
