### ISSUE TITLE
How to set MTU in kube-flannel.yml

### ISSUE THREAD

**Issue by jackchuong** [flannel-io/flannel#1775]
Hi all,
I have K8S self-managed on premise (v1.26 - Ubuntu 22.04) , setup with kubeadm , CNI Flannel latest , CRI docker with Mirantis cri-dockerd as Docker Engine shim.
Deploying Flannel with kubectl
`kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml`
Here my MTU status
```
ifconfig | grep mtu
cni0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
ens160: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
veth16587678: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
veth2f7e5b5d: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
veth7e986d31: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
vetha0cb99ca: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
vethc5c13a28: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450
```
How can I set MTU in yml to 1500 and redeploy it ?

**Comment by jackchuong** [comment]
I changed kube-flannel.yml and redeploy it
```
---
apiVersion: v1
...
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan",
        "MTU": 1500
      }
```
I can see pod in kube-flannel namespace was recreated , but ifconfig | grep mtu still same result , should I reboot the node ?

**Comment by rbrtbnfgl** [comment]
The MTU is right. The MTU configured on the pod interface is base MTU - Header overhead.
