### ISSUE TITLE
Set mtu separately for ipv4 and ipv6 

### ISSUE THREAD

**Issue by bingoct** [flannel-io/flannel#1781]
## Expected Behavior

give mtu option of ipv4/ipv6 separately
or
the mtu of ipv6 should be 20 less than that of IPv4 

## Current Behavior
i set the mtu as 1414. both ipv4 and ipv6 flannel interface mtu config as same.
```plaintext
48: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1364 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 46:e0:5d:83:24:80 brd ff:ff:ff:ff:ff:ff
49: flannel-v6.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1364 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether fa:a0:6b:9c:4f:f5 brd ff:ff:ff:ff:ff:ff
50: cni0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1364 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 8e:a9:a6:5f:c6:98 brd ff:ff:ff:ff:ff:ff
```

## Steps to Reproduce (for bugs)
```
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "IPv6Network": "fd00::1234:5678:100:0/104",
      "IPv6SubnetLen": 120,
      "EnableIPv6": true,
      "Backend": {
        "Type": "vxlan",
        "MTU": 1414
      }
    }   
```

## Context

the length of ipv4 is  20 Bytes without extra option and length of ipv6 is 40 Btye.
when i don't config MTU in flannel config file, it works right (ipv4 MTU - 50 , ipv6 MTU - 70 ) in default .

## Your Environment

* Flannel version: 0.22.0
* Backend used (e.g. vxlan or udp): vxlan
* Kubernetes version (if used): 1.23
* Operating System and version: centos 7

**Comment by rbrtbnfgl** [comment]
The MTU size it's managed by linux with the default config. It configures the Interface with IPv6 because it has only the IPv6 address. The MTU is configured by kubelet on the pod network interface using 50 by default to have the right MTU for IPv6 should be 70 everywhere.
