### ISSUE TITLE
Failed to create pod sandbox: rpc error: code = Unknown desc = failed pulling image "registry.k8s.io/pause:3.6":

### ISSUE THREAD

**Issue by Hans-Wu-cn** [flannel-io/flannel#1782]
## Expected Behavior
I need to build a cluster consisting of one main node and one work node for learning
## Current Behavior
After applying kube flannel.yml, there are two flannel pods with different suffixes, one of which has an error. I found it through describe
`Warning FailedCreatePodSandBox 4s kubelet Failed to create pod sandbox: rpc error: code=Unknown desc=failed pulling image "registry. k8s. io/pause: 3.6": Error response from daemon: Head“ https://asia-northeast1-docker.pkg.dev/v2/k8s-artifacts-prod/images/pause/manifests/3.6 : dial TCP 142.251.8.82:443: I/O timeout`

Due to the special network environment, it is not possible to download to pause: 3.6, but I remember when I started kubelet, I specified pause: 3.9
```
master0@master0 :~$kubeadm config images list
Registry. k8s. io/kube apiserver: v1.27.3
Registry. k8s. io/kube controller manager: v1.27.3
Registry. k8s. io/kube scheduler: v1.27.3
Registry. k8s. io/kube proxy: v1.27.3
Registry. k8s. io/pause: 3.9
Registry.k8s. io/etc: 3.5.7-0
Registry. k8s. io/coredns/coredns: v1.10.1
```
Then I went to the mirror website and downloaded it through Docker, and modified his tag
`sudo docker tag registry.aliyuncs.com/google_containers/pause:3.6 `
But it still hasn't worked, it seems like there's no use for local mirroring

## Environment
Kubelet: 1.27.3
Kubeadm: 1.27.3
Flannel: 0.22.0
Ubuntu: 22.04.1
CRI Docker: 0.3.3

**Comment by rbrtbnfgl** [comment]
I think you should check Kubelet logs it should be responsible of which pause container should be used not flannel.
