### ISSUE TITLE
Kubernetes Service using 10.88.x.x instead 10.244.x.x

### ISSUE THREAD

**Issue by angudadevops** [flannel-io/flannel#1784]
Different CIDR block IP for Kubenretes service 
## Expected Behavior
When we deploy 0.22.0 flannel version on Kubernetes 1.27.0 we observed with different cidr block ip

## Current Behavior
when we deploy any service we can see endpoint starting with 10.88.x.x 

```
kubectl get endpoints
NAME                    ENDPOINTS                                         AGE
kubernetes              192.168.100.1:6443                                42h
metrics-server          10.88.0.12:4443                                   41h
```
Suggestion: it should be 10.244.x.x instead 10.88.x.x

## Steps to Reproduce (for bugs)
create a standard kubernetes cluster 1.27 and deploy 0.22.0 flannel and create sample service 

## Context
we don't want to break any service connectivity in future so wanted to make sure 

## Your Environment
* Flannel version: 0.22.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5
* Kubernetes version (if used): 1.27.0
* Operating System and version: Ubuntu

**Comment by rbrtbnfgl** [comment]
Flannel is not selecting the service IPs. Flannel configures the pod IPs to change the IPs used by the endpoints you have to configure them when you start kubernetes.

**Comment by angudadevops** [comment]
can you please point me how to configure the endpoints to use flannel IP because we have started the kubernetes cluster as per below 
```
kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/run/containerd/containerd.sock --kubernetes-version="v1.27.0" 
```

**Comment by rbrtbnfgl** [comment]
you can't. Pod IPs and endpoint IPs can't be overlapped.

**Comment by angudadevops** [comment]
Thank you for the clarification, you can close this issue.
