### ISSUE TITLE
Flannel Pod on remote node can't connect to Kubernetes API on Control Plane Node.

### ISSUE THREAD

**Issue by MaxDXDX** [flannel-io/flannel#1785]
I'm trying to start my first K8s cluster (v1.27). But it seems that something goes wrong with flannel.

## Expected Behavior
I want to see that all my flannel Pods are running normally without errors.

## Current Behavior
Flannel Pod on Central Plane Node is running well, but flannel pod on remote (working) node is not. It is always restarting:
![image](https://github.com/flannel-io/flannel/assets/85105113/9602d7ce-9519-440e-ad30-d2902e8506e2)
And here are the log data from remote flannel pod:
`E0716 13:09:49.360285       1 main.go:229] Failed to create SubnetManager: error retrieving pod spec for 'kube-flannel/kube-flannel-ds-z8lxw': Get "https://10.96.0.1:443/api/v1/namespaces/kube-flannel/pods/kube-flannel-ds-z8lxw": dial tcp 10.96.0.1:443: i/o timeout
`
I suppose that process in container can not connect to <10.96.0.1> host, which is the K8s API server:
![image](https://github.com/flannel-io/flannel/assets/85105113/e7d3e199-1676-4693-9a40-9a3c59fed4c8)

My set flannel network - 10.244.0.0/16 (default)
My pods subnet (pods-cidr) in cluster config is the same - 10.244.0.0/16

I tried to play around with services subnet `serviceSubnet` in cluster config. By default cluster services use IPs from 10.96.0.0/16 network and I thought I had to change this setting to match flutter network: I tried different variants for `podSubnet` and `serviceSubnet` settings. For example: 10.244.1.0/24 for pods and 10.244.2.0/24 for services. But this one and any others did not help or led to other problems.

I can't figure out:
It is normal that cluster services use **different network** (10.96.0.0/16) **from flannel network** (10.244.0.0/16).
How can I **debug the** connection unavailable **problem** (`dial tcp 10.96.0.1:443: i/o timeout`) in flannel pod on remote node.

Maybe it is worth to notice that my app deployments (I tested **nginx**) work - the nginx pods are deploying on remote node:
![image](https://github.com/flannel-io/flannel/assets/85105113/e4ed3b0d-1159-4986-96db-3ac422bbc6cc)
_There are some problems with DNS in that pods, but I think this is a consequence of the main problem with flannel pod._

## Steps to Reproduce (for bugs)

1. Start K8s cluster with kubeadm (1.27) with podSubnet 10.244.0.0/16
2. Connect one remote node to cluster
3. Start flannel add-on with default config file
4. Inspect flannel pod on remote node

## Your Environment

* Flannel version: 0.22.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version:
* Kubernetes version (if used): 1.27
* Operating System and version: Ubuntu 22.04
* Link to your project (optional):

**Comment by mayeul200212** [comment]
Hello, I have exactly the same problem.

With this error when I try to describe the pod:

```
kubectl describe pod kube-flannel-ds-pdr5l -n kube-flannel:

~
~
~
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  10m                  default-scheduler  Successfully assigned kube-flannel/kube-flannel-ds-pdr5l to isaure-z690-ud-ddr4
  Normal   Pulled     10m                  kubelet            Container image "docker.io/flannel/flannel-cni-plugin:v1.1.2" already present on machine
  Normal   Created    10m                  kubelet            Created container install-cni-plugin
  Normal   Started    10m                  kubelet            Started container install-cni-plugin
  Normal   Pulled     10m                  kubelet            Container image "docker.io/flannel/flannel:v0.22.0" already present on machine
  Normal   Created    10m                  kubelet            Created container install-cni
  Normal   Started    10m                  kubelet            Started container install-cni
  Normal   Pulled     7m52s (x4 over 10m)  kubelet            Container image "docker.io/flannel/flannel:v0.22.0" already present on machine
  Normal   Created    7m52s (x4 over 10m)  kubelet            Created container kube-flannel
  Normal   Started    7m52s (x4 over 10m)  kubelet            Started container kube-flannel
  Warning  BackOff    2s (x30 over 9m4s)   kubelet            Back-off restarting failed container kube-flannel in pod kube-flannel-ds-pdr5l_kube-flannel(a72bfad6-f155-498e-ab6b-3f04bd37a58b)
```

and when I try to see the log with this command:
```
kubectl logs kube-flannel-ds-pdr5l  -n kube-flannel -c kube-flannel
```

nothing is displayed

**Comment by rbrtbnfgl** [comment]
@mayeul200212 Could you check Kubelet logs?
@MaxDXDX it's right that the endpoint IPs differ from the ones in Flannel and they shouldn't be overlapped. Could you check if there are any firewall rules that blocks Flannel to reach the api-server on the other node?

**Comment by mayeul200212** [comment]
after rebooting my machine, the kubelet service exits with an error. I preferred to reset my vm azure. I will keep you informed. Thank you so much

**Comment by mayeul200212** [comment]
I recently performed a reset on both my worker and master nodes. Following this operation, running a specific command on the worker node resulted in the output shown below:

```
juil. 20 21:28:40 X kubelet[X]: E0720 21:28:40.029179  X kubelet.go:2760] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
juil. 20 21:28:41 X kubelet[X]: I0720 21:28:41.335013  X scope.go:115] "RemoveContainer" containerID="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
...
<rest of the output>
...
juil. 20 21:29:00 X kubelet[X]: E0720 21:29:00.035190  X kubelet.go:2760] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: cni plugin not initialized"
```

This output was generated by the following command:
```
journalctl -u kubelet -f
```

I tried to find solutions to solve **"cni plugin not initialized"** but I couldn't solve my problem. Should I redup my worker node or reinstall docker and containerd?

Thank you in advance for your assistance!

**Comment by MaxDXDX** [comment]
**solved**

I've spent several days trying to solve this problem, and I'm going to share my solution with anybody who has the same problem.


The core of the problem lies in the multi-networking nature of my hosts.


The physical structure of my cluster is next.
1. The Master Node (control plane) is located on my own local host, which lies beyond the ISP router in my local network.
2. The Working Node is located on the rented VPS.


The important thing is that I don't use default public interfaces to connect my servers to each other. My hosts are communicating over the OpenVPN network through **tun0** interface. And much more: communication between servers by default network interfaces is restricted due to some specific security reasons.


That use case needs some additional tuning for the K8s configuration.


The main (and mostly hard to find for me) option was the ability to set the correct interface for the Flannel daemon. In my case: **tun0** (openVPN interface) instead of **eth0** (system default).
This setting might be done by customizing **kube-flannel.yml** file (DaemonSet spec.template.spec.containers.args -> --iface):
```
containers:
- args:
- --ip-masq
- --kube-subnet-mgr
- --iface=tun0 # <-- this is the place for setting the used interface
command:
- /opt/bin/flanneld
env:


```
After doing that, all Flannel Daemons will use the specified interface on all hosts. I think if you need to use different interfaces on some hosts, you should customize the Flannel configuration on these hosts. But I use the same interface name (tun0) on all nodes.

You can see the used interface in flannel container (pod) logs, in my case (**tun0**):
```
I0720 20:24:54.257051       1 match.go:259] Using interface with name tun0 and address ...
I0720 20:24:54.257095       1 match.go:281] Defaulting external address to interface address (...)

```


Again, this is the most important setting to start working on my tricky cluster.


Below, I placed some additional settings in the cluster configuration for starting the K8s cluster with non-default network interfaces.


1. In the **InitConfiguration** (on the Master Node):
```
kind: InitConfiguration
nodeRegistration:
kubeletExtraArgs:
node-ip: "AAA.BBB.CCC.DDD"
localAPIEndpoint:
advertiseAddress: "AAA.BBB.CCC.DDD"
bindPort: 6443
```
2. In the **JoinConfiguration** (on each Working Node):
```
kind: JoinConfiguration
nodeRegistration:
kubeletExtraArgs:
node-ip: "EEE.FFF.GGG.HHH"
discovery:
bootstrapToken:
apiServerEndpoint: AAA.BBB.CCC.DDD:6443
```
3. In the **ClusterConfiguration**:
```
kind: ClusterConfiguration
controlPlaneEndpoint: "AAA.BBB.CCC.DDD:6443"
```
`AAA.BBB.CCC.DDD` - correct IP address of the K8s master host.


`EEE.FFF.GGG.HHH` - correct IP address(es) of each K8s working host(s)


The option **node-ip** in **kubeletExtraArgs** lets you set the IP address that will be assigned to default static pods (you are seeing those IPs in the output table of the `kubelet get pods -A -o wide` command).


If your cluster is configured properly, you would be able to connect to any Pod(10.244.XXX.YYY) / Service(10.96.0.XXX) from any host (either outside the pod container or inside the pod container).


```
user@working-node:~$ ping 10.244.0.57 -c 1
PING 10.244.0.57 (10.244.0.57) 56(84) bytes of data.
64 bytes from 10.244.0.57: icmp_seq=1 ttl=63 time=31.1 ms
...
user@working-node:~$ nc -zv 10.96.0.10 53
Connection to 10.96.0.10 53 port [tcp/domain] succeeded!
```


Also, I figured out that connections to the services network **10.96.0.0/16** are processed by the NAT tables of **iptables**. After NAT processing, all requests to 10.96.0.0/16 addresses go to the Flannel interface (flannel.1) with the 10.244.0.0/16 subnet. And it is normal that there is a 10.96.0.0/16 subnet next to the configured 10.244.0.0/16 flannel network. There are no conflicts due to NAT algorithms. You don't have to set the 10.96.0.0/16 subnetwork in any configuration files. Flannel and K8s will do it for you in iptables.


I hope that information will be useful for somebody :-)
