### ISSUE TITLE
multicast support

### ISSUE THREAD

**Issue by kalganesan** [flannel-io/flannel#179]
some of the cache servers are using mutlicast for syncing the cache the data by default.
Do we have plan to support multicast for containers.

Regards,
Kalidas.G

**Comment by eyakubovich** [comment]
We don't have plans at the moment. It's unclear to me how to best support it. For one thing, most cloud environments don't support multicast so it would require emulation by replicating the packet at the source, which is very inefficient. We could try to do a distribution tree but without knowing the underlying topology, it would still be inefficient.

If the environment does support it (e.g. bare metal), do we virutalize multicast address space? For example, a container wants to join 239.1.2.3. Can flannel just use that group "on the wire" or do we assume that there might be other users that utilize this group and we need to make sure we don't collide.

**Comment by greenpau** [comment]
@eyakubovich, for some reason PIMv2 hello do not show up on the other end of `flannel0`:

```
03:33:21.654439 IP 10.252.46.0 > 224.0.0.13: PIMv2, Hello, length 10
03:33:21.654477 IP 10.252.46.0 > 10.252.46.0: ICMP net 224.0.0.13 unreachable, length 36
```

Is there something in `flanneld` that filters multicast?

**Comment by greenpau** [comment]
```
# ip addr show dev flannel0
265: flannel0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 8973 qdisc pfifo_fast state UNKNOWN qlen 500
    link/none
    inet 10.252.63.0/16 scope global flannel0
       valid_lft forever preferred_lft forever

# ip addr show dev docker0
8: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 8973 qdisc noqueue state DOWN
    link/ether 56:84:7a:fe:97:99 brd ff:ff:ff:ff:ff:ff
    inet 10.252.63.1/24 scope global docker0
       valid_lft forever preferred_lft forever

# etcdctl ls /coreos.com/network/subnets
/coreos.com/network/subnets/10.252.63.0-24
/coreos.com/network/subnets/10.252.93.0-24

# tshark -i flannel0
  1   0.000000  10.252.93.0 -> 224.0.0.13   PIMv2 30 Hello
1   2   6.071538  10.252.63.0 -> 224.0.0.13   PIMv2 30 Hello
```

**Comment by vascofg** [comment]
Any updates on this?

**Comment by tomdee** [comment]
@vascofg Sorry, not at the moment. I would be happy to discuss designs if anyone wants to submit a PR.

**Comment by tomdee** [comment]
See #200 for some more detailed discussion/investigation.

**Comment by qrpike** [comment]
Are there any updates on this? I would like to have multicast working if possible. I'm using `host-gw` currently, but have to run the containers with host network to be able to receive the multicast packets. Is there a simple IP tables rule or something to forward the packets to the container/flannel?

**Comment by greenpau** [comment]
>  I would like to have multicast working if possible.

@qrpike , my suggesting is moving to OVN/OVS for multicast.

**Comment by psaini79** [comment]
Hi, do we support multicast on flannel? if not, is there any plan in the future to support multicast on flannel?
