### ISSUE TITLE
Helm Chart: make command and args more configurable

### ISSUE THREAD

**Issue by siredmar** [flannel-io/flannel#1790]
When installing flannel via the helm chart i need to do some special actions before flanneld can run. Currently the command isn't configurable via `values.yaml`. 

## Expected Behavior

I'd expect that i'd be able to use a custom command and args.

## Current Behavior

Only the command args can be modified via `values.yaml`.

## Possible Solution

Modify the template slightly to support command and args support

**Comment by rbrtbnfgl** [comment]
What do you mean for special action? Do you want to execute additional commands on the flannel container before flanneld?

**Comment by siredmar** [comment]
@rbrtbnfgl exactly

**Comment by siredmar** [comment]
@rbrtbnfgl can this get merged or rather not? If not, then let us close the issue and PR.

**Comment by rbrtbnfgl** [comment]
sorry for the late response. We are still discussing about this. We have no plan to add it for now.

**Comment by siredmar** [comment]
never mind. this can be closed.
