### ISSUE TITLE
Can not load local docker image when Flannel init

### ISSUE THREAD

**Issue by xzang18** [flannel-io/flannel#1792]
## Expected Behavior
Flannel pods status should be comes to **Running** after run following command:
```bash
kubectl apply -f kube-flannel.yaml
```

## Current Behavior
When I apply the kube-flannel.yaml as normal, it unable to pull docker image (Init:ImagePullBackOff), not sure what is the root cause;
Then I change to another method to init Flannel by pull the image locally with docker pull,
I success pulled the image flannel/flannel-cni-plugin:v1.2.0, and it shows when i run docker image,
But what puzzle me is that when I set **imagePullPolicy: Never** in kube-flannel.yaml and run `kubectl apply -f kube-flannel.yaml`,
the status of flannel pod comes to **Init:ErrImageNeverPull**, and the event details tell the same message I attach below:

image which I pulled manulally:
![image](https://github.com/flannel-io/flannel/assets/89250267/7ae9f7e4-af5d-412e-a308-e57bf87beda7)

setting in kube-flannel.yaml
![image](https://github.com/flannel-io/flannel/assets/89250267/e6928faa-fa71-4832-8d0b-9578718b27a7)

Status of Flannel pod:
![image](https://github.com/flannel-io/flannel/assets/89250267/45d4f04a-c572-4f99-b2b5-52325b709e82)

## Steps to Reproduce (for bugs)

1. pull Flannel image locally;
2. add imagePullPolicy: Never or IfNotPresent to kube-flannel.yml
3. run kubectl apply -f kube-flannel.yml
4. the error status show

## Your Environment

* Flannel version: 0.22.1
* Backend used (e.g. vxlan or udp):
* Etcd version: 3.5.7
* Kubernetes version (if used): 1.27.4
* Operating System and version: Ubuntu22.04

**Comment by rbrtbnfgl** [comment]
Did you get the error when imagePullPolicy: Never is configured or when it's not?
Because if you configure Never it's right to give an error if the image is not available locally.

**Comment by xzang18** [comment]
> Did you get the error when imagePullPolicy: Never is configured or when it's not? Because if you configure Never it's right to have an error if the image is not available locally.

I got the error when **imagePullPolicy: Never** is configured. Thanks for your reply and I think I get the root cause and can fix it now:

The images show by `docker images` is not belong to K8S, k8s use cri to manage the images, the right command to check if images exist is:
```bash
crictl --runtime-endpoint=unix:///run/containerd/containerd.sock images
```
