### ISSUE TITLE
how to change flannel interface via json configs ?

### ISSUE THREAD

**Issue by dberardo-com** [flannel-io/flannel#1803]
k3s does not allow to pass cli arguments to flannel anymore ... so how to adapt the flannel-iface via json ?

**Comment by rbrtbnfgl** [comment]
the flannel-iface flag should be supported on K3s. Which configuration do you want to add on flannel on K3s?

**Comment by dberardo-com** [comment]
you are totally right ... i had an error somewhere else ... sorry
