### ISSUE TITLE
x86_64 and aarch64 verison of flanneld results in different routes?

### ISSUE THREAD

**Issue by shining-snail** [flannel-io/flannel#1809]
I've built a kubernetes with mulit-architecture node including  x86_64 and aarch64. I deployed these two types of node with the same configuration and version of flanneld (v0.20.2), but the route of x86_64 node works well, the one of aarch64 is using the wrong route table and can't access the other node in cluster via flannel network.

I hope those who understand this principle can help analyze how to solve this problem. Thank you！

## Expected Behavior

The node in clusters should access the pod of each other via flannel network.
## Current Behavior

The x86_64 node can access the pod of both x86_64 and aarch64 nodes, but the aarch64 node can not access the pod of any x86_64 or aarch64 node expcept itself.

## Possible Solution

The route table of each type differs in Iface, if we can change the Iface into correct way, the problem will be solved. 

route table of  aarch64 node:
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         73.134.127.62   0.0.0.0         UG        0 0          0 enp3s0
10.1.0.0        0.0.0.0         255.255.255.0   U         0 0          0 docker0
10.1.1.0        73.134.127.42   255.255.255.0   UG        0 0          0 enp3s0
10.1.2.0        73.134.127.43   255.255.255.0   UG        0 0          0 enp3s0
10.1.5.0        10.1.5.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.8.0        73.134.127.44   255.255.255.0   UG        0 0          0 enp3s0
10.1.9.0        10.1.9.0        255.255.255.0   UG        0 0          0 flannel.1
73.134.127.0    0.0.0.0         255.255.255.192 U         0 0          0 enp3s0
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 enp3s0
169.254.169.254 73.134.127.17   255.255.255.255 UGH       0 0          0 enp3s0

route table of x86_64 node:
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         73.134.127.126  0.0.0.0         UG        0 0          0 enp4s3
10.1.0.0        10.1.0.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.1.0        10.1.1.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.2.0        10.1.2.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.5.0        10.1.5.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.8.0        10.1.8.0        255.255.255.0   UG        0 0          0 flannel.1
10.1.9.0        0.0.0.0         255.255.255.0   U         0 0          0 docker0
73.134.127.64   0.0.0.0         255.255.255.192 U         0 0          0 enp4s3
169.254.0.0     0.0.0.0         255.255.0.0     U         0 0          0 enp4s3
169.254.169.254 73.134.127.93   255.255.255.255 UGH       0 0          0 enp4s3

The ip addresss start with 10* is the node address in flannel network. The Iface flannel.1 is the flanneld virtual eth-device and the Iface enp* is the physical eth-device of the node. 
The aarch64 send request to other node in cluster via enp3s0 so that it can not access the pods on those nodes.
The correct way is using flannel.1 to send the request to other node in cluster.

## Steps to Reproduce (for bugs)

1.Start a pod both in x86_64 node and aarch64 node. I choose nginx to test.
2.Get all in-cluster ip address of nginx pods( start with 10*)
3.Exec into a pod and curl the flanneld ip address(start with 10*) of othe pod
4.The x86_64 node work well and all aarch64 failed.

## Context

Because of the wrong route made by flanneld , all apps run on aarch64 node can't access each other in cluster, this may lead to application error.

## Your Environment

* Flannel version:0.20.2
* Backend used (e.g. vxlan or udp):vxlan
* Etcd version:3.5.7
* Kubernetes version (if used):1.23.16
* Operating System and version:linux
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Are there two different clusters or they are on different the same cluster?
I saw that on the aarch64 there are multiple route in docker0 and the network interface.
Are there any other services running on the aarch64 that wrote the routes to the GW?

**Comment by shining-snail** [comment]
> Are there two different clusters or they are on different the same cluster? I saw that on the aarch64 there are multiple route in docker0 and the network interface. Are there any other services running on the aarch64 that wrote the routes to the GW?

All node are in the same cluster. Here is the node list:
node      		 podcidr			arch
73.134.127.41	 10.1.0.0/24		arch64
73.134.127.42	 10.1.1.0/24		arch64
73.134.127.43	 10.1.2.0/24		arch64
73.134.127.44	 10.1.8.0/24		x86_64
73.134.127.121 10.1.9.0/24		x86_64
107.6.141.3	 10.1.5.0/24		x86_64

route table of aarch64 node 73.134.127.41:
Kernel IP routing table
Destination Gateway Genmask Flags MSS Window irtt Iface
0.0.0.0 73.134.127.62 0.0.0.0 UG 0 0 0 enp3s0
10.1.0.0 0.0.0.0 255.255.255.0 U 0 0 0 docker0
10.1.1.0 73.134.127.42 255.255.255.0 UG 0 0 0 enp3s0
10.1.2.0 73.134.127.43 255.255.255.0 UG 0 0 0 enp3s0
10.1.5.0 10.1.5.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.8.0 73.134.127.44 255.255.255.0 UG 0 0 0 enp3s0
10.1.9.0 10.1.9.0 255.255.255.0 UG 0 0 0 flannel.1
73.134.127.0 0.0.0.0 255.255.255.192 U 0 0 0 enp3s0
169.254.0.0 0.0.0.0 255.255.0.0 U 0 0 0 enp3s0
169.254.169.254 73.134.127.17 255.255.255.255 UGH 0 0 0 enp3s0


route table of x86_64 node 73.134.127.121:
Kernel IP routing table
Destination Gateway Genmask Flags MSS Window irtt Iface
0.0.0.0 73.134.127.126 0.0.0.0 UG 0 0 0 enp4s3
10.1.0.0 10.1.0.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.1.0 10.1.1.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.2.0 10.1.2.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.5.0 10.1.5.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.8.0 10.1.8.0 255.255.255.0 UG 0 0 0 flannel.1
10.1.9.0 0.0.0.0 255.255.255.0 U 0 0 0 docker0
73.134.127.64 0.0.0.0 255.255.255.192 U 0 0 0 enp4s3
169.254.0.0 0.0.0.0 255.255.0.0 U 0 0 0 enp4s3
169.254.169.254 73.134.127.93 255.255.255.255 UGH 0 0 0 enp4s3

There is no any other services running on the aarch64 that wrote the routes to the GW. The configuration of aarch64 and x86_64 are the same.
