### ISSUE TITLE
feat-req: Pivot UDP-based tunnel (raw UDP, VXLAN, WireGuard) port info to subnet lease detail and optionally add persistent flanneld identity

### ISSUE THREAD

**Issue by zer0def** [flannel-io/flannel#1810]
### Issue statement

As of the time of this writing (~v0.22.3), when two different Flannel nodes want to join the same overlaynet from behind the same NAT, they end up UDP hole punching through the same port, defined in their backend configuration. This results in all of them adopting the same subnet lease from the datastore with workloads potentially overshadowing each other's in-overlaynet addresses, as each node manages their (now overlapping) subnet independently of others.

### Proposed idea

To my understanding, Flannel's functionality is effectively tightly-coupled with `host-local`, so using a different IPAM could result in unroutable addresses behind handed out (like in case of usage with `whereabouts`). Therefore, in order to distinguish between nodes in NATted situations, each would have to punch a separate hole using a different UDP port. With that said, Flannel nodes wouldn't necessarily have to perform STUN for their host:ip disocvery, instead delegating it externally to `--public-ip=$(shell command)` and a potentially additional argument. Inside the OCI/Docker image, it'd likely be as simple as adding a STUN client (coturn?) for users to take advantage of and calling it a day.

### Additional notes

Optionally, and I haven't tested this scenario yet, so this assumption may prove incorrect, to make matters worse, when a node migrates behind a different pubnet host:ip, it would be handed a new subnet lease, while their old one would decay in 24 hours (going by etcd TTL hardcode, which may require parameterizing out) with old subnet's individual address leases lingering in their overlaynet IPAM's `dataDir` (using `host-local` config keys).

To that end, it may be worthwhile to attach a (potentially configurable?) persistent identity key, likely stashed in `subnetFile`, independent of `PublicIP` and would-be `PublicPort`, in order to preserve in-overlaynet subnets across such migrations. However, this is likely of little concern in scenarios where overlaynet IPs are treated ephemerally, like Kubernetes.

**Comment by rbrtbnfgl** [comment]
I am not following what you are saying.
You have two nodes on the same private network that want to connect to a node with a public IP. It's not suggested to use this setup with Flannel you should probably create a VPN between the nodes to have the same subnet.
I don't understand why they are using the same subnet are you referring to the pods network?

**Comment by zer0def** [comment]
Slight correction: in a Kubernetes scenario two workers from different private subnets behind the same NAT (having the same pubnet IP and, due to static port definition, port, during UDP hole punching) adopt the same in-overlay subnet to hand out host-local pod IPs, which results in collisions and wonky routing, regardless of whether other pods refer to them directly or through a service of any type.

Obviously this scenario is solved by flattening the L3 network using a VPN without that Kubernetes' knowledge, though in that case it'd effectively be overlaying networks twice, where a single overlay over WireGuard with distinct ports, would do the same job just fine, since the datastore out on the pubnet can effectively be used as a STUN replacement.
