### ISSUE TITLE
Version not updated in the latest helm charts for 0.23.0

### ISSUE THREAD

**Issue by roshanirathi** [flannel-io/flannel#1821]
The version in `Chart.yaml` in the 0.23.0 charts still shows 0.22.3. The image version is also not updated

## Expected Behavior
The helm charts and images should be updated for every version.

**Comment by rbrtbnfgl** [comment]
The files on the source aren't automatically updated during the release and they have to be manually updated and it could happen that that it's missed I'll update them. I suggest you to always use the files published during the release that have always the right version value. In case of the chart you can use https://github.com/flannel-io/flannel/releases/download/v0.23.0/flannel.tgz

**Comment by roshanirathi** [comment]
Thanks a lot, I will use this
