### ISSUE TITLE
In a Kubernetes cluster based on a public network, machine A is unable to ping the pods running on machine B.

### ISSUE THREAD

**Issue by WhiteWaterrrr** [flannel-io/flannel#1822]
I have set up a k8s cluster based on the public network, using the Flannel plugin with VXLAN. Machine A and machine B have different private networks, and A and B can ping each other. However, machine A cannot ping the pod running on machine B. After packet capture analysis, it was found that the pod on machine B received the ping packet and returned the ping packet, but the eth0 network card on machine A did not receive it.

**Comment by foursunZero** [comment]
hey, guys.Is it convenient for you to display your routing or iptables information? I think there may be no corresponding route.

**Comment by Sacerdoss** [comment]
It seems like we're running into the same issue after upgrading to debian 12.5. 

`kubeadm version: v1.28.7`
`flannel version:  v0.24.4`
`cni version: v1.2.0`

We have flannel setup in Dualstack mode on a kubeadm cluster using the following net-conf.json:
```json
{
  "Network": "10.244.0.0/16",
  "Backend": {
    "Type": "vxlan"
  },
  "EnableIPv6": true,
  "IPv6Network": "2001:db8:42:0::/56"
}
```
Interestingly enough the routes were all working directly after the upgrade but after restarting a node the IPv6 routes between pods on different from that restarted node were down. The IPv4 routes however kept working. After restarting the rollout for the kube-flannel daemonset the routes started working again but any node restart will kill them again.

`ip -6 route` shows the following before and after restart of the node:
```bash
2001:db8:42::/64 via 2001:db8:42:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:2::/64 via 2001:db8:42:2:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:4::/64 via 2001:db8:42:4:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:5::/64 via 2001:db8:42:5:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:6::/64 via 2001:db8:42:6:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:7::/64 via 2001:db8:42:7:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:8::/64 via 2001:db8:42:8:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:9:: dev flannel-v6.1 proto kernel metric 256 pref medium
2001:db8:42:9::/64 dev cni0 proto kernel metric 256 pref medium
2001:db8:42:a::/64 via 2001:db8:42:a:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:b::/64 via 2001:db8:42:b:: dev flannel-v6.1 metric 1024 onlink pref medium
2001:db8:42:e::/64 via 2001:db8:42:e:: dev flannel-v6.1 metric 1024 onlink pref medium
<SERVER_IPv6>::/64 dev enp0s31f6 proto kernel metric 256 pref medium
fe80::/64 dev enp0s31f6 proto kernel metric 256 pref medium
fe80::/64 dev flannel.1 proto kernel metric 256 pref medium
fe80::/64 dev flannel-v6.1 proto kernel metric 256 pref medium
fe80::/64 dev cni0 proto kernel metric 256 pref medium
fe80::/64 dev vethb74a35fd proto kernel metric 256 pref medium
fe80::/64 dev veth653394f6 proto kernel metric 256 pref medium
default via fe80::1 dev enp0s31f6 metric 1024 onlink pref medium
```

**Comment by DerRockWolf** [comment]
I'm having the exact same issue as you @Sacerdoss. Were you able to figure something out?

I have an dual stack k3s cluster, which is using pod CIDR `fd42::/56`. So it isn't related to public IPv6 networks.
It's also not related to ICMP, other traffic is also affected.

My nodes are running NixOS.

For me the issue occurs bidirectionally, e.g.,: Node A is restarted:
- A is unable to access any pods running on other nodes
- Other nodes are unable to access any pods on A

To temporarily fix this I need to restart k3s on **all** nodes (not just on the restarted node):
`sudo systemctl restart k3s` (which I guess, also restarts flannel).

So the broken routing is polluted across the cluster.

**Comment by Sacerdoss** [comment]
@DerRockWolf The issue somehow went away and did not come back. I suspect it was either a Kubernetes Upgrade or a flannel upgrade. We did not change the config.
