### ISSUE TITLE
Can Flannel enable multiple network queues for the cni0 interface?

### ISSUE THREAD

**Issue by garfcat** [flannel-io/flannel#1841]
The cni0 interface currently has only one receive queue, which may lead to performance bottlenecks. Is it possible to enable multiple queues?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Flannel version:
* Backend used (e.g. vxlan or udp):
* Etcd version:
* Kubernetes version (if used):
* Operating System and version:
* Link to your project (optional):

**Comment by manuelbuil** [comment]
cni0 interface is the bridge interface. Could you elaborate a case where you see a bottleneck there?
