### ISSUE TITLE
The flannel-cni-plugin container seems to be missing the bridge binary file.

### ISSUE THREAD

**Issue by gitlayzer** [flannel-io/flannel#1847]
I am using Kind to deploy the cluster, and when using flannel, it seems that the bridge binary file is missing in the flannel-cni-plugin container，So, I manually downloaded a cni-plugins and took out the bridge from it and put it under /opt/cni/bin/ to solve the problem，Would like to check out the following flannel-cni-plugin mirror
![image](https://github.com/flannel-io/flannel/assets/77761224/a9bbda0d-2977-485e-aa40-ee918e7cfb83)

**Comment by manuelbuil** [comment]
yeah, you are supposed to install the all the cni plugin binaries of the upstream project https://github.com/containernetworking/plugins/releases/tag/v1.4.0

**Comment by gitlayzer** [comment]
> yeah, you are supposed to install the all the cni plugin binaries of the upstream project https://github.com/containernetworking/plugins/releases/tag/v1.4.0
> 
> and place them in /opt/cni/bin/ 

Why not directly package it in flannel cni plugin

**Comment by manuelbuil** [comment]
> > yeah, you are supposed to install the all the cni plugin binaries of the upstream project https://github.com/containernetworking/plugins/releases/tag/v1.4.0
> > and place them in /opt/cni/bin/
> 
> Why not directly package it in flannel cni plugin

What do you mean by package?

**Comment by gitlayzer** [comment]
> > > yeah, you are supposed to install the all the cni plugin binaries of the upstream project https://github.com/containernetworking/plugins/releases/tag/v1.4.0
> > > and place them in /opt/cni/bin/
> > 
> > 
> > Why not directly package it in flannel cni plugin
> 
> What do you mean by package?

What I mean is, why not package the bridge file directly in the flannel-cni-plugin image?

**Comment by gitlayzer** [comment]
> I don't know exactly but probably it is to avoid overriding the cni binaries and also one less thing to maintain :P

I think you can think about this problem. I think this is an area where flannel-cni-plugin needs to be optimized.
