### ISSUE TITLE
Hello, does Flannel (--iface) have a way to configure the network interface through NodeInternalIP like Calico, without specifying the --iface parameter in a multi-network interface environment?

### ISSUE THREAD

**Issue by oomgomgxx** [flannel-io/flannel#1849]
Similar to this: https://projectcalico.docs.tigera.io/networking/ip-autodetection#change-the-autodetection-method

**Comment by rbrtbnfgl** [comment]
No flannel doesn't have an IP autodetecting logic like Calico. K3s has some additional code to configure the right parameters on Flannel to choose the right interface. There should be a `public-ipv-overwrite` configuration but it's not working as expected #1813 I'm still checking the logic.
