### ISSUE TITLE
Can flannel set forceAddress parameters?

### ISSUE THREAD

**Issue by tanberBro** [flannel-io/flannel#1850]
## Expected Behavior
I want to add a forceAddress parameter to the parameter passed to bridge cni so that he can perform the following logic:
<img width="1426" alt="image" src="https://github.com/flannel-io/flannel/assets/53817917/620d4733-c80d-4b8a-b144-ea56c2e16f6b">

## Current Behavior
My current configuration does not have forceAddress parameters. In some cases, the pod reported an error:
![企业微信截图_06982571-b90e-4e0d-bbbc-e755fe21c8a8](https://github.com/flannel-io/flannel/assets/53817917/6ad34239-9bfb-427a-af61-39fa55fb21c2)

## Possible Solution
Set forceAddress  parameters in flannel config.

## Context
The reason why the pod reports an error is: 
This node was originally a node in cluster 1, but now it has become a node in cluster 2, causing the subnet to change.

## Your Environment

* Flannel version: v0.20.2
* Backend used (e.g. vxlan or udp): vxlan
* Kubernetes version (if used): v1.24.10
* Operating System and version: centos7

**Comment by tanberBro** [comment]
@rbrtbnfgl

**Comment by rbrtbnfgl** [comment]
do you cleaned the node when it joined the second cluster?

**Comment by tanberBro** [comment]
yes @rbrtbnfgl

**Comment by rbrtbnfgl** [comment]
yes Flannel is not cleaning older configuration like routes and bridge interface.
