### ISSUE TITLE
Accessing NodePort on K8S host has latency when reaching Pods across different hosts

### ISSUE THREAD

**Issue by wuyanfeiwork** [flannel-io/flannel#1859]
See：https://github.com/kubernetes/kubernetes/issues/122835

I don't quite understand the reason for the issue. Is it a bug in the operating system kernel or in Flannel? How can it be fixed?

**Comment by wuyanfeiwork** [comment]
The issue manifests as follows:

When curling the cluster IP, if the request is directed to a pod across different hosts, it takes 1 second to receive a response. However, if the request is directed to a pod on the same host, the response speed is normal.

Upon packet analysis, it is observed that the initial connection to flannel.1 is reset, causing a 1-second delay.

![image](https://github.com/flannel-io/flannel/assets/104751498/e1d63b8c-6087-44b5-b760-7f9426cf76d0)

![image](https://github.com/flannel-io/flannel/assets/104751498/48ff8515-c16b-476d-8bcd-94ae6809b68e)


flannel:v0.20.1

**Comment by thomasferrandiz** [comment]
There are known issues with hardware offload on some platforms as explained in the issue you linked above.

This isn't an issue that we can solve from flannel as it is more likely tied to the specific kernel/harware combination that is used.

**Comment by wuyanfeiwork** [comment]
> There are known issues with hardware offload on some platforms as explained in the issue you linked above.
> 
> This isn't an issue that we can solve from flannel as it is more likely tied to the specific kernel/harware combination that is used.

@thomasferrandiz What are some graceful ways to solve/avoid this issue?
