### ISSUE TITLE
crictl is not able to pull flannel images

### ISSUE THREAD

**Issue by rishabhatdell** [flannel-io/flannel#1861]
`crictl` is not able to pull flannel-cni-plugin image `sudo crictl pull docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1`

## Current Behavior
```
sudo crictl pull docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1
DEBU[0000] get image connection                         
DEBU[0000] PullImageRequest: &PullImageRequest{Image:&ImageSpec{Image:docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1,Annotations:map[string]string{},},Auth:nil,SandboxConfig:nil,} 
E0122 08:12:27.324173   13369 remote_image.go:171] "PullImage from image service failed" err="rpc error: code = InvalidArgument desc = failed to pull and unpack image \"docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1\": unable to fetch descriptor (sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855) which reports content size of zero: invalid argument" image="docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1"
FATA[0000] pulling image: rpc error: code = InvalidArgument desc = failed to pull and unpack image "docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1": unable to fetch descriptor (sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855) which reports content size of zero: invalid argument 
```

## Possible Solution
unsure

## Steps to Reproduce (for bugs)

1. Pull flannel-cni-plugin:v1.4.0-flannel1 image using crictl
2. `sudo crictl pull docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1`
3.
4.

## Context

When using `kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml`, the pods enter the `Init:ImagePullBackOff` state. Upon investigation, we discovered that the `flannel-cni-plugin:v1.4.0-flannel1` image is not being pulled. We attempted `crictl pull docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1`, resulting in the same error. Surprisingly, its working with docker `docker pull docker.io/flannel/flannel-cni-plugin:v1.4.0-flannel1`.

## Your Environment

* Flannel version: v0.24.2
* Backend used (e.g. vxlan or udp): 
* Etcd version: 3.5.10
* Kubernetes version (if used): 1.28
* Operating System and version: Red Hat Enterprise Linux release 8.6 (Ootpa)
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Do you have the same issue also fro image with an older version like `v1.2.0-flannel3`?

**Comment by rishabhatdell** [comment]
> Do you have the same issue also fro image with an older version like `v1.2.0-flannel3`?

we are facing this issue after [v0.24.1](https://github.com/flannel-io/flannel/releases/tag/v0.24.1) update

**Comment by rbrtbnfgl** [comment]
Now the image should be available. Are yo still facing the issue?
