### ISSUE TITLE
MACSEC communication between flannel nodes

### ISSUE THREAD

**Issue by takuyaK8s** [flannel-io/flannel#1868]
I want to communicate between flannel nodes using MACSEC communication.
Is it correct to understand that MACSEC communication is a specification that requires communication in the same segment?
Also, if flannel is used with K8s, it will be a different segment, but is it possible to use the same segment?

**Comment by takuyaK8s** [comment]
A virtual MACSEC interface is created in the Pod and MACSEC is installed in the Pod.
Communication between Pods is possible, but in the case of communication between nodes, the segments are different in Flannel 1, so communication is not possible.

**Comment by rbrtbnfgl** [comment]
when you are using the Vxlan tunnel I think you can't forward macsec packets. K8s uses different L3 networks for each node then macsec is limited only on the single node. If you want to enforce security on the communication between the node you should use Wireguard as backend.
