### ISSUE TITLE
Investigate use of multiple route tables on AWS

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#193]
This would help us overcome the 50 entries per route table limitation.

**Comment by eyakubovich** [comment]
This should help with https://github.com/coreos/flannel/issues/164

**Comment by panga** [comment]
+1

**Comment by lokesh-shekar** [comment]
Any updates on this ?. Is someone working on this feature ?

**Comment by tomdee** [comment]
I'm not working on, but @jon-shanks might be

**Comment by tomdee** [comment]
Ooops, I forgot about this PR too - #561

**Comment by lokesh-shekar** [comment]
thanks. This PR merge will help us greatly
