### ISSUE TITLE
Flannel is not working：“Error registering network: operation not supported”

### ISSUE THREAD

**Issue by HuangYuFe** [flannel-io/flannel#1953]
I've tried to join the i.mx8 board as a node to the kubernetes cluster, but Flannel keeps not starting properly.
## Expected Behavior

Under normal circumstances, when you run the command to add Kubernetes to a cluster, Flannel is automatically run on the node
## Current Behavior

Nodes other than the IMX8 development board are working normally. flannel on imx8 is always in CrashLoopBackOff state。
![屏幕截图 2024-04-22 154308](https://github.com/flannel-io/flannel/assets/117882542/2bb5e544-9669-46ac-98e3-c34a01f85175)

I tried to look at the log information and it shows“Error registering network: operation not supported”
![屏幕截图 2024-04-22 114208](https://github.com/flannel-io/flannel/assets/117882542/64f4a6fb-5955-4231-b5f9-682a4d07b1b1)

I searched for past issues and executed the "ip link" command, but no "flannel.1" vxlan appeared：
![屏幕截图 2024-04-22 155017](https://github.com/flannel-io/flannel/assets/117882542/eb201121-889e-46b7-80f9-f29351c16632)

## Steps to Reproduce (for bugs)

1.I tried modifying the Linux kernel config options, but it didn't work
![屏幕截图 2024-04-22 155421](https://github.com/flannel-io/flannel/assets/117882542/78c26110-1ad6-4c3e-88d4-367e5695101b)
![屏幕截图 2024-04-22 155416](https://github.com/flannel-io/flannel/assets/117882542/dc0e6fa2-a110-4ba0-8853-041cec9aa586)

2.
3.
4.

## Your Environment

* Flannel version:v0.24.2
* Backend used (e.g. vxlan or udp):
* Etcd version:3.5.0-0
* Kubernetes version (if used):1.22.4
* Operating System and version:NXP i.MX Release Distro 4.14-sumo
* Hardware：NXP IMX8MM
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Does the kernel support the VXLan interface?

**Comment by HuangYuFe** [comment]
Yes, it is not supported. But after I opened some configurations that support VXLAN according to the tutorial, I still can't start VXLAN. Because my attempt to execute "ip link add vxlan0 type vxlan id xxx dstport xxx remote xxx local xxx dev etho" still fails.
![屏幕截图 2024-04-22 155421](https://github.com/flannel-io/flannel/assets/117882542/9b4eba8a-e294-4f39-a0df-88180e5c7421)
![屏幕截图 2024-04-22 155416](https://github.com/flannel-io/flannel/assets/117882542/ffbd8f71-4684-49c2-91bc-d37ee0ccfad7)

![屏幕截图 2024-04-17 205434](https://github.com/flannel-io/flannel/assets/117882542/b0443b03-8dd3-4001-b00a-13d3623ae667)

**Comment by HuangYuFe** [comment]
Is there something wrong with my workaround？

**Comment by HuangYuFe** [comment]
Is there something wrong with my workaround？ @rbrtbnfgl

**Comment by rbrtbnfgl** [comment]
Are you sure that those flags enable VXLan on the kernel? Are you manually building it? Could you try to build the kernel with menuconfig and search if the VXLan modules are enabled? They should be enabled with `y` if the config is `m` you should activate them on the system with modprobe.

**Comment by rbrtbnfgl** [comment]
Could you check #1747 ?

**Comment by HuangYuFe** [comment]
> Could you check #1747 ?

OK，I will try it.
