### ISSUE TITLE
Crash at startup of flannel when setting IPv6 masq rules

### ISSUE THREAD

**Issue by dvergotes** [flannel-io/flannel#1968]
## Expected Behavior
No crash.

## Current Behavior
Crash at startup.

```
I0510 12:10:22.653390       1 iptables.go:115] Current network or subnet (10.44.0.0/16, 10.44.3.0/24) is not equal to previous one (0.0.0.0/0, 0.0.0.0/0), trying to recycle old iptables rules
I0510 12:10:22.677499       1 iptables.go:125] Setting up masking rules
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5aba7b]

goroutine 1 [running]:
math/big.(*Int).Cmp(0x0?, 0x1b9b2a3?)
	/usr/local/go/src/math/big/int.go:381 +0x1b
github.com/flannel-io/flannel/pkg/ip.IP6Net.Equal(...)
	/build/pkg/ip/ip6net.go:192
github.com/flannel-io/flannel/pkg/trafficmngr/iptables.(*IPTablesManager).SetupAndEnsureMasqRules(0xc0005a65d0, {0x1e31ff8, 0xc000487d60}, {0xa2c0000, 0x10}, {0x0, 0x0}, {0x0, 0x0}, {0xc0002e3500, ...}, ...)
	/build/pkg/trafficmngr/iptables/iptables.go:131 +0x438
main.main()
	/build/main.go:366 +0x13a3
```

The `prevIPv6Network.IP` variable is a null pointer.

Seems to be introduced by https://github.com/flannel-io/flannel/commit/2092b830ce0ef212ca38dc451143f844de9d58f5

## Possible Solution
Revert the commit that introduced the issue.

## Steps to Reproduce (for bugs)
Deploy cluster as described in https://github.com/flannel-io/flannel/issues/1813

## Your Environment
* Flannel version: manual build with checkout  of master branch (commit 6d18ae7f)
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: rancher/hardened-etcd:v3.5.9-k3s1-build20230802
* Kubernetes version (if used): v1.29.3+rke2r1
* Operating System and version: Oracle Linux Server 8.9

**Comment by rbrtbnfgl** [comment]
Thanks for reporting this. We'll add a fix for this before the next release.

**Comment by dvergotes** [comment]
Thanks for the fix!
