### ISSUE TITLE
Flannel Health Check Endpoint Use ListenAndServe Instead of ListenAndServeTLS

### ISSUE THREAD

**Issue by praneethvarmakvs** [flannel-io/flannel#2028]
Flannel health check endpoint uses ListenAndServe instead of ListenAndServeTLS, which could lead to potential security vulnerabilities
https://github.com/flannel-io/flannel/blob/v0.25.5/main.go#L482

## Expected Behavior
The health check endpoint for Flannel should use ListenAndServeTLS to ensure that the communication is encrypted and secure, rather than using ListenAndServe.

## Current Behavior
NA

## Possible Solution
Update the Flannel configuration to use ListenAndServeTLS for the health check endpoint to enable TLS/SSL encryption. This would involve configuring the necessary certificates and keys for secure communication.

## Steps to Reproduce (for bugs)
NA

## Context
Using ListenAndServe causes security vulnerabilities. 

## Your Environment
NA

**Comment by rbrtbnfgl** [comment]
This is how the livenessProbe works when enabled with `httpGet` on kubernetes. This is disabled by default in Flannel. It's up to the user who configures it to set up eventually any security on top of it.
