### ISSUE TITLE
Flannel Chart not working with Flux Deployment

### ISSUE THREAD

**Issue by simon-sebold** [flannel-io/flannel#2096]
## Expected Behavior
Flux will deploy Flannel in the Kubernetes Environment

## Current Behavior
This is not working because the following error occured
![image](https://github.com/user-attachments/assets/1068f664-ab2c-47a1-9fba-b60c3fa99186)

## Possible Solution
Perhaps an index.yaml is needed

## Steps to Reproduce (for bugs)
1.
flux create source helm helm-repo-flannel --url=https://flannel-io.github.io/flannel/charts --namespace=kube-system --export > helm-repo-flannel.yaml
flux create helmrelease helm-release-flannel --chart=flannel --source=HelmRepository/helm-repo-flannel --chart-version=0.26.0 --release-name=flannel --namespace=kube-system --export > helm-release-flannel.yaml
echo "kind: Namespace
apiVersion: v1
metadata:
  name: kube-flannel
  labels:
    name: kube-flannel
    pod-security.kubernetes.io/enforce: privileged
" | tee -a namespaces.yaml
echo "apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - helm-repo-flannel.yaml
  - helm-release-flannel.yaml
  - namespaces.yaml
" | tee -a kustomization.yaml

2. Deploy it in the private repository for Flux
3. Wait for the deployment

## Your Environment

* Flannel version: v0.26.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.5.12-0
* Kubernetes version (if used): v1.29.6
* Operating System and version: Ubuntu 24.04.1 LTS
* Link to your project (optional):

**Comment by rbrtbnfgl** [comment]
Hi the repo for the flannel chart should be https://flannel-io.github.io/flannel/ on that path index.yaml should be available.

**Comment by simon-sebold** [comment]
Hi, thank you for the answer. I already applied the change in my repository and renovatebot is happy. Later I will deploy it to my environment.
