### ISSUE TITLE
Adding Consul support

### ISSUE THREAD

**Issue by quatrix** [flannel-io/flannel#233]
I'd like to implement Consul support for Flannel.

I don't want to maintain a fork, would you accept a pull request? Any implementation remarks I should consider?

**Comment by eyakubovich** [comment]
@quatrix I'm not opposed to multiple k/v backends but every time we make something configurable, we add complexity, especially for the user. Therefore I first would like to understand your motivations for using Consul instead of etcd.

**Comment by omribahumi** [comment]
@eyakubovich we're already using Consul. Maintaining an etcd cluster just for flannel is adding more complexity :)
I think we can do this in a simple way - a parameter for controlling which kv store to use, having the default set to `etcd` for maintaining backwards compatibility

**Comment by eyakubovich** [comment]
@quatrix @omribahumi Sounds reasonable. However, whomever is responsible for this PR, can you also become a flannel maintainer to help maintain the Consul support going forward? We don't have functional tests (only unit) for flannel right now but once that develops, we'd like the maintainer to ensure there're functional tests around Consul as well.

Ideally Consul could just implement `subnet.Registry` interface (https://github.com/coreos/flannel/blob/master/subnet/registry.go#L30). Obviously we'll need to abstract out the return type. However b/c Consul has TTLs on sessions and not keys and b/c I don't think there's a way to "look back" into a watch queue, the interface may need to become more high level. At the same time, `subnet.Manager` (https://github.com/coreos/flannel/blob/master/subnet/subnet.go#L95) is probably too high level and will end up with lots of code duplication.

**Comment by omribahumi** [comment]
@eyakubovich could you elaborate a bit more on the TTL issue? Where are TTLs used? What for?

**Comment by eyakubovich** [comment]
@omribahumi TTLs are used to implement the lease expiration. A lease is acquired by creating a key (e.g. `10.1.33.0-24`) with a TTL set to 24 hours. The flannel daemon will then renew it after 23 hours. This allows the node to die and the lease to expire on its own. The 24 hours is not significant -- it just has to be "long enough" (I think Consul's TTLs are capped at 1 hour).

I think we should iterate together over a common interface that will satisfy both etcd and Consul (I'm not too familiar with Consul so it's hard for to design an interface that'll work for it). Can you start by looking at the registry interface (https://github.com/coreos/flannel/blob/master/subnet/registry.go#L30), figuring out how it needs to be adjusted to work with Consul and submitting a meta-PR (not for merge but to discuss) with your proposal?

**Comment by philk** [comment]
I haven't messed with it yet but this seems highly relevant for implementing Consul support and potentially getting Zookeeper for free https://github.com/docker/libkv

**Comment by eyakubovich** [comment]
The problem with `libkv` is that it is (a) still fairly immature and (b) it suffers from the lowest common denominator problem (by the definition of what it does).

**Comment by omribahumi** [comment]
Adding this as reference for TTL on Consul: https://github.com/hashicorp/consul/issues/172

**Comment by nathanleiby** [comment]
Also interested in adding support for Consul. Similarly, we already use consul and don't wish to also run an etcd cluster

**Comment by inadarei** [comment]
+1 for Consul!

**Comment by Azulinho** [comment]
+1

**Comment by nphase** [comment]
+1

**Comment by mrinalwadhwa** [comment]
+1 would prefer not to have to maintain an etcd cluster just for flannel.

**Comment by hubayirp** [comment]
+1 on Consul

**Comment by fieryvova** [comment]
+1 on Consul

**Comment by crhan** [comment]
+1 on Consul

**Comment by panga** [comment]
+1

**Comment by yellowmegaman** [comment]
+1 Any love for this issue? Etcd is surely great, but indeed, running it only to make flannel work is an overkill.

**Comment by signull** [comment]
👍

**Comment by claytonsilva** [comment]
+1

**Comment by ror6ax** [comment]
+1 on Consul

**Comment by h4m24** [comment]
+1 on consul

**Comment by ppomes** [comment]
+1 on consul

**Comment by anandr781** [comment]
+1 consul

**Comment by ankmidh** [comment]
+1 on consul

**Comment by xarinatan** [comment]
+2 for consul support! I'd even chip in a few dozen bucks on a bountysource to make it happen if needed, consul has much smoother automatic (cluster) discovery and recovery than etcd, and I'd prefer not to have to maintain both..

**Comment by monwolf** [comment]
+ 1 too, we are using consul abroad, setting up another kv just for flannel doesn't sount good enough
