### ISSUE TITLE
*: add IPv6 support

### ISSUE THREAD

**Issue by GabMgt** [flannel-io/flannel#248]
Hello, I am using Flannel in CoreOS 717.1.0 with IPv6 but it failed to launch. When I look at the logs, I see the message:

```
Failed to find IPv4 address for interface eth1.
```

Is Flannel compatible with IPv6 ?

Thank you.

**Comment by eyakubovich** [comment]
@Nurza flannel currently does not support IPv6. However let's leave this issue open as we should add IPv6 support in the future.

**Comment by pierrebeaucamp** [comment]
+1

**Comment by eyakubovich** [comment]
@patrickhoefler Can I ask about your use case for IPv6? Are you running out of RFC1918 IPv4 addresses? Or want to migrate to IPv6 throughout your org? Something else?

I'm not against IPv6 support but it is work and considering that it's usually ran in 1918 address space, I don't see it as a high priority item. But I would like to know more.

**Comment by patrickhoefler** [comment]
@eyakubovich You can definitely ask me, but it would probably make more sense to ask @Nurza instead ;)

**Comment by Nurza** [comment]
Because I own a few servers with free IPv6 blocks (IPv4 is SO expensive) and I would like to use flannel with them.

**Comment by fskale** [comment]
I think there are enough use cases, which require ipv6 addresses. I'm working on such and the lack of ipv6 support in kubernetes, flannel forces me to use a single docker host with pipework. Docker supports ipv6 using the command line option: --ipv6 --fixed-cidr-v6=\"xxxx:xxxx:xxxx:xxxx:/64\"". I'm Working with Unique Local Unicast Addresses. The usecase is clear. Ipv6only with DNATS ans SNATS to the pods. Personally i think, you should give ipv6 more priority. So i'm wirting on something like kiwi to track changes to a pod, and then issue pipework cmd to go back to kubernetes.

**Comment by colinrgodsey** [comment]
:+1:

**Comment by goacid** [comment]
+1

**Comment by hwinkel** [comment]
+1

**Comment by atta** [comment]
+1

**Comment by glennswest** [comment]
Currently if you start doing sizing, you can get 300-400 hosts in a rack. (Supermicro microblades), two racks will go over the flannel/ipv4 limites. If you start looking at maximums, the flannel/ipv4 limit sounds ok, at around 261K containers max, but the reality its only 1-2 racks today. If you actually start applying devops/microservices into realworld apps, the container counts explode. I did a sizing for a day trading app im designing and its about 1.8million containers. 

There only a very small number of container types (20+) yet there reused in alot of ways for the app.
And there 4000 equities, and a average of 450 plus containers per equity.
Hardware Config:
https://www.linkedin.com/pulse/building-data-center-deep-neural-networks-thinking-wall-glenn-west
App Overview  
https://www.linkedin.com/pulse/using-containers-docker-change-world-glenn-west

If you consider real wall street system, or if you look at credit risk or a lot of typical commercial apps,
this is not alot of hardware, or even really big apps. The trading app would be alot bigger if you do equities on a global scale with multiple exchanges. 

When looking at hardware preference, you would actually want to do this across multiple data centers, multiple floors in data centers, and multiple racks. When you start looking at this, the number of nodes needs to be bigger.

**Comment by choppsv1** [comment]
+1 Use case: no IPv4 in the network infrastructure. None of my internal servers (next gen internet provider infrastructure) have ipv4 addresses.

**Comment by phillipCouto** [comment]
+1

**Comment by petrus-v** [comment]
+1

**Comment by stevemcquaid** [comment]
+1 - this is probably the most critical issue for my company.

**Comment by kkirsche** [comment]
Instead of +1's, please use the github +1 feature using the smiley face in the upper right of the original post. This will help organize this and allow the actual discussions of how to solve this occur rather than polluting the issue with +1's. Thank you for your understanding and cooperation.

**Comment by rahulwa** [comment]
[Please prioritize this. Nowadays IPv6 support is becoming common among the providers (like aws, scaleway, Hetzner, Online.net).
Our company is becoming IPv6 only network for internal traffic due to easiness of doing cross cloud setup securely. (For example, as on aws, globally routable IPv6 range can be configured on VPC level. This makes easy to do cross providers setup securely as we already know ip6 address range for any machine on that VPC. It especially helps for autoscaling). ](https://github.com/containernetworking/cni/issues/245#issuecomment-287111513)

**Comment by kkirsche** [comment]
Mobile applications for Apple also require IPv6 — https://developer.apple.com/news/?id=05042016a which may increase the desire to transition for some use cases

**Comment by oneiros-de** [comment]
Just curious since this ticket will be two years old soon: Is anybody working on it?

**Comment by burton-scalefastr** [comment]
It's surprising that this isn't implemented yet since IPv6 is very attractive since most hosts have a full /64 to play with.

**Comment by tomdee** [comment]
I'm trying to work out what to prioritize here, are a see a few different things that "IPv6 support" could mean

1) Adding IPv6 support for the control plane. This means using IPv6 for contacting the etcd server or the kubernetes API server.
2) Using IPv6 addresses for containers with an IPv6 host network. This _should_ work for all backends (though IPIP doesn't support IPv6 and maybe some of the cloud providers might not too).



Dual vs single stack

**Comment by choppsv1** [comment]
@tomdee We have no IPv4 addresses, we don't need them or want the complexity of running a dual stack. So I guess this means: 1 and 2.

**Comment by abh** [comment]
For us the use case is similar. We can do pure IPv6 (and have a load balancer in front of the cluster for IPv4 ingress), but IPv4 itself is hard.

For a project at work we're out of IPv4 addresses. Even allocating a not-to-be-routed /19 in 10/8 is difficult.

**Comment by rahulwa** [comment]
I believe 1 and 2 should be good enough.

**Comment by petrus-v** [comment]
In our context 1 and 2 would be great!

**Comment by onitake** [comment]
Are you aware of https://github.com/leblancd/kube-v6 and https://github.com/kubernetes/features/issues/508 ?

I'm actually surprised that IPv6 wasn't chosen as the default networking layer for Kubernetes from the beginning. It makes a lot of sense due to the sheer size and structure of the address space and would virtually eliminate the need for NAT inside a cluster (NAT64/DNS64 access to IPv4 networks notwithstanding).

**Comment by onitake** [comment]
@CalvinHartwell That's a valid concern; however, it's 2018 and there's not much of an excuse left for not supporting IPv6. In fact, I'm quite certain that most software these days is implicitly IPv6 capable.

**Comment by uablrek** [comment]
Since v1.16.0 K8s supports dual-stack. Any plans to support dual-stack in Flannel?

**Comment by xvzf** [comment]
If you don't mind I'll just start working on it at least for the vxlan backend!

**Comment by daniel-garcia** [comment]
any update on the backend support @xvzf ?

**Comment by yaoice** [comment]
+1, any update?

**Comment by yuanying** [comment]
Hi, I'm using host-gw backend.
So I'm also interested in IPV6 support other than VXLAN.
Are there any plans to support IPv6 for other backends?

**Comment by agowa338** [comment]
Wow, is this still open?
Is there any status update on when IPv6 will be supported?

**Comment by jamesharr** [comment]
You might want to [want to check the docs](https://github.com/flannel-io/flannel/blob/master/Documentation/configuration.md#configuration) , I think there's at least partial support for IPv6.

It appears that some backends might be missing v6 support based on comments on this issue, but it also seems like progress has been made too
