### ISSUE TITLE
Documentation: what happens when etcd is down

### ISSUE THREAD

**Issue by philips** [flannel-io/flannel#294]
We need to document what happens in various failure scenarios
- [ ] flanneld gets network partitioned from etcd
- [ ] flanneld machine loses its lease and has machines on the bridge still

Other failure scenarios I am not thinking of? 

@eyakubovich You are probably the best person to at least explain these two points.

**Comment by chbatey** [comment]
Currently evaluating using flannel and would be very interested in these docs. We'll be testing these kinds of things out but it would be nice to have an expected behaviour to compare against.

**Comment by eyakubovich** [comment]
No new machines will be able to join the flannel network. The existing machines will continue to work, including launching new containers.  etcd is only used to grab a new subnet lease and learn about leases of other machines.

**Comment by chbatey** [comment]
Thanks @eyakubovich

**Comment by macb** [comment]
What about if etcd is down for the duration of each lease @eyakubovich?
