### ISSUE TITLE
Better handling of out-of-sync clocks

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#340]
As https://github.com/coreos/flannel/issues/337 demonstrates, if flannel node's clock falls behind etcd, it causes problems. It's easy to detect that the new expiration is in the past (or maybe not far enough in the future) and complain in the logs. Also, slow down on acquiring a new lease.

**Comment by tomdee** [comment]
See also https://github.com/coreos/flannel/issues/404
