### ISSUE TITLE
Router peering support

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#364]
This issue is to gauge the appetite for a backend that would peer with routers via established routing protocols such as OSPF and BGP. Please +1 if you'd like to see that support and which protocols are important to you.

**Comment by gurvindersingh** [comment]
+1:

**Comment by jcollie** [comment]
+1 from me.  OSPF would be the most important.  Right now I'm running flannel on CentOS with the alloc backend and using bird to propogate the Flannel networks to the router.

**Comment by garo** [comment]
+1 for both, OSPF being more important to me.
