### ISSUE TITLE
Investigate VXLAN offload support

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#366]
Some NICs support VXLAN offload (http://www.intel.com/content/dam/www/public/us/en/documents/technology-briefs/overlay-networks-using-converged-network-adapters-brief.pdf) but I don't know what needs to be done (if anything) to enable it with flannel.

**Comment by jeremyeder** [comment]
Nothing special.  It gets enabled/disabled with 
```
# ethtool -k $NIC tx-udp_tnl-segmentation off
```
It's been enabled by default on all the NICs we've experimented with, including the Intel ones you linked to.

**Comment by eyakubovich** [comment]
@jeremyeder That's great news. I now wonder what happens if flannel is running inside a VM. How does VXLAN play with already virtualized NIC w.r.t. to offloads.

**Comment by jeremyeder** [comment]
If you terminate inside the guest, then no, you won't use the offload.  virtio_net doesn't support VXLAN-offload.  AFAICT vmxnet doesn't either.  If you terminate on the host and send decap'd traffic into a guest, then you're OK.

A team mate of mine wrote a whitepaper detailing what OpenStack Neutron does with VXLAN-offloads:  https://access.redhat.com/articles/1749113

**Comment by philips** [comment]
@jeremyeder Is this the same as this? https://github.com/coreos/flannel/pull/397

**Comment by jeremyeder** [comment]
@philips nope.

**Comment by jeremyeder** [comment]
We need NIC-agnostic vxlan offload...until then, 10G is a pipe-dream in the public cloud.

**Comment by chinglinwen** [comment]
@jeremyeder I'm using `ethtool -K flannel.1 tx off` to disable offloading, somehow it got re-enabled (maybe because of flannel restart? )

What can I do ?

```
# check
ethtool -k flannel.1 | grep tx-checksumming
# disable it
ethtool -K flannel.1 tx off
```
