### ISSUE TITLE
[VOTING] supporting traversing 1-N NAT for flannel. In other words add ability to traverse IP Masquerades, similar to STUN.

### ISSUE THREAD

**Issue by nodkz** [flannel-io/flannel#379]
![no-more-vpn-only-flannel](https://cloud.githubusercontent.com/assets/1946920/11553112/be809d06-99b5-11e5-8cdd-9245c99d25d4.png)
Example of abilities, which can provide flannel with 1-N NAT. Deeper integration of CoreOS to DevOps stack. No more VPN, only Flannel. (the addition, from 3 Dec. )
# 

Initial message:

First host:
- CoreOS
- Public IP

Second host:
- CoreOS under vagrant
- **Office IP**

`etcd` setup correctly, and it works.
Flannel try run via coreos config yaml. It startup correctly, networks `flannel0` and `docker0` up correctly. But pings does not work between containers, between container and remote host.

Also I build flanneld from `git`.
- on first host: ran `./flannel/bin/flanneld --listen=185.22.67.104:8888 &` and  `./flannel/bin/flanneld --remote=185.22.67.104:8888 &`
- on second host: run `./flannel/bin/flanneld --remote=185.22.67.104:8888 &`

A see that connection by port 8888 established, and `flanneld`s communicate with each other. But ping does not works. 

Can flannel works between such hosts?

PS. Before I have `centos7 on server` and `boot2docker on dev` machine, and can launch `weave` to communicate between this hosts.

**Comment by eyakubovich** [comment]
Probably not. I'm assuming your Office IP is something like 10.x.x.x or 192.168.y.y, aka RFC 1918 address. There's probably only a handful (or maybe one) of public addresses for the whole office and IP masquerade involved. It's quite challenging to traverse such typologies and usually involves [STUN](https://en.wikipedia.org/wiki/STUN) servers -- things that p2p services such as Skype do.

flannel was not built for this use case. It was designed to run inside the data center or the cloud.

**Comment by nodkz** [comment]
Yep, it's quite challenging via STUN. But may be exists more simple solution?! 

This ability implemented in `weave` https://github.com/weaveworks/weave/issues/1717 
I was able to create network with two hosts:
- at first host with public ip at DC, I ran `weave launch`.
- at the second host behind office-gateway (with internal ip), run `weave launch 76.13.1.9`.
- and all works. No STUN, no any changes on office-gateway. I also can pass internal network from data center to local dev machine.

Weave is a little bit foreign for CoreOS ecosystem. So right now I choose old-school ssh tunelling for my devOps tasks.

`flannel` with such connection ability will give better cooperation with coreOS cluster for developers, administrators. 

PS. My task was create a hidden mongodb's member for backup and analytics at office. Other members are in private network at DC. 

PSS. So I want skilled up with CoreOS and flannel, check it how good its works. And if all goes well, change deployment operations and rolling out staging versions.

**Comment by eyakubovich** [comment]
Weave has ability to traverse IP Masquerades (what they call firewalls) in a way very similar to STUN. That is why you were able to connect you desktop to the DC. flannel does not handle this use case. flannel can handle 1-1 NAT via `--public-ip` flag but that would not be sufficient in your case.

Weave is not integrated into CoreOS like flannel is but check out http://blog.weave.works/2014/10/28/running-a-weave-network-on-coreos/ on how to get it running on CoreOS.

Let's leave this issue open as a vote for supporting traversing 1-N NAT.
