### ISSUE TITLE
Add "WHY" information to README

### ISSUE THREAD

**Issue by rbucker** [flannel-io/flannel#393]
I'm looking at the flannel README file and although I have not experimented with flannnel in order to expose it's capabilities the header of the README describes flannel as performing the one function that kubernetes needs with an absence of WHY? So here are some questions and things that come to mind.
- the example shows a webapp connecting to a backend. Where is the webapp client? How are messages routed from the public?
- the comment "each pod" and "unique subnet" suggests that flannel handles multiple private subnets. An example or at least a stronger hint please? (multi-network experimental??) I'm not sure how this can be experimental with a proper tectonic release (that's a separate issue)

(maybe some of the above are already documented on different pages)[here](https://coreos.com/flannel/docs/latest/flannel-config.html)

Finally, it seems that Apcera does something like this but then adds security. How could that be added to flannel?

... or just close this.

**Comment by tomdee** [comment]
@zbwright / @joshix Do you think this issue can be closed?

**Comment by zbwright** [comment]
may be partially addressed.
1st item: not addressed. there was no additional info added to answer Where is the webapp client? How are messages routed from the public?
2nd item: addressed? references to multi network subnets have been removed. (experimental client-server doc is still available from the CoreOS site, but is slated for removal. https://coreos.com/flannel/docs/latest/client-server.html)
