### ISSUE TITLE
Possibility to change Public IP during runtime

### ISSUE THREAD

**Issue by balboah** [flannel-io/flannel#408]
When using flanneld cross-datacenter routed via public IPs on AWS, it is required that flanneld is restarted whenever I associate an instance with a new elastic IP and its public IP changes. Since Docker requires flanneld, I also have to restart every service from scratch.
I'm wondering if there are ways to reconfigure this during runtime or if there are plans to add this functionality?

Related to https://github.com/coreos/flannel/pull/259

**Comment by tomdee** [comment]
I don't think changing the public IP requires the Docker daemon to be restarted? Is that documented somewhere or am I missing something obvious?

**Comment by balboah** [comment]
I guess it doesn't have to if the bridge IP range stays the same, but there's no guarantee for that. Right?
I mean this from docker.service:
```
EnvironmentFile=-/run/flannel_docker_opts.env
# /run/flannel_docker_opts.env
DOCKER_OPT_BIP="--bip=10.10.122.1/24"
```

**Comment by tomdee** [comment]
Good, I think the code at the moment will fetch a new lease if the public IP changes. So maybe we could add an option for migrating to a new public-ip - that doesn't sound like a bad idea.

As a workaround, you may just be able to stop the flannel daemon, update the public IP in etcd then start the daemon again (with the new public IP).
