### ISSUE TITLE
Set subnet size on per-node basis

### ISSUE THREAD

**Issue by kfox1111** [flannel-io/flannel#451]
I've got a use case where, I know I have a small number of nodes that will have lots of containers, and a significantly larger set of nodes that will have only a few containers each. In the interest of saving some ip space, it would be nice if there was a way to specify the subnet size per node or sets of nodes.

**Comment by eyakubovich** [comment]
@kfox1111 Having each node request subnet size would complicate the subnet allocation algorithm in a non-trivial way (fragmentation). Having defined sets would work but it starts too look very similar to multiple networks. Perhaps multi-network feature could be modified to solve this case. Another option that has been proposed is to just for the node to get multiple subnets. For example, when it runs out of one subnet it could get another. The problem with this approach is how to integrate it with container systems -- Docker, CNI.

**Comment by kfox1111** [comment]
Yeah. I can see it getting complicated fast. For my current use case, I'm going to have one k8s system that has a lot of machines intended mostly for compute jobs, so will have a very small number of containers. ~4 usually. maybe as much as 16. And a very few nodes with maybe in the hundreds for support services. So to handle the support case, I have to allocate a large number of ips to computes that will never use them. It works as is, but seems very wasteful.
