### ISSUE TITLE
[Question] How to change backend type?

### ISSUE THREAD

**Issue by zihaoyu** [flannel-io/flannel#517]
Hi guys,

Currently I'm using `flannel` on CoreOS AWS, and running Kubernetes on top of that. The `Backend` type is `vxlan`. After reading some benchmarks online I'm considering switching to `host-gw` backend. I'm wondering what's the proper way to make such change?

In the README it mentioned [zero-downtime restarts](https://github.com/coreos/flannel#zero-downtime-restarts), but it didn't say if a change in the configuration is supported.

Options:
1. While the CoreOS cluster is running, change the `Backend` type in etcd. Will all members get the new configuration and update network?
2. Stop all the members in the cluster, change the `Backend` type in etcd, then restart members.
3. Some other method.
4. It isn't possible.

Any recommendation? Thanks!

**Comment by tomdee** [comment]
I'd love to see the answer to this written up as a doc to go in this repo. PRs very much welcome.

**Comment by outworlder** [comment]
I have done that by using a variation of method 2. As in, change the Backend type in etcd, then stop and restart members. I guess it works either way, as long as the members are restarted after the change is applied.

Zero downtime for such a change is unlikely, but I'll defer to the experts.

**Comment by fxpester** [comment]
changed backend from udp to vxlan in etcd, restarted all servers with full reboot
k8s pods are not accessible now
flannel spam logs with `L3 miss but route for 10.233.95.4 not found`
in tcpdump I can see:
```
08:20:38.026513 IP 10.111.0.20.44541 > 10.111.0.21.otv: OTV, flags [I] (0x08), overlay 0, instance 1
IP 10.233.88.0 > 10.233.108.0: ICMP host 10.233.88.7 unreachable, length 60
```

**Comment by discostur** [comment]
Is there anything new on this? What is the best way to change the Network Backend Type?

**Comment by TattiQ** [comment]
Guys here   https://github.com/kubernetes/kops/pull/3190   mentioned 
kops edit cluster <- change udp for vxlan
kubectl edit configmap -n kube-system kube-flannel-cfg <- change udp for vxlan
kubectl delete pod -n kube-system -l app=flannel   

but none of it made it to the official docs . 
The coreos docs mention a limitation for making changes at runtime - The backend type cannot be changed. (It can be changed if you stop all workloads and restart all flannel daemons.)  https://coreos.com/flannel/docs/latest/running.html .

**Comment by TattiQ** [comment]
Not clear what they mean by stopping all workloads though.
