### ISSUE TITLE
Allow the interface name (for vxlan) to be configured

### ISSUE THREAD

**Issue by luohoufu** [flannel-io/flannel#532]
after i run flannel,i use ifconfig find the flannel interface is flannel.1 ,how can i change to flanel0。
flanneld --version
v0.6.2
ifconfig flannel.1
flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1450

**Comment by tomdee** [comment]
The `.1` comes from the vxlan ID. Are you saying that you want to have `flannel0.1`?

**Comment by luohoufu** [comment]
tks,i see. maybe can customer setting flannel iface name will a new requirement.
