### ISSUE TITLE
Flannel + etcdv3?

### ISSUE THREAD

**Issue by bhouse** [flannel-io/flannel#554]
Hi!

I'm wondering what the compatibility of flannel with etcdv3 is? If I upgrade to etcdv3 and migrate the storage backend, will that get used by flannel? When I tried it, there seem to still be two storage backends, one for etcdv2 that flannel uses, and etcdv3 that's empty.

My apologies if this is in the docs/code somewhere, I wasn't able to grep for it. Thanks for all your work on this project!

**Comment by mgoodness** [comment]
This is a somewhat pressing question with etcd v3 becoming the default store in Kubernetes 1.6. [This blog post](https://coreos.com/blog/migrating-applications-etcd-v3.html) seems to indicate that the v2 API will keep working after the data has been migrated to v3, but confirmation would be nice.

**Comment by tomdee** [comment]
Flannel still uses the etcdv2 API. It can still talk to a etcd V3 server and share it will Kubernetes even if kubernetes is using etcdv3.

So it works, but it's not ideal so I would like to update flannel to use etcdv3 when I get a chance.

**Comment by chulkilee** [comment]
Okay, @tomdee closed #542 mentioning this, so I guess this will be a placeholder for using etcv3.

Although flannel *is* working with etcv3, I see lots of warning when using etcd behind Amazon ELB since etcdv2 API does not send heart beat (while etcdv3 does). Although it does not break anything (I guess flannel will just reconnect), but it's annoying :)

**Comment by tomdee** [comment]
Yes, I hear and understand the need for etcdv3 for the heartbeat support.

**Comment by ravilr** [comment]
Does flannel continue to work even after `etcdctl migrate` of v2 data to v3 data. @hongchaodeng @xiang90  does migrate keep around v2 data.  Can someone confirm, if they have gone through this process. Thanks.

**Comment by ravilr** [comment]
https://github.com/coreos/etcd/issues/7406 confirms that `etcdctl migrate` leaves the existing v2 data as-is.

**Comment by nesc58** [comment]
Is anyone working on this issue? There're huge issue to create backups for v2 (flannel) and v3 (e.g. kubernetes). The clientv3 for etcd is in the official repo. Are there unsolved issues or is this a personal/timing problem to solve this issue in one of the next versions?

**Comment by andyxning** [comment]
@nesc58 Seems like flannel has updated the etcd dep version to 3.1.x. @tomdee could you please confirm this?

**Comment by tomdee** [comment]
That PR just updates the library version - flannel still only works with the etcdv2 API for now

**Comment by andyxning** [comment]
Any plan to upgrade etcd support to etcd v3? @tomdee

**Comment by alapidas** [comment]
@tomdee Would there be interest in accepting a contribution that added this feature?

**Comment by dxdeidara** [comment]
@tomdee I'd like to know if the latest flannel version v0.9.0 supports etcd v3 now?

**Comment by tomdee** [comment]
@alapidas yes
@dxdeidara Sorry, it's still not supported

**Comment by 372046933** [comment]
Still not support?

**Comment by calvix** [comment]
Are there any plans for adding support etcdv3 ever?

**Comment by fabifrank** [comment]
+1

**Comment by robinsondan87** [comment]
Kubectl 1.13 will be dropping any support for the v2 api so we need flannel to support the v3 api, are there any plans to introduce this soon as 1.13 is currently in alpha status with a RC due soon.

**Comment by unteem** [comment]
I'm a bit confused here, can someone confirm that compatibility between flannel and kubernetes 1.13 is broke or it sill works? Thanks
