### ISSUE TITLE
Implement IPSEC mode

### ISSUE THREAD

**Issue by eyakubovich** [flannel-io/flannel#6]
For users that require network level encryption, flannel should be able to use IPSEC as the encapsulation protocol.

**Comment by offlinehacker** [comment]
+1

**Comment by sporkmonger** [comment]
Honestly, it's really not so much a question of not trusting your hosting provider. Hosting providers don't necessarily get a choice in the matter of whether their fiber lines have been spliced and tapped. It's just a good idea to encrypt any traffic you're not in absolute control over. And even if you are... it's probably still a good idea.

**Comment by runningman84** [comment]
A simple encryption like openvpn would be good enough. I would really like to span a coreos cluster between different cloud providers like linode, online.fr and others.

**Comment by wmark** [comment]
Setting up IPSEC in transport mode with the help of *Consul* or *etcd* is what I currently use. You might find it a viable (and proven) substitute.

**Comment by cornelius-keller** [comment]
Hi mark,

is there any documentation on your consul / etcd solution available?
I would like to try this, but beeing very new to ipsec I would like to have an example to follow.

**Comment by ibotty** [comment]
hi @wmark, I am pretty sure that at least (flannel using) vxlan does not work with ipsec transport mode. It should work using tunnel mode though.

**Comment by balboah** [comment]
this would be very nice as I would like to hookup different data centers across the public internets

**Comment by eyakubovich** [comment]
@MohdAhmad is currently working on IPSec backend so stay tuned.

**Comment by ibotty** [comment]
I have written a [blog entry](https://github.com/ibotty/blog-posts/blob/master/2015/08/01/Securing%20a%20flannel%20network.md) on how to do that.

But @balboah, you surely have a dedicated router on each site of your subnets, right? That should be a stock site-to-site setup. Just (transparently) encrypt traffic coming over udp port 8472.

**Comment by cornelius-keller** [comment]
Hi there,

I created a demo with an encrypted flannel network using ting.
You can find it here https://github.com/cornelius-keller/coreos-vagrant-tinc
As I am really new to coreos systemd etcd etc. I would like to hear your comments / suggestions improvements.

It uses tinc for the encryption, flannel for subnet allocation and etcd for distributiong the configuration.
It is a long weekend hack and I am new to the whole technology stack. An attempt to dive into coreos and do something useful. But it works.

I am sure that the whole systemd services can done much more elegant by an experienced systemd user so I would love to see your comments on that or even better some pull requests.

**Comment by balboah** [comment]
@ibotty cool. Yes setting up routers on each side is an option, but at least initially I feel that peer to peer encryption where flannel sends packets to publicly routed ip's would be more flexible and not requiring high availability setups of additional routers

**Comment by diranged** [comment]
Just chiming in here -- I agree that this would be a great and obvious feature to implement. It both allows for cross-region networking models, as well as adds a layer of warm-fuzzy encryption. Any movement on this?

**Comment by eyakubovich** [comment]
@diranged Yes, we have a PR ready: https://github.com/coreos/flannel/pull/290

Please help by reviewing it and providing feedback.

**Comment by diranged** [comment]
@eyakubovich thanks for the link -- I'm not qualified to comment on the code itself, but I'm reading the PR now and will comment where I can.

**Comment by wikiwi** [comment]
+1

**Comment by mkutsevol** [comment]
PR #637 is the latest one regarding this issue.

**Comment by RyPeck** [comment]
See #929 for the latest work here. Still experimental.

**Comment by Iodun** [comment]
Are there any thoughts on using MACsec on top of VXLAN instead of IPsec?
Available in mainline Linux kernel 4.6 and newer.
https://developers.redhat.com/blog/2016/10/14/macsec-a-different-solution-to-encrypt-network-traffic/

**Comment by eliaslevy** [comment]
If considering using MACsec, then you may also want to look at [WireGuard](https://www.wireguard.com).

**Comment by jameskeane** [comment]
It's not Flannel, but [Scrambler](https://github.com/jameskeane/scrambler) provides an ipsec mesh network on top of strongswan.

It reuses a lot of built-in stuff to stay simple: RBAC, k8s api, and cluster PKI (kubelet client certs). The mesh is created by an agent run on each node that reads the cluster nodes, and generates an ipsec config using each node's name and pod_cidr on an interval; i.e. it dynamically reconfigures on node join/leave. All of that in < 200 lines of bash!

It doesn't do everything flannel does, but it might be enough for some.

**Comment by G3ph4z** [comment]
so is this not yet implemented?

**Comment by artheus** [comment]
https://github.com/coreos/flannel/tree/master/backend/ipsec
Should this issue not be closed, now that ipsec backend exists in master branch?

**Comment by zbindenren** [comment]
Will the ipsec backend be included in the 0.10.0 release?

**Comment by nautikos1235** [comment]
Hello guys,
this issue can be closed no? I see IPSec backend was added & released in 0.11.0

**Comment by txomon** [comment]
Yes this can be closed. Be advised that somethings like forwarding might not work though
