### ISSUE TITLE
Provide more concrete guidance on upgrading flannel on Kubernetes

### ISSUE THREAD

**Issue by tomdee** [flannel-io/flannel#706]
At the moment, the manifest doesn't specify rolling updates, but some more thought is needed to determine if the k8s 1.6 rolling update feature is useful for flannel updates.

See https://kubernetes.io/docs/tasks/manage-daemon/update-daemon-set/

Current policy is "OnDelete"
```
kubectl get --namespace=kube-system ds/kube-flannel-ds -o go-template='{{.spec.updateStrategy.type}}{{"\n"}}'
OnDelete
```

**Comment by pmcgrath** [comment]
If I want to update from 0.9.1 to 0.10.0 today, how do I do so ?
On a cluster installed with kubeadm, I ran kubectl applying the manifest for 0.9.1 at the time
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.9.1/Documentation/kube-flannel.yml
```

As Tom pointed out the existing update strategy is OnDelete and since this impacts networking I need to be cautious

If I do kubectl apply the 0.10.0 manifest the flannel daemonset will not update ? 

If I delete the 0.9.1 daemonset before applying the 0.10.0 manifest, will I lose network access to the cluster and networking within the cluster ?

Couldn't find any guidance when searching, so some guidance would be appreciated ?

Thanks
Pat

**Comment by aba182** [comment]
+1 here, we are looking to do a flannel upgrade and we want to make sure we are following best practices since this is a critical piece of our infrastructure.

**Comment by jansmets** [comment]
any pointers?

**Comment by fodano79** [comment]
I have a Kubernetes Cluster (Bare-Metal) installed with Kubeadm (v1.12.5), Docker (v18.6), kubectl (v1.12.5), flannel v0.10.0.
I was able to upgrade ALL the components at the latest version (kubeadm 1.14, Docker v18.9.5, kubectl v1.14.1, kubelet 1.14.1) but i'm not able to upgrade flannel to 0.11.0 (i need it for Windows Worker Nodes).

I used this the first time to install flannel:
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/bc79dd1505b0c8681ece4de4c0d86c5cd2643275/Documentation/kube-flannel.yml

How can I upgrade to 0.11?

Thanks for the stupid question.

Francesco

**Comment by qqbuby** [comment]
any updates?

**Comment by zebrastack** [comment]
any updates?

**Comment by virtualdxs** [comment]
I don't like to +1, but instructions on how to upgrade such a critical component of a cluster seems important. I ended up applying the new manifest and deleting the pods one by one, waiting for each to be fully terminated before deleting the next, but I have no idea if this would have caused any impact if this cluster were serving anything at the time.

**Comment by giordyb** [comment]
I'm in the same boat, please provide some guidance on how to safely upgrade...would updating the image version in the daemonset sufficient?

**Comment by prashantgnet** [comment]
Any updates on this?

Thanks a lot!

**Comment by shomeprasanjit** [comment]
Guys any updates on the documentation? if anyone has some prior experience, please point out the upgrade steps and the compatibility matrix in kubernetes.

**Comment by rdxmb** [comment]
please /reopen

**Comment by rbrtbnfgl** [comment]
I'll take a look at it

**Comment by naitmare01** [comment]
Also waiting and hoping for some guidance.
