### ISSUE TITLE
enable machines to access the network without allocating a subnet

### ISSUE THREAD

**Issue by sjpotter** [flannel-io/flannel#730]
Flannel as designed seems to only take into account that the network would be used by containers running on multiple nodes.  However, it seem like a legitimate use case to enable a hybrid environment where you have containers and "regular" machines interacting.  i.e. the regular machine will have a "regular" ip address but it has to know how to route to the containers and that's where flannel comes in.

Take aws/gcp/host-gw examples.

If I were doing this manually, in aws/gcp I'd just join the regular machine to the aws route table / gcp network and it would route to the containers or in a host-gw I'd have to manage the routes myself.

## Expected Behavior
today one has to allocate a subnet to any machine joining a flannel network even if it doesn't need a container bridge.

## Current Behavior
today, whenever one joins a flannel network a /24 is allocated to it (generally from the /16 of the network).  If one has lots of "regular" machines trying to join the network to route to containers, can run out of subnets when this isn't required.

## Possible Solution
just allow a machine to get route updates without allocating a subnet.  In aws/gcp can avoid the issue by just allowing those nodes to be part of the route table / network (and in fact what I do) but doesn't help other flannel usages.

In addition, I believe a non subnet/bridge mode would enable me to join windows machines (not container hosts) to the flannel network via the extension mechanism (ala its host-gw example)

## Context
trying to allow many non container hosts to also be able to route to container nodes just like other containers can.

## Your Environment
* Flannel version: v0.7.1
* Backend used: multiple as described above

**Comment by sjpotter** [comment]
I'm digging into this in trying to understand flannel and how one would approach this

There are 2 aspects from what I can see to flannel

1) getting a subnet for the local machine (and setting it up as necessary)
2) ensuring that the local machine can access the rest of the network

1 isn't really necessary in what I'm proposing, but without doing major surgery to the code base probably doesn't fit in

2 is still required.

So in looking into how #1 is handled, basically on startup it will get a network eventually call network.init()  which calls the backend interface method RegisterNetwork()  which gets the subnet lease.

It would make sense in a hybrid situation that RegisterNetwork() actually not do anything of value, but it has to return something that Flannel can make sense of, as the value is used elsewhere (i.e. network.runOnce() calls subnet.WatchLease() on it.

Instinctually, what I'd like to propose for the hybrid case is a wrapper backend that can wrap any other backend, the wrapped backend will handle the 2nd issue describe above, while the wrapper will provide a RegisterNetwork() that returns some form of sentinel value for a lease (perhaps the network is 0.0.0.0) and this lease is handled appropriately by the rest of the code (i.e. never times out and WatchLease() will handle it correctly.

this is just my initial attempt at understanding the code, any pointers / suggestions would be appreciated.

**Comment by tomdee** [comment]
Thanks for the suggestion @sjpotter it's a very interesting idea. 

I think this could be a really useful feature. First some terminology that I can reference further down
* "Normal hosts" have containers on them (that get their own IP addresses) and the host get a subnet lease to allow it to assign addresses to the containers.
* "Leaseless hosts" don't get a subnet lease so they can't give IP addresses to containers.

A problem that I can see is that the leaseless hosts still need an address that's on the flannel network. e.g. if you want to have vxlan encapsulated packets to pass between the normal and leaseless hosts, the source and destination addresses need to be on the flannel network. 
I can't think of an easy solution for this problem.

Another problem I can see comes around when using the Kubernetes API to store data. In this case, kubernetes nodes objects get annotations for the flannel configuration for that node. This is what all the flannel daemons watch to know that they need to set up networking to a new node. This implies that flannel would require kubernetes node objects even for "leaseless" hosts. Maybe this limitation is OK, but I still think it's worth flagging.

**Comment by sjpotter** [comment]
so vxlan is a bit over my head at this point, but doesn't it come down to how packets are routed?

i.e. flannel assigns a /24 space to leaseless hosts.  This wouldn't be a routable subnet (unlike the subnet a "normal" host gets), flannel will have to route each ip assigned from the /24 independently, its in some ways can be viewed as simply a dhcp space.

leaseless hosts will then has a physical ip of X and a flannel overlay IP of Y, if flannel knows to route packets for Y via the physical IP of X, it would work.  In practice isn't this why I can do this today with aws/gcp (non vxlan), because in those cases I can make it that X == Y and the underlying route table of the cloud takes care of routing.

I should note, this does seem possible in ovs/ovn (though haven't tried to implement it there yet either)

**Comment by tomdee** [comment]
When vxlan is being used, there is more going on that just pure routing. 

Let say we have two hosts, and a flannel network of 192.168.0.0/16
* Host A is a "normal" host that has the subnet 192.168.1.0/24 assigned to it.
   * It has one container running on it that has an IP address of  192.168.1.1
   * It has a single NIC with the address 10.0.0.1
* Host B is  "leaseless" host, with no subnet assigned to it.
  * It has no containers running on it.
  * It has a single NIC with the address 10.0.0.2 assigned to it.

If I send a packet from host B to the container on host A, the source address will be 10.0.0.2 and the destination will be 192.168.1.1.

This works fine as long as the network between host A and host B allows packets with the 192.168.1.1 address. Some cloud networks block this which is sometimes why vxlan is used.

When vxlan is used, the packet from 10.0.0.2 to 192.168.1.1 gets encapsulated, which means that there's an additional IP header which has a source address of 10.0.0.2 and a destination of 10.0.0.1. Host A can then un-encapsulated the packet when it arrives there and pass it on to the container.

But we now have a problem - how does the container respond? If it tries to reply to 10.0.0.1  with a source address of 192.168.1.1 the packet isn't going to get encapsulated, because flannel will only encapsulate packets destined for the flannel network. And remember that in this scenario we need to use vxlan because we're on a cloud network that doesn't allow the 192.168.1.1 address to appear on the network between the hosts.


So, where does this leave us? I can see this feature working on the purely routed flannel network backends (e.g. host-gw, aws or gce) but I can't see how it can (easily) be made to work with vxlan.

**Comment by sjpotter** [comment]
Ok, I believe I have more clarity on the issue, namely there's lack of support for controlling the "source" address.

so a thought experiment that I don't know if is possible

Imagine we allocated 192.168.10.0/24 to be the ip space for "leaseless" hosts.

For Host B, we allocate ip (ala dhcp) 192.168.10.54 to be its "vxlan" ip address.  If outgoing packets from Host B looked like they were coming from 192.168.10.54 and vxlan knew that packets being sent to 192.168.10.54 had to be encapsulated to be sent to 10.0.0.2 it be similar to trying to connect to 192.168.1.1

so from a nat perspective, one would want to rewrite the packet so that any packet destined for the flannel network space would first be rewritten so that its source is 192.168.10.54.  so we took our packet that was 
   source:10.0.0.2 dest:192.168.1.1
to
   source:192.168.10.54 dest:192.168.1.1

its then encapsulated so that its has a source of 10.0.0.2 and a dest of 10.0.0.1 and can get routed to host A, unpacked and look to host B as a packet from 192.168.10.54 to 192.168.1.1 and when it tries to respond to 192.168.10.54 it can be encapsulated similarly.

or tldr: is there someway to give leaseless hosts a flannel/vxlan address and route to them individually.

**Comment by sjpotter** [comment]
Where I can believe my thought experiment falls down is that the socket host B uses to connect to host A's container will be bound to IP 10.0.0.2 and routing the packets from 10.0.0.1's container will still be problematic.

on the flips side, what if 10.0.0.1 had a nat type mechanism so that any packets its sending destined for 192.168.10.54 get rewritten for 10.0.0.2.  Dont know if vxlan type mechanism can do NAT or just encapsulation.  Would seem I want both.
