### ISSUE TITLE
Conflicting options in sample kube-flannel.yaml (--kube-subnet-mgr vs Network in net-conf.json)

### ISSUE THREAD

**Issue by jraby** [flannel-io/flannel#763]
## Expected Behavior
I was trying out k8s along with flannel with the host-gw backend and came across a small inconsistency wrt to the sample `kube-flannel.yaml` and the subnet lease that is given out to a node.

In the sample `kube-flannel.yaml` file, `net-conf.json` contains a `Network` key:

```
  net-conf.json: |
    {
      "Network": "10.244.0.0/16",
      "Backend": {
        "Type": "vxlan"
      }
    }
```

Which kind of implies that this parameter (along with other subnet parameters such as `SubnetLen`) is going to be used somehow by flannel.

However, the sample config also passes the `--kube-subnet-mgr`, which seems to delegate the subnet assignment duty to the `kube-controller-manager`. So any Subnet related parameters passed in `net-conf.json` is going to be ignored / have no effect at runtime.

A possible solution might be to simply remove the `Network` parameter from the sample config and document somewhere in `Documentation/configuration.md` that the `kube-controller-manager` is taking over the subnet assignments and that any subnet parameters are going to be ignored when `kube-subnet-mgr` is active.

I think this would save a lot of time to newcomers who have a need for a different config than the default and who are new to all the kubenetes moving pieces.

## Environment
* Flannel version: 0.7.1 amd64
* Backend used : host-gw
* Kubernetes version: 1.6.6

**Comment by antoineco** [comment]
Besides `net-conf.json` doesn't seem to be used anywhere.

**Comment by antoineco** [comment]
I guess this was just to get people covered in case the `--cluster-cidr` `kube-controller-manager` flag is not set.

**Comment by tomdee** [comment]
Some backends need to know the global cluster-cidr (host-gw doesn't IIRC). flannel reads this value from the file and not from the kubernetes API (again IIRC).

**Comment by cristifalcas** [comment]
For vxlan we need the Network key?

**Comment by 372046933** [comment]
At the end of day, what's the exact config of host-gw backend? Can anyone give an example?
