### ISSUE TITLE
Unable to ping the flannel0 and flannel1 IP when flannel is stopped and started manually.

### ISSUE THREAD

**Issue by clchandan** [flannel-io/flannel#795]
Unable to ping the flannel0 and flannel1 IP when flannel is stopped and started manually as part of our Robustness testing.(No Issue seen with other services yet and Not sure if/who need/uses that IP)

## Expected Behavior
Should be able to ping flannel0 IP after flanneld is started on that host(call it Host1) from another Host.
Found that there is some difference  before and after Flanneld stop/start in the ip routes
Also note that Host1 can ping other Hosts and tcpdump shows src ip as Host1's flannel0 IP.

## Current Behavior
 Can't ping flannel0 IP after flanneld is started manually on Host1 from another Host.
Host1 can ping other Hosts flannel0 IP. containers running on Host1 can communicate out to other container on other Hosts. Just that no one can ping Host1 flannel0 IP.

## Possible Solution
 We found that there is a difference in the iproute entries before it was manually stopped vs after it was manually started on Host1. Ran below commands at fresh install and after manually stopping and starting flanneld.
1- ip route show | grep flannel
2- ip route show table local | grep flannel
Fresh install
     1 - 11.0.0.0/16 dev flannel0  proto kernel  scope link  src 11.0.63.0 
     2- broadcast 11.0.0.0 dev flannel0  proto kernel  scope link  src 11.0.63.0 
         local 11.0.63.0 dev flannel0  proto kernel  scope host  src 11.0.63.0 
         broadcast 11.0.255.255 dev flannel0  proto kernel  scope link  src 11.0.63.0 
    
flanneld manually stopped and started.
     1-  11.0.0.0/16 dev flannel0 
     2-  local 11.0.63.0 dev flannel0  proto kernel  scope host  src 11.0.63.0 

## Steps to Reproduce (for bugs)
 - Install of a CoreOS cluster (i had 3 host cluster with etcd, flannel and docker up)
      Flannel setting	
        [Service]
        ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "11.0.0.0/16" }'
- Capture output from below commands
      ip route show | grep flannel
      ip route show table local | grep flannel
- Capture flannel0 IP on a Host1
- Ping flannel0 IP of Host1 from another host. You will get reply
- Systemctl stop flanneld
- Ping flannel0 IP of Host1 from another host. No reply
- Systemctl start flanneld
- Capture output from below commands
     ip route show | grep flannel
     ip route show table local | grep flannel
- Ping flannel0 IP of Host1 from another host. No reply
- Ping flannel0 IP of Host2 from Host1. You will get reply
      You can run tcpdump i just used coreos toolbox and you will see ping coming into Host1 but no reply. And when you ping from Host 1 to Host2 you will see flannel0 IP as src and respective replies.

## Context

We have not seen any issue with our services or containers running on Host1 yet. So the other question to you Guys is what is flannel0 IP used for/which service needs/uses this IP ?
This is as part of our Robustness testing, we have a tester container that would get the flannel IP’s and ping then after each run. In this case we stopped and started flanneld service on Host1 and the Checker failed.

## Your Environment

* Flannel version: v0.7.0 or v0.7.1
* Backend used (e.g. vxlan or udp): not sure how can i check ?
* Etcd version: v2.3.7 or v3.1.7
* Kubernetes version (if used): N/A
* Operating System and version: CoreOS 1353.7.0 or 1409.6.0
* Link to your project (optional):

**Comment by tomdee** [comment]
I can tell from the interface name that you're using the UDP backend. This backend is not recommended and will not allow traffic to flow if the flannel daemon isn't started. Try using vxlan instead - https://github.com/coreos/flannel/blob/master/Documentation/backends.md

**Comment by clchandan** [comment]
Hi Tom,
thanks for looking at it and reply. But not sure why it was closed as in our case we did start the flanneld daemon and that is when it we tried to Ping the flannel0 IP.
Also it would be good to know who/what uses that IP to check what affect it will have on our system.

**Comment by clchandan** [comment]
Any update on this or at least can somebody tell what/who needs to ping the flannel0,1 IP so we get an idea on what side affect to look for.

**Comment by tomdee** [comment]
@clchandan Can you try with the latest version of flannel? And can you post the log output from flanneld?
