### ISSUE TITLE
Flannel should allow non-disruptive ssl certificate rotation connecting to etcd

### ISSUE THREAD

**Issue by trunet** [flannel-io/flannel#829]
On our environment we have per-server ssl certificates. These certificates have a short lifetime and it's renewed every week (certificates are issued valid for 2 weeks).

## Expected Behavior
Reloading flannel should re-read the certificates that is used to connect to etcd.

## Current Behavior
A full flannel restart is needed

## Possible Solution
trap a SIGHUP, reload method or any other way should re-read the certificates and reconnect to etcd.

**Comment by tomdee** [comment]
Thanks for the feature request @trunet. Just so I understand the impact this has on you, are you seeing any problems with doing a full flannel restart. The dataplane should not be affected by restarting the flannel daemon. The only problem I can think of is that new hosts that are added while the flannel daemon isn't running won't be spotted until the daemon has started up again.

**Comment by trunet** [comment]
We had a dependency between flannel and docker on systemd. Everytime that flannel was restarted, docker was being restarted as well. I removed the RequiredBy from docker unit to fix this behaviour.

So, there's no impact on doing the full restart. flannel restart is part of the certification rotation script that run once a week.

**Comment by tomdee** [comment]
@trunet Thanks for the reply and clarification!
