### ISSUE TITLE
set  --ip-masq=true, iptables rules can not be deleted  when we stop flannel

### ISSUE THREAD

**Issue by tanshanshan** [flannel-io/flannel#836]
## Expected Behavior

when we stop flannel , IP masquerade rules in the table nat will be deleted.
and the log such as

> I1011 10:46:20.562264 31786 ipmasq.go:64] Deleting iptables rule: -s 172.16.0.0/12 -d 172.16.0.0/12 -j RETURN
> I1011 10:46:20.565606 31786 ipmasq.go:64] Deleting iptables rule: -s 172.16.0.0/12 ! -d 224.0.0.0/4 -j MASQUERADE
> I1011 10:46:20.577259 31786 ipmasq.go:64] Deleting iptables rule: ! -s 172.16.0.0/12 -d 172.16.0.0/12 -j MASQUERADE

## Current Behavior

 stop flannel  with ctrl+c or kill , the  iptables rules are not deleted.
## Steps to Reproduce (for bugs)

1. ./flanneld -etcd-endpoints https://10.10.10.163:2379 -etcd-prefix /cluster.local/network -etcd-cafile /etc/flannel/certs/ca_cert.crt -etcd-certfile /etc/flannel/certs/cert.crt -etcd-keyfile /etc/flannel/certs/key.pem -iface 10.10.10.163 -subnet-file /run/flannel/subnet.env --ip-masq=true
2. ctrl +c or kill pid
3. watch log

## Context
in version 0.6.2 ,  iptables rules can be deleted

## Your Environment

* Flannel version: 0.8.0
* Backend used (e.g. vxlan or udp): vxlan 
* Etcd version: v3.0.17
* Kubernetes version (if used): 1.9.6
* Operating System and version:centos7
* Link to your project (optional):

Thanks.

**Comment by tomdee** [comment]
This is tracking the fact that iptables rules aren't deleted. Although originally rules were being deleted I no longer think this is desired behaviour. We want to leave the dataplane untouched when flanneld stops to facilitate upgrades. We should provide a cleanup command though.
