### ISSUE TITLE
Configuration for kube subnet manager should be clearer.

### ISSUE THREAD

**Issue by tomdee** [flannel-io/flannel#848]
Users get confused about this 
* As shown in #847, the SubnetLen gets ignored. Also subnetMin and Max would be ignored too
* Also, the Network (https://github.com/coreos/flannel/blob/85662a7453fa14d11d53af9be6663847e0ae8f7a/Documentation/kube-flannel.yml#L65) in the netconf could do with better documentation as it must match the podCidrs that Kubernetes is using.

We could print a warning if config has been specified that will be ignored.
And of course we could add more documentation to make it clearer.

**Comment by marchuobi** [comment]
Would it be possible to just put a comment in the kube-flannel.yml file saying this is ignored with a pointer to the correct doc page?  Everything I found via google said it worked this way, the troubleshooting page never came up in search.

**Comment by tomdee** [comment]
Sounds sensible - PRs are of course welcome :smile:

**Comment by MikeSpreitzer** [comment]
Yeah, I just wasted some time on this too.  The documentation for how this works on kube should not be closeted in the troubleshooting section.

**Comment by MikeSpreitzer** [comment]
BTW, it is also unclear to the non-experts why flanneld has _both_ `--public-ip` and `--iface`.  And, BTW, on my first read of the doc I got the idea I only need to specify `--public-ip`.  WRONG.  Specifying both works.

In a related vein, the exhibited log messages from the troubleshooter ---
```
I0629 14:28:35.866987    5522 main.go:399] Using interface with name enp62s0u1u2 and address 172.24.17.174
I0629 14:28:35.867000    5522 main.go:412] Using 10.10.10.10 as external address
```
--- do _not_ make it clear what purposes each address will be used for.

**Comment by MikeSpreitzer** [comment]
I probably was led to thinking about `--public-ip` by the comment at https://github.com/coreos/flannel/blob/master/Documentation/kubernetes.md#annotations about an annotation for public IP.  I suppose that is also obsolete?
