### ISSUE TITLE
The file kube-flannel-rbac.yml is not available in the repository  but is still referenced

### ISSUE THREAD

**Issue by rawroland** [flannel-io/flannel#870]
## Expected Behavior

The documentation on the page [troubleshooting](https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md) should be updated to reflect the absence of said files.

## Current Behavior

The documentation currently references the non-existent kube-flannel-rbac.yml file, which was removed in version 0.9.0.

## Possible Solution

Update the documentation on the [troubleshooting page](https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md) to reflect the absence of the aforementioned file.

## Steps to Reproduce (for bugs)

1. `kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel-rbac.yml`

## Context

An installation which was automated with ansible started failing, since the file was no more available.

## Your Environment

* Flannel version: Using the master branch
* Backend used (e.g. vxlan or udp): ?
* Etcd version: ?
* Kubernetes version (if used): v1.7.3
* Operating System and version: Ubuntu xenial
* Link to your project (optional):

**Comment by rushins** [comment]
we hit the same error kubernetes 1.8.4. can some one provide the RBAC flannel file.

**Comment by rushins** [comment]
i found this location but this only creates role-bindings not t flannel pod or overlay network 
https://gist.github.com/joejulian/a5f308f73bfee7444810870313cec251

check the URL and download 2 files , try  executing one by one see if this helps. i tried but my cluster FLANNEL PODS still craching .
https://gist.github.com/joejulian/


[7:52] 
however our flannel pod is crashing

**Comment by osoriano** [comment]
The main kube-flannel.yml was updated to include RBAC resources. Would that work for you?

`kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml`
