### ISSUE TITLE
RFC: Add cleanup command

### ISSUE THREAD

**Issue by tomdee** [flannel-io/flannel#886]
The design of flannel is currently a little unclear around what state it changes _after_ it has existed.

# Desired behaviour
I believe the correct behaviour should be:
* When flannel stops, it should leave the dataplane "intact", e.g. leave routes configures, leave tunnel devices in an UP state. This leads to more reliable operations if flannel crashes and needs to be restarted and it makes zero downtime upgrades possible.
* Following on this, when flannel starts it should ensure that the dataplane has the correct state but it should avoid disturbing it if the state is already correct (e.g. if a tunnel device already exists and is configured correctly then don't remove and recreate it).

# Current issues
The code currently implements this, more or less but has a few holes
* Flannel _claims_ to be cleaning up iptables rules when it stops, but doesn't actually succeed in doing so. The rules shouldn't actually be cleaned (as per the desired behaviour above), so this code should be cleaned up.
* Flannel creates a subnet.env files on the filesystem but never cleans it up
* It creates network config on the host that it never cleans up.

# Suggestion for resolving
Add a flag to `flanneld`, e.g. `flanneld --cleanup`. It would be an error to use this flag with any other flags.
It would make a *best effort* attempt to clean everything up
* Remove the subnet.env file
* Remove any network config (devices/routes/etc...)
  * Should it call a `cleanup()` function on _all_ backends (which means it doesn't need to connect to the datastore to find the backend), or just call `cleanup()` on the configured datastore (which means it can't clean up network config if it can't connect to the datastore).
* Remove iptables rules (for masq and forwarding)

# References
https://stackoverflow.com/questions/46276796/kubenetes-cannot-cleanup-flannel/46438072#46438072
https://github.com/coreos/flannel/issues/739
https://github.com/coreos/flannel/issues/820

**Comment by tomdee** [comment]
cc @xh3b4sd WDYT?

**Comment by xh3b4sd** [comment]
Hey man. Thanks for your efforts here and considering my input. Sounds like I can dream on a green field here. :) 

In my issue earlier I questioned flannel's interface. My current understanding is that etcd is the interface and the configuration you provide describes the desired state. What I would find nice would be to decide on an interface and then use it consistently. Assuming etcd is the interface then desired state and status updates should be readable/writable through this interface. One cool thing would be to do the custom resource thing when being on Kubernetes. The interface would then be a CRD/CRO. Uncertain how you want to roll with this. 

From my point of view only making flannel cleaning up when it is started with a specific flag is quite bad when you want to automate the process. You would need to schedule it once to setup and later schedule it again, but differently to cleanup. Would be cool if you schedule it and use some interface where you can set the desired state and check for some status. So it would be cool to have the operator approach to reconcile state gradually. 

Have a nice weekend.
