### ISSUE TITLE
Have no route like "10.2.0.0/16 dev flannel", and replaced by "10.2.22.0/24 via 10.2.22.0 dev flannel.1 onlink "

### ISSUE THREAD

**Issue by kenzhaoyihui** [flannel-io/flannel#901]
## Issue
Have no route like "10.2.0.0/16 dev flannel", and replaced by "10.2.22.0/24 via 10.2.22.0 dev flannel.1 onlink ", and cannot forward the package.

## Expected Behavior
```
#ip route
10.2.0.0/16 dev flannel.1
```

## Current Behavior
```
#ip route
10.2.22.0/24 via 10.2.22.0 dev flannel.1 onlink
```

## Steps to Reproduce (for bugs)

1. Run etcd : `etcd -listen-client-urls http://192.168.122.1:2379 -advertise-client-urls http://192.168.122.1:2379`
2. Store the network info
```
[root@localhost opt]# etcdctl --endpoints=192.168.122.1:2379 get /docker-test/network/config
{
	"Network": "10.2.0.0/16",
	"SubnetLen": 24,
	"Backend": {
		"Type": "vxlan"}
}

```
3. Start the flannel:
```
flanneld -etcd-endpoints=http://192.168.122.1:2379 -iface=eth0 -etcd-prefix=/docker-test/network
```
4. Check the route :  `ip route`

## Context

Two VM subnets: 10.2.22.0/24, 10.2.98.0/24
flannel.1: 10.2.22.0/32, 10.2.98.0/32

## Your Environment

* Flannel version: build the latest from the github(github.com/coreos/flannel)
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: etcd-v2.3.7
* Kubernetes version (if used): no
* Operating System and version: fedora 26, virbr0(192.168.122.1), two VM(centos): 192.168.122.171, 192.168.122.166
* Link to your project (optional): no

**Comment by Cougar** [comment]
Same thing here. Server running CoreOS 1520.7.0 works fine:

```
10.255.0.0/16 dev flannel.100 
10.255.88.0/22 dev docker0 proto kernel scope link src 10.255.89.1 
```

New server running new CoreOS stable 1576.4.0 installs partial route only to flannel:

```
10.255.96.0/22 via 10.255.96.0 dev flannel.100 onlink 
10.255.172.0/22 dev docker0 proto kernel scope link src 10.255.173.1 
```

Configuration in etcd2 is:
```json
{ "Network": "10.255.0.0/16", "SubnetLen": 22, "SubnetMin": "10.255.1.0", "SubnetMax": "10.255.199.0", "Backend": { "Type": "vxlan", "VNI": 100, "Port": 8472 } }
```

**Comment by Cougar** [comment]
It looks like this is the new and normal behavior. flanneld monitors etcd2 and inserts/removes node networks as they come and go.

Btw, there was a problem in my network config. Never use non subnet address in `SubnetMin`. Flannel doesn't fix that but allocates wrong network addresses and other nodes can't install subnet routes for that. It worked with one supernet route before but not any more.
