### ISSUE TITLE
 Lease has been revoked. Shutting down daemon

### ISSUE THREAD

**Issue by w564791** [flannel-io/flannel#904]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

```
Dec 17 08:23:27 ip-10-10-7-229.cn-north-1.compute.internal flanneld-start[1071]: E1217 08:23:27.578015    1071 main.go:398] Lease has been revoked. Shutting down daemon.
Dec 17 08:23:27 ip-10-10-7-229.cn-north-1.compute.internal flanneld-start[1071]: I1217 08:23:27.578046    1071 main.go:321] Waiting for all goroutines to exit
Dec 17 08:23:27 ip-10-10-7-229.cn-north-1.compute.internal flanneld-start[1071]: I1217 08:23:27.578065    1071 main.go:332] Stopping shutdownHandler...
Dec 17 08:23:27 ip-10-10-7-229.cn-north-1.compute.internal flanneld-start[1071]: I1217 08:23:27.578160    1071 main.go:324] Exiting cleanly...

```
## Your Environment

* Flannel version: v0.9.1
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.2.7
* Kubernetes version (if used): 1.7.10
* Operating System and version: CentOS 7(kernel 4.4.105-1.el7.elrepo.x86_64)
* Link to your project (optional):

**Comment by w564791** [comment]
What should I do, T_T

**Comment by w564791** [comment]
the problem happened again

```
Dec 18 01:31:46 ip-10-10-6-90.cn-north-1.compute.internal systemd[1]: Started Flanneld overlay address etcd agent.
Dec 19 09:31:47 ip-10-10-6-90.cn-north-1.compute.internal flanneld-start[1096]: E1219 09:31:47.078227    1096 main.go:398] Lease has been revoked. Shutting down daemon.
Dec 19 09:31:47 ip-10-10-6-90.cn-north-1.compute.internal flanneld-start[1096]: I1219 09:31:47.078257    1096 main.go:321] Waiting for all goroutines to exit
Dec 19 09:31:47 ip-10-10-6-90.cn-north-1.compute.internal flanneld-start[1096]: I1219 09:31:47.078317    1096 main.go:332] Stopping shutdownHandler...
Dec 19 09:31:47 ip-10-10-6-90.cn-north-1.compute.internal flanneld-start[1096]: I1219 09:31:47.078395    1096 main.go:324] Exiting cleanly...
Dec 19 09:33:05 ip-10-10-6-90.cn-north-1.compute.internal systemd[1]: Starting Flanneld overlay address etcd agent...

```

**Comment by tomdee** [comment]
s someone removing data from etcd? What about the server's clock, is it being changed?

**Comment by w564791** [comment]
Thanks Reply ! I checked all the server's clock, there is not much time between them.and no time to change when this problem occurs.This project is my personal maintenance, so I confirm that no one removed data from etcd.

**Comment by deepakprabhakara** [comment]
I am seeing this issue on our productrion sytem. I can confirm that no data is being removed from etcd. Only flannel on 1 node shuts down though, rest are fine. A restart of flannel and it continues working fine.

**Comment by timchenxiaoyu** [comment]
I0816 14:15:12.460636  997012 network.go:160] Lease renewed, new expiration: 2018-08-17 06:15:12.397323577 +0000 UTC
I0817 13:15:12.424162  997012 network.go:160] Lease renewed, new expiration: 2018-08-18 05:15:12.409554615 +0000 UTC
I0818 12:15:12.772691  997012 network.go:160] Lease renewed, new expiration: 2018-08-19 04:15:12.425758602 +0000 UTC
I0819 11:15:12.680788  997012 network.go:160] Lease renewed, new expiration: 2018-08-20 03:15:12.439583798 +0000 UTC
I0820 10:15:12.522387  997012 network.go:160] Lease renewed, new expiration: 2018-08-21 02:15:12.456519505 +0000 UTC
I0821 09:45:48.418973  997012 network.go:160] Lease renewed, new expiration: 2018-08-22 01:45:50.425406892 +0000 UTC
W0822 09:48:14.516109  997012 network.go:170] Lease has been revoked

**Comment by timchenxiaoyu** [comment]
not renew lease  lead this problem

**Comment by hjydxy** [comment]
Same trouble, kubernetes 1.10  flannel 0.10.0  
I notice that there is no information under  /coreos.com/network/subnets/.
The subnets information is gone.

**Comment by hjydxy** [comment]
Do you solve it? @timchenxiaoyu

**Comment by timchenxiaoyu** [comment]
not solve yet，but we set etcd ttl = 0  to avoid lost data in etcd

**Comment by hjydxy** [comment]
Do you see "time difference is too high" or sth in etcd  log. 
Maybe my trouble is caused by this . 
Do you run ntp or chrony on your cluster? @timchenxiaoyu

**Comment by heshengkai** [comment]
@w564791 I meet same problem yet,I have run chrony in my cluster.Have you solved the problem by now?

**Comment by w564791** [comment]
> @w564791 I meet same problem yet,I have run chrony in my cluster.Have you solved the problem by now?

No,look here : https://coreos.com/flannel/docs/latest/reservations.html
