### ISSUE TITLE
iptables filter table issue

### ISSUE THREAD

**Issue by cezarysupron** [flannel-io/flannel#934]
Dysfunctional iptables/filter table on kubernetes nodes with Fedora 27

## Expected Behavior

iptables/filter table with proper structure, should provide smooth communication via flannel network  throughout the whole kubernetes cluster as below:

kubectl get nodes
NAME                        STATUS    ROLES     AGE       VERSION
cluster1-vm-00.localdomain   Ready     master    3d        v1.9.2
cluster1-vm-01.localdomain   Ready     \<none>    3d        v1.9.2

kubectl get pods -o wide
NAME                                   READY     STATUS    RESTARTS   AGE       IP            NODE
test-65bdb459f6-c6d22                  1/1       Running   3          2d        10.244.1.32   cluster1-vm-01.localdomain

kubectl exec test-65bdb459f6-c6d22 -- curl -k https://10.96.0.1/version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   260  100   260    0     0  21146      0 --:--:-- --:--:-- --:--:-- 21666
{
  "major": "1",
  "minor": "9",
  "gitVersion": "v1.9.2",
  "gitCommit": "5fa2db2bd46ac79e5e00a4e6ed24191080aa463b",
  "gitTreeState": "clean",
  "buildDate": "2018-01-18T09:42:01Z",
  "goVersion": "go1.9.2",
  "compiler": "gc",
  "platform": "linux/amd64"

## Current Behavior

To the iptables/filter table on my kubernetes nodes, flannel adds rules whose are grouped by KUBE- prefix, but not all of them. In my case two important flannel "ACCEPT" rules are always inserted after previously existing firewalld "REJECT" rule, which means that they do not participate in further processing:
...
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -s 10.244.0.0/16 -j ACCEPT
-A FORWARD -d 10.244.0.0/16 -j ACCEPT
...
This in turn blocks the correct communication in the whole kubernetes cluster.

## Possible Solution

It seems to me that these rules should be added as FLANNEL-FORWARD group after KUBE-FORWARD:
...
-A FORWARD -m comment --comment "kubernetes forward rules" -j KUBE-FORWARD
-A FORWARD -m comment --comment "flannel forward rules" -j FLANNEL-FORWARD
...
-A FLANNEL-FORWARD -s 10.244.0.0/16 -j ACCEPT
-A FLANNEL-FORWARD -d 10.244.0.0/16 -j ACCEPT
...

## Steps to Reproduce (for bugs)

1. Prepare two VM's Fedora-Cloud-Base-27-1.6.x86_64
2. Install base cloud environment: dnf group install "Fedora Cloud Server"
3. Install kubeadm 1.9.2 with flannel 0.10.0 on master (https://kubernetes.io/docs/setup/independent/install-kubeadm)
4. Init master and add one node (https://kubernetes.io/docs/setup/independent/create-cluster-kubeadm)
5. Fire up test pod (https://github.com/kubernetes/ingress-nginx/blob/master/docs/troubleshooting.md)
6. Test connection to kubernetes service from test pod:

  kubectl get services
  NAME                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
  kubernetes            ClusterIP   10.96.0.1       <none>        443/TCP          2d

  kubectl exec test-65bdb459f6-c6d22 -- curl -k https://10.96.0.1/version
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 10.96.0.1 port 443: No route to host

## Your Environment

* Flannel version: 0.10.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.1.11
* Kubernetes version (if used): 1.9.2
* Operating System and version: Fedora release 27 (Twenty Seven)
* Link to your project (optional):

**Comment by wuzm2k05** [comment]
that's exactly what I met, those two rules allow flannel network packages are APPENDED after the prohibited rule. Then I insert those two rules before prohibited rule, everthing is okay.

**Comment by wuzm2k05** [comment]
How is the bug going? I didn't see any comments here, so have this one ben fixed already?
