### ISSUE TITLE
Flannel creation fails with certificate signed by unknown authority

### ISSUE THREAD

**Issue by ImmanuelJDaniel** [flannel-io/flannel#939]
I'm trying to create a flannel network and the pods fail with CrashLoopbackOff.

## Expected Behavior

Flannel to be created with pods in running state.

## Current Behavior

Fails with the below error,

Failed to create SubnetManager: error retrieving pod spec for 'kube-system/kube-flannel-ds-pvpzc': Get https://10.90.0.1:443/api/v1/namespaces/kube-system/pods/kube-flannel-ds-pvpzc: x509: certificate signed by unknown authority

## Steps to Reproduce (for bugs)

kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

## Environment

* Flannel version: Latest Version
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 3.0.17
* Kubernetes version (if used): 1.8
* Operating System and version: Ubuntu 16.04

**Comment by ydp** [comment]
@ImmanuelJDaniel  Did you solve this?

**Comment by audig** [comment]
Same issues, one pod can start, but 2 others failed. The node is never the same

**Comment by melvynpan** [comment]
Same issues，anyone help?
