### ISSUE TITLE
Could not find valid interface on windows

### ISSUE THREAD

**Issue by devenfan** [flannel-io/flannel#944]
got issue when running flanneld 0.10 windows 

<pre>
flanneld  -etcd-endpoints "http://127.0.0.1:2379"  -etcd-prefix "/test/network"  -iface "10.5.225.34"
I0206 18:33:48.506022    4464 main.go:417] Searching for interface using 10.5.225.34
I0206 18:33:48.678026    4464 main.go:201] Could not find valid interface matching 10.5.225.34: error looking up interface 10.5.225.34: no index found for interface ""
E0206 18:33:48.678026    4464 main.go:225] Failed to find interface to use that matches the interfaces and/or regexes provided
</pre>

**Comment by suylem** [comment]
any update about this issue ?  i also meet this problem.
OS:  windows server 2016 core 1709 and window server 2016 version 1607
flannel version:  v0.10.0

**Comment by suylem** [comment]
i can work fine,  after install English language on my server and set as default language

**Comment by devenfan** [comment]
My windows 10 has been changed to English as below, but the error is still there with a small difference:

![image](https://user-images.githubusercontent.com/1137401/36640061-79acdb74-1a53-11e8-89ba-f5f982eca141.png)

<pre>
flanneld  -etcd-endpoints "http://127.0.0.1:2379"  -etcd-prefix "/test/network"  -iface "10.5.225.34"
I0225 17:44:29.893162    4932 main.go:417] Searching for interface using 10.5.225.34
I0225 17:44:30.736004    4932 main.go:201] Could not find valid interface matching 10.5.225.34: error looking up interface 10.5.225.34: route ip+net: no such network interface
E0225 17:44:30.736004    4932 main.go:225] Failed to find interface to use that matches the interfaces and/or regexes provided
</pre>

As you can see above:

 **error looking up interface 10.5.225.34: no index found for interface**

changed to:

**error looking up interface 10.5.225.34: route ip+net: no such network interface**

**Comment by guhuajun** [comment]
Greetings,

I have installed a new Windows Server 1709. Flanneld can find my interface.

![image](https://user-images.githubusercontent.com/14121694/36775094-919103d8-1c9b-11e8-9139-17032f18c24b.png)

**Comment by devenfan** [comment]
@guhuajun You have only one network interface right?

**Comment by guhuajun** [comment]
@devenfan Yes, I do.

https://kubernetes.io/docs/getting-started-guides/windows/ mentions that Flannel and Weavenet are not yet supported. Maybe we should give up at this moment?

**Comment by devenfan** [comment]
@guhuajun I think you may want to deploy Kubernetes Slaves on windows machines, and I suggest you use CentOS 7 instead.

And my problem is, how to connect docker network on different Windows machines automatically...

**Comment by funky81** [comment]
Hi all, any guidelines to develop flannel in Windows node? Thanks

**Comment by laoshancun** [comment]
> Hi all, any guidelines to develop flannel in Windows node? Thanks

same issue,any updates?

**Comment by kinglionsoft** [comment]
Same issue on Windows Server 2019.

**Comment by ekochen** [comment]
solve this issue on my env by type **`chcp 65001`**  to ues utf8 ,then re run the flannel start command

**Comment by kinglionsoft** [comment]
@ekochen You save my many many days. Thank you very much.

**Comment by ekochen** [comment]
encounter this 
waiting for the Network to be created
Waiting for the Network to be created
I1127 10:24:28.829686 3668 kube.go:133] Node controller sync successful
I1127 10:24:28.829686 3668 main.go:244] Created subnet manager: Kubernetes Subnet Manager - windows-kube-139
I1127 10:24:28.832687 3668 main.go:247] Installing signal handlers
I1127 10:24:28.832687 3668 main.go:386] Found network config - Backend type: host-gw
I1127 10:24:28.833674 3668 hostgw_windows.go:73] HOST-GW config: {Name:cbr0 DNSServerList:}
I1127 10:24:28.853822 3668 hostgw_windows.go:157] Attempting to create HNSNetwork {"Name":"cbr0","Type":"L2Bridge","Subnets":[{"AddressPrefix":"10.20.4.0/24","GatewayAddress":"10.20.4.1"}]}
I1127 10:24:28.859820 3668 hostgw_windows.go:164] Waiting to get ManagementIP from HNSNetwork cbr0
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x10e43ea]

goroutine 1 [running]:
main.main()
/home/kasubra/repo/gopath/src/github.com/coreos/flannel/main.go:297 +0xbfa


i see this bug https://github.com/coreos/flannel/issues/1066

do you also have this issue?
