### ISSUE TITLE
flannel pods in CrashLoopBackoff Panic assignment to entry in nil map

### ISSUE THREAD

**Issue by yashgiri** [flannel-io/flannel#969]
Using flannel as a CNI in kubernetes i am trying to implement a network for pod to pod communication spread on different vagrant vms. I am using this https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml to create flannel pods. But the kube-flannel pods go in CrashLoopBackOff error and do not start.

## Expected Behavior

**kube-flannel pods in running state on all nodes**

## Current Behavior

**kube-flannel pods in CrashLoopBackOff state on all nodes**

[root@flnode-04 ~]# kubectl logs kube-flannel-ds-2kqpv --namespace=kube-system 
I0327 10:28:44.103425       1 main.go:483] Using interface with name mgmt0 and address 192.168.30.14
I0327 10:28:44.105609       1 main.go:500] Defaulting external address to interface address (192.168.30.14)
I0327 10:28:44.138132       1 kube.go:130] Waiting 10m0s for node controller to sync
I0327 10:28:44.138213       1 kube.go:283] Starting kube subnet manager
I0327 10:28:45.138509       1 kube.go:137] Node controller sync successful
I0327 10:28:45.138588       1 main.go:235] Created subnet manager: Kubernetes Subnet Manager - flnode-04
I0327 10:28:45.138596       1 main.go:238] Installing signal handlers
I0327 10:28:45.138690       1 main.go:348] Found network config - Backend type: vxlan
I0327 10:28:45.138767       1 vxlan.go:119] VXLAN config: VNI=1 Port=0 GBP=false DirectRouting=false
panic: assignment to entry in nil map
goroutine 1 [running]:
github.com/coreos/flannel/subnet/kube.(*kubeSubnetManager).AcquireLease(0xc420010cd0, 0x7f5314399bd0, 0xc420347880, 0xc4202213e0, 0x6, 0xf54, 0xc4202213e0)
    /go/src/github.com/coreos/flannel/subnet/kube/kube.go:239 +0x1f7
github.com/coreos/flannel/backend/vxlan.(*VXLANBackend).RegisterNetwork(0xc4200b3480, 0x7f5314399bd0, 0xc420347880, 0xc420010c30, 0xc4200b3480, 0x0, 0x0, 0x4d0181)
    /go/src/github.com/coreos/flannel/backend/vxlan/vxlan.go:141 +0x44e
main.main()
    /go/src/github.com/coreos/flannel/main.go:278 +0x8ae

## Possible Solution

fix/reason : the file github.com/coreos/flannel/blob/master/subnet/kube/kube.go contains a nil map n.Annotations which without a kubectl annotation overwrite would be empty and cause a panic

hack to make it work : kubectl annotate node <node-name> flannel.alpha.coreos.com/public-ip=10.10.10.10 --overwrite=true
run this on each and every node of cluster so that there is no nil entry in the map before creating flannel pods

## Steps to Reproduce (for bugs)

1. Remove old kuberenetes CNI
2. Install Flannel CNI plugin 
3. kubectl create -f https://raw.githubusercontent.com/coreos/flannel/v0.9.0/Documentation/kube-flannel.yml

## Your Environment

* Flannel version: v 0.9.0
* Backend used (e.g. vxlan or udp): vxlan
* Etcd version: 
* Kubernetes version (if used): 1.8.6
* Operating System and version: Centos 7.4
* Link to your project (optional):

**Comment by Pezhvak** [comment]
i have the same problem

**Comment by IonutDanielButnariu** [comment]
Hello,
Are there any updates on this issue?
Thank You,
Daniel

**Comment by yashgiri** [comment]
sorry got no update the last time i checked and changed work so i dont have any solution from my side
