### ISSUE TITLE
Reserve a subnet from the podCidr network for every node

### ISSUE THREAD

**Issue by def0def0** [flannel-io/flannel#972]
## Expected Behavior
Is there currently a way to reserve the host a subnet from the podCidr network?

I found an article mentioning setting the lease TTL to 0 but cannot find the values in etcd (is it stored there in Kubernetes install anyway?). Also I found this pull request which looks like the reservation support is removed https://github.com/coreos/flannel/pull/809.

## Current Behavior
Every time I restart the Kubernetes nodes they get a different subnet from podCidr network.

## Context
I use host-gw networking with external load balancer and need to set static routes to the podCidr subnetworks on specific hosts. 

## Your Environment
* Flannel version: 0.9.1
* Backend used (e.g. vxlan or udp): host-gw
* Etcd version: 3.2.14
* Kubernetes version (if used): 1.7.10
* Operating System and version: CentOS 7

**Comment by olljanat** [comment]
I ended up to here as part of host-gw studying so some comments to this one.

> ## Current Behavior
> 
> Every time I restart the Kubernetes nodes they get a different subnet from podCidr network.

Code creates lease for 24 hours on https://github.com/flannel-io/flannel/blob/1249f1b6d7763456ab19ba7a36d63b70eb3353ce/subnet/kube/kube.go#L348-L351
so podCidr should not change on reboot unless nodes have been kept on down or if there have not been some bug on renewal logic in past.

https://github.com/flannel-io/flannel/blob/master/Documentation/reservations.md#reservations contains info how to make those leases permanent.

Also if I understand logic correctly it should be possible to reserve subnet for new nodes by creating `/var/run/flannel/subnet.env` as part of server provisioning before Flannel starts first time.

**Comment by olljanat** [comment]
Figured it out. This example if from K3s but should works on all Kubernetes version.

Trick is give `--allocate-node-cidrs false` flag for kube-controller-manager before starting node first time. Then you can manually set podsCidr you want.

```bash
# Start K3s
k3s server --flannel-backend=host-gw --kube-controller-manager-arg allocate-node-cidrs=false --cluster-cidr "10.100.0.0/16"

# Check that node is up
kubectl get nodes

# Add podCird for node
kubectl patch nodes <node name> --type=merge --patch '{"spec":{"podCIDR": "10.100.200.0/24","podCIDRs": ["10.100.200.0/24"]}}'
```

Also the original problem that podCidr changes every time looks to be fixed already to Kubernetes it selves on way that podCidr gets stored to etcd and stay there as long node is part of cluster.
