### ISSUE TITLE
--iface-regex doesn't work with interfaces that have multiple IPs

### ISSUE THREAD

**Issue by iMartyn** [flannel-io/flannel#981]
## Expected Behavior
I have an interface with both a public IP and an rfc1918 IP on it.  I want flannel to use the internal IP so I pass in the daemonset `--iface-regex=10\.64\.*\.*` (and variations with [0-9]* and [0-9]+ etc etc.).
Flanneld returns `Could not find valid interface matching 10\.64\.*\.*: Could not match pattern 10\.64\.*\.* to any of the available network interfaces`
Looking at the code, https://github.com/coreos/flannel/blob/master/main.go#L479 expects all interfaces to have one IP which is a bad assumption.  This code calls https://github.com/coreos/flannel/blob/master/pkg/ip/iface.go#L39 which returns as soon as it finds an IPv4 address. 

## Current Behavior
Flanneld returns `Could not find valid interface matching 10\.64\.*\.*: Could not match pattern 10\.64\.*\.* to any of the available network interfaces`

## Possible Solution
Don't assume anywhere in flannel's code that you will always have a single IP per interface.
I appreciate that this will require lots more "is this an IP or array of IPs" throughout the flannel codebase, but it is the correct thing to do.

## Steps to Reproduce (for bugs)
1. create an interface with multiple IPs
2. start flanneld with `--iface-regex=` and a regex that matches not the first IP
3. observe `Could not find valid interface matching`....

## Context
Packet.net provides a single bonded interface on their bare metal machines that has both an external and internal IP.  Without addressing this issue, we cannot ensure flannel traffic remains within the internal network.

## Your Environment
* Flannel version: v0.9.1
* Backend used (e.g. vxlan or udp): vxlan I think but irrellavent
* Etcd version: again, irrellevant
* Kubernetes version (if used): 1.10.0 but again, irrellavent
* Operating System and version: CentOS with upgraded kernel but again... well you get the picture.

**Comment by ccollicutt** [comment]
I also face this problem. Packet.net is slightly unusual in how they manage their private networking, though in a good way :), but I'm sure there will be situations in which flannel needs to deal with an interface that has multiple IPs associated.

For now I've migrated the internal IP to a macvlan interface attached to the bond and it seems to be working, and then I tell flannel to use that interface instead.

**Comment by ivan-section-io** [comment]
I too faced this problem today. Also at Packet.net - worked around by removing+re-adding the public IP from the interface at boot (this made the existing private 10.n.n.n address the "first").
```
ipPublicCIDR=$(ip -o addr show  label bond0 | grep -Po 'inet \K[\d.]+/\d\d')
ip addr del ${ipPublicCIDR} dev bond0
ip addr add ${ipPublicCIDR} dev bond0
```
Would have been nice if `--iface-regex=^10\.` would have found it.

**Comment by kinglionsoft** [comment]
same issue.

**Comment by rkoster** [comment]
I had success with the following container-linux-config:
```
flannel:
  interface: '{PRIVATE_IPV4}'
  public_ip: '{PRIVATE_IPV4}'
```

Apparently `--iface` [also accepts an ipaddress](https://github.com/coreos/flannel/blob/master/main.go#L453-L458).

**Comment by adeleglise** [comment]
I'm also facing this issue. I have a private interface with two private adresses. If I specify a regex for the alliased address on his private interface, it cannot be used.
