### ISSUE TITLE
flannel not able to communicate with etcd 

### ISSUE THREAD

**Issue by Dileep2016** [flannel-io/flannel#990]
Flannel Not able to communicate with etcd cluster

## Expected Behavior
hi i am trying to setup flannel in kubernetes nodes master is working working fine..
master i did the set up fine..
etcdctl
--cert-file /etc/etcd/kubernetes.pem
--key-file=/etc/etcd/kubernetes-key.pem
--ca-file /etc/etcd/ca.pem
--endpoints "https://172.17.37.22:2379,https://172.17.37.6:2379"
set
-- coreos.com/network/config '{"Network":"10.20.0.0/16", "SubnetLen": 24,"Backend":{"Type":"vxlan"}}'

it working fine on master but worker node throwing error. not able to start

etcd.service
-------------------------------------------------------------------------------
Unit]
Description=flannel is an etcd backed overlay network for containers
After=network-online.target
Wants=network-online.target
After=etcd.service
Before=docker.service

[Service]
Type=notify
EnvironmentFile=-/etc/default/flanneld
ExecStart=/usr/bin/flanneld --etcd-endpoints=${FLANNELD_ETCD_ENDPOINTS} --etcd-prefix=${FLANNELD_ETCD_PREFIX} $FLANNEL_OPTIONS
Restart=on-failure

[Install]
WantedBy=multi-user.target
RequiredBy=docker.service

----------------------------------------------
/etc/default/flanneld
---------------------------------------
FLANNELD_ETCD_ENDPOINTS=" https://172.17.37.22:2379,https://172.17.37.6:2379"
FLANNELD_ETCD_PREFIX="coreos.com/network/"
FLANNELD_ETCD_CERTFILE="/etc/etcd/kubernetes.pem"
FLANNELD_ETCD_KEYFILE="/etc/etcd/kubernetes-key.pem"
FLANNELD_ETCD_CAFILE="/etc/etcd/ca.pem"
FLANNEL_OPTIONS="-ip-masq"
---------------------------------------------------
Node also i have put the same configuration but not bale to start the flannel service...
Error is :---

● flanneld.service - flannel is an etcd backed overlay network for containers
Loaded: loaded (/etc/systemd/system/flanneld.service; enabled; vendor preset: enabled)
Active: inactive (dead) (Result: exit-code) since Mon 2018-05-07 14:01:14 UTC; 21s ago
Main PID: 26207 (code=exited, status=1/FAILURE)

May 07 14:01:13 ip-172-17-37-60 systemd[1]: Failed to start flannel is an etcd backed overlay network for containers.
May 07 14:01:13 ip-172-17-37-60 systemd[1]: flanneld.service: Unit entered failed state.
May 07 14:01:13 ip-172-17-37-60 systemd[1]: flanneld.service: Failed with result 'exit-code'.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: flanneld.service: Service hold-off time over, scheduling restart.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: Stopped flannel is an etcd backed overlay network for containers.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: flanneld.service: Start request repeated too quickly.
May 07 14:01:14 ip-172-17-37-60 systemd[1]: Failed to start flannel is an etcd backed overlay network for containers.
 Linux Version

ubuntu

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)

**Comment by omkensey** [comment]
A few things occur to me right off:

1. `172.17.*.*` looks like the default Docker bridge network to me.  If your etcd containers are running on the host-only Docker bridge network they won't be accessible outside that host by default.
2. Your endpoints list only has two endpoints.  Ideally you should have an odd number -- 1, 3, 5 or 7.
3. Do the etcd SSL cert/key/etc. exist on the worker nodes in the same directories and file names as on the master?

**Comment by Dileep2016** [comment]
@omkensey SSl  keys are same place in worker nodes..
etcd running on ubuntu machine .. not on docker host.. for testing purpose i spun up 2 maste and 2 nodes
 enpoints i will add 1 more etcd .. may i know the reason behind odd number

**Comment by Dileep2016** [comment]
@omkensey  etcd.service  file is correct right is there anything to add...
interface = eth0 or eth1 do i need to add this one
