### ISSUE TITLE
flannel complains about route when starts

### ISSUE THREAD

**Issue by 372046933** [flannel-io/flannel#996]
## Expected Behavior

When flannel is started, it prints the route info. 
## Current Behavior

But there are unreachable network which is saved in the last boot.
## Possible Solution

Remove unnecessary route
## Steps to Reproduce (for bugs)

1. `systemctl stop flanneld`
2. `systemctl start flanneld`
3. `journalctl --follow --unit=flanneld`
4. 

## Context

Host ip is 192.168.70.65/20, the IP 192.168.1.109 below is acquired on another network on last boot.
Network configuration saved in etcd is 
➜  ~ etcdctl get /coreos.com/network/config
{"Network":"10.1.0.0/16", "Backend":{"Type":"host-gw"}}
➜  ~ 

Below are the error logs reported by flanneld

May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.912758    6456 local_manager.go:147] Found lease (10.1.8.0/24) for current IP (192.168.70.65), reusing
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.915508    6456 ipmasq.go:51] Adding iptables rule: -s 10.1.0.0/16 -d 10.1.0.0/16 -j RETURN
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.916912    6456 ipmasq.go:51] Adding iptables rule: -s 10.1.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.918291    6456 ipmasq.go:51] Adding iptables rule: ! -s 10.1.0.0/16 -d 10.1.8.0/24 -j RETURN
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.919595    6456 ipmasq.go:51] Adding iptables rule: ! -s 10.1.0.0/16 -d 10.1.0.0/16 -j MASQUERADE
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.921068    6456 main.go:279] Wrote subnet file to /var/run/flannel/subnet.env
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.921080    6456 main.go:284] Finished starting backend.
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.921191    6456 hostgw_network.go:51] Watching for new subnet leases
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.921735    6456 main.go:367] Waiting for 22h59m59.991133824s to renew lease
May 22 09:43:38 arch flanneld[6456]: I0522 09:43:38.922443    6456 hostgw_network.go:83] Subnet added: 10.1.86.0/24 via 192.168.1.109
May 22 09:43:38 arch flanneld[6456]: E0522 09:43:38.922541    6456 hostgw_network.go:116] Error adding route to 10.1.86.0/24 via 192.168.1.109: network is unreachable

## Your Environment

* Flannel version: v0.8.0
* Backend used (e.g. vxlan or udp): udp
* Etcd version: 3.3.5
* Kubernetes version (if used):
* Operating System and version: Arch Linux(4.6.19 kernel)
* Link to your project (optional):

**Comment by makeloffve** [comment]
Check if there are multiple **default** routes in your ip route, make sure there is only one **default** route.

**Comment by 372046933** [comment]
The problem seems to be how to process the network record saved in etcd
